build.sh

Fuzzyc2cpg is public, we can use the https version.

fuzzyc2cpg location

---

docs/themes/hugo-theme-docdock-master/layouts/partials/menu-footer.html

Added watch/star/fork buttons for joern and code property graph.

Github buttons for website

---

.scalafmt.conf
project/plugins.sbt
src/main/scala/io/shiftleft/joern/CpgLoader.scala
src/main/scala/io/shiftleft/joern/JoernQuery.scala

Bring in scalafmt and format code

---

build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala
joern-cli/src/test/scala/io/shiftleft/joern/GenerationTests.scala

I noticed that executing `sbt test` two times in a row without running `sbt clean` does not work. I'll investigate that first before merging.

Update to newest fuzzyc2cpg

---

build.sbt
updateDependencies.sh

Update script wasn't working for fuzzyc2cpg due to a typo.

Bump dependencies and fix update script

---

build.sbt
joern-cli/src/test/scala/io/shiftleft/joern/CallGraphTests.scala
joern-cli/src/test/scala/io/shiftleft/joern/DataFlowTests.scala
joern-cli/src/test/scala/io/shiftleft/joern/LocalsTests.scala
joern-cli/src/test/scala/io/shiftleft/joern/MethodTests.scala
joern-cli/src/test/scala/io/shiftleft/joern/SampleDocuTest.scala
joern-cli/src/test/scala/io/shiftleft/joern/StructureTests.scala
joern-cli/src/test/scala/io/shiftleft/joern/TestCpg.scala
joern-cli/src/test/scala/io/shiftleft/joern/TypeDeclTests.scala

Update to newest CPG and FuzzyC version

---

.travis.yml

Change oraclejdk8 to openjdk8 to make the build on Travis-CI pass.

change oraclejdk to openjdk

---

docs/content/essentials/cpgloader/_index.md

Add CpgLoading file to website.

Add CPG loading spec

---

joern-cli/src/main/scala/io/shiftleft/joern/CpgLoader.scala
joern-cli/src/main/scala/io/shiftleft/joern/console/AmmoniteBridge.scala
joern-cli/src/main/scala/io/shiftleft/joern/console/Console.scala

`loadCpg` now works on the joern shell.

LoadCpg for joern shell

---

.travis.yml

Adding more gatekeepers:
1) Check that `scalafmt` passes PR and master builds
2) Check that tests also pass on master builds

You shall not pass sometimes (scalafmt)

---

docs/config.toml
docs/themes/hugo-theme-techdoc/layouts/partials/edit-page.html

Make `Edit on GitHub` work

---

docs/content/shell/_index.md

A bit of documentation about reading code on the shell. I made this a sub section of the article on the Joern shell.

Docs on inline code reading

---

joern-cli/src/test/scala/io/shiftleft/joern/RunScriptTests.scala
scripts/ast-for-funcs/ast-for-funcs.scala
scripts/cfg-for-funcs/cfg-for-funcs.scala
scripts/graph-for-funcs/description.json
scripts/graph-for-funcs/graph-for-funcs.scala
scripts/pdg-for-funcs/pdg-for-funcs.scala

Added graph-for-funcs script and its test.
Performance improvement to scripts: removed multiple iterations on methods.

Added graph-for-funcs script and performance improvements

---

build.sbt
docs/content/shell/_index.md

This release brings inline code reading with syntax highlighting :)

Update dependencies and docs accordingly

---

README.md
build.sbt
docs/content/installing/_index.md
docs/content/shell/_index.md

Bug fixes for line numbers and code dumper

---

.travis.yml
README.md
joern-install.sh

- Update Travis to include the install script in the release.
- Update README.

Modify installer to download distributons.

---

build.sbt

- Prevents a crash when running CPG enhancements over select projects.

Downgrade the version of CPG.

---

scripts/functions-to-dot/functions-to-dot.scala

- Fixes crash with Blender CPG.

Ignore unhandled node types.

---

build.sbt

- Fix command line parsing issue with the fuzzy preprocessor.

Bump fuzzyc2cpg version.

---

joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala
joern-server/src/main/resources/application.conf
joern-server/src/main/scala/io/shiftleft/joern/server/cpg/JoernCpgProvider.scala

Fixes https://github.com/ShiftLeftSecurity/fuzzyc2cpg/issues/165

Scan for .cc files by default

---

joern-cli/src/main/resources/scripts/c/scripts.json
joern-cli/src/main/resources/scripts/c/userspace-memory-access.sc
joern-cli/src/test/resources/testcode/syscalls/syscalls.c
joern-cli/src/test/scala/io/shiftleft/joern/RunScriptTests.scala

Tested on the Linux kernel source.

Add script to list accesses to userspace memory addresses.

---

build.sbt

placeholder for upgrading joern after https://github.com/ShiftLeftSecurity/codepropertygraph/pull/584

use latest dependencies

---

build.sbt
joern-cli/src/main/resources/scripts/c/malloc-leak.sc

Fixes build failure for `joern-lastest-dependencies`

Update to latest CPG version

---

build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala

Re: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/678

Adapt to changes in `codepropertygraph`

---

build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala
joern-cli/src/main/scala/io/shiftleft/joern/CpgLoader.scala

Re: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/681

Adaptions to changes in `codepropertygraph`

---

build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/console/AmmoniteBridge.scala

See https://github.com/ShiftLeftSecurity/codepropertygraph/pull/726

Prompt user to `save` on exit + bring in working copy of CPG

---

build.sbt

Brings in performance improvements for `importCode`. See https://github.com/ShiftLeftSecurity/codepropertygraph/pull/741 and
https://github.com/ShiftLeftSecurity/codepropertygraph/pull/742

Upgrade CPG

---

.gitignore
.travis.yml
build.sbt
joern-cli/build.sbt
joern-cli/src/universal/bin/scalac
joern-cli/src/universal/schema-extender.sh
project/Projects.scala
schema-extender/build.sbt
schema-extender/src/bash/test.sh

depends on https://github.com/ShiftLeftSecurity/codepropertygraph/pull/743

package schema-extender with joern-cli

---

.gitignore
.travis.yml
build.sbt
joern-cli/build.sbt
joern-cli/src/universal/bin/scalac
joern-cli/src/universal/schema-extender.sh
project/Projects.scala
schema-extender/build.sbt
schema-extender/src/bash/test.sh

This reverts commit 025154bc3282533ea143017eb31fce3749f18539.

Revert "Revert "package schema-extender with joern-cli (#258)""

---

joern-cli/src/main/resources/scripts/graph/ast-for-funcs-dump.sc
joern-cli/src/main/resources/scripts/graph/ast-for-funcs.sc
joern-cli/src/main/resources/scripts/graph/cfg-for-funcs-dump.sc
joern-cli/src/main/resources/scripts/graph/cfg-for-funcs.sc
joern-cli/src/main/resources/scripts/graph/cfgToDot.sc

This is part 1/2 - a few helper methods are still missing in odb.

use odb native api instead of tinkerpop

---

build.sbt
joern-cli/src/main/resources/scripts/graph/cfgToDot.sc

Brings in a fix for predictable node ids.

Upgrade dependencies

---

joernd

Missed it at the joern server removal

Remove `joernd` symlink

---

.travis.yml

My file grepping setup ignored dot files and I missed this one

Remove server mention from .travis.yml

---

docs2/docs/code-property-graph.mdx
docs2/docs/installation.mdx
docs2/docs/shell.mdx

Point to HTTPS URLS instead of HTTP

---

docs2/docusaurus.config.js

The Joern docs should always be in dark mode really.

Disable dark mode toggle

---

build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala
joern-cli/src/test/scala/io/shiftleft/joern/AbstractJoernCliTest.scala

This brings in the new fuzzyc2cpg, which is based on CPG passes. Fixes joern-latest-deps

Bring in pass-based fuzzyc

---

build.sbt
joern-cli/build.sbt

Test artifacts are now published separately
https://github.com/ShiftLeftSecurity/codepropertygraph/pull/965

Fetch test artifacts from codepropertygraph

---

build.sbt

Re: https://github.com/ShiftLeftSecurity/codepropertygraph/issues/955

Bring in fix for `ddgIn` and associated `dotDdg`.

---

build.sbt
joern-cli/src/main/resources/default.semantics
joern-cli/src/main/scala/io/shiftleft/joern/CpgBasedTool.scala
joern-cli/src/main/scala/io/shiftleft/joern/JoernExport.scala
joern-cli/src/main/scala/io/shiftleft/joern/JoernFlow.scala
joern-cli/src/universal/joern-flow
joern-flow

Introducing a new command line utility to showcase the capabilities of the data flow engine. `joern-flow <src> <dst>` will find all (source,sink) pairs and report sample flows for each.

Beta release of `joern-flow`

---

joern-cli/build.sbt

This is a bit of a controversy: for local development this is
expected, since the fuzzycpp binary is released to github from the cpg
release build. When using an official cpg release this should not fail
however.
Now, if we fail to download the binary, sbt prints a warning and
allows to retrieve the root exception.

make fuzzycpp download optional

---

docs2/package.json
docs2/yarn.lock

Removes usage of known vulnerable package versions

Update Node dependencies for documentation site

---

joern-cli/src/universal/bin/scalac
joern-cli/src/universal/schema-extender.sh

* generated classes are in the codeproperty-domain-classes.jar now
* the shipped scalac bash script was broken... not sure if this ever worked...

fix schema-extender

---

README.md
build.sbt
joern-cli/build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala
joern-cli/src/main/scala/io/shiftleft/joern/plume/PlumeCpgGenerator.scala

Seems to work but plume is crashing silently, see https://github.com/plume-oss/plume/pull/40 , so I'm waiting with the merge.
Update: fixed upstream, now the generated CPGs look alright.

Allow creating CPGs from jars

---

README.md
joern-install.sh

I'd like to make installing joern as simple as possible so this PR introduces non-interactive installation mode.

Non-interactive installation mode

---

README.md

While I'm fiddling with the non-interactive installer, I'm rewinding the README to suggest interactive installation.

README back to non-sudo installation

---

.github/workflows/pr.yml
joern-cli/build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/JoernScan.scala
joern-install.sh

Allows downloading and installing newest `query-database`, removing any old versions if present.

Introduce `joern-scan --updatedb`

---

joern-cli/src/main/scala/io/shiftleft/joern/JoernScan.scala
joern-install.sh

* Allow installation into custom directory (required to simplify plugin template)
* Allow installation without plugins

Installer polishing

---

joern-install.sh

One more installer feature I'm requiring for simplification of the extension template: choosing the version to install in non-interactive mode.

Allow custom version to be installed

---

build.sbt
joern-cli/build.sbt
project/build.properties

upgrade to scala 2.13.4 and latest cpg

---

joern-cli/build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/plume/PlumeCpgGenerator.scala

Re: https://github.com/ShiftLeftSecurity/joern/issues/450 - do not silently crash in `project`.

Do not swallow exceptions in Java CPG generation

---

joern-cli/build.sbt

Fixes https://github.com/ShiftLeftSecurity/joern/issues/450

Upgrade plume

---

joern-cli/build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/plume/PlumeCpgGenerator.scala

Reverting to enable debugging of a soot-related issue without time pressure: This reverts commit d517e88e3d0e7e8c3616f2565b1ac2cdacc8c7d2.

Revert "Simplified Java file intake (#460)"

---

joern-cli/build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/plume/PlumeCpgGenerator.scala

- Let Plume handle JAR intake internally
- v0.1.7 cleans up and initializes temporary files better

Simplified file intake and upgraded Plume version

---

build.sbt
joern-cli/build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala
joern-cli/src/main/scala/io/shiftleft/joern/plume/PlumeCpgGenerator.scala

Second try to bring in plume fixes.

Bring in Plume fixes

---

joern-cli/build.sbt

This reverts commit 28917e02d77278326a1a87a6e76f92b46f0cb4a6.

Revert "Upgrade plume (#481)"

---

joern-cli/src/main/scala/io/shiftleft/joern/JoernScan.scala

Contains a few tags for the query export

Update version of QueryDB

---

joern-cli/src/main/scala/io/shiftleft/joern/JoernScan.scala

```
$ ./joern-scan ./examples/ex1.c --overwrite
Detailed logs at: /tmp/joern-scan-log.txt
Result: 1.0 : Number of parameters larger than 4: /home/claudiu/code/joern/examples/ex1.c:3:two_rets
Result: 1.0 : Multiple returns: /home/claudiu/code/joern/examples/ex1.c:3:two_rets
Result: 8.0 : Dangerous function gets() used: /home/claudiu/code/joern/examples/ex1.c:16:main
$ ./joern-scan ./examples/ex1.c --overwrite --only-tags badfn
Detailed logs at: /tmp/joern-scan-log.txt
Result: 8.0 : Dangerous function gets() used: /home/claudiu/code/joern/examples/ex1.c:16:main
$ ./joern-scan ./examples/ex1.c --overwrite --only-tags metrics
Detailed logs at: /tmp/joern-scan-log.txt
Result: 1.0 : Number of parameters larger than 4: /home/claudiu/code/joern/examples/ex1.c:3:two_rets
$ ./joern-scan …
```

Filter scan queries by tags and name

---

joern-cli/src/main/resources/default.semantics

Sorting and renaming default operators

Sorting and renaming: default.semantics

---

build.sbt
joern-cli/build.sbt

feel free to merge if you quickly need to upgrade cpg, I'm working on
a separate branch to also port the schema extender

quickfix: upgrade cpg without porting schema extender

---

joern-cli/src/main/resources/default.semantics

Reverts ShiftLeftSecurity/joern#501
Need to check some tests.

Revert "Update default.semantics"

---

build.sbt

See https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1172

Bring in data flow engine bug fix

---

build.sbt
ghidra2cpg
ghidra2cpg-build/build.sbt
joern-cli/build.sbt
joern-cli/src/universal/ghidra2cpg
project/Projects.scala

use system zip because all jvm zip utils i tried delete file flags

include ghidra in distribution, this time for real

---

build.sbt
joern-cli/build.sbt

we don't publish anything to maven central as of now, so this doesn't have any real effect just yet...

use io.joern as organization

---

build.sbt
joern-cli/build.sbt

Revert "use io.joern as organization"

---

build.sbt
c2cpg.sh
joern-cli/build.sbt
joern-cli/src/main/scala/io/shiftleft/joern/C2Cpg.scala
joern-cli/src/universal/c2cpg.sh

```
sbt stage
./c2cpg.sh -o /tmp/cpg.bin example.c
./joern
```
with `Joern` results:
```
joern> importCpg("/tmp/cpg.bin") 
...
res0: Option[Cpg] = Some(value = io.shiftleft.codepropertygraph.Cpg@3f04847e)
joern> cpg.method.name("main").toList 
res1: List[Method] = List(
Method(
id -> 1000101L,
astParentFullName -> "<empty>",
astParentType -> "<empty>",
code -> "int main (int arr[0][0])",
columnNumber -> Some(value = 0),
columnNumberEnd -> Some(value = 0),
filename -> "/home/johannes/scratch/example.c",
fullName -> "main",
hash -> None,
isExternal -> false,
lineNumber -> Some(value = 1),
lineNumberEnd -> Some(value = 4),
name -> "main",
order -> 1,
signature -> "int main (int)"
)
)
```

Make it possible to run c2cpg directly

---

joern-cli/src/main/scala/io/shiftleft/joern/JoernScan.scala

A small change to add a `list-query-names` option to `joern-scan` which simply prints a sorted list of names of all the available queries, which is potentially useful for debugging. This doesn't contain any information that you could not get through the `dump` option, but avoids some JSON parsing.
```
❯ ./joern-scan --list-query-names
call-to-exec
call-to-gets
call-to-getwd
call-to-scanf
...
```

Add option to list available query names to joern-scan

---

updateDependencies.sh

follow-up on https://github.com/joernio/joern/pull/587
I was about to comment on the above PR but you were faster :)

add missing entries in updateDependencies.sh

---

joern-cli/src/main/scala/io/shiftleft/joern/JoernScan.scala

When users run `joern-scan` and no query bundles were installed, `joern-scan` would first generate the CPG only to then inform the user that bundles were not installed. Instead, we now first check whether queries are available, and if not, we bail out immediately.

Report missing querydb before generating CPG

---

build.sbt

Bump dependency versions

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala

fixes: https://github.com/joernio/joern/issues/684

c2cpg: fix end line number

---

build.sbt
joern-cli/frontends/fuzzyc2cpg/build.sbt

also some reshuffle of settings for better readability

fuzzyc: target jvm8 to support downstream java8 projects

---

build.sbt
joern-cli/src/main/resources/scripts/binary/mips-gadgets.sc
joern-cli/src/main/scala/io/joern/console/Predefined.scala

also adds a script for finding gadgets on mips.

Update dependencies and introduce `script`-shorthand

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala

Fixes: https://github.com/joernio/joern/issues/708

Fixes for global struct initialization

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala

This is a follow-up to https://github.com/joernio/joern/pull/711 plus some minor clean-ups.

Fixed order for locals from initialization 

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala

Previously, assignment calls were missing.
Fixes: https://github.com/joernio/joern/issues/516

Improved uniform initialization

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala

Fixes: https://github.com/joernio/joern/issues/719

Fixed declaration handling for declarations without explicit declarator

---

joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Ghidra2Cpg.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Main.scala
joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/fixtures/GhidraBinToCpgSuite.scala

Just a few minor edits to ghidra2cpg to increase readability as I'm debugging.

Minor cleanups for ghidra2cpg

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/TypeNodePassTests.scala

Fixes: https://github.com/ShiftLeftSecurity/codepropertygraph/issues/1526

Fixed typeFullName for IASTArrayDeclarator

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ControlStructureTests.scala

Notes:
* Add a `this` identifier for standalone `this` references (e.g. `switch (this) {`)
* Default to creating an `Unknown` node instead of an empty list when parsing an unhandled expression or statement. This improves general robustness

Add javasrc fixes for parsing pulsar and improve general robustness

---

.gitignore

should unbreak our release build
re https://github.com/joernio/joern/runs/4256197863

add test output files to gitignore

---

.gitignore

sorry this doesn't isn't required on my machine, maybe due to different
js setups, no idea, so i'm debugging this on gh actions...

more gitignore

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala

- Fixed bug where paths are misconfigured if a file is given as the source code path.
- Fixed issue where unnormalised paths would induce a similar issue. e.g. `/path/../to/./code`

Fixed jimple2cpg Source Code Path Misconfiguration Bug

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala

Fixes: https://github.com/joernio/joern/issues/777

Fixed call name and fullName for indirection on calls

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala

To be  consistent with the old frontend.
Fixes: https://github.com/joernio/joern/issues/776

Fix cast argument index 

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/FileDefaults.scala

Fixed CPP file extensions 

---

console/src/main/scala/io/joern/console/cpgcreation/package.scala

re https://github.com/joernio/joern/issues/788

check for more C file endings

---

console/src/main/scala/io/joern/console/Console.scala
console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala
console/src/test/scala/io/joern/console/ConsoleTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/SynchronizedTests.scala
querydb/src/test/scala/io/joern/scanners/c/QueryWithReachableBy.scala

before: 
after:
re https://discord.com/channels/832209896089976854/832214243230744626/913760581109047298

simplify types for ImportCode, since it's repl-user facing

---

joern-install.sh

fixes https://github.com/joernio/joern/issues/779

default install dir for root: /opt/joern

---

.gitignore

should fix release, see https://github.com/joernio/joern/runs/4417862051

gitignore for more js test artifacts

---

console/src/main/scala/io/joern/console/Console.scala

Fixes: https://github.com/joernio/joern/issues/782

Run image viewing asynchronously

---

build.sbt
console/src/main/scala/io/joern/console/Console.scala
console/src/main/scala/io/joern/console/Help.scala
console/src/test/scala/io/joern/console/HelpTests.scala
joern-cli/src/main/scala/io/joern/console/Predefined.scala

This only fixes the changes in @Doc annotation API and the corresponding
annotation extraction code.
Does not yet compile. @mpollmeier can you please adjust the usage of
methodReturn to your API change.

Bump CPG dependency and adjust to changed API.

---

joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Ghidra2Cpg.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/TypesPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/mips/MipsFunctionPass.scala

Seems that i only have moved the NPE before. 
Tested on multiple internal binaries.

MIPS: NPE fix for sorting

---

joern-cli/frontends/ghidra2cpg/build.sbt

Upgrade to new ghidra version

---

console/src/main/scala/io/joern/console/workspacehandling/WorkspaceManager.scala
console/src/test/scala/io/joern/console/workspacehandling/WorkspaceLoaderTests.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/unpacking/JarUnpacking.scala

Preparation for scala 3 migration.

Stop using classes from scala.reflect.io.

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala

c2cpg crashed on broken symlinks. This PR handles that.

Gracefully handle broken symlinks in c2cpg

---

build.sbt
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dotgenerator/DotAstGeneratorTests.scala
joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/dotgenerator/DotAstGeneratorTests.scala

Applied dot generation fix from upstream cpg

---

joern-cli/build.sbt
joern-cli/frontends/c2cpg/build.sbt
joern-cli/frontends/fuzzyc2cpg/build.sbt
joern-cli/frontends/javasrc2cpg/build.sbt
project/Versions.scala
updateDependencies.sh

* now looks at maven repo rather than git tags, to determine latest version
* only ask for actual changes
* more detailed feedback, e.g. what was the old version
Also: log4j

updateDependencies.sh: use maven repo as source of truth

---

build.sbt
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IOUtils.scala

Relies on: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1564

Fixed file reading for non-UTF8 encodings

---

build.sbt

Fix https://github.com/joernio/joern/issues/849

Update CPG to bring in fix for newc

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/LocationTests.scala

Fixes https://github.com/joernio/joern/issues/847

Add line number info to locals

---

build.sbt

Fixes https://github.com/joernio/joern/issues/847

Upgrade CPG to bring in `local` fix

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala

Fixes: https://github.com/joernio/joern/issues/854

Fixed types for local in array decls

---

build.sbt
joern-cli/src/main/resources/scripts/c/malloc-leak.sc
querydb/src/main/scala/io/joern/scanners/c/CopyLoops.scala
querydb/src/main/scala/io/joern/scanners/c/CredentialDrop.scala
querydb/src/main/scala/io/joern/scanners/c/DangerousFunctions.scala
querydb/src/main/scala/io/joern/scanners/c/FileOpRace.scala
querydb/src/main/scala/io/joern/scanners/c/HeapBasedOverflow.scala
querydb/src/main/scala/io/joern/scanners/c/IntegerTruncations.scala
querydb/src/main/scala/io/joern/scanners/c/Metrics.scala
querydb/src/main/scala/io/joern/scanners/c/MissingLengthCheck.scala
querydb/src/main/scala/io/joern/scanners/c/NullTermination.scala
querydb/src/main/scala/io/joern/scanners/c/QueryLangExtensions.scala
querydb/src/main/scala/io/joern/scanners/c/RetvalChecks.scala
querydb/src/main/scala/io/joern/scanners/c/SignedLeftShift.scala
querydb/src/main/scala/io/joern/scanners/c/SocketApi.scala
querydb/src/main/scala/io/joern/scanners/c/UseAfterFree.scala
querydb/src/main/scala/io/joern/scanners/ghidra/DangerousFunctions.scala
querydb/src/main/scala/io/joern/scanners/ghidra/UserInputIntoDangerousFunctions.scala
querydb/src/main/scala/io/joern/scanners/java/CertificateChecks.scala
querydb/src/main/scala/io/joern/scanners/java/CompilerOptimizations.scala
querydb/src/main/scala/io/joern/scanners/java/CrossSiteScripting.scala
querydb/src/main/scala/io/joern/scanners/java/DangerousFunctions.scala
querydb/src/main/scala/io/joern/scanners/java/SQLInjection.scala

Re: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1573

Adapt to changes in operator extension

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/TypeNodePassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/LocalsTests.scala
joern-cli/src/main/resources/scripts/c/pointer-to-int.sc

Fixes: https://github.com/joernio/joern/issues/863

Fixed type full names for pointers / structs

---

build.sbt
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala
joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/passes/AstCreationPassTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ArrayTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ObjectInstantiationTests.scala
joern-cli/src/main/resources/scripts/c/const-ish.sc
querydb/src/main/scala/io/joern/scanners/c/CopyLoops.scala
querydb/src/main/scala/io/joern/scanners/c/HeapBasedOverflow.scala
querydb/src/main/scala/io/joern/scanners/c/NullTermination.scala
querydb/src/main/scala/io/joern/scanners/c/QueryLangExtensions.scala

Bring in operator extension improvements

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IncludeAutoDiscovery.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/standard/TypeDeclTests.scala
joern-cli/src/main/resources/scripts/c/const-ish.sc

Also in this PR: improved handling of running gcc externally (only check once).

Fixed type full names with C/C++ restricted type specific keywords

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala

Fixes: https://github.com/joernio/joern/issues/869

Fixed code field for C++ qualified name field access

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ArithmeticOperationsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/AssignmentTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ClassLiteralTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ObjectExpressionTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ParenthesizedExpressionTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/QualifiedExpressionsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/SpecialOperatorsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/SubscriptTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ThisTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/types/InferenceJarValidationTests.scala

Fix a few props for Kotlin CPGs

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/AnnotatedExpressionsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/AnonymousFunctionsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ArithmeticOperationsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ArrayAccessExprsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/AssignmentTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ByTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallbackTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ClassLiteralTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ConstructorTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/DotQualifiedExpressionsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/FieldAccessTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LambdaTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ParenthesizedExpressionTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/QualifiedExpressionsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/SafeQualifiedExpressionsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/SpecialOperatorsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/StdLibTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/StringInterpolationTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/SuperTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeInferenceForAndroidSDKTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeInferenceTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/ValidationTests.scala

after a conversation with @ml86

Change dispatch type of Kotlin extensions

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kt2Cpg.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Main.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreationPass.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/NameGenerator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/Kt2CpgTestContext.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/integration/IntegrationTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/HigherOrderFnsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LambdaTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ScopeFunctionTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/StdLibTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeInferenceErrorsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/types/CompilerAPIStabilityTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/types/KotlinScriptFilteringTests.scala

- changes various FULL_NAMEs around lambdas
- adds new nodes around lambdas
- refactors a main component

Tweak AST around lambda-related Kotlin constructs

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LambdaTests.scala

Put Kotlin lambda TYPE_DECLS under NAMESPACE_BLOCK

---

build.sbt
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/HeaderContentLinkerPass.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/standard/MethodReturnTests.scala

For: https://github.com/joernio/joern/issues/947

Fixed method returns for c2cpg

---

dataflowengineoss/src/test/resources/default.semantics
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/DataFlowTests.scala
joern-cli/src/main/resources/default.semantics

For: https://github.com/joernio/joern/issues/954

Fixed <operator>.indirectIndexAccess semantics

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/NameGenerator.scala

saw this java-esque code in a PR... isn't this equivalent and better readable?
same pattern is used a few more times in this class...

refactor namegenerator

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/NameGenerator.scala

* replacing a lot of java-style with scala-style
* please review diligently

major refactor of NameGenerator

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/NamespaceBlockTests.scala

done mostly for the upstream, not required by spec

Add NAMESPACE_BLOCKs for Kotlin import stmts

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala

Certain types of CPP if statements may not contain a condition expr but a condition declaration instead.
re: https://discord.com/channels/832209896089976854/832214243230744626/943111748108574720

Fixed if statements for CPP

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Main.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/files/SourceFilesPicker.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/ConfigPass.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/CompilerAPI.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/InferenceSourcesPicker.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/utils/PathUtils.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/SourceFilesPickerTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/integration/IntegrationTests.scala

some files have gotten a bit too hard to read

Move misc kotlin2cpg logic into own files

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CustomFileContentProvider.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/PreprocessorPass.scala

* added support for C++ Array Designators
* added support for dangling declarations from unresolved macros (happens e.g., in/from system header files)
* replaced CDT file reading in our custom file content provider with the one from IOUtils dealing with non-UTF8 stuff correctly
* simplified the CdtParser interface

Several improvements for c2cpg

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/Report.scala

Fixes: https://github.com/joernio/joern/issues/1045

Fixed LOC reporting for non-UTF-8 files

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/NameGenerator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeRenderer.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeInferenceErrorsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/PrimitiveTypeMappingTests.scala

https://kotlinlang.org/docs/java-interop.html#mapped-types

Map renders of primitive arrays in Kotlin CPGs

---

build.sbt
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IOUtils.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Main.scala

Re: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1596

Update imports for IOUtils

---

build.sbt
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/HeaderContentPass.scala
joern-cli/frontends/x2cpg/build.sbt

This relies on https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1597

Migrate cpg passes to new style, using odb BatchedUpdate

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/DataFlowTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/standard/ControlStructureTests.scala

Fixes: https://github.com/joernio/joern/issues/1093

Fixed AST generation for for-loop with multiple assignments

---

console/src/test/scala/io/joern/console/testing/ConsoleFixture.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/C2Cpg.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/Main.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/CCodeToCpgSuite.scala
joern-cli/src/test/scala/io/joern/joerncli/AbstractJoernCliTest.scala

Re: https://github.com/joernio/joern/pull/1102

c2cpg: use base class `X2CpgFrontend`

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Main.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreationPass.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/Jimple2CpgTestContext.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/testfixtures/JimpleCodeToCpgFixture.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/unpacking/JarUnpacking.scala

Re: https://github.com/joernio/joern/pull/1102

jimple2cpg: use `X2CpgFrontend`

---

joern-cli/frontends/ghidra2cpg/build.sbt
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Ghidra2Cpg.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/FunctionPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/JumpPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/LiteralPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/NamespacePass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/arm/ArmFunctionPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/mips/LoHiPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/mips/MipsFunctionPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/mips/MipsReturnEdgesPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/x86/ReturnEdgesPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/x86/X86FunctionPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/processors/X86Processor.scala
joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/mips/CallArgumentsTest.scala
joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/mips/DataFlowThroughLoHiRegistersTests.scala
joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/x86/FileTests.scala
joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/x86/NamespaceBlockTests.scala

sbt test worked on my machine, let's see what the GH tests are complaining about

Ghidra2cpg: Reintroducing changes

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/FunctionCallTests.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/IfTests.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/LoopTests.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/ObjectTests.scala

Added the following tests:
- FunctionCallTests
- IfTests
- LoopTests

jimple2cpg: Function and Control-Flow Data-Flow Testing

---

.github/workflows/pr.yml

* this should shorten the wait time for PRs significantly
* also: use ubuntu 20.04

run testDistro job in parallel with other jobs

---

joern-cli/frontends/pysrc2cpg/pythonGrammar.jj
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/CodeToCpg.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/LineAndColumn.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2CpgOnFileSystem.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitorHelpers.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pythonparser/ast/Ast.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pythonparser/ast/AttributeProvider.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/FunctionDefCpgTests.scala

As requested by: https://github.com/joernio/joern/issues/1141

Add lineNumberEnd and columnNumberEnd properties to METHOD nodes.

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Constants.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2Cpg.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala

Create ANY TYPE_DECL and <global> NAMESPACE_BLOCK.

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Main.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/TestContext.scala

Forgot to remove it in the previous PR...

Remove `no-misc-jars` CLI flag for `kotlin2cpg`

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/DestructuringTests.scala

this logic needs some deduplication, but i'd rather do it in a separate pr

Lower kt destructuring decls with plain call rhs

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/Constants.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ControlStructureTests.scala

Fix lowering of `for-in` statements

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/DestructuringTests.scala

see docs:
https://kotlinlang.org/docs/destructuring-declarations.html#underscore-for-unused-variables

Ignore Kotlin's `_` destructuring constructs

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dotgenerator/DotCdgGeneratorTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala

Fixes: https://github.com/joernio/joern/issues/1274

Fixed c2cpg if statements without explicit blocks

---

.github/workflows/pr.yml
console/build.sbt
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/LocalsTests.scala

This is for: https://github.com/joernio/joern/issues/1256

c2cpg: re-added modifier to code field of local

---

joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/TestCpg.scala

Forgot to use suffix variable and put specific suffix .java...

Fix TestCpg.

---

composer-setup.php
joern-cli/frontends/php2cpg/installdeps.sh

alternative to https://github.com/joernio/joern/pull/1335

use fixed version of the php installer

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/LocalsTests.scala

Fixes: https://github.com/joernio/joern/issues/1341

Fixed code field of locals for multiple declarations in one place

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala

I forgot to clean up all the variable names when I made the change to use `Ast` instead of `AstWithCtx`.

javasrc: Remove WithCtx from ast variable names

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala

We in some cases (see new tests) had methodFullName on CALLs set to the
actual implementation method and not to the actual statically assure
methodFullName.

Fix CALL methodFullName.

---

console/src/main/scala/io/joern/console/Commit.scala
console/src/main/scala/io/joern/console/Run.scala

fixes https://github.com/joernio/joern/issues/1379

fix store step missing implicit by bringing back the deprecated old DiffGraphBuilder

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoCalculator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeTests.scala

Fixes https://github.com/joernio/joern/issues/1385.

javasrc: Fix crash when getting wildcard type name

---

joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/dependency/DependencyResolverTests.scala

e.g.  `io.joern.x2cpg.utils.dependency.DependencyResolverTests`
without the change, the release action fails with:
```
Run sbt ciReleaseTagNextVersion ciReleaseSonatype createDistribution
[info] welcome to sbt 1.6.2 (AdoptOpenJDK Java 11.0.11)
[info] loading settings for project joern-build from meta-build.sbt,plugins.sbt ...
[info] loading project definition from /home/runner/work/joern/joern/project
[info] loading settings for project joerncli from build.sbt ...
[info] loading settings for project querydb from build.sbt ...
[info] loading settings for project console from build.sbt ...
[info] loading settings for project dataflowengineoss from build.sbt ...
[info] loading settings for project macros from build.sbt ...
[info] loading settings for project semanticcpg from build.sbt ... …
```

Introduce new test fixture for Gradle test suite

---

joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/Code2CpgFixture.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/TestCpg.scala

The class extending Code2CpgFixture can now override the applyPasses
method in order to run more passes than in the default setup.
I also moved the code directory cleanup to TestCpg class to have
directory creation and deletion in the same place.
This change was triggered by the discussion in:
https://github.com/ShiftLeftSecurity/js2cpg/pull/168

Provide override mechanism for cpg passes in Code2CpgFixture.

---

joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/dependency/DependencyResolverTests.scala

Without this change, IntelliJ 2021.3.2 does not detect individual test
cases, which makes them annoying to run individually.

Restructure dependency resolver test suite

---

joern-cli/src/main/scala/io/joern/joerncli/console/JoernConsole.scala

fixes https://github.com/joernio/joern/issues/1380

fix `version`

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/GradleDependencies.scala

blind attempt at getting more info about a failed analysis in a specific
environment, with the following full log of a `kotlin2cpg` analysis:
```
2022-05-17 16:37:03.974 INFO initializing 0 nodes from existing storage
2022-05-17 16:37:03.984 INFO installed GC monitors. will clear references if heap (after GC) is larger than 80%
2022-05-17 16:37:04.002 INFO Fetching Gradle project information at path `.` with project name `app`.
Downloading https://services.gradle.org/distributions/gradle-5.6.4-all.zip
.....................................................................................................................................
2022-05-17 16:37:23.747 INFO shutdown: start
2022-05-17 16:37:23.754 INFO shutdown finished
```

Add try-catch around Gradle Tooling API usage

---

benchmarks/README.md
benchmarks/src/test/resources/default.semantics
benchmarks/src/test/scala/io/joern/benchmarks/testfixtures/BenchmarkFixture.scala
joern-cli/src/main/resources/default.semantics

- Added default semantic for `PrintWriter.println`
- This has drastically improved the results for Securibench

Improved Java False Positives with a println Semantic

---

joern-cli/frontends/javasrc2cpg/build.sbt

fixes https://github.com/joernio/joern/issues/1429

javasrc: explicitly add gradle-tooling-api to classpath

---

console/src/main/scala/io/joern/console/BridgeBase.scala
console/src/main/scala/io/joern/console/PluginManager.scala
joern-cli/src/main/scala/io/joern/joerncli/CpgBasedTool.scala
joern-cli/src/main/scala/io/joern/joerncli/JoernParse.scala
joern-cli/src/main/scala/io/joern/joerncli/JoernScan.scala

I'm currently reviewing the plugin API and attempting to simplify it. While doing so, I cleaned up `BridgeBase`, which holds the entry points for the plugin API in particular.

Cleanup of `BridgeBase`

---

joern-cli/src/universal/js2cpg.bat
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NodeTypeStarters.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/package.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/ImportTraversal.scala

A tiny bit of query language for dealing with import nodes - required for a demo.

A bit of language for IMPORT nodes

---

README.md

- Added badges to indicate the latest version on ScalaDex and number of downloads from GitHub
- Removed stray paragraph about javasrc

Added more badges and cleaned up README

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/callgraph/StaticCallLinker.scala

not really a game changer, i was simply looking at 
https://github.com/joernio/joern/pull/1478/files#diff-9ec67418d9561f635eb57b8f871771ad601f47b64af4246b810a64908fd904cdR21-R24 
while waiting for a build...

StaticCallLinker: minor refactoring

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala

this should help me debug an sptests-javasrc issue...

javasrc: add log message about how many source files we found

---

build.sbt
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NodeTypeStarters.scala

This is related to https://github.com/ShiftLeftSecurity/overflowdb/pull/309
Version will be fixed once upstream is merged.

make it easier to use the odb index for traversals

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala

encountered on https://github.com/tachiyomiorg/tachiyomi

Fix NPE in `kotlin2cpg`

---

console/build.sbt
joern-cli/build.sbt
joern-cli/frontends/c2cpg/build.sbt
querydb/build.sbt

https://github.com/eclipse-equinox/equinox.bundles/issues/54 has been fixed

Dependencies resolution workaround no longer needed

---

joern-cli/frontends/jssrc2cpg/README.md
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala

Clean-ups and removed some code duplication.

jssrc2cpg: more refactorings

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/standard/CMethodTests.scala

Fixes: https://github.com/joernio/joern/issues/1517

c2cpg: normalize method names/signature

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TsAstCreationPassTest.scala

Also: fixed type decl parent for declared functions

jssrc2cpg: support for declared classes

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/NodeBuilders.scala

Another small cleanup PR, mostly for modifiers.

javasrc cleanup #2

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala

Fixes https://github.com/ShiftLeftSecurity/codescience/issues/6289

Fix name for  identifier nodes

---

joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/dataflow/SimpleDataFlowTests.scala
joern-cli/src/main/resources/default.semantics

& update semantics for special operators

kotlin2cpg: add more dataflow tests

---

joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/ExcludeTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/ProjectParseTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/AbstractPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/AstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/BuiltinTypesPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ConfigPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/DependenciesPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TsAstCreationPassTest.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NodeTypeStarters.scala

Also in this PR: added dependency to NodeTypeStarters

jssrc2cpg: test refactorings

---

.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/upgrade-deps.yml
README.md
joern-cli/frontends/jssrc2cpg/README.md
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/Main.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/Environment.scala

I was finally able to build a native custom version of astgen (based on @joernio/astgen 2.0.4) using 'pkg' (available [here](https://github.com/max-leuthaeuser/astgen)).
This enables us to run it entirely without node (as a stripped down node comes with the binary), and it is ultimately much faster.

jssrc2cpg: bring in native astgen invocation

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/DependencyResolver.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/MavenDependencies.scala
joern-cli/src/universal/conf/log4j2.xml

Fix Maven dependency fetching for multiple sub-projects

---

console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala
console/src/test/scala/io/joern/console/ConsoleTests.scala

Fixes: https://github.com/joernio/joern/issues/1607

console: warn about non-existent dir

---

sdkman_release_new_candidate_version.sh

see: https://sdkman.io/vendors
```
$ sdk list
// output trimmed...
Joern (1.1.997)                                                https://joern.io/
Joern is a platform for analyzing source code, bytecode, and binary executables.
It generates code property graphs (CPGs), a graph representation of code for
cross-language code analysis. Code property graphs are stored in a custom graph
database. This allows code to be mined using search queries formulated in a
Scala-based domain-specific query language. Joern is developed with the goal of
providing a useful tool for vulnerability discovery and research in static
program analysis.
$ sdk install joern
```

Add script for publishing to `SDKMAN!`

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/MethodMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/MethodTraversal.scala

fixes https://github.com/joernio/joern/issues/1597

method.typeDecl as alias for method.definingTypeDecl

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/compiler/CompilerAPI.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/files/SourceFilesPicker.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreationPass.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala

one-liner to find spots using it
```
grep '[^"]*"[^"]*"[^+]+' -R joern-cli/frontends/kotlin2cpg/src/main -n -I
```

kotlin2cpg: use string interpolation instead of +

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/C2Cpg.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/Defines.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/datastructures/CGlobal.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/DefaultDefines.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/FileDefaults.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IOUtils.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CompleteCpgFixture.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CpgAstOnlyFixture.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CpgCfgFixture.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CpgTypeNodeFixture.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/TestAstOnlyFixture.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala

- formatting
- removal of dead code
- improved CGlobal and its type storage / generation handling (for seen types during CPG construction)

c2cpg: clean-up and refactoring

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/dataflow/TypeDeclTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ConstructorTests.scala

- various METHOD nodes of class methods were missing the VIRTUAL
modifier
- METHOD_RETURN nodes of ctors had two incorrect props set

kotlin2cpg: tweak ASTs around classes

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/BindingTable.scala

Fix a crash encountered in https://git.magnolia-cms.com/projects/platform/repos/main.pub/browse

Fix crash when getting annotation methods

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/Main.scala

Fixes: https://github.com/joernio/joern/issues/1683

jssrc2cpg: fixed scanning with relativ input path

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

This is for: https://github.com/joernio/joern/issues/1685

jssrc2cpg: fix call receiver and base handling

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/DependencyAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

We had dangling sub ASTs for multiple declarators in the same declaration.
This fixes crashes with the closed-source DF engine.

jssrc2cpg: fix declaration handling

---

console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala
console/src/test/scala/io/joern/console/testing/ConsoleFixture.scala

so there's no excuses anymore for me not to produce minimal test-cases

add importCode.*.fromString for more languages

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala

This PR wraps all resolve calls in `tryWithSafeStackOverflow`, since these issues seem to be popping up all over. This is an ugly implementation which will be replaced with a more elegant one in future.

Catch more javasrc2cpg stack overflow issues

---

.github/workflows/pr.yml
.github/workflows/release.yml

see https://github.com/actions/runner-images/issues/6002

`s/ubuntu-18.04/ubuntu-20.04/g` GitHub Action vms

---

joern-cli/frontends/kotlin2cpg/build.sbt
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Main.scala

experimental feature
example invocation:
```
./kotlin2cpg.sh ~/src/http4k-webgoat --jar4import-url http://localhost:8081
```

kotlin2cpg: fetch dependencies via `jar4import`

---

joern-cli/frontends/solidity2cpg/src/main/scala/io/joern/solidity2cpg/passes/AstCreator.scala

The first in a series of cleanup PRs. Any TODOs can be ignored since I just added those as notes to myself for later, more ambitious changes.
Note: Checks on these PRs will fail until I've updated the setup scripts to install surya, so ignore any red crosses for now. I'll verify that unit tests pass locally before opening any of these PRs.

Solidity2cpg Cleanup #1

---

build.sbt

depends on https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1658

upgrade deps

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/OperatorTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ExternalCommand.scala

*also includes some php2cpg cleanup

Add PHP unary and binary operations and fix ExternalCommand race condition

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala

This fixes a bug where import information wasn't being used to figure out the method return type if it could not be resolved by JavaParser. It also removes some redundant type resolution.

Fix javasrc2cpg MethodReturn type bug

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/Constants.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeRenderer.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ResolutionErrorsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeAliasTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/MissingTypeInformationTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/ValidationTests.scala

... instead of own defined in kotlin2cpg.

Use Defines.UnresolvedNamespace and Defines.UnresolvedSignature.

---

joern-cli/frontends/php2cpg/bin/php-parse
joern-cli/frontends/php2cpg/php2cpg

Fixes https://github.com/joernio/joern/issues/1740

Fix php symlinks issue

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/EnumTypeTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/StructTypeTests.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/1758

Fixed class member initialization lowering for c2cpg and jssrc2cpg

---

joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/CodeDumperTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/ProjectParseTest.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/codedumper/CodeDumper.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NodeSteps.scala

Required modifications to NodeSteps and CoreDumper to account for relative paths.
Fixes: https://github.com/joernio/joern/issues/1514

jssrc2cpg: enable .dump

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/EnumTypeTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/StructTypeTests.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/NameConstants.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MemberTests.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/EnumTests.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Defines.scala

It is now available for all frontends as helper method in AstCreatorBase. c2cpg, jssrc2cpg, and javasrc2cpg now make use of it.

Refactored creation of static initialization method

---

console/src/main/scala/io/joern/console/Commit.scala
console/src/main/scala/io/joern/console/Run.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NewNodeSteps.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NewTagNodePairTraversal.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/testing/package.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/NewNodeStepsTests.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/types/structure/MethodTests.scala

Revert "Replace deprecated usage of CpgPass and DiffGraph.newBuilder"

---

joern-cli/src/main/scala/io/joern/joerncli/JoernVectors.scala

* Include `label` in node properties
* Only emit certain fields
* Only emit internal methods

Improve `joern-vectors`

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala

This PR provides some very basic support for tracking into lambda methods + a test showing how that affects JS CPGs.

ossdataflowengine: handle method references

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/MethodStubCreator.scala

Fixes https://github.com/joernio/joern/issues/1782

Ensure that METHOD_RETURN is last

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CfgTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/PocTest.scala

Also fixes the CFG for switch bodies by creating a block to wrap around the body statements.

Add PHP do statements and cfg tests

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/codedumper/SourceHighlighter.scala

Fixes: https://github.com/joernio/joern/issues/1787

Enable source highlighting with .dump for JSSRC and JAVASCRIPT

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NewTagNodePairTraversal.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/testing/package.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/types/structure/MethodTests.scala

doing this in smaller chunks than the previous attempt https://github.com/joernio/joern/pull/1778/files

Remove `semanticcpg/testing` deprecated class use

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CfgTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala

Also removes the pushing/popping of block scopes, since this doesn't make sense for PHP code.

Add PHP try-catch and throw

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NewNodeSteps.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NewTagNodePairTraversal.scala

helper trait to ease the switch to the new DiffGraph API

Introduce `HasStoreAndPersistMethods` trait

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/Defines.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/TypeNodePass.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala

requested after Lukas' experiments

jssrc2cpg: multiple fixes for TS type handling

---

build.sbt
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/datastructures/Scope.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/PocTest.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala

Field accesses, method calls and anonymous classes are still a TODO.

Add PHP classes, methods, class constants and fields

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/DataFlowCodeToCpgSuite.scala

With ```EngineContext(config = EngineConfig(maxCallDepth = 4))``` 😂

Fix pending dataflow test case in C

---

benchmarks/src/test/scala/io/joern/benchmarks/testfixtures/BenchmarkFixture.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/DataFlowCodeToCpgSuite.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaDataflowFixture.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/testfixtures/JimpleDataflowFixture.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/testfixtures/PhpCode2CpgFixture.scala

https://github.com/joernio/joern/pull/1837
https://github.com/joernio/joern/pull/1841

Clean up maxCallDepth in test fixtures

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/ExpressionMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/generalizations/ExpressionTraversal.scala

Also an assortment of minor (assumed) bugs. This came up during review of https://github.com/ShiftLeftSecurity/codescience/pull/6567

fix expressionUp

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/datastructures/Scope.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CallTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CfgTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/NamespaceTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala

This also adds namespaces and some methodFullNames (with unresolved signatures)

Add PHP method calls and misc small statements

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala

As reported by @itsacoderepo, there is an issue where some methods crash if they are built from a non-Java language. An example is analysing Scala-build JAR files. 
The fix is to simply add, for example, the Scala 2.12 SDK JAR to the analysis, but the current error messages don't make this obvious. In this change, I have added a few heuristics to point this out.
This, however, points to a bigger issue where the SDK that is brought in is interpreted as internal code. This may or may not be intended, so we may want a way to configure marking the SDK as excluded or find a way to give this to Soot as a library.

jimple2cpg: Helpful Error Message when JVM Language SDK is Required

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotSerializer.scala

Improve dot ast

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/datastructures/ArrayIndexTracker.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ArrayTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CommentTests.scala

Also adds support for the PHP-Parser specific `Nop` statement, but until comment support is added, that's just to prevent crashes.

Add PHP arrays and array accesses

---

build.sbt
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala

Both of these are new control structure types, so CFGs are still TODO.

Add PHP match and yield expressions

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/1915

jssrc2cpg: set typeFullName for literals with primitive types

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/DependencyAstCreationPassTest.scala

jssrc2cpg: fixed generation of names for SpreadElements

---

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala

Changed this anyway while testing something else.

Convert just a few JavaSrc frontend tests to new test fixture.

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/ObjectTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/RequirePassTests.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/dependency/DependencyResolverTests.scala

Detect when we are trying to solve a task again (with the same context), and if so, don't do it.
Also disables a flaky test.

ossdataflowengine: do not solve the same task twice

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/KtPsiToAst.scala

request from @mpollmeier for scala3 migration

kotlin2cpg: move file to different namespace

---

joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/AnonymousFunctionsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallGraphTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallbackTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallsToConstructorTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ConstructorTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/DestructuringTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/GenericsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/InnerClassesTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LabeledExpressionsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LocalClassesTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LocalFunctionsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/SafeQualifiedExpressionsTests.scala

add type annotations for implicits

---

benchmarks/README.md
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/DefaultSemantics.scala

- Added a bunch of C semantics
- Added a bunch of Java semantics
- Updated Joern benchmark results → better precision for `SecuribenchMicro`

DefaultSemantics: More C and Java Semantics

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/xml/SecureXmlParsing.scala
querydb/src/main/scala/io/joern/scanners/android/AndroidMisconfigurations.scala

x2cpg: add class for secure xml parsing

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/JavascriptCallLinker.scala
querydb/src/main/scala/io/joern/querydb/language/android/ManifestXmlTraversal.scala
querydb/src/main/scala/io/joern/scanners/android/Intents.scala

at @mpollmeier's recommendation

querydb: change namespace of single class

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskSolver.scala

In the past, we solved data flow tasks in parallel but derivation of new tasks from results was done on one core. We now perform task creation as the last step of task solving, meaning that tasks are now also created in parallel. Nonetheless, they are submitted in a single thread, making it possible to ensure that each task is only solved once.

Perform task creation in parallel

---

dataflowengineoss/build.sbt
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala

The recently introduced last stage of data flow calculation - where held tasks are completed based on table lookup - can be run in parallel.

Run handling of held tasks in parallel.

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/dotgenerator/DotDdgGeneratorTests.scala

I'm not the best person to judge wether those calls really _should_
be part of the DDG, but from our discussion on
[discord](https://discord.com/channels/832209896089976854/832209896089976857/1044687371800678420)
it sounds like the answer is 'yes'.
Anywhere, since I was asked about this I just added a (failing) test
to hopefully make it easier to grok the context and take it from
there.

WIP add (failing) test to verify that two calls are part of the DDG

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeRenderer.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/InnerClassesTests.scala

& change METHOD_FULL_NAMES of inner classes from `pkg.Outer.Inner` to `pkg.Outer$Inner`

kotlin2cpg: refactor `TypeRenderer`

---

console/src/main/scala/io/joern/console/cpgcreation/package.scala
tests/frontends-smoketest.sc
tests/frontends-tests.sh

without this change:
```scala
joern> importCode.python.fromString("""
def my_fun():
println("Hello, world!")
def main():
my_fun()""")
io.joern.console.ConsoleException: unable to generate cpg from given String
io.joern.console.ConsoleException: no cpg generator for language=PYTHON available!
```

fix python frontend wiring and add test

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/MixedCfgCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2034

jssrc2cpg: proper code for destructuring assignments

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/ExtendedCfgNode.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala

Parallelised task creation, as well as parallelised end result processing inside reachableByInternal.

Improved parallel processing of reachableByFlows

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/VueJsDomAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2045

jssrc2cpg: added synthetic variable assignments from class definitions

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2047

jssrc2cpg: fixed handling of ThisExpression

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2049

jssrc2cpg: fixed argument indizes in push calls within desugared array literals

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/VueJsDomAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2052

jssrc2cpg: added missing locals / closure bindings for implicit variables from class definitions

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala

jssrc2cpg: remove left-over typeref

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/DependencyAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/VueJsDomAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2066
Fixes: https://github.com/joernio/joern/issues/2067
Fixes: https://github.com/joernio/joern/issues/2069

jssrc2cpg: fixes for 2066, 2067, 2069

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/MethodStubCreator.scala

While debugging an issue, I discovered that the MethodStubCreator does not create formal instance parameters for dynamically dispatched calls. This PR fixes that.

MethodStubCreator: add instance for dynamic calls

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ConfigPass.scala

Fixes: https://github.com/joernio/joern/issues/2083

jssrc2cpg: added .pug files as config files

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/HeaderContentPass.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/FileTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/MethodTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/ClassTypeTests.scala

For: https://shiftleftinc.atlassian.net/browse/SEN-300

c2cpg: get rid of absolut paths

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2084

jssrc2cpg: fix missing closure bindings for destructing elements

---

build.sbt
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/ProjectParseTest.scala

Fixes: https://github.com/joernio/joern/issues/2087

Update cpg and fix #2087

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala

Forgot about this piece here.
edit: I will do a round of refactoring later on to extract this to a helper method.

c2cpg: fix relative/absolute path handling 2

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskCreator.scala

This reverts commit ad109a2d242ab7e06f2cd8bd0fddc2d58b2b5b37.

Revert "Do not create new tasks for literal sinks (#2098)"

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IOUtils.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/dotgenerator/DotDdgGeneratorTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/macros/MacroHandlingTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/FileTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/MethodTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/ClassTypeTests.scala

Mostly for relative/absolute path handling (left-overs from last PRs on that)

c2cpg: cleanups and refactorings

---

benchmarks/src/test/resources/default.semantics
benchmarks/src/test/scala/io/joern/benchmarks/testfixtures/BenchmarkFixture.scala
dataflowengineoss/README.md
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/DefaultSemantics.scala
dataflowengineoss/src/test/resources/default.semantics
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/x86/DataFlowTests.scala
querydb/src/test/resources/default.semantics

Fixes: https://github.com/joernio/joern/issues/2114
Also: removed remaining occurrences of default.semantics

c2cpg: fixed handling of expression lists in unary nodes

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala

Fixes: https://github.com/joernio/joern/issues/2118

c2cpg: fixed macro call / block handling and macro call filename

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/datastructures/CGlobal.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/HeaderContentPass.scala

Follow up and partial revert of https://github.com/joernio/joern/pull/2139
Otherwise, we lose intern/extern information for methods which fails SCA analysis.

c2cpg: fix dangling sub ASTs (2)

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala

The results produced when completing a task only depend on the entries in the main table for the fingerprint of the task. Therefore, we only have to recalculate results for a task when there are changes in those entries, as opposed to recalculating whenever any entry has changed.

Optimze `completeHeldTasks`

---

project/build.properties

Because of this issue https://github.com/sbt/sbt/issues/7117

Bumps sbt.version (1.8.2)

---

.gitignore

This is some Coursier cache folder.

Added null/ to .gitignore

---

console/build.sbt
joern-cli/build.sbt

* continuation of https://github.com/joernio/joern/pull/2180

speed up build: run console and joern-cli tests in parallel

---

.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/upgrade-deps.yml
README.md
joern-cli/src/universal/schema-extender/sbt
joern-cli/src/universal/schema-extender/schema/src/main/scala/CpgExtCodegen.scala

partly driven by https://github.com/Homebrew/homebrew-core/pull/120622

upgrade to JDK 17

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/HeldTaskCompletion.scala

Before I forget how this works, I'd rather comment it.

Add comments for held task completion

---

console/src/main/java/io/github/retronym/java9rtexport/Export.java

will test this here first and then provide an upstream fix

shadow io.github.retronym.java9rtexport.Export with bugfix

---

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/CallCpgTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/impl/PythonTypeHintCallLinker.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/impl/PythonTypeRecovery.scala

- Added tests for field assignments and field invocations
- Separated test suite and now testing on 3 categories
- Fixed bug where callee names may be duplicated and falsely not set `methodFullName`
- Moved language specific `calleeNames` implementation out of `XTypeHintCallLinker`

[PythonTypeRecovery] Field invocation type speculation

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/CallLinkerPassTest.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/JavascriptCallLinker.scala

Fixes: https://discord.com/channels/832209896089976854/832209896089976857/1069951841456099338

jssrc2cpg: fixed JS call linker for this expressions

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/Main.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/ExcludeTest.scala

Works exactly like in js2cpg and jssrc2cpg.
For: https://shiftleftinc.atlassian.net/browse/SEN-433
(We want this for all frontends I guess. Next refactoring step is to extract this to x2cpg)

c2cpg: added --exclude and --exclude-regex

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2236

jssrc2cpg: fixed closure bindings for locals from identifiers with type annotation

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/DependencyAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2239
Fixes: https://github.com/joernio/joern/issues/2237

jssrc2cpg: fixes for export lowering and destructed params

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/ReturnTests.scala

fix dataflow of return statement

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/KtPsiToAst.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala

Also adds code/line/column properties on javasrc2cpg' `astForDo` - figured I might as well.

x2cpg: Introduces (do)whileAst methods in AstCreatorBase

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

Fix minor bug in previous PR on handling of flows starting in member variables in Python.

Fix for #2252

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

- Avoid crashing when encountering unexpected symbols
- Handle most warnings on real-world programs
- Log errors with DEBUG instead of WARN

XTypeRecovery: Graceful Error Handling

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/ReturnTests.scala

This PR handles dataflow of ```return new Bar()```, which is lowered to
`return {Bar tmp = Bar.alloc(); tmp.init(); tmp}`

Fix dataflow for return statement like return new XXX(...)

---

build.sbt
joern-cli/frontends/ghidra2cpg/build.sbt
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/SimpleCombinedTypeSolver.scala
joern-cli/frontends/jimple2cpg/build.sbt
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ImportsPass.scala
joern-cli/frontends/kotlin2cpg/build.sbt
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/KtPsiToAst.scala
joern-cli/frontends/php2cpg/build.sbt
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/pysrc2cpg/build.sbt
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala
joern-cli/frontends/x2cpg/build.sbt
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/TestCpg.scala
joern-cli/src/main/scala/io/joern/joerncli/JoernSlice.scala
querydb/build.sbt
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/NewNodeStepsTests.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/StepsTest.scala

Mostly from the Scala 3 compiler (warnings) and Intellij linting.

Refactoring / clean-ups

---

.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/upgrade-deps.yml

https://github.com/coursier/cache-action

github actions: configure cache

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/AnnotationTests.scala

- Added line number info for annotation nodes

javasrc2cpg: Line Numbers for Annotations

---

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

Added few unit tests to test flows from global variable

Unit test for flows from global variable

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/FunctionDefCpgTests.scala

* Simplified methodParameterNode to replace overridden parameters with their optional equivalents
* Parse type hints for parameters and returns and add them to `dynamicTypeHintFullName`
* If hint is detected as a builtin or from the typing package, the full name is given instead of the symbol alone

pysrc2cpg: Type Hint Support for Parameters and Returns

---

joern-cli/src/main/scala/io/joern/joerncli/JoernParse.scala
joern-cli/src/main/scala/io/joern/joerncli/JoernSlice.scala
joern-install.sh

* Added `joern-slice` symlink to `joern_install.sh`
* Check extension before appending to output file
* Joern slice can generate CPG if given code using code from `JoernParse`

joern-slice: Quality Improvements

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/src/main/scala/io/joern/joerncli/slicing/UsageSlicing.scala
joern-cli/src/main/scala/io/joern/joerncli/slicing/package.scala
joern-cli/src/test/resources/testcode/jssrc-slice/main.js
joern-cli/src/test/scala/io/joern/joerncli/AbstractJoernCliTest.scala
joern-cli/src/test/scala/io/joern/joerncli/JoernSliceTests.scala

* Do not extract UDTs without fields and method definitions
* Extended JoernCLI testing to handle other languages
* Added test for usage slices
* Fixed handling of constructors and do not slice temporary variables

JoernSlice: Added Testing & Fixed Constructor Handling

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/macros/MacroHandlingTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/StructTypeTests.scala

Fixes: https://github.com/joernio/joern/issues/2335

c2cpg: fixed handling of macros in binary expressions

---

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

Added a UT to trace flow of function params to sinks.

Python: Added UT for function param tracing

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitorHelpers.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonNaiveCallLinker.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeHintCallLinker.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

To increase readability and be more conform to Scala coding conventions.

py2cpg: small refactorings

---

joern-cli/frontends/rubysrc2cpg/build.sbt
joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyLexer.g4
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala

This is only a starting point. Stuff like regex literals or heredocs are next. However, I figured this is enough of a lexer for us to start fleshing out the parser as well.

Ruby: Adding a skeleton lexer

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsDecoratorAstCreationPassTest.scala

Decorators are added as Annotations now at
- functions
- parameters
- classes
just like we do in javasrc2cpg.

jssrc2cpg: added support for Decorators

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala

And applied that to jssrc2cpg and javasrc2cpg.

Extracted annotation AST creation to AstCreatorBase

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

Additional test case along with windows issue fix for .import use case handling for Python.

Additional test case along with windows issue fix for .import use case handling for Python

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TypeRecoveryPassTests.scala

(`.isInstanceOf[Some[Block]]` does not work due to type erasure)
And a small refactoring for its tests.

jssrc2cpg: small fix for JavaScriptTypeRecovery

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsClassesAstCreationPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsDecoratorAstCreationPassTest.scala

We need them in CS to resolve requires/imports and build synthetic type decls.

jssrc2cpg: add typedecl members for class/interface functions

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/VueJsDomAstCreationPassTest.scala

Another fix for JSXAttribute handling (binds).

jssrc2cpg: fix for vue.js handling

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTemplateDomCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/VueJsDomAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2399

jssrc2cpg: restore Vue attribute colon

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/SimpleCfgCreationPassTest.scala

https://github.com/joernio/joern/issues/2404

[jssrc2cpg]Order of assignments

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/Path.scala

related: 
https://github.com/joernio/joern/pull/2366
https://discord.com/channels/832209896089976854/832214243230744626/1087990504836309072

dataflow tracked column: allow to configure width via env var

---

joern-cli/frontends/ghidra2cpg/build.sbt
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Ghidra2Cpg.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/FunctionPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/NamespacePass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/mips/MipsFunctionPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/utils/Decompiler.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/utils/Utils.scala
joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/mips/CallArgumentsTest.scala

fixes https://github.com/joernio/joern/issues/2416

upgrade ghidra to 10.2.3 and fix many nullpointer exceptions

---

console/src/main/scala/io/joern/console/BridgeBase.scala

fixes https://github.com/joernio/joern/issues/2460

joern-scan: map `JAVA` binary input to `importCode.jvm`

---

console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/InheritanceFullNamePass.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/InheritanceFullNamePass.scala

* Added a pass to heuristically determine possible super classes
* Will then modify the type declaration accordingly
* Modified the type recovery pass to no longer compensate for this missing info
This is added as a pass since it is not an exact science, so it would be best to allow it to be optional.

pysrc2cpg: Inheritance Full Name Pass

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

For-in/of loops may also be written without explicit loop variable declaration.

jssrc2cpg: more for-in/of loop support

---

joern-cli/src/main/scala/io/joern/joerncli/slicing/UsageSlicing.scala

Wrapped a `Try` around the weird race error of a query not finding a `methodReturn` when one is in fact present. More info [on this thread.](https://github.com/joernio/joern/issues/2463#issuecomment-1504867212)
Resolves #2463
cc: @pr0me

JoernSlice: Flaky Slice Hotfix

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/HeaderContentPass.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/DependencyTests.scala

For #include directives.
Consistent to jssrc2cpg's require/import.

c2cpg: added creation of dependency and import nodes

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

* Instead of using `Call` nodes with `import` in the properties, make use of the official `ImportNode`
* Remove legacy `Call` import handling from `XTypeRecovery`
`XTypeRecovery` now fully focuses around `Import` nodes when dealing with imported external entities.

PythonTypeRecovery: Use `Import` Node

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MethodTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/NamespaceTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala

Fixes https://github.com/joernio/joern/issues/2502 and https://github.com/joernio/joern/issues/2504

Use relative filenames for php2cpg and prepend those to global namespace and methods

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala

* Changed exported identifier O(n) look-up times to O(1) by preloading identifier names into a set
Resolves #2530
cc @fabsx00

JavaScriptTypeRecovery: `isField` Performance Fix

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/TranspiledFileDetectionTest.scala

Fixes: https://github.com/joernio/joern/issues/2547

jssrc2cpg: added simple detection of transpiled files

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala

This is useful (and perhaps necessary) for sl integration.

Add option to specify php-parser path via an envvar

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/CallTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/NamespaceTypeTests.scala

Fixes: https://github.com/joernio/joern/issues/2559

c2cpg: fix for fully-qualified call names of static methods

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala

Fixes: https://github.com/joernio/joern/issues/2563

c2cpg: turn comma operator into block for statements with condition branch

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala

Fixes: https://github.com/joernio/joern/issues/2561

c2cpg: added missing argument for placement in NewExpression

---

joern-cli/src/main/scala/io/joern/joerncli/JoernExport.scala

re https://github.com/joernio/joern/issues/2571

be more clear about unsupported combinations of `repr` and `format`

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala

Added a config flag to enable generic type recovery for JavaSrc

JavaTypeRecovery: Frontend Arg for Type Recovery

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala

No real changes, only straightforward simplifications.

rubysrc2cpg: basic clean-up on AstCreator

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/preprocessing/EjsPreprocessor.scala

Fixes: https://github.com/joernio/joern/issues/2579

jssrc2cpg: fixed EJS preprocessing for special tags in script block

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2578

jssrc2cpg: fixed parsing of TS type assertions

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/CallTests.scala

First step towards: https://github.com/joernio/joern/issues/2569

c2cpg: improved call method full names

---

build.sbt
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/parser/BabelJsonParser.scala

Is there any catch on doing this? EDIT: I suppose BOM wouldn't be handled. Will rework that.
Fixes: #2601

jssrc2cpg: Replace IOUtils.readLinesInFile with IOUtils.readEntireFile

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/preprocessing/EjsPassTest.scala

Fixes: https://github.com/joernio/joern/issues/2614

jssrc2cpg: fix file renaming during EJS preprocessing

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/JavaTypeRecoveryPass.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeHintCallLinker.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TypeRecoveryPassTests.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

Tested various imports and calls thereof and verifying their behaviour.

JavaScriptTypeRecovery: Recover Types for Various Import Styles

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala

Fix cases where external exports would accidentally get associated with an internal module by checking if the import is relative.

JavaScriptTypeRecovery: Fix Internal vs External Imports

---

README.md
ci/Dockerfile.alma
ci/Dockerfile.alma8

https://docs.docker.com/engine/reference/builder/#cmd

Changed ENTRYPOINT to CMD to support other joern commands

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala

fix arithmeticShiftRight copy-paste issue: >> vs <<

Fixes #2653 - fix arithmeticShiftRight copy-paste issue: >> vs <<

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MethodTests.scala

Resolves https://github.com/joernio/joern/issues/2603

Add php2cpg constructor modifier and fix missing default public modifier

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MethodTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala

Resolves https://github.com/joernio/joern/issues/2590

Add filenames to methods that were missing them

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/JavaTypeRecoveryPass.scala
joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/CodeDumperTest.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XInheritanceFullNamePass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

jssrc2cpg: bump astgen version

---

.github/workflows/containers.yml

the containerbuild doesn't get triggered by release tags for some
reason, try to widen the glob pattern

trying to fix containerbuild trigger - attempt 1

---

joern-cli/frontends/ghidra2cpg/build.sbt
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Ghidra2Cpg.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/FunctionPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/utils/PCodeMapper.scala

Not tested yet. Please share a build to test this or share some instructions.

Ghidra 10.3 support

---

.github/workflows/containers.yml

nicer alternative to https://github.com/joernio/joern/pull/2723
will try this one first, otherwise we'll go with the cron

container build: trigger by release

---

ci/Dockerfile.alma
ci/Dockerfile.alma8
ci/Dockerfile.slim

joern-slim works for js now without crashing due to missing x2cpg.

Use HARD link instead of delete. Use correct JOERN_HOME

---

.github/workflows/containers.yml

'trigger on version tag' model didn't work, no idea why

run container build daily and manually on request

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala

Used control structure wrappers from x2cpg in several places

rubySrc2Cpg: Control struct wrappers

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/DataFlowCodeToCpgSuite.scala

Data flow test file with one test cases\added

rubysrc2Cpg: Added data flow test file for Ruby

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TypeRecoveryPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

* Extract and use type hints from TS parameters
* Resolved these correctly in type recovery and persist the resolved type
Note, this branch is extended from #2792

Register TS parameter type hints

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/IdentifierTests.scala

1. Scope resolution operator `::` further implementation and corrections
2. Rescue and associated implementation
3. Associated unit tests
4. More data flow tests. One is not working and needs to be fixed and hence has been marked as ignore

rubysrc2cpg: Scope resolution operator and more tests

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/DependenciesFromRequirementsTxtPass.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2Cpg.scala

DendenciesFromRequirementsTxtPass => DependenciesFromRequirementsTxtPass

Renamed to fix typo

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Main.scala

The soot PR is to expose dynamic dirs and dynamic pkgs. In the java world, some jars would appear in the classpath and would always be loaded even if they are not explicitly referred to in the code. log4j-impl and spring are famous examples
cc: @DavidBakerEffendi

Additional soot configuration

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/IdentifierTests.scala

Proper operator usage for Associations, defined and negation before expression.

rubysrc2cpg: Associations, defined and negation before expression

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

Corrected implementation for chainedInvocationWithoutArgumentsPrimary

rubysrc2cpg: chainedInvocationWithoutArgumentsPrimary implementation and unit tests

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/AnonymousFunctionsTests.scala

these are different from lambdas https://kotlinlang.org/docs/lambdas.html#anonymous-functions

kotlin2cpg: add support for anonymous functions

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala

Continuing the on-going refactoring. The TODOs mentioned are also on-going, but decided to PR this before it gets too confusing for review.

rubysrc2cpg: refactoring astForStatement

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala

rubysrc2cpg: Dataflow unit tests

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala

1. Lot more data flow tests that are very specific
2. Used operator for yield. The data flow for this is not working and fix for this will be in another PR

rubysrc2cpg: Data flow test coverage increase and yield operator

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ExternalCommand.scala

Replaces: https://github.com/joernio/joern/pull/2879

Fix for astgen version on Windows

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/cfg/CfgCreationPassTests.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala

Fixes the ruby AST such that the `CfgCreator` generates a correct CFG.

ruby2cpg: case/when

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/OperatorTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ScalarTests.scala

* Clean up scalar creation code
* Improve encaps code which resolves https://github.com/joernio/joern/issues/2585
* Add basic scalar tests

Clean up PHP scalars

---

console/src/main/scala/io/joern/console/Console.scala

Pass `enhance=false` to importCpg to disable enhancements

Added option to disable enhancements

---

console/build.sbt
joern-cli/build.sbt
joern-cli/frontends/jssrc2cpg/build.sbt
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
project/meta-build.sbt
project/metals.sbt

Updated few packages

---

build.sbt
console/src/main/scala/io/joern/console/cpgcreation/GoCpgGenerator.scala
joern-cli/build.sbt
joern-cli/frontends/gosrc2cpg/README.md
joern-cli/frontends/gosrc2cpg/build.sbt
joern-cli/frontends/gosrc2cpg/gosrc2cpg.sh
joern-cli/frontends/gosrc2cpg/src/main/resources/log4j2.xml
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/GoSrc2Cpg.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/Main.scala
joern-cli/frontends/gosrc2cpg/src/test/resources/log4j2-test.xml
joern-cli/frontends/rubysrc2cpg/project/build.properties
joern-cli/src/universal/gosrc2cpg
joern-cli/src/universal/gosrc2cpg.bat
project/Projects.scala

1. All the required connecting dots to invoke the go frontend from the Joern.
shell.
2. At present, it only creates an empty CPG and return that CPG.

Initial gosrc2cpg project structure

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/Main.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/Environment.scala

Refactored and moved utility to detect environment details from `jssrc2cpg` to `x2cpg` module.

Refactored and moved common code

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

rubysrc2cpg: refactoring defined? expressions

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/AssignmentTests.scala

All new tests work now. removed the filtering on RHS I had introduced

rubysrc2cpg: more tests and fix for multiple assigns with calls

---

LICENSE

We are seeing a lot of commits from different parties these days, so, it seems in order to add "The Joern Project" in general.

Add "The Joern Project" to LICENSE

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MiscTests.scala

Tests for rescue. Ignored tests that are not working. Fixes will be in subsequent PRs

rubysrc2cpg: Tests for flows through rescue

---

.github/workflows/master.yml

Added ruby and bundler dependency on master workflow environment.

rubysrc2cpg: Added ruby and bundler in master workflow

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CallTests.scala

Fixes https://github.com/joernio/joern/issues/2900

php2cpg: use sensible unresolved call names

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/ExpressionMethods.scala

For argument expressions on non Call nodes like Return the step used to
cause an exception.

Fix `.parameter` step on expression nodes.

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ScalarTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/AstPropertiesUtil.scala

Fixes https://github.com/joernio/joern/issues/2866
Fixes https://github.com/joernio/joern/issues/2822

Fix php magic constants that were represented as field accesses

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ConfigFileCreationPass.scala

Thanks @DavidBakerEffendi for the suggestion (via #2963)

rubysrc2cpg: removing inputPath from ConfigFileCreationPass

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/EnumTypeTests.scala

Fixes: https://github.com/joernio/joern/issues/2987

c2cpg: fix aliasing of inline enums

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala

1. Lot of new test cases
2. Fixes for some test cases. Added several new disabled test cases for later fixing
3. Fixes for crashes while loading repositories
4. Comments in the code to track test case status of code that is not covered under successful cases

rubysrc2cpg: More test case and fixes

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/dataflow/DataflowTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AstCreationPassTests.scala

The PR covers the following
- Basic Ast handling for IF-Else block
- Nested If-else block
- Implemented `code` method which return code snippet for a Node

GoSrc2Cpg : If Else statement Ast handling

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodTests.scala

Method node partial structure
1. Handled different combination parameters while creating the signature
for the method.

[gosrc2cpg] - Method node partial structure

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala

This reverts commit 8631129a657b13b1849f648e529e7c23e9192e73.

Revert "kotlin2cpg: remove a few unnecessary LOC (#2970)"

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/DataFlowSlicing.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/UsageSlicing.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/package.scala
joern-cli/JOERN_SLICE.md
joern-cli/src/main/scala/io/joern/joerncli/JoernSlice.scala
joern-cli/src/test/scala/io/joern/joerncli/JoernSliceTests.scala

* Added line/col number, file name, method name, etc. in as many places as possible
* Changed object slice JSON structure to no longer be a map but a list. Method names are now part of the method usage slice
* Removed `methodToChildNode` under data-flow slices, instead the parent method is a property of the node itself.
cc: @prabhu

[joern-slice] Comprehensive Location Information 

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/TypeDeclAstCreationPassTest.scala

* Added a few foundational tests for type declarations
* Fixed an instance where a null `StatementsContext` would throw an exception when parsing some moderately invalid Ruby
* Solved methods under type declarations by handling class bodies differently to successfully construct methods and their modifiers correctly
Resolves #3005 and partially resolves #3008

[rubysrc2cpg] Type Decl AST Tests

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala

The relevant test case is "DataFlowTest72". Scalafmt created some noise in the PR..

DF: missing operator, Operators.indirectFieldAccess

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeRenderer.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/MissingTypeInformationTests.scala

kotlin2cpg: change error type render logic

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MethodOneTests.scala

Fixes a minor issue and a test. We may need to remove multiple method return tests themselves since they don't seem valid. Will consult @pandurangpatil @DavidBakerEffendi and update this

rubysrc2cpg: fix more method param issues

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/FieldAccessTests.scala

[rubysrc2cpg] Initial Field Access Unit Tests

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala

There was a bracket matching issue causing incorrect test alignment. Fixed it

rubysrc2cg: Properly aligned test cases

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/ModuleTests.scala

1. Module handling similar to Class, along with Namespace block node.
2. Respective unit tests 
3. Handling of constants is yet to be done. <TODO> will handle that in separate PR.

[rubysrc2cpg] AST for Module

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

rubysrc2cpg: Bridge AstCreator for proc definition

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala

Showing that we can close #3140

RubyLexer: extra unit-test

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/AstCreationPass.scala

1. Catching error at compliation unit level, so incase there is any error while processing any file. This should not stop the engine processing other files and generating CPG.
2. At other place inside AstForTypesCreator, was facing ctx null issue. Added handling for this error.

Error handling

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

[rubysrc2cpg] [WIP] Added support for proc parameters with no name

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

AST creation and data flow unit tests for https://github.com/joernio/joern/issues/3173

[rubysec2cpg] regex define after when

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ClassDefinitionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/EnsureClauseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RescueClauseTests.scala

RubyParser: support for endless methods

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MiscTests.scala

This fixes https://github.com/joernio/joern/issues/3164
Tagging @xavierpinho

rubysrc2cpg: Workaround for << operator in class definition

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/SymbolTests.scala

RubyParser: support for interpolated symbols

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/TernaryConditionalTests.scala

RubyParser: allow new lines in ternary conditionals

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

AST creation unit tests for https://github.com/joernio/joern/issues/3144

[rubysrc2cpg] method call chained invocation

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/HashLiteralTests.scala

RubyParser: Allow splatting elements in hash literals

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MiscTests.scala

rubysrc2cpg: Fix for assignment linked method identifier

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

@xavierpinho can you review this?

[rubysrc2cpg] Interpolated double-quoted string literal support

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

@xavierpinho can you review this?

[rubysrc2cpg] Ternary operator with multiple line

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/AstCreationPass.scala

we can now exclude file for ruby frontend: 
```
importCode.ruby.apply(inputPath = "path", projectName = "name", args = List("--exclude-regex", "regex"))
```
previous conversation: https://github.com/joernio/joern/pull/3329

[Rubysrc2cpg] Support to exclude files

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

This also fixes crashes related to endless methods
@xavierpinho

rubysrc2cpg: Code to handle ENDless methods

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

@xavierpinho, tagging for review.

[rubysrc2cpg] Added ast support for keyword parameters and test-cases

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

Added Ast fix, its unit test and dataflow test for %w array.

[rubysrc2cpg] AST fix and unit tests for %w

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

Added AST test case for double escaped string

[rubysrc2cpg] AST Test Case for Double Escaped String

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

Unit tests for https://github.com/joernio/joern/pull/3215

[rubycode2cpg] Parenthesised arguments in a return jump

---

console/src/main/scala/io/joern/console/Console.scala
console/src/main/scala/io/joern/console/ConsoleConfig.scala

Fixes: https://github.com/joernio/joern/issues/3373

Support for OS-specific open for plotDot*

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

Covered test case for: https://github.com/joernio/joern/pull/3135
Expression such as: x+@y

added test case for expression having @ and +

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

fix for https://github.com/joernio/joern/issues/3037, added unit and dataflow test.

[rubysrc2cpg] Method call association identifier

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/DataFlowSlicing.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/UsageSlicing.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/package.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/slicing/JsUsageSliceTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/slicing/TsUsageSliceTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/slicing/PyUsageSliceTests.scala
joern-cli/src/main/scala/io/joern/joerncli/JoernSlice.scala

* Refactored slicing for better re-usability
* Added Python slicing test
* Changed how receivers are detected to be robust to the presence of different operators
* Added test validation more robust to flakiness
Resolves #3402

Slice Refactoring & Python Test

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AstCreationPassTests.scala

- Support for Break, continue, goto
- Supporting Ast Test cases for the same
- Ast test case for Nested For Loop
- Refactoring to have `BaseExpr`, `BasePrimitive`, `BaseStmt` base classes for more easier grouping
cc - @DavidBakerEffendi

[gosrc2cpg] Support for break, continue, goto

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/psi/PsiUtils.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala

a tree visitor is much more suited to the task

kotlin2cpg: improve object literal idx counting

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/parser/BabelAst.scala

Less code duplication. A bit cleaner.

jssrc2cpg: refactor ForInOfStatement loop variable handling

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/HeaderAstCreationPassTests.scala

Import nodes were never correctly hooked into the AST. This PR fixes that.
Fixes: https://github.com/joernio/joern/issues/3438

c2cpg: attach import nodes correctly

---

console/build.sbt
project/Versions.scala
semanticcpg/build.sbt
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/Steps.scala

similar to `browse()` from ammonite:
```
joern> new Steps(Iterator(1, 2, 3)).browse
```

Steps.browse command: open `less` pager

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf

* brings ignoring if minified files (already at Babel -> json phase, so more performance there)
* brings latest Babel and TS

jssrc2cpg: updated astgen

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala

Data flow tests for tests for array initialization
@xavierpinho

rubysrc2cpg: Array initialization tests

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4

Slight performance improvement by rearranging some rule priorities.

RubyParser: easy performance improvements

---

joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AstCreationForArraysTests.scala

Added unit test for array array along with handling for struct type and pointers. tests are failing for pointer.

[gosrc2cpg] - Unit test for array with handling for struct and pointer

---

console/src/main/scala/io/joern/console/cpgcreation/CCpgGenerator.scala
console/src/main/scala/io/joern/console/cpgcreation/GhidraCpgGenerator.scala
console/src/main/scala/io/joern/console/cpgcreation/KotlinCpgGenerator.scala

Frontend args need to go last.
(all other frontends do that already correctly)
For: https://github.com/joernio/joern/issues/3526

Fixed frontend args

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/dataflow/OperatorDataflowTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/dataflow/ParameterInDataFlowTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ASTCreationForMethodCallTests.scala

few unit test and code refactor
1. Did some code refactoring to arrange case statements logically grouped under one case.
2. Additional data flow unit tests.
3. Code refactoring related to array initializer AST creation and some other code refactoring done to improve the coding standard.
4. Simple call node implementation

[gosrc2cpg]- Simple method call node implementation with some code refactor

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf

To bring in https://github.com/joernio/astgen/pull/16

Updated astgen

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/jartypereader/descriptorparser/TypeParser.scala

This branch should never be triggered, but add handling for it anyways.

Fix non-exhaustive match

---

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/AnnotationTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/generalizations/AstNodeTraversal.scala

starting with one class to gather feedback...

replace @unchecked with typed api

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStructuresCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ASTCreationForStructureTests.scala

Addressed code review comment under: https://github.com/joernio/joern/pull/3567

gosrc2cpg: updated typeDecl's fullname property

---

joern-cli/frontends/javasrc2cpg/build.sbt

Bring in  fixes from https://github.com/javaparser/javaparser/releases/tag/javaparser-parent-3.25.5

[javasrc2cpg] Bump javaparser

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AstCreationForGenericTests.scala

Added support to handle the ast creation for single generic type method.

[gosrc2cpg] - Generic parameter type handling

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/dataflow/MethodAndCallDataFlowTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ASTCreationForMethodCallTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/GenericsTests.scala

1. Return statement handling 
2. Updated unit tests for array return type 
3. A few data flow tests within the file and across the file calls.

[gosrc2cpg] - return statement handling

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala

* Investigated switch statement AST construction, found it was pretty broken
* Fixed it and now the data-flow test works as expected

[rubysrc2cpg] Fixed Switch Statements

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/GenericsTests.scala

Added support to handle the ast creation for return generic type method. Also added test for multiple generic type parameter.

[gosrc2cpg] - Generic type return handling

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodCallTests.scala

Handled case where method call is executed on chain of variable such as:
```
1. person.address.state.getName()
2. student.contact.getEmail()
```
In existing code method call on single variable is handled.

[gosrc2cpg]: handled method call on chain of variable

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/VariableReferencingTests.scala

Added support for empty local var declaration

[gosrc2cpg] Added Support for Empty Local Var

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodTests.scala

Handling reference node object while processing Identifier.

added support to handle reference object

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/Defines.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/dataflow/OperatorDataflowTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/BuiltInMethodCallTests.scala

Extension of: https://github.com/joernio/joern/pull/3647
added support for channel.

gosrc2cpg: added channel support for make function

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala

Added lookup for astgen binaries at ASTGEN_BIN, similar to what php2cpg with its parser binaries does.
For: https://shiftleftinc.atlassian.net/browse/SEN-1550

jssrc2cpg: lookup of astgen binaries at env var

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/CacheBuilder.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeDeclTests.scala

Added support to handle the struct defined in unordered. 
Ticket: https://github.com/joernio/joern/issues/3652

[GoSrc2cpg] - Handle TypeSpec defined unordered

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/CacheBuilder.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodTests.scala

Handled the ValueSpec and FuncDecl reference-id issue fixed
Ticket: https://github.com/joernio/joern/issues/3652

[GoSrc2cpg] - ValueSpec and FuncDecl reference-id fix

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala

The lookup for astgen binaries at ASTGEN_BIN is now able to handle paths to the binary itself as well as to its directory.
For: https://shiftleftinc.atlassian.net/browse/SEN-1550

jssrc2cpg: improved lookup of astgen binaries at env var

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ExpressionsTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodCallTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/SwitchTests.scala

1. Unit test to reproduce the issue #3677 
2. Handled a few compilation warnings.
3. Updated warning logs to add line number information to identify the specific code resulting into warning

[gosrc2cpg] - Unit test to reproduce the issue #3677

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/GoSrc2Cpg.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/Main.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/model/GoMod.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/DownloadDependenciesPass.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/MethodAndTypeCacheBuilderPass.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/model/GoModTest.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/DownloadDependencyTest.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/testfixtures/GoCodeToCpgSuite.scala

1. Changed Object implementation of GoMod to create Class one as we need to use many instances and context to parse files downloaded from dependencies.

[gosrc2cpg] - Code refactor

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/DoBlockTest.scala

Generalized the solution from PR #3708 by applying it to other call argument construction.
Fixes #3693

[rubysrc2cpg] Comprehensive follow up to #3708's fix

---

joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/DownloadDependencyTest.scala

With reference to the discussion on this PR #3753 ignoring the tests which are downloading the dependencies

[gosrc2cpg] Ignore "Download Dependencies" Tests

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/ClassTypeTests.scala

Fixes: https://github.com/joernio/joern/issues/3768

c2cpg: fixed call fullnames for C++ class member methods

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrParser.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/ParserAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/ParserAstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ConfigFileCreationPass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/BooleanLogicTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ConditionalTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/FieldAccessTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HashTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/IndexAccessTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/LiteralTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ModuleTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RangeTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SetterTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

As a follow-up for #3755 and #3764, this brings in the current work-in-progress AstCreator that uses the new RubyParser.g4

[rubysrc2cpg] kick-starting the new AstCreator

---

README.md

To avoid repeating errors of first-time contributors, added a contributor guideline.

Developers: Contribution Guidelines

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/astcreation/AstCreator.scala

Hotfix for: https://github.com/joernio/joern/actions/runs/6825626462/job/18563864239

[jimple2cpg] Fix unimplemented method in AstCreator

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala

We handle the following cases now:
1) no astgen binary in the systems `PATH` and `ASTGEN_BIN` is not set: take astgen from joern
2) astgen binary in the systems `PATH`: take that
3) `ASTGEN_BIN` contains a valid path to a file: take that concrete file as astgen binary
4) `ASTGEN_BIN` contains a valid path to a directory: take that dir and look for an executable named `astgen` there
(higher number means higher priority)
For: https://shiftleftinc.atlassian.net/browse/SEN-1805

[jssrc2cpg] improved ASTGEN_BIN handling

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/preprocessing/EjsPreprocessor.scala

Fixes: https://github.com/joernio/joern/issues/3817

[jssrc2cpg] Fix EJS opening/closing tag handling

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

Just like we did with c2cpg.
For: https://github.com/joernio/joern/issues/3819

[jssrc2cpg] Truncate very long array expressions

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf

Contains a astgen vue parsing fix.

[jssrc2cpg] Updated astgen

---

joern-cli/frontends/csharpsrc2cpg/build.sbt
joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf

* Downloads are initially compressed and now uncompressed during build
* New DotNetAstGen strips away unrelated syntax-specific properties and has improved logging/error handling

[c#] Upgraded DotNetAstGen

---

.gitignore
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForLambdaCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/datastructures/GoGlobal.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AnonymousFuncTests.scala

1. Handling of basic lambda method (creation of Method and MethodRef node)
2. gitignore for dotnetastgen binaries
TODO:
1. Handling of Lambda TypeDecl along with struct type.
2. Adding more combinations of unit tests.
3. Handling of Closure use case.
4. Lambda invocation call node.

[gosrc2cpg] - Initial Lambda Handling

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForLambdaCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/dataflow/AnonymousFuncDataflowTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/dataflow/ArrayDataflowTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AnonymousFuncTests.scala

1. Handling for lambda call node for its invocation along with a few more unit tests.
2. Data flow unit tests for the lambda.
TODO:
1. Handling of Lambda TypeDecl along with its inheritance mapping with struct type TypeDecl
2. Handling of Closure use case.
3. Adding more combinations of unit tests

[gosrc2cpg] - Handling for lambda call node for invocation

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonImportResolverPass.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala

The new import resolution simplified the world for internal code, then gave external code to the old fall-back functionality.
The issue is that the old fall-back functionality still assumed the code may be in the CPG, but this would be assured not the case.
This change fixes the pseudo-path based on this guarantee.

[py] Simplify Pseudo Imports for External Modules

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForLambdaCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AnonymousFuncTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeDeclMembersAndMemberMethodsTest.scala

Handling of lambda TypeDecl
1. Handling of lambda TypeDecl creation
2. Few additional tests.
TODO:
1. Handling of global package level constructor node. Along with verification of lambda defined at the package level and the respective data flow.
2. Handling of lambda TypeDecl inheritance mapping with matching signature Struct types.
3. Handling of closure use case.
4. More data flow unit tests

[gosrc2cpg] - Handling of lambda TypeDecl

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/io/ProjectParseTests.scala

More details found here:
https://github.com/orgs/joernio/projects/13/views/1?pane=issue&itemId=45764470

[c#] Implement AST Generation with DotNetAstGen

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForLambdaCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForTypeDeclCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/CacheBuilder.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/datastructures/GoGlobal.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AnonymousFuncTests.scala

1. Handling of lambda function types and mapping it with lambdas with matching signature.
2. Respective Unit tests.
TODO:
1. Handling of global package level constructor node. Along with verification of lambda defined at the package level and the respective data flow.
2. Handling of closure use case.
3. More data flow unit tests.

[gosrc2cpg] - TypeDecl handling for inheritsFromTypeFullName with type

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala

Fixes: https://github.com/joernio/joern/issues/3859

[c2cpg] Added line/column number to While control structures

---

joern-cli/src/main/scala/io/joern/joerncli/JoernExport.scala

Upon exporting `Representation.Cpg`, an iterator based on methods is started, and then the result is reduced.
If the iterator is empty, the reduce will throw an exception.
This change instead returns an empty result.
Resolves #3892

[joern-export] Handle Empty CPG

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala

Fixes: https://github.com/joernio/joern/issues/3904
Fixes: https://github.com/joernio/joern/issues/3905
Fixes: https://github.com/joernio/joern/issues/3906
Fixes: https://github.com/joernio/joern/issues/3902

[jssrc2cpg] Multiple fixes for Vue.js and ObjectPattern handling

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/ProjectParseTest.scala

Fixes: https://github.com/joernio/joern/issues/3923

[jssrc2cpg] Fixed handling of astgen parse failures

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/GoSrc2Cpg.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/datastructures/GoGlobal.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/dataflow/AnonymousFuncDataflowTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AnonymousFuncTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/GlobalVariableAndConstantTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/VariableReferencingTests.scala

1. Handling for package level global lambda function along with its unit tests and different combinations within the same file and different package with different file.
2. Respective data flow unit tests.
3. Refactored some of the unit tests and moved them under global variable tests.
TODO:
1. Handling of Lambda closure.

[gosrc2cpg] - Package level global lambda function handling

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/io/ProjectParseTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/passes/MetaDataPassTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/FileTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/NamespaceTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/testfixtures/CSharpCode2CpgFixture.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/MetaDataPass.scala

* Upgraded DotNetAstGen with further compressed binaries
* Added MetaData node using raw string "CSHARPSRC" until CSHARPSRC is in the schema
* Editted `x2cpg`'s `MetaDataPass` to allow the hash to be specified
* Completed file node properties
* Added namespace nodes with nesting and stacks
Resolves #3854
Resolves #3852
Resolves #3850

[c#] MetaData, File, and Namespace Nodes

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ExternalCommand.scala

Just as we did in js2cpg.
For: https://shiftleftinc.atlassian.net/browse/SEN-1926

[jssrc2cpg] Give astgen more heap memory

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MethodTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeDeclTests.scala

* Generating type declarations with modifiers
* Generating method nodes with modifiers, a block, parameters, and a method return
Resolves https://github.com/joernio/joern/issues/3854
Resolves https://github.com/joernio/joern/issues/3855
Resolves https://github.com/joernio/joern/issues/3951

[c#] Classes, Methods, and Method Decorators

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCollectionCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/DeclarationTests.scala

[swiftsrc2cpg] Added support for Array/List like declarations

---

build.sbt
console/src/main/scala/io/joern/console/cpgcreation/package.scala
console/src/test/scala/io/joern/console/LanguageHelperTests.scala
joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MethodTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/NamespaceTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ParameterTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeDeclTests.scala

* Upgraded new DotNetAstGen that includes types and a code property
* Implemented method signature and added basic type information into parameter nodes
* Using CPG CSHARPSRC language entry
Resolves #3971

[c#] Method Signature, Param Types, & Code

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala

In list-like and assignment expressions.

[swiftsrc2cpg] handle function references correctly

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ConstClosurePass.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/CallLinkerPassTest.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ConstClosurePassTests.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala

Fixes: https://github.com/joernio/joern/issues/3967

[jssrc2cpg] Handle methods created within ObjectExpressions

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSwiftTokenCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCollectionCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/passes/DependenciesPass.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/DeclarationTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/dependency/DependenciesPassTests.scala

Also: fixes string segment syntax handling.

[swiftsrc2cpg] Added support for index access of list-like structures

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MemberTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MethodTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ParameterTests.scala

* Basic structures in place for handling field members
* Added list of builtin system types/keywords as well as their mappings to their full namespaces
* Handled implicit type casting of numeric literals
Resolves #3952

[c#] Field Member Nodes

---

console/build.sbt
console/src/main/scala/io/joern/console/BridgeBase.scala

Windows paths need escaping.
Fixes: https://github.com/joernio/joern/issues/4015

[console] Fixed Windows path handling

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/passes/ast/OperatorsTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ExternalCommand.scala

This PR adds support for operators (arithmetic, logical, comparison, and bitwise) in the `csharpsrc2cpg` frontend.

[csharpsrc2cpg] Handle basic operators

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/GuardTests.scala

Guard statements may appear multiple times in a block (sequentially or nested).

[swiftsrc2cpg] Improved support for Guard Statements

---

joern-cli/frontends/csharpsrc2cpg/build.sbt
joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/resources/builtin_types.json
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/TypeMap.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/ScopeType.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/CallTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/testfixtures/CSharpCode2CpgFixture.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/datastructures/Scope.scala

* Have type map able to generate type stubs from JSON input
* Replaced initial simple stack with custom scope object for better scoping
* Generating basic static call nodes with arguments and receivers
* Updated DotNetAstGen
TODO: Load imports and known types into scope for basic type resolution

[c#] Basic Static Calls & Improved Scoping, Type Map

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/Constants.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ControlStructureTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Defines.scala

* Updated AST Gen
* Handling `throw` call
* Basic handling for object creation expression (`new`)
* Implemented blocks for try-catch-finally
* Added type handling for boolean
* Added assignment condition for binary operators
* Added `ANY` to `io.joern.x2cpg.Defines`
Resolves [#3988](https://github.com/joernio/joern/issues/3988)

[c#] Try-Catch-Finally Handling

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ConditionalTests.scala

This PR handles, 
1. `if` Statements
2. `else if` Statements
3. `else` Statements
Resolves [#3983](https://github.com/joernio/joern/issues/3983)

[c#] If-Else Conditional Statements

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/LoopsTests.scala

This PR includes,
1. Upgrading `DotNetAstGen` version to allow a new property.
2. AST Creation for `for` loops.
3. AST Creation for `do...while` loops.
4. AST Creation for `while` loops.
5. Refactor implementation for `astForExpression`
Resolves #3985 
Resolves #3987

[c#] Ast creation for `for`, `do..while`, and `while` loops

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/ControlStructureDataflowTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/testfixtures/CSharpCode2CpgFixture.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/astgen/AstGenNodeBuilder.scala

* Fixed data-flow test mode for the test fixture
* Added null-safety to the x2cpg `AstGenNodeBuilder` methods
* Added a small if data-flow test to validate flows

[c#] Initial Data-Flow Test

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForPatternSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForStmtSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ForeachTests.scala

Incl. de-sugaring for ForEach loops with simple identifier, expressions, and tuple declarations with and without where clauses.

[swiftsrc2cpg] Added support for ForEach loops

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCollectionCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForTypeSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/passes/Defines.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/utils/ExternalCommand.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/dependency/DependenciesPassTests.scala

- fixed err code handling when calling SwiftAstGen on Windows machines
- added support for await expressions
- added support for import decls
- added support for is expressions
- added support for nil literals
- added support for identifier types

[swiftsrc2cpg] Various improvements

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/TypeMap.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeDeclTests.scala

[c#] Struct value types

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/testing/package.scala

(this would have saved me some time debugging a downstream issue)

more details on test error

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/JumpStatementsTests.scala

This PR includes,
1. AST Creation for `break`, `continue` and `goto` statements.
2. Corresponding tests.

[C#] Ast creation for jump statements

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/ControlStructureDataflowTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/MemberDataflowTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/MethodsAndCallDataflowsTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/OperatorDataflowTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/SwitchDataflowTests.scala

This PR includes,
1. Dataflow tests for existing AST structures.
2. Minor refactoring.

[C#] Initial dataflow tests

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/TypeMap.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeDeclTests.scala

- AST creation for two variants of `record` types
- Tests
Resolves #3997

[C#] support record types

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForStmtSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstNodeBuilder.scala

Discovered them testing on https://github.com/apple/swift itself.

[swiftsrc2cpg] Improved support for previously missed Swift AST elements

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/ast/CallCpgTests.scala

Ignoring a flaky test resulting from this commit https://github.com/joernio/joern/commit/527ed917dd762909c66d347e151a9e3e657f0b39

[ruby] Flaky Test Ignore

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/parser/SwiftJsonParser.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/passes/AstCreationPass.scala

Had a few crashes on https://github.com/apple/swift due to broken encoding (they use it as parser/compiler robustness checks - nothing we need, but we should never crash).

[swiftsrc2cpg] Several crash fixes

---

joern-cli/frontends/swiftsrc2cpg/src/main/resources/application.conf

Brings in some improvements for file iteration and crash handling.

[swiftsrc2cpg] Updates SwiftAstGen version

---

joern-cli/src/universal/csharpsrc2cpg

Fixes frontend invocation from within Joern shell

[c#] fix invocation script

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

* Fix name for `OptionalParameter`
* Better handling of default parameter values
* Expand default parameter values to the following in the AST for the Method block:
```ruby
if !defined?(variable)
variable = defaultValue
end
```
Resolves #3933

[ruby] Default Parameter Values

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/builtin_types.json
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/TypeMap.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/CallGraphTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/CallTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/MethodsAndCallDataflowsTests.scala

Hot and messy call resolution. Some technical debt here in `astForInvocationExpression` but calls are now largely being resolved.
Resolves [#4176](https://github.com/joernio/joern/issues/4176)

[c#] Hotfix for CSharp Call Resolution

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/CodeDumperFromContentTest.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/CodeDumperFromFileTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/FileTests.scala

Just like in jssrc2cpg and swiftsrc2cpg.

[c2cpg] Enable file content and content for method and type decl

---

joern-cli/frontends/pysrc2cpg/pythonGrammar.jj
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/CodeToCpg.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/LineAndColumn.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeToCode.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2Cpg.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2CpgOnFileSystem.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitorHelpers.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pythonparser/CharStreamImpl.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/Py2CpgTestContext.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/ContentCpgTests.scala

Contains fix for not emitted new line token at end of file.

Implement file content support for pysrc2cpg.

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala

A `FileNotFoundException` was thrown for the `builtin_types` directory in the C# frontend, when the frontend was invoked from the release/local build. Turns out it is a age old bug in Java itself. This is a small workaround to solve this problem. 
Bug: https://bugs.java.com/bugdatabase/view_bug?bug_id=4523159

[C#] Fix not found exception on jar path for builtin_types

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCollectionCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForTypeSyntaxCreator.scala

Discovered during testing with all swift source files in https://github.com/apple/swift

[swiftsrc2cpg] Added support for more missing operators and expressions

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/passes/DependencyPass.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/DependencyTests.scala

Parse `.csproj` files to find dependencies.
Resolves #4180

[c#] Dependency Pass

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeCastTests.scala

Includes Ast Creation and in turn type resolution for Cast Expression. Type coverage should increase as a result of this PR.
Resolves #4300

[C#] Ast creation for `CastExpression`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

* Handles array and hash parameters
* Added `CollectionParameter` trait to join the two variadic parameter types
Resolves #4268

[ruby] Variadic Parameters

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyLexer.g4
joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/HereDocHandling.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HereDocTests.scala

* Heredoc handling at a very trivial level. This is simply to get the parser to stop crashing on heredocs until a more involved solution has been completed so that flows can be tested.
Partially resolves #3937

[ruby] Here-Docs Pt 1

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/Constants.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeDeclTests.scala

This PR includes AST Creation for `AnonymousObjectCreationExpression`, and child fields.
Resolves #4005

[C#] Ast creation for `AnonymousObjectCreationExpression`

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/CollectionTests.scala

Includes AST Creation and tests for `ImplicitArrayCreationExpression`
Resolves #4332

[C#] Ast for implicit arrays

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/passes/ast/OperatorsTests.scala

This PR includes AST Creation for String Interpolation expressions in C#.
Resolves  #4335

[C#] Ast creation for interpolated strings

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForPatternSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCollectionCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/SwitchTests.scala

- handling for switch cases behind IfConfigDecl (conditional compiling)
- handling for ValueBindingPattern and OptionalBindingCondition (only generate locals if needed)

[swiftsrc2cpg] Several improvements

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MemberAccessTests.scala

This PR includes AST Creation for Conditional Access Expression, and corresponding tests. 
Resolves #4346

[C#] Ast creation for Conditional Access Expression

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/AnnotationTests.scala

Includes ast creation for member, class and method annotations.
Resolves #4386

[C#] Asts for method, class and member annotations

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/passes/DependencyPass.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/passes/DependencyTests.scala

* Included `Update` Attribute to DependencyPass
* Added safe access to `AttributeLists` key
* Moved `DependencyTests` to `passes` package

[c#] Included `Update` Attribute to DependencyPass

---

.github/workflows/master.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/upgrade-deps.yml

Also replaced `+test` with simple `test` (leftover from Scala 2 -> 3 transition).

Updated GH Action for go

---

console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala
console/src/main/scala/io/joern/console/cpgcreation/JsSrcCpgGenerator.scala
console/src/test/scala/io/joern/console/ConsoleTests.scala
console/src/test/scala/io/joern/console/testing/ConsoleFixture.scala

This came up already multiple times here as issue and also via Discord.
This PR adds support for importing single JS files by copying them into a temporary folder.

[console] Fixed handling of single files when importing JS code

---

.scalafmt.conf
build.sbt
console/build.sbt
joern-cli/frontends/c2cpg/build.sbt
joern-cli/frontends/csharpsrc2cpg/build.sbt
joern-cli/frontends/ghidra2cpg/build.sbt
joern-cli/frontends/gosrc2cpg/build.sbt
joern-cli/frontends/javasrc2cpg/build.sbt
joern-cli/frontends/jssrc2cpg/build.sbt
joern-cli/frontends/kotlin2cpg/build.sbt
project/Versions.scala
project/plugins.sbt

But not going to Scala 3.4.1 yet (brings in some syntax changes / many rewrites required with -rewrite source3.4migration).

Updated dependencies

---

joern-cli/frontends/gosrc2cpg/src/main/resources/application.conf

goastgen version upgrade 
1. which fixes exclusion rule handling for path as well.
2. Graceful handling of mod file parsing in the even module name is not present

[GO] goastgen version upgrade

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/SuperTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ToplevelLibraryTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/TryTests.scala

Also: fixed function node name and fullname handling to map call methodfullnames correctly

[swiftsrc2cpg] Few more tests

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/CallTests.scala

- Collect imports in program summary
- Filter type stubs based on import
- Add ignored tests for some method resolution problems found along the way.

[csharp] Filter unused type stubs

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/LiteralTests.scala

* Added handling for Symbol interpolation
The issue resolved was resolved as part of some other change, but I validated and enabled the LiteralTests
Resolves #4521

[ruby] Validate & Enable String Interpolation Flows

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/PhpDownloadDependenciesTest.scala

Improved the robustness of the semver parser by simplifying the string given to the SemVer class.
Resolves #4513

[php] Semver Parsing Robustness

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/DependencyPass.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/PhpDownloadDependenciesTest.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/FileUtil.scala

* Fixed issue where directory merging throws an error if the target directory is non-empty by implementing a custom merge
* Included handling of `psr-0` autoloading specs
* Handle parsing of package responses without `dist` keys

[php] Hardening Dependency Download

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/FunctionDefCpgTests.scala

* Added names to decorator calls

[python] Decorator Call Names

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/util/ProgramHandlingUtil.scala

* Fixed `ZipInputStream` not being opened with an auto-close
* Only check that the first entry works which effectively checks that the stream's protocol (at least from the header and a few bytes in) conforms to ZIP format.
The purpose of this is to improve performance on large recursive archives.

[jimple] Simplify ZIP Test & Fix Mem Leak

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/PhpDownloadDependenciesTest.scala

* handles cases where dep version is "x/y/z" etc.
* normalize this to ">=0.0.0"

[php] handle corner case for dependency version

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MethodRefTests.scala

Currently these are just `Unknown` nodes in the AST

Add MethodRefeferenceExpr to javasrc asts

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/PhpTypeRecovery.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/PhpTypeRecoveryPassTests.scala

Added a test that tests type flow to a method return which is inherited by another class and should then be propagated to the assigned identifier.
So far this test only fixes the bug where calls to the method return were discovered and resolved but not persisted. Additionally, made sure operator calls were not loaded into the symbol table.
Next steps: Investigate call resolution for superclass methods

[php] Type Recovery on Method Returns

---

joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/pom.xml
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/passes/ConfigFileCreationPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XConfigFileCreationPass.scala

Including pom.xml in the CPG could help with debugging maven issues in the future

Include pom.xml in java config files

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/package.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala

Follow-up refactoring for #4582 which should've been proposed the first time.

[dataflowengineoss] refactor globalFromLiteral

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/MavenDependencies.scala

```
❯ ./joern-cli/frontends/javasrc2cpg/javasrc2cpg ~/code/java/HelloShiftLeft --fetch-dependencies
...
[INFO ] Enabling dependency fetching: --fetch-dependencies flag was set
[INFO ] got 63 Maven dependencies
...
```
```
❯ ./joern-cli/frontends/javasrc2cpg/javasrc2cpg ~/code/java/HelloShiftLeft-mvn-test --fetch-dependencies
...
[INFO ] Enabling dependency fetching: --fetch-dependencies flag was set
[WARN ] Retrieval of compile class path via maven return with error.
The compile class path may be missing or partial.
Results will suffer from poor type information.
To fix this issue, please ensure that the below command can be executed successfully from the project root directory:
mvn --fail-never -B dependency:build-classpath -DincludeScope=compile …
```

Add mvn command being run to dependency fetching failure message to help debugging

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HereDocTests.scala

* A silently failing context was `CommandWithDoBlockContext` is now handled
* Added failing heredoc test case

[ruby] Handle Command With Do Block

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/TypeEvalPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/TypeRefPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/callgraph/StaticCallLinker.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ConcurrentTaskUtil.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/LinkingUtil.scala

Just some fixed MAX_BATCH_SIZE until we come up with something better.
Fixes: https://github.com/joernio/joern/issues/4611

Hotfix for broken grouping of parts as input to parallel passes

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala

This PR does two things:
1) DEBUG logs the frontend name, version and raw arguments passed down
2) INFO logs the CPG output path if not set explicitly by the user

[x2cpg] Log frontend version and raw argument and out path

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/PhpTypeRecovery.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/PhpTypeRecoveryPassTests.scala

Added a recursive aspect to the call type recovery if the receiver of the call is possibly recoverable (and it's receiver if that's a call and so on)

[php] Long Call Chain Type Recovery

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrParser.scala

Moved parser logging of memory clearing from INFO to DEBUG

[ruby] Antlr Parser Logging Level

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala

ICPPASTExpression.getEvaluation may fail throwing an unrecoverable exception in case of unresolved includes etc.

[c2cpg] Safe getEvaluation for CPP

---

joern-install.sh

This PR just adds a check for the unzip utility during joern install.
Nothing fancy.

Adding unzip check

---

joern-cli/src/universal/c2cpg.bat
joern-cli/src/universal/csharpsrc2cpg.bat
joern-cli/src/universal/ghidra2cpg.bat
joern-cli/src/universal/gosrc2cpg.bat
joern-cli/src/universal/javasrc2cpg.bat
joern-cli/src/universal/jimple2cpg.bat
joern-cli/src/universal/joern-export.bat
joern-cli/src/universal/joern-flow.bat
joern-cli/src/universal/joern-parse.bat
joern-cli/src/universal/joern-scan.bat
joern-cli/src/universal/joern-slice.bat
joern-cli/src/universal/joern-vectors.bat
joern-cli/src/universal/joern.bat
joern-cli/src/universal/jssrc2cpg.bat
joern-cli/src/universal/kotlin2cpg.bat
joern-cli/src/universal/php2cpg.bat
joern-cli/src/universal/pysrc2cpg.bat
joern-cli/src/universal/rubysrc2cpg.bat
joern-cli/src/universal/swiftsrc2cpg.bat

fixes https://github.com/joernio/joern/issues/4661

adjust double-quotes in windows starter scripts

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/SingleAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

Method-Members for singletons are now implemented and bound to their respective types.

[ruby] Singleton Method-Member Bindings

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala

For: https://shiftleftinc.atlassian.net/jira/software/c/projects/SEN/issues/SEN-2777

[c2cpg] Fixed match errors in astForCppCallExpression

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala

For: https://shiftleftinc.atlassian.net/browse/SEN-2838

[c2cpg] Fixed match errors in astForFunctionDeclarator

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf

Brings in latest babel and typescript to astgen.

[jssrc2cpg] Update astgen version

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefProblem.scala

@mpollmeier can you test whether this solves / improves the memory issue?

[speculative] minor work on reachingDef

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/TypeNodePass.scala

For: https://shiftleftinc.atlassian.net/browse/SEN-2840

[c2cpg] Register call typefullnames correctly

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/AssignmentParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/BooleanParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ControlStructureParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/DoBlockParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/FieldAccessParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/IndexAccessParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RangeParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/UnlessConditionParserTests.scala

This PR adds a few more parser tests based on tests in the `querying/` folder for Ruby.

[ruby] Parser tests

---

joern-install.sh

Removed joern-stats from install script

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/CallTests.scala

- we had one stackoverflow in fullname
- evaluation.getOverload may return null

[c2cpg] Fixed more exceptions

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ProcParameterAndYieldTests.scala

This PR remodels `yield` calls as explicit invocations of the implicit or explicit block parameter of the surrounding method.
Resolves #4760

[ruby] Remodel `yield` Calls

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/MethodTests.scala

[c2cpg] Create locals for function pointer decls

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/preprocessing/EjsPassTests.scala

Fixes: https://shiftleftinc.atlassian.net/browse/SEN-2963

[jssrc2cpg] Apply file filtering also to .ejs and .vue files

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ArrayParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala

This PR adds:
* Handling for String Array Literal with Interpolations, denoted by `%W()`
TODO: Add parser test once #4809 is merged
Resolves #4810

[ruby] String Array with Interpolations

---

build.sbt
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/layers/LayerCreator.scala

Using the old SerializedCpg API hat no effect anymore.

Bump cpg version and cleanup.

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RegexParserTests.scala

This PR fixes the last two parser test set:
* Regex parser tests
* Method defs in classes parser tests

[ruby] Fix last parser tests

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ArrayParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/AssignmentParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/BeginStatementParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/BitwiseOperatorParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/BlockParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/BooleanParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/CaseConditionParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ClassDefinitionParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ControlStructureParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/DoBlockParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/FieldAccessParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/HashLiteralParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/IndexAccessParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesisParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithoutParenthesesParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MathOperatorParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ProcDefinitionParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RangeParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RegexParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RescueClauseParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ReturnParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/StringParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/YieldParserTests.scala

Added parser tests from [Ruby Parser Tests](https://github.com/seattlerb/ruby_parser/blob/master/test/test_ruby_parser.rb). Failing tests are ignored in their own test cases until fixed.

[ruby] More Parser Tests

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/FullNameProvider.scala

For: https://shiftleftinc.atlassian.net/browse/SEN-3030

[c2cpg] Fix infinite recursion in fullname calculation

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/CaseConditionParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesisParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionParserTests.scala

General fixes to `AstPrinter` to fix some of the parser test cases.

[ruby] `AstPrinter` fixes

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/YieldParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ProcParameterAndYieldTests.scala

Added `assoication` to `YIELD` argument list

[ruby] Fix `YIELD` argument list

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/DoBlockParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala

* Added `GroupedParameter` type and handling for new type
* Fixed ANTLR grammar rules for different combinations of block parameters
* Updated relevant parser tests

[ruby] `Block Parameter` fixes

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesisParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala

Added handling for different argument types being used in the same call.

[ruby] Add handling for different arguments in calls

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/semanticsloader/FullNameSemantics.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

Follow up to #4952, including @DavidBakerEffendi's suggestion to log such entries.

[dataflowengineoss] FullNameSemantics logs and merges conflicting FlowSemantics

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/CodeDumperFromContentTests.scala

These synthetic METHOD nodes did not have an offset at all.
For: https://shiftleftinc.atlassian.net/browse/SEN-3250

[jssrc2cpg] Fix offsets for :program and <init> method nodes

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/FileTests.scala

Using the CDT API (getContainingFilename) now.
For: https://github.com/joernio/joern/issues/4924

[c2cpg] Fixed fileName helper

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/Steps.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/StepsTest.scala

fixes https://github.com/joernio/joern/issues/4976

include node id in json (for StoredNode)

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala

Updated handling of `ForEach` loops in Ruby.

[ruby] Fix structure for `ForEach` loops in Ruby

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/json/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/json/ControlStructureTests.scala

* Adds summary/type/dependency hooks into `useJsonAst=true` path
* Outlines basic helper functions for having class and module bodies created correctly

Handle initial class/module body creation & summary creation

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/ExternalCommand.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IncludeAutoDiscovery.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DotNetAstGenRunner.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/DownloadDependenciesPass.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Delombok.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/compiler/CompilerAPITests.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/ClassParser.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/utils/ExternalCommand.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/astgen/AstGenRunner.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ExternalCommand.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/DependencyResolver.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/MavenDependencies.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/ExternalCommandTest.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/dependency/DependencyResolverTests.scala

Works with Java Process / ProcessBuilder now. No more scala.sys.process.

[x2cpg] Refactor ExternalCommand

---

joern-cli/frontends/csharpsrc2cpg/build.sbt
joern-cli/frontends/gosrc2cpg/build.sbt
joern-cli/frontends/jssrc2cpg/build.sbt
joern-cli/frontends/swiftsrc2cpg/build.sbt

Re: https://github.com/joernio/joern/issues/5029
For whatever reason `.listFiles().foreach` crashed there. Maybe this helps.

Copy with executable flag

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/FileDefaults.scala

E.g., used in https://cmake.org/cmake/help/latest/guide/tutorial/index.html

[c2cpg] Allow .cxx extension

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForDeclarationsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeConstants.scala

* kotlin2cpg: run cleanupDelombokOutput and clearJavaParserCaches after using the AstCreationPass from javasrc2cpg (somehow it was forgotten there)
* some minor cleanup/refactoring

[kotlin2cpg][javasrc2cpg] More cleanups

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

Added handling for global variable assignment

[ruby] Global Variable assignment

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

Desugars aliased methods to the form
```ruby
def new_name(*args, &block)
old_name(*args, &block)
end
```
Resolves #5110

[ruby] Alias Methods via Forwarding

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala

* updates astgen to the new version written entirely with Typescript
* fixes relative / full path during *.ejs file handling

[jssrc2cpg] astgen update

---

console/src/main/scala/io/joern/console/Help.scala

usage example for extension mechanism:
```
echo 'Help.additionalHelpEntries += (("aa", "bb", "cc"))' > test-help.sc
./joern --import test-help.sc
joern> help
...
┌────────────────┬────────────────┬─────────────────────────┐
│command         │description     │example                  │
├────────────────┼────────────────┼─────────────────────────┤
│aa              │bb              │cc                       │
...
```

help: simplify generated code and make extensible

---

console/src/main/scala/io/joern/console/BridgeBase.scala

fixes https://github.com/joernio/joern/issues/4999

fix runbefore code order

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala

Added AST generation for `MatchVariable` found in `CaseMatch` expressions.

[ruby] `MatchVariable` handling

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

Added implicit return for Singleton Class.
Resolves #5118

[ruby] Implicit Return for Singleton Class

---

console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala

No longer applicable, but still available in the REPL.

[console] remove rubyDeprecated

---

project/Versions.scala

as per https://github.com/joernio/joern/issues/4999#issuecomment-2520521844

fix joern-server

---

.github/workflows/master.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/upgrade-deps.yml

sbt is no longer included by default in the ubuntu 24 runner
https://github.com/sbt/setup-sbt
https://github.com/actions/setup-java/issues/712#issuecomment-2557396980

fix github actions runner

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForPatternExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/PatternExprTests.scala

I tested this with the cs dataflow tests locally and they pass again. I still have no idea why they passed before...

Fix pattern cast line numbers

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/LocalQueryTests.scala

Fixes: https://shiftleftinc.atlassian.net/browse/SEN-3604

[c2cpg] Fix code string for locals from ICPPASTNamedTypeSpecifier

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala

Provides a `CSharpProgramSummary.filter` operation to simplify creating filtered summaries, in an attempt to reduce the need for manually constructing one every time we wish to restrict `namespaceToTypeMap`.
Additionally, the lower level `BuiltinTypes` and `fromExternalJsons` (both returning `NamespaceToTypeMap`) are now hidden behind the higher level `builtinTypesSummary` and `externalTypesSummary` (both returning `CSharpProgramSummary`).

[c#] provide a filter operation to CSharpProgramSummary

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/ImplicitUsingsCollector.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ImplicitUsingsTests.scala

Handles `<ItemGroup><Using Include="XXX"/></ItemGroup>` tags in `.csproj` files, allowing one to manually add an implicit global using. Interestingly enough, the order in which we write `<Using Include=.../>` and `<Using Remove=.../>` matters.
Aliases, e.g. `<Using Include=XXX Alias=YYY />` are not supported yet.

[c#] support for <Using Include=XXX> in csproj files

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/astcreation/declarations/AstForMethodsCreator.scala
project/Versions.scala

https://github.com/soot-oss/soot/releases/tag/4.6.0
soot 4.6.0 release at Nov 18, 2024.

[jimple2cpg]Update soot to 4.6.0

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/MavenDependencies.scala

A '$' was missing to be able to directly copy-paste the logged command
suggestion.

[javasrc2cpg] Fixed logged debug command suggestion.

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala

Simplifying `astForSimpleMemberAccessExpression` and making sure to use `line/column/code(node)` primitives for setting these properties.

[c#] refactor astForSimpleMemberAccessExpression on getters

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/Defines.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/FullNameProvider.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroArgumentExtractor.scala

Seen during testing on https://github.com/blender/blender
For: https://github.com/joernio/joern/issues/5254

[c2cpg] Multiple crash fixes for blender sources

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala

In a few places we were invoking `astForModifers` only to get their inner `NewModifier` nodes. Shuffled things around so we can avoid that pattern.

[c#] refactor astForModifiers

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala

Splits `astForInvocation` in two (the cases currently supported) smaller, dedicated visitors, by moving the creation of the AST into a common `createInvocationAst` utility. Also took the opportunity to clear up `astForMemberAccessInvocation` as it wasn't super clear when/where extension methods entered the scene.

[c#] refactor astForInvocationExpression

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/GradleDependencies.scala

We ran into the following gradle error when fetching dependencies for a customer project:
```
Failed to apply plugin 'org.gradle.java-test-fixtures'.    
> Project#afterEvaluate(Action) on project '<project-name>' cannot be executed in the current context
```
This PR attempts to avoid this issue by removing the `afterEvaluate {...}` call in the init script we use and doing the task registration whenever `allprojects { project -> ... }` would do it. I wasn't able to reproduce the issue, so I don't know if this will fix the customer's issue or not. I'm also no gradle expert, so I don't know what the full implications of removing `afterEvaluate` are, but the test projects I've tried have all worked equally well with and without it. Most of the logic should be handled lazily, as far as I …

Remove afterEvaluate in gradle dependency fetcher init script

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/astcreation/declarations/AstForDeclarationsCreator.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/MemberTests.scala

[jimple2cpg] add modifiers for field of class.

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala
querydb/build.sbt
querydb/src/main/scala/io/joern/scanners/Crew.scala
querydb/src/main/scala/io/joern/scanners/php/PhpJoern.scala
querydb/src/test/scala/io/joern/scanners/php/PHPJoernTests.scala
querydb/src/test/scala/io/joern/suites/PHPQueryTestSuite.scala

This update improves **PHP version parsing** and **security vulnerability detection** in `php2cpg`. The changes ensure better compatibility with **complex PHP version formats** and enhance **Joern-based queries** for identifying security risks such as **SQL injection, command injection, code execution, unrestricted file operations, and XSS**, which was mentioned in the PhpJoern paper.
- Previous version parsing failed for formats like:  
```
PHP 7.1.33-65+ubuntu20.04.1
```
- We now extract **only the numeric version (`7.1.33`)** to ensure compatibility with **`VersionHelper.compare()`**.
- This prevents failures when checking PHP version support.
We have refined and extended the detection of security vulnerabilities by:
- **Expanding the list of functions monitored** for various security …

[PHP] Enhancing PHP version check logic and add more vulnerabilities detecting types for PHP in queryDB

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/cpp/features17/Cpp17FeaturesTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala

For: https://shiftleftinc.atlassian.net/browse/SEN-3782

[c2cpg] Fixed constructor initializer handling

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/MemberTests.scala

[jimple2cpg] if a member have ConstantValueTag in SootField info, add the tag value to the member possibleTypes.
add tests in MemberTests.

[jimple2cpg] Add ConstantValueTag to the member's`code`

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/cfg/CfgCreationPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala

@DavidBakerEffendi You may want to have a look. The tests you added for this case for javasrc2cpg are still working as expected.
Fixes: https://github.com/joernio/joern/issues/5338

[CFG] Fix CFG in try-catch statements for multiple returns

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/Defines.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/ForEachLoopTests.scala

Basically the same as we do in jssrc2cpg but with types and fullnames.

[c2cpg] Added lowering for for-each loops

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/ForEachLoopTests.scala

Otherwise, we end up with multi-line code fields which breaks sptests findings representation.

[c2cpg] Reverted for-each loop code field to previous version

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/Defines.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/ForEachLoopTests.scala

More in line with javasrc2cpg and kotlin2cpg now. Was too jssrc-ish.

[c2cpg] Simplify for-loop lowering

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForFunctionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/BindingContextUtils.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LambdaTests.scala

Previous version was rather cumbersome and did not correctly handle the
case where a lambda was passed into generic vararg function.
We now use the (i guess) intended way which is
`.getArgumentsWithConversion` instead of looking up the parameter
manually and taking its type as SAM interface.
At least partial fix for: https://shiftleftinc.atlassian.net/browse/SEN-3747

Fix SAM (Single Abstraction Method) interface lookup.

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/NamespaceTypeTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/LocalQueryTests.scala

Fixes: https://shiftleftinc.atlassian.net/browse/SEN-3887

[c2cpg] Fix namespace blocks

---

project/plugins.sbt

https://github.com/xerial/sbt-sonatype/pull/591
https://github.com/ShiftLeftSecurity/sbt-ci-release-early/pull/99

use patched sbt-sonatype which includes our timeout fix

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/FullNameProvider.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/TypeNameProvider.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala

Type string calculation is quite a mess right now and to enable further refactorings and clean-ups I started with extracting everything related to it into its own trait.

[c2cpg] Extract type string calculations into separate trait

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForFunctionsCreator.scala

This blew up a customer scan. CF slack for details, not linking the issue because this repo is public.

[kotlin2cpg] fix an NPE

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForDeclarationsCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeDeclTests.scala

Replaces: https://github.com/joernio/joern/pull/5285/files

[kotlin2cpg] Fix AST for nested classes

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/utils/ExternalCommandImpl.scala

note: I know renaming `cwd` to `workingDir` is technically a breaking change, but IMO that's justified, since `cwd` is misleading / wrong

ExternalCommand: refactor, logging, minor improvements

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForDeclarationsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForFunctionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForStatementsCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/DataClassTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/NestedDeclarationsTests.scala

Basically same as https://github.com/joernio/joern/pull/5407
Also added one testcase for data classes.

[kotlin2cpg] Fix AST for companion classes and declarations in blocks

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstNodeBuilder.scala

This doesn't include any tests to make sure the offsets make sense yet, but those should be added per frontend and fixed on the frontend side.

[x2cpg] Populate offset and offsetEnd for all AST nodes

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/Main.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CustomFileContentProvider.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/JSONCompilationDatabaseParser.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/ParseProblemsLogger.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/ParserConfig.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/PreprocessorPass.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/JSONCompilationDatabaseParserTests.scala

Mostly for readability (although that's subjective ofc).

[c2cpg] Some refactoring

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/utils/Scope.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/utils/ScopeElement.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala

Added a local node for variables in catch statements
Added basic `BlockScope` for PhpScope

[php] Add local node for variable in catch stmt

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/C2CpgScope.scala

No .get calls on Option anymore.
Follow-up to: https://github.com/joernio/joern/pull/5439

[c2cpg] Option-safe scope implementation

---

joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Ghidra2Cpg.scala

Simplified the Ghidra project creation, importing and analysis of the binary file by using the [GhidraProject](https://ghidra.re/ghidra_docs/api/ghidra/base/project/GhidraProject.html) class and its high level abstractions.
The functionality did not change:
- [`importProgram()`](https://github.com/NationalSecurityAgency/ghidra/blob/5e825ebb5a374aaabec26317adc18f4713a47ebe/Ghidra/Features/Base/src/main/java/ghidra/base/project/GhidraProject.java#L641) uses the same `importByUsingBestGuess()` method and returns the primary domain object
- [`analyze()`](https://github.com/NationalSecurityAgency/ghidra/blob/5e825ebb5a374aaabec26317adc18f4713a47ebe/Ghidra/Features/Base/src/main/java/ghidra/base/project/GhidraProject.java#L534) runs the auto-analysis the same way
- …

[ghidra2cpg] Simplify project and program handling

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForStmtSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForTypeSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/AsyncTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/DirectiveTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ForeachTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/SuperTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ToplevelLibraryTests.scala

To be more in line with the other frontends.

[swiftsrc2cpg] Refactor synthetic name generation

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/FullNameProvider.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/TypeNameProvider.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/NamespaceTypeTests.scala

Just like in https://github.com/joernio/joern/pull/5468

[c2cpg] Implement scope-local unique names

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsClassesAstCreationPassTests.scala

https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties

[jssrc2cpg] Added support for Parameter Properties

---

console/src/main/scala/io/joern/console/BridgeBase.scala

Fixes https://github.com/joernio/joern/issues/5469

[console] Fix importing with Windows paths

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/AstQueryTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/LocationQueryTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/Location.scala

This should fix a match error causing crashes later.

Implement more robust method finding logic in LazyLocation

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/AstNodeMethods.scala

of course I find the bug right after merging the previous PR...

[DSL] fix sourceCode if there is no file content

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Delombok.scala

Reverts joernio/joern#5566
More testing needed

Revert "Delombok resource limits"

---

joern-cli/frontends/jssrc2cpg/README.md
joern-cli/frontends/swiftsrc2cpg/README.md
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/Main.scala

- update READMEs
- clarify Swift requirements

[swiftsrc2cpg][jssrc2cpg] Update READMEs

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala

A single problematic file should not crash the whole process. That is not a real fix but will gain is more insights what is going on if we encounter a file causing CDT to crash.

[c2cpg] Handle StackOverflowError

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForFunctionsCreator.scala

When only partial type information is available, the expected type of a
lambda or function expression may not be available. This scenario was
not correctly handled which led to the NoSuchElementException.
Fix for https://shiftleftinc.atlassian.net/browse/SEN-4472

[kotlin2cpg] Fix NoSuchElementException in SAM interface handling.
