src/main/resources/default.argdef, src/main/scala/io/shiftleft/Main.scala
Required by new codepropertygraph library which does not provide
semantics any more.
=> Add default.argdef file.

build.sbt, project/SbtHelper.scala, project/meta-build.sbt
... shamelessly stolen from @mpollmeier. Fixes #15.
Documentation can be generated via
```
sbt generateScalaDocs
```
and ends up in `target/api`.
=> Generation of API documentation

.gitignore, build.sbt, docs/content/querying/_index.md, src/main/scala/io/shiftleft/joern/Main.scala, src/test/scala/io/shiftleft/joern/MethodTests.scala
On each build, we want to ensure that all queries we showcase in the documentation still work. Furthermore, we want to provide a test-based spec for the query language, making it easy for people to pick up the language. This PR brings in the necessary boilerplate for this and some first tests for method stubs.
=> Support for integration tests and sample tests for method stub

docs/config.toml
I decided against the "gitter sidecar" because that big button used up quite a bit of space on mobile, making the text harder to read.
=> Add link to our gitter

docs/content/baselanguage/_index.md, src/test/scala/io/shiftleft/joern/CallGraphTests.scala, src/test/scala/io/shiftleft/joern/DataFlowTests.scala, src/test/scala/io/shiftleft/joern/LocalsTests.scala, src/test/scala/io/shiftleft/joern/MethodTests.scala, src/test/scala/io/shiftleft/joern/SampleDocuTest.scala, src/test/scala/io/shiftleft/joern/package.scala
The way we documented using tests isn't self explanatory, it seems, so, I've added a short into to how this works. I've also taken this as an opportunity to further simplify the boilerplate code.
=> Describe DocuTest concept and simpliy test boilerplate

build.sbt, src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala, src/main/scala/io/shiftleft/joern/CpgLoader.scala, src/main/scala/io/shiftleft/joern/JoernParse.scala, src/test/scala/io/shiftleft/joern/DataFlowTests.scala, src/test/scala/io/shiftleft/joern/LocalsTests.scala, src/test/scala/io/shiftleft/joern/package.scala
This is the corresponding `joern` commit for https://github.com/ShiftLeftSecurity/codepropertygraph/pull/165
The idea is to separate enhancements into semantic-dependent and semantic-independent enhancements and execute the semantic-independent enhancements at generation time, while delaying semantic-dependent enhancements to load time. That way, semantic can be changed and the graph can be reloaded for this to take immediate effect - without needing to recalculate all other enhancements.
=> Add enhancements at generation time (except for data flow)

joern-parse, joern-query, joern-server.sh, joernd
- Rename `joern-server.sh` to `joernd` to be consistent with naming convention (no .sh extension) and not clash with the directory name `joern-server`
- Ensure that `joernd` works when called from different directories
- Check if code has already been compiled and tell user to run `sbt stage` if not.
=> Cleanup shell scripts

joern-server/src/main/scala/io/shiftleft/joern/server/JettyLauncher.scala
While testing the client, I often found myself opening up a server when one was already running. Cancelling that with ctrl+c causes delays, so this PR determines whether the port is already in use, and if so, the server is terminated immediately. Also, I renamed the environment variable `PORT` to `JOERN_PORT` to avoid name clashes.
=> Clean exit if port is in use

docs/content/essentials/building/_index.md
Add comment about tuning JVM memory parameters, as this seems to be a reoccurring problem people run into on initial use of Joern.
=> Add documentation about configuring the JVM

joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala, joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala, joern-cpg2scpg
`joern-parse` currently executes `fuzzyc2cpg`, followed by `cpg2scpg` (enhancements). For performance testing, we want to be able to run `cpg2scpg` as a a standalone program without needing to regenerate the base CPG via `fuzzyc2cpg` every time. This PR makes it possible to run `joern-parse` without enhacements (--noenhance) and `cpg2scpg` as a standalone program.
=> Allow running cpg2scpg as a standalone program

build.sbt
see https://github.com/ShiftLeftSecurity/codepropertygraph/pull/218
=> upgrade to latest cpg, includes a fix for the references and a memory leak

joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala, joern-cli/src/main/scala/io/shiftleft/joern/CpgLoader.scala
We used to apply semantics every time we loaded the CPG - even before running enhancements in cpg2scpg. That's not necessary, so, we're now not doing that anymore.
=> Do not apply semantics twice.

joern-cpg2scpg, joern-parse, joern-query, joernd
1) cpg2sp is 10-20% faster than with other GCs (haven't benchmarked other use cases though)
2) with the same Xmx setting it allows to allocate ~10% more objects (in a very simplistic test, see below)
3) the default GC acts strangely when Xms isn't set at the same time, and the above difference goes up to 20%!
part of https://github.com/ShiftLeftSecurity/product/issues/2681
```
import java.util.ArrayList;
import java.util.List;
public class HeapTests {
/**
* -Xmx4g
* -Xms4g
* -XX:+UseParallelGC
* -XX:+UseConcMarkSweepGC
* -XX:+UseG1GC
*/
public static void main(String[] args) throws Exception {
System.out.println("max heap: " + Runtime.getRuntime().maxMemory() / 1024 / 1024);
List<int[]> data = new ArrayList<>();
int i = 0;
try {
while (true) {
data.add(new int[1024]);
i++;
if (i % 10000 …
```
=> use G1GC garbage collector: faster, more usable space

joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala, joern-cli/src/main/scala/io/shiftleft/joern/CpgLoader.scala, joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala, joern-cli/src/test/scala/io/shiftleft/joern/GenerationTests.scala, joern-server/src/main/scala/io/shiftleft/joern/server/JoernServerImpl.scala
Usually, people will not want to edit the semantics file. In this case, we should not apply semantics on each load (which can often take longer than the loading operation itself), but rather, we should apply semantics on parsing and store edges as part of `cpg.bin.zip`. This PR introduces this default behavior and allows `joern-parse` and `cpg2scpg` to be configured for deviating behavior.
=> Run data flow analysis as part of joern-parse

joern-cli/src/main/scala/io/shiftleft/joern/console/AmmoniteBridge.scala
Forgot an import on launch of the joern shell. This import is necessary for pipe operators to work.
=> Add missing import to support pipes in `./joern`

joern-parse, joern-query, joernd
Change `SCRIPT` path setting to fix the issue of unrecognizing the successful `sbt stage` process. Please refer to this issue [#110](https://github.com/ShiftLeftSecurity/joern/issues/110)
=> Fix wrong path setting 

joern, joern-parse, joern-query
After running `sbt stage`, executable scripts for joern, joern-parse, and joern-query end up in a target directory, and these are then included in the distribution. For fast turn-around during development, I suggest we introduce these symlinks so that we can already access joern, joern-parse, and joern-query without building the distribution and without tasking us where the build target directory is.
=> Add symlinks for `joern(-(parse|query))?`

docs/content/essentials/quickstart/_index.md
This reverts commit b3e4b09b1ad167a9ce1a967014dc9ae6d2ebf640.
Since we added symlinks to `joern`, `joern-parse`, and `joern-query`, the quick start guide is accurate again and updating the docs (https://github.com/ShiftLeftSecurity/joern/issues/122) is optional.
=> Revert "Fix quick start guide."

build.sbt
Use newest version of fuzzyC that does not crash when a compilation unit cannot be translated.
=> Use newest version of fuzzyc

scripts/ast-for-funcs/ast-for-funcs.scala, scripts/cfgToDot/cfgToDot.scala
Json generated from ast-for-funcs now contains all AST edges at AST nodes iff this node is an inVertex or outVertex for that edge.
=> Added edges to ast-for-funcs

README.md, joern-cli/src/universal/joern, joern-cli/src/universal/joern-cpg2scpg, joern-cli/src/universal/joern-parse, joern-cli/src/universal/joern-query, joern-server/src/universal/joernd
On OSX you couldn't use readlink so have to use greadlink from coreutils package.
=> Add greadlink option for macOS

joern-cli/src/main/scala/io/shiftleft/joern/JoernScriptExecutor.scala, joern-cli/src/main/scala/io/shiftleft/joern/JoernScriptManager.scala, joern-cli/src/main/scala/io/shiftleft/joern/console/Console.scala, joern-cli/src/test/scala/io/shiftleft/joern/RunScriptTests.scala
Running scripts via the Script Manager can now be parameterized with a CPG filename (other than the default one) or a pre-loaded CPG.
As a side effect: this improves performance during testing a lot as CPGs are not loaded/copied multiple times for the same test project anymore. Same holds if a user runs his scripts multiple times with a pre-loaded CPG.
=> Refactored the Joern Script Manager

docs/content/importing/_index.md
Added a bit more color to the preprocessor docs.
* Changed the section title so that it becomes clear on first sight that this section is about what to do when you have header files
* Since we will usually end up not having all header files after all, I've removed the idea of completeness from the text, and instead, just talk about higher quality CPGs, generated by taking into account the additional information contained in the header files.
=> Light edits to preprocessor docs

build.sbt
I can't download the newest version of `codepropertygraph` yet, although publication to sonatype was successful. With this PR, I am testing whether the artifact can be downloaded when requested from travis. Who knows.
=> Update to newest dependencies.

joern-cli/src/main/scala/io/shiftleft/joern/JoernScriptExecutor.scala, joern-cli/src/test/scala/io/shiftleft/joern/RunScriptTests.scala, scripts/functions-to-dot/description.json, scripts/functions-to-dot/functions-to-dot.scala
- Adds a new script, `functions-to-dot`, that produces a DOT graph for all internal functions contained within a CPG.
=> Add script to produce DOT for funcs in a CPG

smoke-test.sh
We fail to fully parse TF and MS Terminal as we catch the exception thrown and "skip" the failed module. This isn't communicated outside the JVM therefore we have no way to detect these unless we change our code to stop handling these exceptions.
I have created two separate issues to fix these:
- https://github.com/ShiftLeftSecurity/fuzzyc2cpg/issues/158
- https://github.com/ShiftLeftSecurity/fuzzyc2cpg/issues/159
=> Add joern-parse smoke tests.

joern-cli/src/main/scala/io/shiftleft/joern/JoernScriptManager.scala
Allows scripts to be run without passing the cpg as a parameter:
```scala
cpg.runScript("script-name")
```
=> Add extension to Cpg for running scripts.

build.sbt
Typing `joern --help` now displays the correct help information.
=> Bump CPG version to fix help prompt.

build.sbt, docs/content/kernelexamples/_index.md, joern-cli/src/main/scala/io/shiftleft/joern/console/AmmoniteBridge.scala
- Use `~/.shiftleft/joern` as the REPL directory (previously `~/.shiftleft/ocular`).
- Additional docs changes to match Linux v4.7 (previous based on master).
=> Use separate repl directory.

README.md, docs/content/importing/_index.md, joern-cli/src/universal/joern, joern-cli/src/universal/joern-cpg2scpg, joern-cli/src/universal/joern-parse, joern-server/src/universal/joernd
- Fix minor issue with launcher scripts using `sh` even though the scripts contain bash extensions. The scripts now run with `bash` rather than `sh`.
=> Clarify usage of cpg-create script with joern-server.

joern-cli/src/main/resources/scripts/general/pdg-for-funcs-dump.sc, joern-cli/src/main/resources/scripts/general/pdg.sc, joern-cli/src/main/resources/scripts/general/scripts.json, joern-cli/src/test/scala/io/shiftleft/joern/RunScriptTests.scala
For the following program:
```c
int main() {  
int a = 2;
int b = 3;  if (a > 0) print(a);
int result = foo(a, b);
return result;  
}
int foo(int x, int y) {
return x + y;
}
void print(int x) {
printf(x);  
}
```
This script will print:
```
res2: AnyRef = (
List(
(57L, 54L),
(26L, 20L),
(24L, 20L),
(31L, 10L),
(31L, 15L),
(24L, 10L),
(35L, 28L),
(28L, 31L),
(46L, 42L),
(43L, 45L),
(46L, 41L),
(7L, 35L),
(20L, 10L)
),
List(
(35L, "return result;"),
(28L, "result = foo(a, b)"),
(24L, "print(a)"),
(20L, "a > 0"),
(7L, "RET"),
(31L, "foo(a, b)"),
(46L, "x + y"),
(57L, "printf(x)"),
(43L, "RET"),
(26L, "a")
)
)
```
The first list contains the edges between the vertices `in_vertex_id => out_vertex_id`. The second contains all of the vertices in the PDG, along with the code that the vertex …
=> Add new PDG script.

docs/content/importing/_index.md
We had problems finding methods in cpgs that were built with fuzzy2cpg. This explains why we had those problems and provides a solution. 
@fabsx00 Do we actually want to put this information in the official docs? This place seems the most logical to search for this info, that's why I put it here.
=> Add description for using fuzzyc2cpg cpgs

build.sbt, joern-cli/src/test/scala/io/shiftleft/joern/RunScriptTests.scala
Recent updates in fuzzyc2cpg and codepropertygraph caused failing builds. This bumps versions to incorporate the bugfixes, and adapts test expectations to the new reality.
=> bump dependencies, adjust test expectations

build.sbt, joern-cli/src/main/resources/scripts/c/const-ish.sc, joern-cli/src/main/resources/scripts/c/scripts.json, joern-cli/src/test/resources/testcode/const-ish/const-ish.c, joern-cli/src/test/scala/io/shiftleft/joern/RunScriptTests.scala
This supports the detection of modifying a member of a const object directly, or via casting it to a non-const type and then modifying.
I attempted to add support for detecting assignment to const class members but the `Member` node isn't a `TrackingPoint` so I was unable to find any flows for these. If there is a way do let me know and I'll re-add it!
=> Add script to detect assignment to member of const object.

build.sbt, joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala, joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala, joern-cli/src/test/scala/io/shiftleft/joern/AbstractJoernCliTest.scala
Re: https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/182
Use FuzzyC2Cpg's overflowDB output mode. The entire CPG creation thus now uses lazy-loading.
=> Use FuzzyC2Cpg's overflowdb mode by default

build.sbt, joern-cli/src/main/resources/scripts/c/malloc-leak.sc, joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala
In addition, log time it takes to close the CPG and remove redundant call to `createIndex`.
=> Update `cpg` dependency

build.sbt, joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala, joern-cli/src/universal/joern-parse
To create an overflowdb for all Linux Kernel 5.5 drivers, with `-Xmx30G` on `Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz`, we are now at approximately 1 hour. This includes running all passes, in particular intra-procedural reachability analysis, `CDG` edges, and `CONTAINS` edges.
I have been running tests on creating overflowdb files for all drivers of the Linux kernel, and it turned out that `joern-parse` ran into GC trouble while `./joern-parse --noenhance`, followed by `./joern-cpg2scpg` did not. In other words, although all memory allocated as part of `fuzzyc` could be freed, it is not, possibly due to a memory leak. To circumvent this problem and similar problems in the future, we now spin up `joern-cpg2scp` in a separate JVM.
=> Run fuzzyc and enhancements in separate JVMs

joern-cli/src/main/scala/io/shiftleft/joern/Predefined.scala, joern-cli/src/main/scala/io/shiftleft/joern/console/AmmoniteBridge.scala, joern-cli/src/main/scala/io/shiftleft/joern/scripting/JoernAmmoniteExecutor.scala
We were using slightly different predefs for ammonite for the interactive shell vs scripts. To reduce duplication and make the difference immediately visible, I've introduced a `Predef` object hosting shared code and the diffs.
=> Reduce duplication for predefs

joern-install.sh
The `readlink` command on macOS does not support the `-f` / `--canonicalize`
parameter available in the GNU version. This adds a check for the Darwin
kernel and provides an alternative approach to finding the script's
directory.
Addresses: #229
=> Support installation via script on macOS

joern-cli/build.sbt, joern-cli/src/main/scala/io/shiftleft/joern/console/JoernConsole.scala
* For some reason, the pager doesn't work if ammonite is not specified as a direct dependency in joern
* Print a little message to point people to `help` and `browse(help)`
=> Fix pager + tell people about `help`

fuzzyc2cpg.sh, joern-cli/src/main/scala/io/shiftleft/joern/Fuzzyc2cpg.scala, joern-cli/src/universal/fuzzyc2cpg.sh
Fuzzyc2cpg needs to be runnable directly from the joern install directory for `importCode` to work.
=> Make it possible to run fuzzyc directly

joern-install.sh
The script indicated that the default answer to "install [Y|n]" is "yes" by capitalizing Y, however, the default value was "no".
=> Fix install script

build.sbt, joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala, joern-cli/src/main/scala/io/shiftleft/joern/CpgLoader.scala, joern-cli/src/main/scala/io/shiftleft/joern/console/JoernAmmoniteExecutor.scala, joern-cli/src/main/scala/io/shiftleft/joern/console/Predefined.scala
- Adaptions to changes in https://github.com/ShiftLeftSecurity/codepropertygraph/pull/738
- Also, make `run.ossdataflow` work by default
=> Fix passing of semantics to OssDataFlow pass

joern-cli/build.sbt
for simplicity and also to avoid `line too long` error on windows
=> wildcard import from staged `lib` dir

build.sbt, joern-cli/build.sbt
using zt-zip resulted in losing executable file attributes, while
sbt-native-packager does set those just fine - i didn't even know this existed
=> use sbt-native-packager to preserve executable file attributes

joern-cli/src/universal/joern
Slight regression: while joern-parse uses the correct logger config, joern does not.
=> Make sure `joern` script picks up log4j2.xml

joern-cli/src/universal/conf/log4j2.xml
Ran Joern a bit with the default logger config and while the info printed is relevant for devs, it's quite noisy for users. Tuned down the log level to WARN again.
=> Tune down default logger config

schema-extender/build.sbt, schema-extender/src/main/scala/io/shiftleft/repl/schemaextender/SchemaExtender.scala
DRY is important, but sometimes it stands in the way of simplicity.
Moving the schema-extender code to the cpg repo for reuse brought a
number of complications, so instead, let's go for copy/pasta managed
sources in joern/ocular now.
=> copy the schema-extender code to joern/ocular, drop from cpg

build.sbt, docs/content/querying/flows/_index.md, joern-cli/build.sbt, joern-cli/src/main/resources/scripts/c/const-funcs.sc, joern-cli/src/main/resources/scripts/c/const-ish.sc, joern-cli/src/main/resources/scripts/c/malloc-leak.sc, joern-cli/src/main/resources/scripts/graph/graph-for-funcs.sc, joern-cli/src/main/resources/scripts/graph/pdg-for-funcs-dump.sc, joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala, joern-cli/src/main/scala/io/shiftleft/joern/CpgLoader.scala, joern-cli/src/main/scala/io/shiftleft/joern/console/Predefined.scala
`dataflowengine` was renamed to `dataflowengineoss` to avoid name clash with package of the same name in `codescience`.
=> Adapt to changes in `codepropertygraph`

html/packages/website/gatsby-config.js, html/packages/website/package-lock.json
Github seems to now include checking of context-less checking of dependencies for versions that are known to contain vulnerabilities of some sort. Upgraded versions to make it happy again. Also replaced gatsby default theme color.
=> Make github happy

docs2/src/theme/DocSidebar/index.js
This default Docusaurus responsive behaviour of disabling the sidebar
and showing a menu item instead in the top right corner is confusing, so
it will be disabled for the moment until a better reponsive solution is
found.
=> Disable responsive sidebar

docs2/docs/cpgql/augmentation-directives.mdx, docs2/docs/cpgql/complex-steps.mdx, docs2/docs/cpgql/core-steps.mdx, docs2/docs/cpgql/execution-directives.mdx, docs2/docs/cpgql/filter-steps.mdx, docs2/docs/cpgql/help-directive.mdx, docs2/docs/cpgql/node-type-steps.mdx, docs2/docs/cpgql/repeat-steps.mdx
Some of the wording used to describe various CPGQL steps was inconsistent and also not flexible enough to describe dataflow steps. This change in terminology fixes those two issues by making the `Directive` a basic building block for definitions in CPGQL.
```
> OVERVIEW
>>> Directive
CPGQL Directives are keywords of the Code Property Graph Query Language.
>>> Step
CPGQL Steps are combinations of one or more Directives that describe graph traversals in the CPGQL. They are represented by one or more Directives.
>>> Node-Type Step
CPGQL Node-Type Steps are Steps that traverse nodes based on their type. They are represented by a single Directive.
>>> Filter Step
CPGQL Filter Steps are Steps which filter nodes in a traversal according to a criterion. They are represented by one or more …
```
=> Update CPGQL terminology

docs2/docusaurus.config.js, docs2/src/css/custom.css
=> Fix a few items in the styling of the documentation site

build.sbt, joern-cli/src/main/resources/scripts/c/const-funcs.sc, joern-cli/src/main/resources/scripts/c/const-ish.sc, joern-cli/src/main/resources/scripts/c/malloc-leak.sc, joern-cli/src/main/resources/scripts/c/malloc-overflow.sc, joern-cli/src/main/resources/scripts/c/pointer-to-int.sc, joern-cli/src/main/resources/scripts/c/syscalls.sc, joern-cli/src/main/resources/scripts/c/userspace-memory-access.sc, joern-cli/src/main/resources/scripts/graph/ast-for-funcs-dump.sc, joern-cli/src/main/resources/scripts/graph/ast-for-funcs.sc, joern-cli/src/main/resources/scripts/graph/cfg-for-funcs-dump.sc, joern-cli/src/main/resources/scripts/graph/cfg-for-funcs.sc, joern-cli/src/main/resources/scripts/graph/cfgToDot.sc, joern-cli/src/main/resources/scripts/graph/functions-to-dot.sc, joern-cli/src/main/resources/scripts/graph/graph-for-funcs.sc, joern-cli/src/main/resources/scripts/graph/pdg-for-funcs-dump.sc, joern-cli/src/main/resources/scripts/graph/pdg.sc, joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala, joern-cli/src/main/scala/io/shiftleft/joern/console/Predefined.scala, joern-cli/src/test/scala/io/shiftleft/joern/ConsoleTests.scala
important: this is part of the 'big bang' and should only be merged once we're happy with the migration guide and ready to merge all related PRs
depends on https://github.com/ShiftLeftSecurity/codepropertygraph/pull/923
=> use odb traversal instead of tinkerpop api

build.sbt, joern-cli/src/main/resources/scripts/c/const-funcs.sc, joern-cli/src/main/resources/scripts/c/const-ish.sc, joern-cli/src/main/resources/scripts/c/malloc-leak.sc, joern-cli/src/main/resources/scripts/c/malloc-overflow.sc, joern-cli/src/main/resources/scripts/c/pointer-to-int.sc, joern-cli/src/main/resources/scripts/c/syscalls.sc, joern-cli/src/main/resources/scripts/c/userspace-memory-access.sc, joern-cli/src/main/resources/scripts/graph/ast-for-funcs-dump.sc, joern-cli/src/main/resources/scripts/graph/ast-for-funcs.sc, joern-cli/src/main/resources/scripts/graph/cfg-for-funcs-dump.sc, joern-cli/src/main/resources/scripts/graph/cfg-for-funcs.sc, joern-cli/src/main/resources/scripts/graph/cfgToDot.sc, joern-cli/src/main/resources/scripts/graph/functions-to-dot.sc, joern-cli/src/main/resources/scripts/graph/graph-for-funcs.sc, joern-cli/src/main/resources/scripts/graph/pdg-for-funcs-dump.sc, joern-cli/src/main/resources/scripts/graph/pdg.sc, joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala, joern-cli/src/main/scala/io/shiftleft/joern/console/Predefined.scala
This reverts commit 53ce3b10c069f241a8e1a21db49b7be0201e9b7a.
=> Revert "use odb traversal instead of tinkerpop api (#334)"

docs2/package.json, docs2/src/cpgqlref.js
This change fixes the documentation build errors that arose from
949d34f3a1d93dab59482c8875dbe739cdd39f37 and adds an a `yarn` command
for running the test suite to check for this kind of errors more easily.
=> Fix errors in `cpgqlref.js`

build.sbt
This reverts commit 2f0adb8c30a34599b9da0c66d44783b85e8fbbc3 because it seems to break completion.
=> Revert "Bring in PDG improvements (#344)"

build.sbt, joern-cli/src/main/scala/io/shiftleft/joern/console/Predefined.scala
`generated.nodes` now has a package object, so we need to apply the
"import tax" for ammonite :)
=> upgrade dependencies

joern-cli/src/main/scala/io/shiftleft/joern/console/JoernConsole.scala
Fix a recent regression: the implicit of type `Semantics` was no longer available by default.
=> Make `Semantics` implicit available by default

joern-cli/src/main/scala/io/shiftleft/joern/JoernExport.scala
Completed work on initial version of `joern-export`, a command line tool for exporting different intraprocedural intermediate representations into dot format. The exporter is quite fast. See an example below where we export ASTs for all functions in VLC in 38 seconds. Exports 2014 Code Property Graph by default.
=> Completed initial version of `joern-export`

Dockerfile
This Pull request is in response to #360 
For some reason when the docker build failed on my machine at the step `RUN curl -sL "https://piccolo.link/sbt-$SBT_VERSION.tgz" | gunzip | tar -x -C /usr/local` and I have determined that the issue is downloading the tar file. It seems as though the file is not located at that address anymore.
The official [sbt website](https://www.scala-sbt.org/download.html) offers downloads for each version of sbt straight from GitHub. Swapping the location of sbt from `https://piccolo.link/sbt-$SBT_VERSION.tgz` to `https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz` seems to fix the issue
=> Fix local Dockerfile issue

build.sbt
New `codepropertygraph` fixes overtainting issue with access paths. This PR brings in that fix.
=> Bring in member access fix

joern-cli/src/main/scala/io/shiftleft/joern/JoernStats.scala, joern-cli/src/universal/joern-stats, joern-stats
Useful for printing statistics on Code Property Graph files
when an interactive session is too overkill.
Example usage:
```
$ ./joern-stats example.cpg.bin.zip
METADATA  1
NAMESPACE 3827
TYPE_DECL 29983
METHOD    262613
CALL      5708704
FINDING   275
```
=> Implement `joern-stats` subtool

joern-install.sh
The install script includes an option where the default answer once is stated as yes, once as no. This PR removes the "yes" part, leaving the "no" part which is what the code actually does.
=> Promt about installing Joern tools

joern-cli/build.sbt
We were previously not including scripts in the distribution. This PR addresses that.
=> Include scripts in distribution

build.sbt, joern-cli/build.sbt, joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala, joern-cli/src/main/scala/io/shiftleft/joern/JoernStats.scala, joern-cli/src/universal/joern-parse
You can now import java code and the load the corresponding CPG as follows:
* `./joern-parse --language java ../plume/src/test/resources/extractor_tests/dir_test`
* `./joern`
*  `importCpg("cpg.bin")`
* `cpg.method.l`
I have also cleaned up the `joern-parse --help` text a bit and grouped items. In `joern-parse.sh`, a hack has been removed that provides better performance but severally complicated matters.
The next step is to make `importCode` work to enable importing Java code directly from the shell and in joern scripts. This is a bit tricky because we now have two alternative frontends for Java, one available in both joern and ocular, and one available only in ocular.
=> Integrate plume into `joern-parse`

lib
Created a symlink from `lib` to `joern-cli/target/universal/stage/lib/` so that both in the installed distribution and in the development tree, plugins can be installed in `config.install.root` + `lib`.
=> Add `lib` symlink to allow plugins in dev tree

build.sbt, joern-cli/src/main/scala/io/shiftleft/joern/JoernScan.scala, joern-cli/src/universal/joern-scan, joern-scan
Brings `joern-scan` from `query-database` to main joern. Goal is to ensure that the query database only contains queries yet `joern-scan` can be used from it.
Depends on: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1071
=> `JoernScan`

joern-install.sh
`joern-install.sh` always fetches the latest release and installs it and github takes about 20 minutes to deliver that release to Germany. That's making iterative work on the installer a pain. It also means that one can't test-install a modified local version of joern. To fix both of these problems, I'm introducing a `--no-download` flag that runs joern-install.sh for the local source code.
=> Add `--no-download` flag for `joern-install.sh`

joern-install.sh
* Detect existing installations and remove them, guided by user or with the `--reinstall` flag in non-interactive mode
* Copy over missing symlinks to `/usr/local/bin`
* In interactive mode, use `sudo` only for link creation
* In non-interactive mode, warn if not run with `sudo`
* Make sure that installation is owned by user even if sudo is used.
=> New cleaned up installer script

README.md, joern-install.sh
* By default, install non-interactively
* Removed `--non-interactive` flag and introduced `--interactive` instead
* Indentation fixes
* README adaptions
=> Make non-interactive installation the default

joern-cli/src/main/scala/io/shiftleft/joern/JoernScan.scala
By default, --updatedb will download the version specified in the Joern release, however, it allows the user to alternatively specify a version. We now also allow supplying "latest", saving the user from needing to check what the latest version is. It should be noted, however, that the latest version of querydb may not be compatible with the installed version of joern.
=> Allow specifying `--dbversion latest` in `--updatedb`

joern-cli/build.sbt, joern-cli/src/main/scala/io/shiftleft/joern/plume/PlumeCpgGenerator.scala
- Upgraded Plume version (this one supports JAR intake directly)
- Combined functions that handle JAR and directory separately into one case
- Internally, Plume v0.1.6 unzips the JAR file to `$TEMP/plume` where it then reads it in as a directory
=> Simplified Java file intake

joern-cli/build.sbt
The current version of Plume in Joern has the following bug: https://github.com/plume-oss/plume/issues/69
This is not reproducible in v0.1.8.
=> Bump up Plume to v0.1.8

.gitignore
This stopped us from releasing after the plume upgrade. It would probably be better to configure the log dir via env vars, but this works too...
re https://github.com/ShiftLeftSecurity/joern/pull/481
=> fix gitignore for release

joern-cli/build.sbt
- `ArrayRef` now gets projected as an `Operators.indexAccess` call with index and base identifier as the arguments.
- `InstanceOfExpr` now gets projected as an `Operators.instanceOf` call.
- `LengthExpr` now gets projected as an `Operators.lengthOf` call. This is a custom operator
- `MonitorStmt` now gets projected as an `Unknown` vertex.
- `NegExpr` now gets projected as an `Operators.minus` call.
- Crashing passes from making the program hang. Exceptions are caught, logged, and the build is saved as far as it got.
- `ThrowStmt` is now an `Unknown` vertex where control flow ends at.
- `NewArrayExpr` is now an `Unknown` vertex.
=> Upgrade Plume to v0.4.0

joern-cli/src/main/scala/io/shiftleft/joern/JoernScan.scala
Previously, `joern-scan` attempted to guess the source language, and it was frequently wrong. With this PR, we can specify the language via the `--language` flag.
=> Allow specifying language in joern-scan.

joern-cli/src/main/scala/io/shiftleft/joern/JoernScan.scala
* Do not run all queries but only queries with the `default` tag
* Rename `--onlyTags` to `--tags` and introduce special argument `all`
* Rename `--only-names` to `--names` for consistency
What remains an open issue is that we do not yet select only the queries for a specific language.
**Warning**: do not merge before updating querydb to contain queries with the `default` tag and changing the default version of querydb here. Furthermore, a corresponding PR to update the documentation is required for the `website` repo.
=> `joern-scan`: improve default query selection

joern-cli/src/universal/schema-extender/build.sbt
... mostly so that works seamlessly within an IDE
=> read cpgVersion from file rather than env var

joern-cli/build.sbt
- Plume now defaults to constructing call graph using Spark (Andersen-style pointer analysis) instead of simple CHA
- Call graph is now much more precise and may result in fewer unrealisable paths during data-flow analysis but this may give a slower initial build and use more memory during CPG build
- All methods are now correctly set as possible entry points
=> Upgrade to Plume 0.5.12

build.sbt, joern-cli/build.sbt, joern-cli/src/main/scala/io/shiftleft/joern/Js2Cpg.scala, joern-cli/src/universal/js2cpg.sh, js2cpg.sh, project/Versions.scala
These changes add `js2cpg.sh` to the Joern repo, allowing users to both generate the cpg from javascript code by calling `./js2cpg <SRC_DIR>` from the root directory, as well as in Joern through `importCode.javascript("src_dir")
`sbt clean test`, as well as manual tests creating the cpg both by calling `js2cpg.sh` and through Joern. I didn't test whether this specifically works when installing joern via `joern-install.sh`, but I did verify that `c2cpg` is successfully installed by this, and the approach followed here mimics that one almost exactly.
=> Add js2cpg to Joern

.github/workflows/release.yml, build.sbt, joern-cli/build.sbt, joern-cli/src/main/scala/io/shiftleft/joern/C2Cpg.scala, joern-cli/src/main/scala/io/shiftleft/joern/Fuzzyc2cpg.scala, joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala, joern-cli/src/main/scala/io/shiftleft/joern/Js2Cpg.scala, joern-cli/src/universal/c2cpg.sh, joern-cli/src/universal/fuzzyc2cpg.sh, joern-cli/src/universal/ghidra2cpg, joern-cli/src/universal/js2cpg.sh, joern-install.sh, project/Frontends.scala, project/SimpleCache.scala, project/Versions.scala
* also: upgrade cpg
* smaller classpath
* sbt/idea/... work faster
* joern/ocular start faster
* no hidden memory leaks (as observed with fuzzyc2cpg)
* less complexity in classpath
* no issues with jre versions
* only a matter of time until we have version clashes between frontends
=> change packaging: download frontends as binaries

build.sbt, project/Frontends.scala, project/Versions.scala
This is a convenience follow-up to https://github.com/joernio/joern/pull/583 and decouples the version used to fetch `c2cpg` and `fuzzyc2cpg` from the `codepropertygraph` version. This lets you test local `codepropertygraph` changes without having to use local `c2cpg` and `fuzzyc2cpg` distributions, provided no changes to the front-ends need to be tested as well (a common case).
`sbt clean stage test`, followed by 
```
❯ ./c2cpg.sh
Error: Missing argument input-dirs
Try --help for more information.
```
=> Add a separate C front-end version to decouple front-end and codepropertygraph staging

.github/workflows/release.yml, joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala
https://github.com/joernio/joern/runs/3493692134 was failing due to a mismatch between the JDK version used for the PR and release actions. Either one of the included changes should fix it, but I'm including both since switching to `trim` shouldn't have a significant impact on joern-parse functions.
__With these changes, Joern will build for Java 11. If this is an issue, we can add an option to build for Java 8 instead__
=> Switch to legacy String.trim and switch to JDK11

joern-cli/build.sbt, joern-cli/frontends/plume/src/main/scala/io/joern/plume/Main.scala
- Plume upgraded to 0.5.14
- OverflowDBDriver `close()` called via `Using.resources` to write results
=> Plume Empty ODB Fix

build.sbt, updateDependencies.sh
Bumped versions with `./updateDependencies.sh`
`sbt clean test stage`
=> Add js2cpg and javasrc2cpg to updateDependencies and bump versions

joern-cli/src/main/scala/io/shiftleft/joern/Cpg2Scpg.scala
Fix a bug in `joern-parse` where `dataflowOss` wasn't added to `metaData.overlays`.
=> Make sure `dataflowOss` is added to `metaData.overlays`

Dockerfile
I got a `java.lang.UnsupportedClassVersionError` when I tried to use the image built by the Dockerfile.
Docker build command: `docker build -t joern .`
Docker run command: `docker run -it -v$PWD:/share --name joern_worker joern bash`
Error log running inside the Docker container: [error-log.txt](https://github.com/joernio/joern/files/7228722/error-log.txt).
My solution was to bump the JRE version from 8 to 11 in the Docker container. My development machine runs Windows so I'm trying to use Joern in Docker. Bumped Java version following this guidance: https://www.baeldung.com/java-lang-unsupportedclassversion and seeing that the CI action runs JDK 11 (https://github.com/joernio/joern/blob/master/.github/workflows/pr.yml#L11).
I hope this is helpful!
=> Bump JRE version from 8 to 11 in Dockerfile

joern-cli/src/main/scala/io/shiftleft/joern/JoernParse.scala, joern-cli/src/main/scala/io/shiftleft/joern/JoernScan.scala
Adds a `list-languages` option to list available languages with `joern-scan` and `joern-parse`, for example
```
❯ ./joern-scan --list-languages
Available languages (case insensitive):
- golang
- fuzzy_test_lang
- csharp
- java
- php
- c
- kotlin
- ghidra
- javascript
- python
- llvm
- newc
- javasrc
```
=> Add a list-languages option to joern-scan and joern-parse

console/src/main/scala/io/joern/console/cpgcreation/CpgGeneratorFactory.scala, console/src/main/scala/io/joern/console/cpgcreation/package.scala, console/src/test/scala/io/joern/console/LanguageHelperTests.scala
* if input is a directory, scan it recursively, rather than just the top level
* do a group count of all files in given directory, rather than just searching for one language followed by the next etc. rationale: most projects have a mix of languages
* cleanup, docs, refactor
* add javasrc as potential language option
=> rework/improve heuristics for language/frontend detection

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/ExtendedCfgNode.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/LoopTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/SwitchTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/TryTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaDataflowFixture.scala
When executing the data flow engine on a multi-core machine and paths for multiple sinks overlap, results are not 100% stable. I will address this in a follow-up PR. For now, I am fixing the flaky test that highlights this problem by making it more precise.
=> Fix flaky test

build.sbt, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/MacroHandlingTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/unpacking/JarUnpacking.scala
Depends on https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1516
=> Include `lineNumberEnd` in method full names of calls to macros

console/src/main/scala/io/joern/console/BridgeBase.scala, console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala, console/src/main/scala/io/joern/console/cpgcreation/package.scala, console/src/test/scala/io/joern/console/ConsoleTests.scala
After plenty of testing and improving of the macro handling, with this PR, we make the new Eclipse-CDT-based C/C++ the default frontend for C/C++. This enables us to process modern C++ and handle the preprocessor without requiring the user to jump through configuration hoops. As is the true for the old frontend, the new frontend does NOT require a working build environment: if default header files are installed on the system, they will be taken into account. If they can be heuristically identified in the code base, they are picked up. If not, the analyzer continues with what it has and does not simply abort. This makes the tool ideal for analyzing code that is only partially available, code that comes from a decompiler, old code for which configuring a build environment is time consuming, …
=> Make the new C/C++ frontend the default frontend

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/ExtendedCfgNode.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/ResultTable.scala, dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/queryengine/ResultTableTests.scala
Introduces `reachableByDetailed` as a replacement for `reachableByTable`, which was introduced a few weeks back for experimental purposes, but unfortunately, contained a race condition. `reachableByDetailed` returns the sequence of `ReachableByResult`s, which now include the table.
=> `reachableByDetailed` replaces `reachableByTable` (minus the race)

console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala
With all the work on language frontends, the overview provided by `importCode` had become outdated and misleading. This PR fixes that, cleans up naming and ensures that for source-based frontends, `.fromString` is available.
=> Cleanup `importCode`

joern-cli/src/main/scala/io/joern/DefaultOverlays.scala, joern-cli/src/main/scala/io/joern/JoernParse.scala, joern-cli/src/test/scala/io/shiftleft/joern/AbstractJoernCliTest.scala
Now that data flow analysis is sufficiently fast, let's always calculate DDGs instead of having users run into the situation where data flow analysis doesn't work because these edges have not been calculated. Also, let's get rid of the term "enhancing the graph" when we mean enhancing it in a very specific way, that is, by applying the default overlays. Finally, if a user just runs `./joern-parse`, show them how to use it.
=> joern-parse: cleanup and simplification

console/src/main/scala/io/joern/console/BridgeBase.scala
Previously, `--for-input-path` only worked for the interactive shell and `joern-scan` but not for `--script` runs. This PR fixes that. One thing I noticed here, which we may want to change is that if the joern workspace already contains a CPG for the given input path, then we do not reimport.
In short: `joern --script foo.sc --for-input-path /home/foo/code/project` now works.
=> Honor `--for-input-path` when running scripts

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreationPass.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/unpacking/JarUnpacking.scala
- Fixes bug in `astForDefinition` where LHS is only expected to be a local variable and fails for fields and arrays
- Fixes any bugs related to "whole program" analysis by loading all classes in and removing them together only after AST pass
- Safely adds superclass by checking if it exists
- If a method body cannot be extracted it will safely log the warning and create a "stub-style" method body instead of only catch issue on class-level
=> Jimple2Cpg Unhandled Field/ArrayRefs in Definition Fix

joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Decompiler.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Ghidra2Cpg.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/FunctionPass.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/arm/ArmFunctionPass.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/mips/MipsFunctionPass.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/x86/X86FunctionPass.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/utils/Nodes.scala
Isolated decompiler into a wrapper class that caches and returns options. We now also see clearly where we are still dereferencing potential null pointers - something to take care of in another PR.
This brings down CPG generation time from 1:25 to 0:48 on our current test binary.
=> ghidra2cpg: cache decompiler results

joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/FunctionPass.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/mips/MipsFunctionPass.scala
For arguments on MIPS, we started counting at 0 while for all other architectures, we begin counting at 1. Fixed that.
=> ghidra2cpg: fix order/argumentIndex for MIPS arguments

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/ResultTable.scala, dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/queryengine/ResultTableTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/EnumTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/InstanceOfTests.scala
When expanding into a sibling callee during backwards tracking, we were not keeping track of the callsite and therefore ended up returning to any caller of the sibling callee - the classical unrealisable path. Fixed that.
=> Fix invalid expansion in data flow engine

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala
This PR adds a default dispatch type of `DYNAMIC_DISPATCH` to unresolved calls. Without this, the `StaticCallLinker` logs an unknown dispatch type warning, which is quite noisy (and expected) for large codebases using external libraries. 
An alternative to using `DYNAMIC_DISPATCH` as a default would be to add a new `UNKNOWN` dispatch type, which would make this issue more explicit.
=> Add default dispatch type to javasrc2cpg

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/CDataFlowTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/NewCDataFlowTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/FunctionCallTests.scala
Previously, when we had expanded into a callee and then managed to traverse up towards one of its parameters, we would consider this is a partial path that we would need to continue exploring. From there on, we would expand back upwards into the parameter, leading to some very confusing results. Turned that off.
=> Do not consider callee to its parameter as partial path

console/src/main/scala/io/joern/console/ConsoleConfig.scala, console/src/main/scala/io/joern/console/cpgcreation/CCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CpgGeneratorFactory.scala, console/src/main/scala/io/joern/console/cpgcreation/FuzzyCCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala, console/src/main/scala/io/joern/console/cpgcreation/package.scala, console/src/test/scala/io/joern/console/ConsoleTests.scala, console/src/test/scala/io/joern/console/testing/ConsoleFixture.scala
* required for ocular, which ships a different frontend for C
* implement generator.isAvailable for fuzzyc2cpg and c2cpg frontends
* for language.C|NEWC: use the new default frontend if available, otherwise try the alternative one
* improve reporting of chosen frontend
* refactor code: make testable by not linking cpgGeneratorForLanguage statically
* Option.get is unsafe - change to filter, and improve error message
=> frontend heuristic: take frontend availability into account

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ConditionalTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LambdaTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/SpecialOperatorTests.scala
Fixes included:
* Handling of cast expressions
* The body of a lambda expression will now always be represented as a block (to fix an issue where an AST edge from an identifier in the body to the method return was not supported)
Also includes some tests and minor cleanup.
=> Add some javasrc2cpg fixes for issues parsing spring

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dotgenerator/DotAstGeneratorTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dotgenerator/DotCfgGeneratorTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dotgenerator/DotDdgGeneratorTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/TypeNodePassTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/ExtendedCfgNodeTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/CCodeToCpgSuite.scala
* used ScalaTest matcher where possible
* used ScalaTests inside matcher instead of manual pattern matching with fail() case
This improves consistency and readability of test failures a lot.
=> Refactored c2cpg tests

joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Ghidra2Cpg.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/x86/ReturnEdgesPass.scala
First approach to connect the return values of functions to actual register. 
Testing code: https://github.com/hac425xxx/sca-workshop/blob/master/ql-example/example.c#L222-L229 
Queries
```
run.ossdataflow
def src = cpg.call.name("get_user_input_str")
def sink = cpg.call.name("system").argument
sink.reachableByFlows(src).p
```
Flow:
```
"""____________________________________________________________________________________________
| tracked                         | lineNumber| method                   | file             |
|===========================================================================================|
| get_user_input_str              | 1054336   | call_system_safe_example | /tmp/joern/a.out |
| MOV qword ptr [RBP + -0x10],RAX | 1054341   | call_system_safe_example | …
```
=> Init x86 return edges

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/ResultTable.scala
Added `ResultTable::keys` in order to obtain the keys from the table to iterate the table using `ResultTable::get`
=> Added keyset accessor in ResultTable

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/DefaultDefines.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/ParserConfig.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/CallConventionsTests.scala
Without the default defines for stuff like __cdecl or __fastcall Eclipse CDT is unable to parse the methods.
See: https://stackoverflow.com/a/165529 and Joern Discord.
=> Added support for calling conventions

joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/mips/MipsFunctionPass.scala, joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/mips/CallArgumentsTest.scala
Resolving the arguments for MIPS calls (not instructions!) added test for it.
Given the source
```
/*
void test(char *input, int size) {
char arr[168];
char *chr = (char *)memcpy(arr,input + 5,size - 5);
}
int main() {
char *foo = "abcdefghij";
int size = strlen(foo);
printf("%s\n", foo);
test(foo,size);
}
*/
```
We now have the arguments `auStack180`, `param_1 + 0x5`, `param_2 - 0x5` for `memcpy`, the operators are calls too. 
The call to `test` has the arguments `abcdefghij` and `sVar1`, meaning we resolve the literal and the variable (instead of an address), Same goes for `strlen` (`"abcdefghij"`) and `puts` (one time `"abcdefghij"` and the other is `__s`) .
=> MIPS: Resolving arguments for calls  

console/build.sbt, console/src/main/scala/io/joern/console/cpgcreation/CCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CpgGeneratorFactory.scala, console/src/main/scala/io/joern/console/cpgcreation/FuzzyCCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala, console/src/main/scala/io/joern/console/cpgcreation/JavaCpgGenerator.scala, console/src/test/scala/io/joern/console/ConsoleTests.scala, console/src/test/scala/io/joern/console/testing/ConsoleFixture.scala
`fromString` now optionally takes arguments and passes them to the individual frontend.
`importCode` already had this. Added tests for that.
Fixes: https://github.com/joernio/joern/issues/762
=> Allow passing arguments to frontends

console/src/main/scala/io/joern/console/QueryDatabase.scala, joern-cli/src/main/scala/io/joern/JoernScan.scala, querydb/src/main/scala/io/joern/dumpq/Main.scala, querydb/src/test/scala/io/joern/suites/QDBArgumentProvider.scala
The refactoring is done to not required the deriving classes to import
scala.reflect. This is part of the preparation for the scala 3
migration.
=> Refactor DefaultArgumentProvider to reduce scala.reflect surface.

console/src/main/scala/io/joern/console/QueryDatabase.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefProblem.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/CDataFlowTests.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallGraphTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CfgTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/FunctionCallTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/ObjectTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/StaticMemberTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaDataflowFixture.scala
* NB!! In the ossdataflowengine, definitions of identifiers will now kill any field access calls accessing an object matching that identifier. For example, the statement `x = new Box()` will kill previous definitions of `x.value()`, `x.value.toString()` etc.
* Add explicit `this` to method `code` fields where required to match `java2cpg`.
* For an explicit method call like `obj.someMethod()` or `this.someMethod()`, represent the left-hand side as a field access operation instead of just an identifier (to match c2cpg).
* Fix some testcases that were broken by this change.
=> Make javasrc method call AST structure more consistent with c2cpg

console/src/main/scala/io/joern/console/BridgeBase.scala, joern-cli/src/main/scala/io/joern/JoernParse.scala, joern-cli/src/main/scala/io/joern/JoernScan.scala
This PR adds the ability to specify arguments for the front-end when running joern-scan (or any other plugin that fills the frontendArgs config field) from the command line. The syntax and behaviour match that of joern-parse.
Example use:
```
./joern-scan --language javascript js_project --frontend-args --no-babel --no-ts
```
=> Add --frontend-args option to joern-scan

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala
JavaParser expects the input to be a source code directory (as opposed to a single file). This is somewhat annoying for testing and tinkering with the front-end, so this PR solves the problem by copying the input file to a temporary directory if a single-file input is given. 
The `fileName` used for CPG nodes will still be the original input file.
=> Add single file input support for javasrc2cpg

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MethodReturnTests.scala
Return nodes were missing argument edges to the arguments (present in c2cpg), possibly causing some missing nodes in DF flows (still to be confirmed). 
While fixing this, I also noticed that some fields were missing, so added those.
=> Add missing args and fields to javasrc returns

updateDependencies.sh
the latter were only introduced recently...
=> use curl silent|show-error params instead of no-progress-meter

joern-cli/src/main/scala/io/joern/DefaultOverlays.scala, joern-cli/src/main/scala/io/joern/JoernParse.scala
The OSS data flow engine has a parameter: the maximum number of definitions a method may have to be considered for data flow analysis. We now let users pass this parameter to `joern-parse`.
```
./joern-parse --max-num-def 10000 <path/to/code>
```
=> Allow passing number of definitions to `joern-parse`

project/Versions.scala
After the recent release of 2.17.0 of log4j, there was [another CVE](https://nvd.nist.gov/vuln/detail/CVE-2021-44832) disclosed. The latest version, 2.17.1, has no disclosed vulnerabilities.
=> Update log4j to 2.17.1

joern-cli/src/main/scala/io/joern/JoernParse.scala
Most (all?) front-ends use the `-o` or `--output` options to specify an output file. It makes sense for `joern-parse` to use the same and this is what one would expect after running the front-ends directly.
This change would break any scripts that rely on the output option being `--out`, but given `joern-parse` was recently rewritten almost entirely, the impact of this seems limited.
=> Change joern-parse output option to -o or --output for consistency

joern-cli/frontends/kotlin2cpg/src/main/resources/log4j2.xml
Most probable cause for the currently failing release build:
```
[error] java.lang.AssertionError: assertion failed: git repository (/home/runner/work/joern/joern/./.git) isn't clean. Some indication of what it may be:
[error] changed: []
[error] changed: []
[error] conflicting: []
[error] added: []
[error] missing: []
[error] modified: []
[error] removed: []
[error] uncommitted: []
[error] untracked: [joern-cli/frontends/kotlin2cpg/sl-kt2cpg.log]
```
=> Remove local log file target for  Kotlin frontend

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/ExternalCommand.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IncludeAutoDiscovery.scala
This happens for C++ field accesses after macro expansion.
`org.eclipse.cdt.core.dom.ast.ASTSignatureUtil.getNodeSignature` will return an empty string for them.
We have to fall-back to `getRawSignature` instead.
Also in this PR: fixed gcc system include file discovery for Windows.
=> Fixed empty code fields

console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala, querydb/src/main/scala/io/joern/scanners/c/Metrics.scala
The fake global method needs line numbers to enable dumping its code.
Also: we should not immediately delete the temporary file generated from importCode / writeCodeInTmpFile to keep .dump / .dumpRaw functional after the CPG generation / import.
=> Fixed .dump / .dumpRaw for c2cpg

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeInfoProvider.scala
- introduce `WithDefaultType` trait allows pattern matching on a number of
descriptors
- improve log messages for failed type info fetching
=> Improve descriptor support in type info provider

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/NameGenerator.scala
Breaks runs on JDK8 (& are not needed)
=> Remove kotlin2cpg `java.lang.String.strip()` calls

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Main.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/NameGenerator.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/integration/IntegrationTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/AnonymousFunctionsTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ExtensionTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LambdaTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/ValidationTests.scala
- Context not being passed back up the chain led to IDENTIFIER nodes without AST parents
- parsing of inline named function leads to stray IDENTIFIERs, disabled for now
- more tests
- various small fixes
=> Fix various cases of Kotlin CPGs with stray IDENTIFIERs

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Main.scala
instead of absolute ones.
we want people to be able to scan a dir like:
```
/home/user/testprojects/kotlintest/src/*
```
with inputDir
```
/home/user/testprojects/kotlintest
```
=> Filter Kotlin source files on relative paths

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/ArrayTests.scala
- Fixed access path issue where array index accesses were reported to be invalid ASTs. This was just a change in AST children's `order` from `(0, 1)` to `(1, 2)`
- Updated frontend to leverage `Call(<operator>.arrayInitializer)` instead of `Unknown(new)` vertices
- Support for multi-array creation added
- Array tests derived from JavaSrc2Cpg included
- Fixed bug where if a single file was specified then all files in the directory were loaded
=> Jimple2Cpg: Array/Multi-array Support + Single File Load Bug Fix

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/TypeInfoProvider.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/EnumTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeDeclTests.scala
* Before we only parsed top-level classes. This PR adds recursive parsing for nested type declarations. Note: This still doesn't add support for classes defined in methods (as opposed to in other classes). Support for that will be added along with support for lambdas.
* Change nested class names to be consistent with java2cpg where class names are separated by a `$` instead of a `.`
* Fix some type name issues from a previous PR.
=> Handle nested type declarations in javasrc2cpg

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/EnumTests.scala
Calls for statically initialized variables/members (in enums) or static calls in general (in elaborated types) are now attached to a fake initialization method rather than their defining TypeDecl.
=> Fixed handling of static initializers and calls

console/build.sbt, console/src/main/scala/io/joern/console/cpgqlserver/CPGQLServer.scala
This is part of Scala 3 preparations. We need to get rid of the scala
meta dependency since it has transitive dependency conflicts.
=> Use ammonite parser instead of scala metas parser.

build.sbt, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dotgenerator/DotCfgGeneratorTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dotgenerator/DotDdgGeneratorTests.scala
Depends on: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1588
Fixes: https://github.com/joernio/joern/issues/969
=> Make use of deduplicated CFG edges for dot generation from codepropertygraph

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstNodeBuilder.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/HeaderContentPass.scala
`nodeSignature` sometimes gives wrong names in the context of macro expansion.
`ASTStringUtil.getSimpleName` is more reliable.
=> Fixed fullName calculation

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/TypeInfoProvider.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ArithmeticOperationsTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/FileTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LambdaTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/NamespaceBlockTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeDeclTests.scala
Notes:
* Add an empty default constructor for typeDecls with no constructors defined.
* If a variable was declared in scope, use the actual variable type for future references instead of the type `JavaParser` resolves to. For example, if we have `SomeInterface x = new SomeClass()`, then future identifier nodes for `x` in that scope will have the type `SomeClass` instead of `SomeInterface`
* The identifier changes broke some lambda-related tests. Since javasrc lambdas are effectively completely broken as is, I decided to ignore these for now. All of this will be fixed once I get back to the lambda implementation.
* Reduced `INFO` level logging noise somewhat.
=> Add default constructors and fix types

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/ParserConfig.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/HeaderContentPass.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IncludeAutoDiscovery.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/MacroHandlingTests.scala
Before this PR we always included all system header files when creating a CDT scanner.
Without checking whether it is a C or a CPP file.
This PR checks the file to parse beforehand.
=> Fixed c2cpg system header file discovery

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/ImplementsInterfaceTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/InterfaceTests.scala
- Interfaces are now recognized and treated as types with implementation represented by `INHERITS_FROM`.
=> Jimple2Cpg: Handles interfaces

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/util/ProgramHandlingUtil.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/CfgTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/StaticCallGraphTests.scala
- Plume prefix replaced with Joern when naming temporary extraction directory
- Generate `<operator>.assignment` call node's `code` property from child argument `code`
=> Jimple2Cpg: Accurate Definition .code Property

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefPass.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefProblem.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/DataFlowTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/DataFlowCodeToCpgSuite.scala
Previously, kill sets did not contain method parameter declarations, meaning that data flows in functions where the parameter was redefined were incorrect.
=> Do not forget to include method parameter declarations in kill sets

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/ParseProblemsLogger.scala
The exception message might be null for parse failures due to ambiguous nodes that can't be resolved successfully.
We now extract better log messages for this case.
=> Improved parse failure logging

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/MethodParameterTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/MethodTests.scala
- Method parameters now have correct evaluation strategies
- Fixed instance in methods where `this` parameter was not generated for dynamic calls.
=> Jimple2Cpg: Parameters Eval Strategies and this Parameters

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala
Fixed instances where `.fieldRef.getField` would return a null and crash method body parsing. This appears to happen when `.getField` is an external class/type but that's my guess. Have now reverted to `.fieldRef.getFieldRef` which works since it refers to the immediate reference instead of the concrete location of the field.
Resolves #1036
=> Jimple2Cpg: Use .fieldRef instead of nullable .field

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallsToConstructorTests.scala
not having it set leads to crashes in backend
=> Set TYPE_FULL_NAME prop for Kotlin ctor calls

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/ConstructorInvocationTests.scala
- Methods now have modifier nodes.
- Made constructors a bit friendlier to work with and they now have `this` parameters.
=> Jimple2Cpg: Constructor Tests and Method Modifiers

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala
- Instances where dynamic calls were failing because of `soot.dummy.InvokeDynamic` not being loaded at `SIGNATURES`
level. This used to occasionally crash on loading certain methods.
=> Jimple2Cpg: Fixed instances where InvokeDynamic Methods would Crash

joern-cli/frontends/py2cpg/src/main/resources/log4j2.xml
The release process does not like any additional files to be lingering
around after a test/build cycle.
=> Do not always log test runs into log file.

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/MethodParameterTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/MethodTests.scala
Often during a dynamic invoke, obtaining the method called will fail. I have now replaced the direct method resolution with the method reference since this is enough to generate the `Call` node.
=> Jimple2Cpg: Handling Method Resolve Failure on InvokeExpr

console/src/main/scala/io/joern/console/scan/ScanPass.scala, joern-cli/frontends/fuzzyc2cpg/src/main/scala/io/joern/fuzzyc2cpg/passes/StubRemovalPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kt2Cpg.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreationPass.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/ConfigPass.scala
`ParallelCpgPass` is now deprecated and so I have replaced it with `ConcurrentWriterCpgPass` in all frontends except for ghidra2cpg, jimple2cpg, and pysrc2cpg.
- For ghidra2cpg, @itsacoderepo needs to take a look. The `FunctionPass` seems like it doesn't work as intended. While it extends from `ParallelCpgPass`, the list of parts is `List("")`.
- For jimple2cpg, I did not make changes to not mess with the keypools @DavidBakerEffendi requires for his experiments
- For py2cpg, `DiffGraph.Applier` is used and it is supposed to be replaced with `DiffGraphApplier`, however, that class is private.
=> Use `ConcurrentWriterCpgPass` in most frontends

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kt2Cpg.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreationPass.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/ConfigPass.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/CodeToCpg.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/EdgeBuilder.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2Cpg.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala
Turns out that only the deprecation warning was wrong for `DiffGraph.Applier`: one can use the public method `applyDiff` as a replacement. Now the only frontends that still use `ParallelCpgPass` are ghidra2cpg and jimple2cpg.
=> Use `ConcurrentWriterCpgPass` in pysrc2cpg + cleanup

joern-cli/frontends/kotlin2cpg/build.sbt, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kt2Cpg.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Main.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreationPass.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/CallKinds.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/Constants.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/NameReferenceKinds.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeInfoProvider.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/Kt2CpgTestContext.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/integration/IntegrationTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/plugins/KotlinCompilerPluginTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallsToFieldAccessTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/FieldAccessTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeInferenceForAndroidSDKTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/types/CompilerAPIStabilityTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/types/KotlinScriptFilteringTests.scala
- rename `NameGenerator` -> `TypeInfoProvider`
- move multiple objects from the `*kotlin2cpg.types*` namespace into their own files (IntelliJ sometimes fails to recognize imports otherwise which is really annoying)
=> Move various classes into their own files

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/C2Cpg.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/HeaderContentPass.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CompleteCpgFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CpgAstOnlyFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CpgCfgFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CpgTypeNodeFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/TestAstOnlyFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/TestProjectFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala, joern-cli/frontends/fuzzyc2cpg/src/main/scala/io/joern/fuzzyc2cpg/FuzzyC2Cpg.scala, joern-cli/frontends/fuzzyc2cpg/src/main/scala/io/joern/fuzzyc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/CpgTestFixture.scala, joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/passes/AstCreationPassTests.scala, joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/passes/CfgCreationPassTests.scala, joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/passes/StubRemovalPassTests.scala, joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/passes/TypeNodePassTests.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Ghidra2Cpg.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/MetaDataPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
As both frontends no longer use `ParallelCpgPass`, they no longer require us to specify keypools manually. Also removing keypools from the `MetaDataPass` in ghidra2cpg, but since the `FunctionPass` still needs to be rewritten, we can't remove keypools from the entire frontend yet.
=> Remove keypools from c2cpg and fuzzyc2cpg

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/CfgTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/ConstructorInvocationTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/StaticCallGraphTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/ObjectTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/OperatorTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/testfixtures/JimpleDataflowFixture.scala
- Object data flow tests that explores fields and inter-procedural calls (both static + virtual)
- Removed parsing Jimple `IdentityStmt` since they end up duplicating parameters as locals
- Virtual calls now get passed the correct `this` object as the object the method is actually invoked with
- Virtual call `code` properties now include the object invoking the method
=> Jimple2Cpg: Object Data-Flow Tests + Bug Fixes

console/src/test/scala/io/joern/console/testing/ConsoleFixture.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/C2Cpg.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/Main.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/CCodeToCpgSuite.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/JavaSrc2CpgTestContext.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala, joern-cli/src/test/scala/io/joern/joerncli/AbstractJoernCliTest.scala
The APIs that frontends currently offer to the user are specific for each frontend, leading to code duplication, missing error handling in some of the frontends, and the necessity to learn per frontend how it is used. In an effort to create a single frontend API that works well across frontends, I have extracted the trait `X2CpgFrontend` from `Javasrc2Cpg`. This trait defines the frontend API.
For frontend authors, with this new API, one only has to implement `createCpg(config : Config)` and `createCpg` methods that accept a single input path and multiple input paths are automatically available.
In follow-up PRs, I will port over other frontends to this API.
=> Extracted and `X2CpgFrontend` utility trait from `Javasrc2Cpg`

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/datastructures/Global.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/datastructures/Scope.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/datastructures/ScopeElement.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/datastructures/Stack.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ExternalCommand.scala
Following off of @max-leuthaeuser's structure on `js2cpg` where these are separated into a package, I'm pulling some of these commonly used data structures into `x2cpg` to avoid duplication on this end.
Note `ExternalCommand` is added since `solidity2cpg` will be calling an `npm` package too.
Should this PR also reformat other frontends to adopt these or shall each frontend's maintainer do it in their own?
=> Added commonly used data structures to x2cpg

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/TypeInfoProvider.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeTests.scala
Using a default `<empty>` type instead of `ANY` if a type could not be resolved resulted in missing `TYPE_EVAL` edges causing cpg2sp crashes (specifically tested with HelloShiftLeft). Defaulting to the `ANY` type instead fixes this issue, while also being a better representation for the missing types in question.
=> Default to type ANY instead of <empty> if javasrc type info is missing

joern-cli/frontends/jimple2cpg/build.sbt, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreationPass.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala
- Upgraded Soot to 4.3.0.
- Now using `x2cpg` shared `Global` type.
- Disabled Soot whole program/application mode since we only use AST's / Unit types. This will improve Soot performance.
=> Jimple2Cpg: Upgrade to Soot 4.3.0

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/TypeInfoProvider.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CfgTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ConstructorInvocationTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeTests.scala
This PR fixes some inconsistencies between static/dynamic dispatch logic and when `this` nodes are created for implicit `this` arguments. It also fixes the type of the `this` node for the `<init>` call used to represent `super`.
=> Fix javasrc super types

.github/workflows/pr.yml, build.sbt, joern-cli/build.sbt, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/Main.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Ghidra2Cpg.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Main.scala, joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/fixtures/GhidraBinToCpgSuite.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Main.scala, joern-cli/frontends/php2cpg/README.md, joern-cli/frontends/php2cpg/build.sbt, joern-cli/frontends/php2cpg/installdeps.sh, joern-cli/frontends/php2cpg/php-parse, joern-cli/frontends/php2cpg/php2cpg, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Main.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala, project/Projects.scala
This PR brings in a new class called `X2CpgMain` which can be used to implement Main classes for CPG frontends. The class is then used in `javasrc2cpg`, `c2cpg`, `jimple2cpg` and `ghidra2cpg`. Moreover, this PR brings in boilerplate for a new `phpsrc2cpg` frontend.
=> Introduce `X2CpgMain` class

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala
`astForInvokeExpr` still had two more instances where the direct method instance was being retrieved. This gives NPE on a methods whose bodies cannot be retrieved for some reason or another.
=> Jimple2Cpg: NPE on Checking Phantom Method for Being a Constructor

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefProblem.scala
We were using `.name` which performs lookup by regular expression. Some identifiers passed in from `javasrc2cpg` contained non-alphanumeric characters, triggering a crash. Using `.nameExact` now.
=> data flow engine: fix for detection of same variable

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallsToFieldAccessTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/MemberTests.scala
- makes them easier to spot in dataflow results
- also make CODE prop of ctor-defined members consistent with
non-ctor-defined ones
=> Tweak props around kt fieldAccess calls

joern-cli/frontends/pysrc2cpg/pythonGrammar.jj, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pythonparser/ParserTests.scala
Format strings with triple quotes could cause exceptions. This is now
fixed.
=> Fix python parser bug.

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/OperatorTests.scala
Added a statistic tracker to the data flow query engine. This is essentially a wrapper around a enum-driven concurrent map.
Example output at the end of Jimple's `OperatorTests`:
```scala
Map(PATH_CACHE_HITS -> 5, PATH_CACHE_MISSES -> 83)
```
=> Added a Query Engine Statistics Tracker

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/MethodTests.scala
- `java.lang.Object` only added if supers list is empty
- Added `lineNumberEnd` to `Method` nodes
Resolves #1149
=> jimple2cpg: Line Number End for Methods

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/util/ProgramHandlingUtil.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/ImplementsInterfaceTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/unpacking/JarUnpacking.scala
- JARs are now unpacked then repacked according to the package in the class file assembly.
- Fixed issue where if there was an interface for a type, `java.lang.Object` would still be added additionally as an inherited type.
=> jimple2cpg: Fix JAR File Package Resolution

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/SourceRootFinder.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoProvider.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/InferenceJarTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/util/SourceRootFinderTests.scala
Copied from `SourceRootFinder` comment:
>Given a `codeDirectory`, the SourceRootFinder attempts to find all the source roots (so that the subdirectories
>match the package structure of the source files). The JavaParserTypeSolver is path-dependent, so without this the
>user would need to ensure that they specify the correct source directory when running javasrc2cpg.
>
>This works by checking if any subdirectories of the given directory match common java directory structures. In order
>of preference: * Maven's default structure, e.g. src/main/java/io/... and src/test/java/io/... * Top-level src and
>test directories, e.g. src/io/... and test/io/... If neither of these match, then it defaults to using the given
>user input as the source root.
This also moves the `TypeInfoProvider` and …
=> Javasrc: Attempt to find true source roots from given dir.

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallsToFieldAccessTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/ValidationTests.scala
i incorrectly assumed a _this_ receiver will always need dynamic dispatch
=> Fix DISPATCH_TYPE for certain kt fieldAccess calls

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/datastructures/Global.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IOUtils.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/MethodHeaderTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/MacroHandlingTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/standard/CMethodTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/standard/CallTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/standard/MethodParameterTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/standard/MethodReturnTests.scala
- Moved ast creation out of global lock in order to avoid threads waiting for the
lock the majority of the time.
- Improve column calculation algorithm.
The old version managed to be slow enough to be the number one hot spot
during profiling of c2cpg. The new version makes this fast so that it does
not show up during performance measuring anymore.
Column number now start at one instead of zero like the line numbers and
the new implemention obsoleted a bug in the old column end calculation
which led to complete bogus numbers.
=> Improve c2cpg performance.

joern-cli/frontends/pysrc2cpg/pythonGrammar.jj, joern-cli/frontends/pysrc2cpg/src/main/java/io/joern/pythonparser/PositionToken.java, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/CodeToCpg.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeToCode.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitorHelpers.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pythonparser/ast/Ast.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pythonparser/ast/AttributeProvider.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/ReturnCpgTests.scala
Most of this PR is the infrastructure needed to obtain the original code
belonging to an AST node which is for now only used to set the code
propertu of RETURN nodes.
As requested by: https://github.com/joernio/joern/issues/1145
=> Put original code into RETURN node code property.

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/util/ProgramHandlingUtil.scala
- Jimple2Cpg uses ASM's `ClassReader` to determine how to extract the file from the class's package. This change allows us to read JDK16+ class files.
=> jimple2cpg: Read Classes with ASM9 for Java 16+ compatibility

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala
For now we treat the base expressions as proper full names which is
obviously not correct but at least allows a preliminary access.
=> Set inheritsFromFullNames for TYPE_DECL nodes.

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoProvider.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/InferenceJarTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeInferenceTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/ObjectTests.scala
With these changes, javasrc2cpg will use more available information improve type information where JavaParser's type solver has failed.
Notably: 
* If a vardecl/param type could not be resolved, check the imports for a matching type (based on name) and use that if one was found. If no matching import was found, but there's only a single wildcard import, use that instead. If there are 2 or more wildcard imports, then we don't know which it could've come from, so give up at this point.
* If a call could not be resolved, try to infer the methodFullName from type information we have in scope about the target, an expected return type (defaulting to void if the return value isn't used), and type info from arguments if those can be resolved/retrieved otherwise.
=> javasrc: Make use of more available type info to infer types where javaparser resolution fails.

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Ast.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/AstTests.scala
Measured this with a c2cpg run on ffmpeg on my laptop and got roughly
15% shorter runtime with Vector. I also tried mutable.ArrayBuffer which
lead to approximately the same performance as for Vector.
=> Switch from List to Vector for increased performance.

joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/Decompiler.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/FunctionPass.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/arm/ArmFunctionPass.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/mips/MipsFunctionPass.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/x86/X86FunctionPass.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/processors/ArmProcessor.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/processors/MipsProcessor.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/processors/PCodeProcessor.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/processors/Processor.scala, joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/processors/X86Processor.scala
@itsacoderepo Since this came up today in the meeting, I took a quick look at the FunctionPass and addressed some nits.
1. The cache of Decompiler had a race condition. Now fixed.
2. We used to search `functions: List[Function]` quite often for matching names. Let's put it into a hashtable instead of a singly linked list. I took the liberty of adding a warning if two functions name-clash -- is this correct? Or was the old behavior better (take first matching name, silently ignore the other ones)?
3. The various `Processor` subclasses instantiated a brand-new HashMap for every lookup. That is silly, we only need one.
4. The `Processor` interface used `scala.collection.immutable.HashMap`. It is a common misconception that `scala.collection.immutable` is meant for immutable data -- it is …
=> Ghidra2cpg FunctionPass nits

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/GradleDependencies.scala
Intended to help debugging issues around runs inside Docker containers
or other unusual situations.
=> Add `try-catch` around Gradle deps fetching logic

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoProvider.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ControlStructureTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/GenericsTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LiteralTests.scala
With this PR, javasrc basically ignores generic type information for consistency with bytecode. The unit tests give a fairly good overview of what's expected now, so I won't repeat that here.
This also fixes some areas that I missed with https://github.com/joernio/joern/pull/1193 and just fixes some type logic in general. There's more to do here, but I'll follow up with a separate PR after checking new results with HelloShiftLeft
=> javasrc: make generics more consistent with bytecode and fix some "inference" bugs

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/ArrayTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/IfGotoTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/ArrayTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/StaticMemberTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/SwitchTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/TryTests.scala
- Added the rest of the tests from `javasrc2cpg`
- Improved `code` for `new array`, `throw`, `goto` statements
- Fixed `javasrc2cpg` typo on `operator.<throw>` -> `<operator>.throw`
=> jimple2cpg: Data Flow Tests for Arrays, Static Members, Try/Catch, and Switch

dataflowengineoss/README.md, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala
- For experimental purposes to evaluate the effectiveness of the cache, an option to disable re-use of already calculated results. Right now we see the overhead of collecting results to give back to the engine context being quite slow despite the improve cache hit ratio. By measuring the speed of a fully disabled cache we can approximate how useful the current caching strategy is.
- Added some basic documentation to make the engine friendlier
PS: Running experiments locally show that disabling the cache basically doubles memory consumption and increases analysis time by loads!
Example of results from giving `initialTable` to `EngineContext` to re-use results on an m5d.large EC2 instance:
=> dataflowengineoss: Option to Disable Cache Use + Some Simple Documentation

joern-cli/frontends/kotlin2cpg/build.sbt, joern-cli/frontends/x2cpg/build.sbt, project/Versions.scala
optional dependencies are non-transitive when it comes to staged
binaries, so we need to explicitly list this dependency here as
well...
turns out we can't have the cake and eat it...
=> add gradle-tooling to kotlin frontend

build.sbt, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/IfExpressionsTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TryExpressionsTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/WhenExpressionTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/ArgumentIndexTests.scala
A CONTROL_STRUCTURE is appropriate for `try`-statements, but not
`try`-expressions.
=> Lower Kotlin `try`-expressions correctly

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/MethodReturnTests.scala
Added code for `Return` nodes, fixed lack of argument edges and issue with orders
=> jimple2cpg: Return Arg + Order Fix and Defined Code Property

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/GradleDependencies.scala
before:
```
2022-04-04 17:51:23.657 WARN Caught exception while trying to establish a Gradle connection: 'java.lang.NoClassDefFoundError: org/gradle/tooling/GradleConnector'.
```
after:
```
2022-04-04 17:51:23.657 WARN Caught exception while trying to establish a Gradle connection: 'org/gradle/tooling/GradleConnector'.
```
=> Print full exception msgs in GradleDependencies

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/FieldAccessTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/ObjectTests.scala
- Added field access tests
- Corrected `canonicalName` property
- Corrected LHS of the `code` property
=> jimple2cpg: Fixed fields by using correct canonical name and code property

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/MethodParameterOutMethods.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/MethodParameterOutTraversal.scala
Due to reasons, adding the `index` method to the method parameter out node doesn't work. It seems to be shadowed by the methods in the corresponding traversal class. Adding those methods there instead.
=> Utility functions for method parameter out traversal

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/generalizations/AstNodeTraversal.scala, semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/StepsTest.scala
- Allowing the ability to retrieve the first block on an AST node
- Returns an empty traversal if no AST node is found
This is useful for comparing the scope of identifiers who shadow one another for example.
=> `parentBlock` step to `AstNode`

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LambdaTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LocalTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/IdentifierReferencesTests.scala
To be consistent with the rest of the frontends
e.g. for:
```
fun main() {
val x: Int = 1
}
```
before:
```
LOCAL
\-> NAME: x
\-> CODE: val x: Int = 1
```
after:
```
LOCAL
\-> NAME: x
\-> CODE: x
```
=> Remove cruft from CODE field of Kotlin LOCALs

build.sbt, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/ArrayTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/ConstructorInvocationTests.scala
- Upgraded CPG
- Memory allocation calls for arrays and objects now use `Operators.alloc`
=> [jimple|javasrc]2cpg: Arrays and objects use `Operators.alloc`

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/JP2JavaSrcTypeAdapter.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Scope.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoProvider.scala
This moves a lot of the ugly JavaParser type resolution logic into a separate class and merges some type methods where possible. Some of the scope type logic has also been moved into the `TypeInfoProvider` in an attempt to contain that as much as possible.
There's still work to do for separating everything cleanly, but this should give a decent indication of the general idea.
This is PR  1269 so, for no reason in particular, I  checked to see if anything interesting happened in the year 1269. From Wikipedia, there were a few mildly interesting candidates, but one stood out in particular:
* [Pélerin de Maricourt](https://en.wikipedia.org/wiki/Peter_of_Maricourt) first describes [magnetic poles](https://en.wikipedia.org/wiki/Magnet), and remarks on the nonexistence of [isolated magnetic …
=> javasrc: Clean up typeInfoProvider a bit

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/AnnotationTests.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotSerializer.scala
Borrowed `javasrc2cpg` tests for annotations and have implemented these in `jimple` with subtle differences:
- Included missing string implementation for annotation nodes in `DotSerializer`
- All `code` properties for annotations include call parenthesis e.g. `@NormalAnnotation()`
- `code` properties for string literals are surrounded by double quotations (`"`)
=> jimple2cpg: Annotation Support

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/ReflectionTests.scala
- Created a test suite for reflection-related operations
- Implemented the `Literal` for class constants and nulls
- Brought in `parseAsmType` from the annotations branch for jimple2cpg
=> jimple2cpg: Correctly Handling Class Constants

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/JP2JavaSrcTypeAdapter.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoProvider.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MethodReturnTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MethodTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ScopeTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/ObjectTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/MavenDependencies.scala
Improvements:
- Fetch compile class path from maven.
- Use upper bound of type variables in type full names.
- Add VIRTUAL modifier to non static methods.
- Fix method full name for static calls with no scope.
- Add REF edges between identifiers and parameter/local nodes.
- Implement void return handling.
- Correct type full name of `this` identifier in field access.
- Make method calls via `super` keyword always STATIC_DISPATCH.
- Implment `super` keyword handling.
=> Bring in javasrc2cpg frontend improvement branch.

joern-cli/frontends/c2cpg/build.sbt, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/VarDeclTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/Code2CpgFixture.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/CodeToCpgFixture.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/TestCpg.scala
This fixture allows to specify multiple input files while not placing
additional burden on the user.
As example i migrated one java src test.
But it is also possible to use the same cpg for multiple different
tests like:
```
class SomeTests extends JavaSrcCode2CpgFixture {
"foo" should {
val cpg = code("<someCode>")
"test1" in {
}
"test2" in {
}
}
}
```
as reference the initial proposal PR: 
https://github.com/joernio/joern/pull/1230
=> New test fixture.

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/dotgenerator/DotCpg14Generator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/dotgenerator/DotDdgGenerator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/dotgenerator/DotPdgGenerator.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/CallGraphGenerator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotAstGenerator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotCallGraphGenerator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotCdgGenerator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotCfgGenerator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotSerializer.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/dotextension/InterproceduralNodeDot.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/package.scala
- jimple2cpg method nodes now use `astParent` properties
- Extended dot serialised `Graph` case classes to include subgraph clusters
- Added entry point for dot serialisers to now be called from the `cpg` itself
- Type clusters are obtained via `TypeDecl` via AST in info but defaults to `astParentFullName` otherwise
Example call graph on Java
```java
package test;
class Foo {
int add(int x, int y) {
return x + y;
}
int main(int argc, char argv) {
return add(argc, 3);
}
int bar(int argc) {
foo(argc);
}
}
class MyObject {
public static String staticCall(String s) {
return s;
}
public String myMethod(String s) {
return s;
}
}
public class Bar {
MyObject obj = new MyObject();
public static void staticMethod() {}
public String foo(MyObject myObj) {
return myObj.myMethod("Hello, world!");
} …
```
=> Interprocedural Dot File Generator: Call Graphs

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotSerializer.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotTypeHierarchyGenerator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/TypeHierarchyGenerator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/dotextension/InterproceduralNodeDot.scala
- Added a means to visualise the type hierarchy of the CPG in a traditional type hierarchy sense
- Clusters types by their namespace full names
- This namespace information is simply extracted from type full names as I've found in JavaSrc2Cpg that nested types don't have an associated namespace block
Example Java code:
```java
package a.b.c.d;
class Bar extends Woo {
int x;
int method () { return 1; }
};
class Woo {}
public class OuterClass {
interface InnerInterface {
int id(int x);
}
class InnerClass implements InnerInterface {
@Override
public int id(int x) {
return x;
}
class InnerClass2 {}
}
public int method(int bbb) {
InnerInterface innerInterface = new InnerClass();
return innerInterface.id(bbb);
}
public static void main(String[] args) { }
}
enum TestEnum {
A, B, C;
public void …
```
=> Dot Generator: Type Hierarchy

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/ValidationTests.scala
following a complaint of the `TypeHierarchyPass`
```
2022-05-02 16:56:19.289 INFO Start of pass: io.joern.x2cpg.passes.typerelations.TypeHierarchyPass
2022-05-02 16:56:19.291 INFO Could not create edge. Destination lookup failed. edgeType=INHERITS_FROM, srcNodeType=TYPE_DECL, srcNodeId=81, dstNodeType=TYPE, dstFullName=kotlin.Function0
2022-05-02 16:56:19.291 INFO Could not create edge. Destination lookup failed. edgeType=INHERITS_FROM, srcNodeType=TYPE_DECL, srcNodeId=82, dstNodeType=TYPE, dstFullName=kotlin.Function1
2022-05-02 16:56:19.291 INFO Could not create edge. Destination lookup failed. edgeType=INHERITS_FROM, srcNodeType=TYPE_DECL, srcNodeId=83, dstNodeType=TYPE, dstFullName=kotlin.Function0
```
=> Register types for certain Kotlin lambda calls

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/ValidationTests.scala
Following complaints of the `TypeUsagePass`
```
2022-05-03 10:19:42.933 INFO Start of pass: io.joern.x2cpg.passes.base.TypeUsagePass
2022-05-03 10:19:42.936 INFO Could not create edge. Destination lookup failed. edgeType=EVAL_TYPE, srcNodeType=CALL, srcNodeId=25, dstNodeType=TYPE, dstFullName=kotlin.Pair
2022-05-03 10:19:42.936 INFO Could not create edge. Destination lookup failed. edgeType=EVAL_TYPE, srcNodeType=CALL, srcNodeId=28, dstNodeType=TYPE, dstFullName=kotlin.Pair
2022-05-03 10:19:42.937 INFO Could not create edge. Destination lookup failed. edgeType=EVAL_TYPE, srcNodeType=BLOCK, srcNodeId=8, dstNodeType=TYPE, dstFullName=java.lang.Void
```
=> Register types of Kotlin binary expressions

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CompleteCpgFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CpgAstOnlyFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CpgCfgFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/CpgTypeNodeFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/TestAstOnlyFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/fixtures/TestProjectFixture.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/PreprocessorPassTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/DumpDdgTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/CCodeToCpgSuite.scala
Fixes: https://github.com/joernio/joern/issues/1326
Also: we do not need to run system header file auto discovery during tests. Just wasting time there.
=> Fix for wrong identifier names

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dotgenerator/DotAstGeneratorTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dotgenerator/DotCdgGeneratorTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dotgenerator/DotCfgGeneratorTests.scala, joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/dotgenerator/DotAstGeneratorTests.scala, joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/dotgenerator/DotCfgGeneratorTests.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotSerializer.scala
- Switching from quoted labels to HTML labels on nodes
- Added line number info as subscript if present
Resolves #381 
Example:
```java
class Foo {
int foo(int x, int y) {
if (y < 10)
return -1;
if (x < 10) {
sink(x);
}
System.out.println("foo");
return 0;
}
}
```
=> Dot Graph Serializer: Rich HTML Formatting + Line Numbers

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/JP2JavaSrcTypeAdapter.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/BindingTests.scala
For methods which override a method from a super class or interface, we
also need to add bindings with the erased signature of the overriden
methods.
=> Implement overriden binding signatures.

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoCalculator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MethodParameterTests.scala
This avoids running into a bug where successful resolves were rendered
invalid due to overzealous casting. See code comment for more details.
Also extended parameter test suite to be able to test this.
=> Use symbolResolver directly instead of .resolve().

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/DataFlowCodeToCpgSuite.scala, joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/testfixtures/DataFlowCodeToCpgSuite.scala, joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/fixtures/DataFlowBinToCpgSuite.scala, joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/mips/DataFlowTests.scala, joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/x86/DataFlowTests.scala
`relativise` and `Semantics.fromList(new Parser().parseFile(semanticsFilename))` can't handle symlinks (Windows only).
We ended up with empty semantics there.
=> Fixed DF semantics file location

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/GradleDependencies.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/dependency/DependencyResolverTests.scala
i'd like to get this merged in the interest of time, it's good enough for the demo app and a few other projects it's been tested on
the bulk of the work is in the gradle init script, open todos:
- add good test cases for various Android app Gradle setups
- place init script in temp directory and pass `--init-script` arguments to the task invocation
- add CLI flags for specifying `gradleProjectName` and `gradleConfigurationName` 
- other similar cleanups
=> Add initial support for Android Gradle dependency downloading

joern-cli/frontends/c2cpg/src/test/resources/log4j2-test.xml, joern-cli/frontends/fuzzyc2cpg/src/test/resources/log4j2-test.xml, joern-cli/frontends/ghidra2cpg/src/test/resources/log4j2-test.xml, joern-cli/frontends/jimple2cpg/src/test/resources/log4j2-test.xml, joern-cli/frontends/kotlin2cpg/src/test/resources/log4j2-test.xml, joern-cli/frontends/pysrc2cpg/src/test/resources/log4j2-test.xml, joern-cli/frontends/x2cpg/src/test/resources/log4j2-test.xml
As a follow-up to https://github.com/joernio/joern/pull/1373, this adds log4j config for all frontend tests to limit logging to WARN and above. This reduces visual noise when looking at tests results and makes identifying warnings/errors much easier.
This doesn't hide Ghidra/Joern console output, but results in much cleaner output regardless.
It's probably possible to do this with a single configuration file in the project root. This is a quick 'n dirty fix though.
=> Add log4j test config to filter out INFO logging

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala
In case the call was to a generic method, the type parameter was not
correctly replaced by the substitute type of the context.
=> Fix call expression type.

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala
Let REF edges from BINDING nodes be created by backend and only store
necessary information in BindingInfo.
=> Simplify BINDING node creation.

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
empty expressions are passed to that fn in lots of different valid cases and just makes log-debugging harder for DEBUG log level
=> Reduce log noise in `kotlin2cpg`

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/GradleDependencies.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/dependency/DependencyResolverTests.scala, joern-cli/src/test/resources/testcode/SlimAndroid/app/build.gradle, joern-cli/src/test/resources/testcode/SlimAndroid/app/src/main/java/com/example/slimandroid/MainActivity.kt, joern-cli/src/test/resources/testcode/SlimAndroid/app/src/main/res/layout/activity_main.xml, joern-cli/src/test/resources/testcode/SlimAndroid/gradle.properties
A large number of Android dependencies are distributed as `aar`
files which are just a specially laid-out zip file:
https://developer.android.com/studio/projects/android-library
The embedded Kotlin compiler does not accept `aar` files directly, so 
their `classes.jar` need to be extracted first, which is what this 
PR accomplishes.
=> Extract `classes.jar` from aar dependency files

joern-cli/src/main/scala/io/joern/joerncli/JoernExport.scala
`neo4jcsv` really isn't a repr(esentation), but rather a format. This PR cleans up after #1402
Example for valid arguments:
```
--repr=ast
--repr=cfg
--repr=all --format=neo4jcsv
```
=> joern-export arguments grouped differently

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/BindingTable.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/BindingTests.scala
While not being completely correct in terms default method precedence,
this binding table implementation fullfils the basic requirements
to achieve proper data flow tracking results.
We will need to revise its interface at some point in order to allow
it to be reused for lambda method type binding tables.
=> Implement proper binding table calculation.

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala
In case of a type variable bound by a type varible we did correctly
calculate the signature.
=> Fix method signature.

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoCalculator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala
Doing possible type variable substitutions in TypeInfoCalculator avoid
having dublicate code in substituteTypeVariable().
This also fixes the bug of not properly substituted type variables in
array types.
=> Allow for type variable substitution in TypeInfoCalculator.

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala
This `f` already returns a Try, wrapping it into another `Try` led to
always triggering the `Success` match case, rendering the logging
functionallity of this method to be dead code.
=> Fix withErrorsToConsole.

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/BindingTable.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoCalculator.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/MavenDependencies.scala
-  Also take into account partial mvn dependency results.
-  Used maven in batch mode.
-  Handled union type ( can occour in exception handling).
-  Catch exception if parameter cannot be retrieved.
-  Fix crashed in javasrc found on WebGoat input.
=> Various javasrc improvements.

joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/querying/CfgTests.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/CfgNodeMethods.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/generalizations/CfgNodeTraversal.scala
- While we have `reachableBy`, as it stands there is no way to kill paths that flow through sanitisers
- Here is a prototype `passes` and `passesNot` that probably needs fine tuning but gets the job done with `postDominatedBy`
=> CfgNode extension "passesNot" to filter out flows through sanitisers

.github/workflows/upgrade-deps.yml
This essentially runs `./updateDependencies.sh --non-interactive` and
runs the regular tests, to notify us if some upstream dependency
introduced breaking changes. If it's red, that's not the end of the
world, but we should get it back on track to unblock others.
=> add nightly job that verifies that we can upgrade all internal dependencies

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala
- `Operator.notEquals` was a missing binary operation not being handled. It is now fixed.
- Added logging and a better placeholder (`<operator.unknown`) incase an unexpected binary operation is encountered in the future.
=> jimple2cpg: Added missing binop "Operator.notEquals"

build.sbt, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/NodeTypeStartersTests.scala, joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/querying/NodeTypeStartersTests.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NodeTypeStarters.scala, semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/StepsTest.scala
`.outV` is only valid on `Traversal[Edge]`, trying this now results in
a compiler error.
Depends on https://github.com/ShiftLeftSecurity/overflowdb/pull/307
Re https://github.com/joernio/joern/issues/1367
=> ensure `cpg.id.outV` doesn't compile

build.sbt, joern-cli/src/universal/js2cpg.sh
`js2cpg` recently introduced the `--optimize-dependencies` flag. When used, `js2cpg` will be more selective about downloading dependencies, which significantly reduces CPG construction time. While the flag is not enabled by default for `js2cpg` runs, I am making it the default for `joern`. It is expected that it will be the default in a few months, at which point we do not need to specify the flag manually anymore.
=> Make `--optimize-dependencies` the default for `js2cpg`

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/ImplementsInterfaceTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/InterfaceTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/TypeDeclTests.scala
- Improved the `code` property of `TypeDecl` nodes to include modifiers and superclasses/interfaces
- Added `Modifier` nodes to `TypeDecl`
Note: I have added an unofficial `INTERFACE` modifier type accompanied by `ABSTRACT` (since interfaces are implicitly abstract). Let me know if this is okay or not.
=> jimple2cpg: Descriptive TypeDecl Modifiers

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/CompilerAPI.scala
Previously we'd allocate a new `LazyList:Cons` for each byte that we
read from the resource, which ended up being the biggest memory consumer
on the heap (only on a 1g heap, but still)...
This was uncovered by a OutOfMemory issues during `kotlin2cpg/test` as part of https://github.com/joernio/joern/pull/1451, but it's semantically different enough that it deserves a separate PR.
It doesn't entirely fix the OOM issues in the linked PR though.
=> write resourcefile efficiently

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/JavaSrc2CpgTestContext.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala
Having the option to disable dependency downloading is nice in general, but in particular dependency downloads failing created a lot of warnings when running tests (even though we don't expect a build system). This PR adds the `skip-dependency-download` option (still leaving dependency downloading as the default) and disables downloads for our unit test suites.
=> javasrc: Add skip-dependency-download option and enable for tests

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala
Now only handle `VisibilityAnnotationTag` since the rest aren't necessary for handling annotations.
=> jimple2cpg: Fix "Unhandled Method Tags" Warnings

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala
- improve readability
- add more idiomatic Scala code
- use fns from `x2cpg`
=> Clean up `kotlin2cpg`'s AstCreator a bit more

.sbtopts
Reverts joernio/joern#1464
Not sure what's going on, but github actions fails on `sbt scalafmtCheck +test` with 
Not sure why that's happening, apparently there's a `-J` missing, but no idea where that's coming from. I can test this in PR builds, for now let's revert.
=> Revert "also set Xms to avoid potential clash with user-defined settings"

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/CfgCreationPassTests.scala, joern-cli/frontends/fuzzyc2cpg/src/test/scala/io/joern/fuzzyc2cpg/passes/CfgCreationPassTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/CfgCreationPassTest.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala
When a Cfg for a loop construct is done, we need to set `continues` and `breaks` to empty lists. Similarly, when the construction for a switch statement is done, we need to set `caseLabels` to an empty list.
=> Fix handling of nested breaks, continues, and cases.

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/callgraph/StaticCallLinker.scala
In cases where multiple methods with the same full name exist, we only linked to one of them. For C/C++, this meant that if there was both a prototype and a function definition, we would sometimes end up only linking to the prototype. This PR fixes this by linking to all methods with the given full name rather than just one.
=> Fix a bug in the static call linker

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/DependencyResolver.scala
For Java projects without maven/gradle build files, the dependency resolver will fail, logging an error. However, errors should only be reported when it's not possible to continue analysis, which isn't true in this case. Lowered to `warn`.
=> Lower log level for dependency resolver

console/build.sbt, joern-cli/build.sbt, joern-cli/frontends/c2cpg/build.sbt, querydb/build.sbt
Right now `master` does not build because of:
```
Error:  sbt.librarymanagement.ResolveException: Error downloading org.osgi.service:org.osgi.service.prefs:[1.1.0,1.2.0)
```
It's a workaround for https://github.com/eclipse-equinox/equinox.bundles/issues/54
=> Workaround for dependency resolution issue

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskSolver.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/DataFlowTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/callgraph/StaticCallLinker.scala, joern-cli/src/main/scala/io/joern/joerncli/console/JoernConsole.scala
The `maxCallDepth` parameter of the OSS data flow engine is picked up by the engine via `config.context.maxCallDepth`. Previously, however, it was not possible to set this parameter on the shell due to a bug fixed in this PR. In addition, with this PR, when setting `maxCallDepth` to -1, the engine will expand as far as possible.
=> Allow `maxCallDepth` to be configured

joern-cli/src/main/scala/io/joern/joerncli/console/JoernConsole.scala, joern-cli/src/test/scala/io/joern/joerncli/ConsoleTests.scala
driven by a user question in
https://discord.com/channels/832209896089976854/832214243230744626/986545250497597510
: hard wiring xdg-open to open images works for most, but not all
users. That's why it was already defined as a `var`, but that didn't
have any effect because config itself was a `def`.
If this gets approval, I'll also update the docs (incl. discussing
`predef.sc`) and ocular.
=> make console config configurable

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala
helps debugging when memory usage is a problem
=> kotlin2cpg: print max heap size value on start

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/ContentSourcesPicker.scala
without this change, a directory structure like the following one would
lead to an empty list of directories to analyze:
```
/tmp/nothing
|- main.kt
\- other
|- one.kt
\- two.kt
```
=> kotlin2cpg: fix bug in directory selection logic

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/BindingTable.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/NodeBuilders.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Scope.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoCalculator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Util.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ControlStructureTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/InferenceJarTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LambdaTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/SynchronizedTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeDeclTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeInferenceTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/VarDeclTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/ArrayTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/FunctionCallTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/LambdaTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/SourceFilesPickerTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/TypeNodePass.scala
This is effectively a full re-write of lambda support for javasrc2cpg. It adds a `TYPE_DECL` corresponding to the lambda method (and inheriting from the implemented functional interface) and bindings to the implemented method, all of which were missing with the previous implementation.
It relies heavily on the `ExpectedType` information to create correct signatures for the lambda method node and bindings, so in cases where we don't know the expected type, these are left as `java.lang.Object`, even if JavaParser could resolve the lambda type. In cases where neither the expected type nor the lambda type could be resolved, the results will be effectively useless. In this case we don't know which method the lambda implements, so the relevant bindings aren't created at all.
A specific case …
=> Re-implement javasrc lambdas and add more comprehensive tests

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/Path.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/nodemethods/ExpressionMethods.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefProblem.scala
While working on removing explicit order setting in javasrc2cpg, I ran into some dataflow issues due to order and argumentIndex/index no longer being the same in all cases. There are still a few checks in the dataflow engine that use order instead of index/argumentIndex, but I think using the latter makes more sense. This PR removes all uses of the order field from dataflowengineoss, except for one case where arbitrary expressions are sorted so we won't necessarily have an argumentIndex field available.
=> Remove most order-dependence from dataflowengineoss

build.sbt, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/AstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TsAstCreationPassTest.scala
This PR together with https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1642
enables joern imports of JS/TS projects containing template code.
_TODO_: update cpg version here once https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1642 is released.
=> jssrc2cpg: fixes for duplicated AST node storage

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/FileTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/NamespaceBlockTests.scala
NAMESPACE_BLOCK NAME actually need to be the full namespace identifier
and FULL_NAME need to be a unique identifier for the block itself.
This is at the moment contradicting the CPG docu but the docu is wrong
and will be updated shortly.
=> Fix NAMESPACE_BLOCK properties.

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CompanionObjectTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/DestructuringTests.scala
- remove unnecessary ARG_IDX sets
- make fns more readable
=> kotlin2cpg: Refactor N°8

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, README.md
Provide a develop enviroment docker container.
Developers can use it and don't need to deploy the build environment again.
=> :hammer: Add devcontainer

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/JsSrc2Cpg.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/Main.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTemplateDomCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/TypeHelper.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ConfigPass.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/DependenciesPass.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/PrivateKeyFilePass.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/a.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/folder/b.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/folder/c.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/foo.bar/d.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/index.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/tests/a.spec.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/tests/b.mock.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/tests/c.e2e.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/tests/d.test.js, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/ExcludeTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/ProjectParseTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ConfigPassTest.scala
We had these config files in js2cpg already and they may carry information required for our internal codescience passes.
Also: file filtering / user defined excludes were supported by js2cpg - ported that over.
=> jssrc2cpg: Added ConfigPass and file filtering

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/AstLinkerPass.scala
* also: use dsl steps rather than generic graph steps
=> AstLinkerPass: stop using property based traits

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/DependencyAstCreationPassTest.scala
Typescript allows to export almost anything: https://www.typescriptlang.org/docs/handbook/modules.html
If the exported entity does not provide a name itself (anonymous functions and classes) we derive one from the generated AST.
Supersedes: https://github.com/joernio/joern/pull/1594
=> jssrc2cpg: Fix export names

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/Path.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/DataFlowCodeToCpgSuite.scala, joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/fixtures/GhidraBinToCpgSuite.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaDataflowFixture.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/testfixtures/DataFlowCodeToCpgSuite.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/testfixtures/KotlinCodeToCpgFixture.scala
motivation: I wanted to compare dataflows for similar contructs in kotlin2cpg and javasrc2cpg, but no method for getting the points was available for the latter. so i went ahead and added it, and removed the duplication in the other frontends while at it
=> frontends: remove duplication from helper fn

console/src/main/scala/io/joern/console/cpgqlserver/CPGQLServer.scala, console/src/test/scala/io/joern/console/cpgqlserver/CPGQLServerTests.scala
Looks to me like the `success` field is always false even if the query was actually executed without problems. This PR changes that.
=> Fix `success` field for CPG server

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/parser/BabelAst.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/ExcludeTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/ProjectParseTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/AbstractPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/CallLinkerPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/testfixtures/JsSrc2CpgFrontend.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/types/TSTypesTest.scala
- no need to call `.getClass.getName` each and every time
- do not run the whole frontend if only ASTs are required
- clean-up tmp dir properly.
=> jssrc2cpg: small performance fix

joern-cli/build.sbt, joern-cli/frontends/jssrc2cpg/build.sbt, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala, joern-cli/src/universal/joern-export.bat, joern-cli/src/universal/joern-flow.bat, joern-cli/src/universal/joern-parse.bat, joern-cli/src/universal/joern-scan.bat, joern-cli/src/universal/joern-stats.bat, joern-cli/src/universal/joern.bat
We actually need to copy the binaries of astgen required for jssrc2cpg to the final distribution.
Also added remaining missing .bat files for executing joern and joern-* under Windows.
=> Fixed joern-cli distribution

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/AnnotationTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ArithmeticOperationsTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ArrayTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/BindingTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/BooleanOperationsTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallGraphTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CfgTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ConditionalTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ConstructorInvocationTests.scala
This PR moves the first couple of test classes to the new `JavaSrcCode2CpgFixture`. In some cases I left the tests unchanged, using a single code block, since the tests themselves are very simple and, in my opinion, the effort of restructuring the tests outweighs the benefits of doing so. For more complex test suites (especially once I get to the dataflow tests) this will not be the case.
=> javasrc: New test fixture migration #1

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ArrayTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ControlStructureTests.scala
* flatten the AST for expressions like `new int[] {1, 2, 3}`, which were previously represented as an `<operator>.alloc` call with an `<operator>.arraiInitializer` call as a child. 
* add resource initialisers to the AST directly before the `try-with-resources` block in which they are defined.
=> Misc javasrc fixes

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/ConfigFileCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/application.conf, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/basic.jsp, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/basic.properties, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/basic.tf, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/basic.tfvars, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/basic.vm, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/batis/conf.xml, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/dwr.xml, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/faces-config.xml, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/nested/nested.properties, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/no-conf-1.xml, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/no-conf-2.conf, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/routes, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/struts.xml, joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/web.xml, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/passes/ConfigFileCreationPassTests.scala
The list of config file filters is based on that used by `java2cpg` in [ConfigFile.java](https://github.com/ShiftLeftSecurity/java2cpg/blob/master/java2cpg/src/main/java/io/shiftleft/java2cpg/configfiles/ConfigFile.java).
=> Add ConfigFile nodes to javasrc2cpg ASTs

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/ConfigFileCreationPass.scala
Before these changes, the frontend would crash if the frontend was invoked with a relative path to the java project. This fixes the absoluteness of the paths and is just more robust in general.
=> javasrc: Fix relative path crash during config file creation

joern-cli/frontends/jssrc2cpg/src/test/resources/broken/broken.js, joern-cli/frontends/jssrc2cpg/src/test/resources/broken/good.js, joern-cli/frontends/jssrc2cpg/src/test/resources/closurebinding/foobar.js, joern-cli/frontends/jssrc2cpg/src/test/resources/closurebinding/nested/a.js, joern-cli/frontends/jssrc2cpg/src/test/resources/closurebinding/nested/b.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/.sub/e.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/a.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/a.min.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/b-min.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/c.spec.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/d.chunk.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/folder/b.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/folder/c.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/foo.bar/d.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/index.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/tests/a.spec.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/tests/b.mock.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/tests/c.e2e.js, joern-cli/frontends/jssrc2cpg/src/test/resources/excludes/tests/d.test.js, joern-cli/frontends/jssrc2cpg/src/test/resources/rec/a.js, joern-cli/frontends/jssrc2cpg/src/test/resources/rec/b.js, joern-cli/frontends/jssrc2cpg/src/test/resources/rec/sub/c.js, joern-cli/frontends/jssrc2cpg/src/test/resources/rec/sub/d.js, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/ExcludeTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/ProjectParseTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/AbstractPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala
Test files and their content that is required during jssrc2cpg tests is now generated on-the-fly.
This is way easier to maintain as the single point of truth is now directly visible in the test code.
Hence, we do not have to rely on external files any longer. Also, the handling of resource paths / URIs during testing within Intellij or a SBT shell is quite error prone.
=> jssrc2cpg: removed test resource files

console/src/main/scala/io/joern/console/cpgcreation/JsCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/package.scala
* still required by ocular...
* partial revert of https://github.com/joernio/joern/pull/1563/files#diff-ae06dd079f8134c67a12684b24f703f9cdbb25ec59aa327ca3af32819831a646R26
=> bring back js2cpg frontend as a fallback, if jssrc isn't available

joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NodeSteps.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/StoredNodeMethods.scala
Both `.tag` and `.tagList` did essentially the same thing, but tagList
deferred from our naming convention and unnecessarily instantiated
a `NewTag` for each existing `Tag` node.
Successor of https://github.com/joernio/joern/pull/1602
=> StoredNode.tag|tagList: deduplicate and refactor

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Scope.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoCalculator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/InferenceJarTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeInferenceTests.scala
This PR fixes a couple of bugs where types in method full names for unresolvable calls were `<unresolved...>` even though there was enough type information available to use the actual types.
It also replaces the `<unresolvedReceiver>` and `<unresolvedSignature>` types with `<unresolvedType>` for the sake of uniformity.
=> Fix some javasrc type bugs

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/Path.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LambdaTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/SynchronizedTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ConstructorTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ControlStructureTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/DataClassTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/DestructuringTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LambdaTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/MethodTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/SpecialOperatorsTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TryExpressionsTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/PrimitiveArrayTypeMappingTests.scala, querydb/src/main/scala/io/joern/scanners/android/AndroidUnprotectedAppParts.scala, querydb/src/main/scala/io/joern/scanners/c/UseAfterFree.scala, querydb/src/main/scala/io/joern/scanners/java/CertificateChecks.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/CfgNodeMethods.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/LocalMethods.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/MethodMethods.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/operatorextension/nodemethods/TargetMethods.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/package.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/MethodParameterOutTraversal.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/testing/package.scala, semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/types/expressions/generalizations/CfgNodeTraversalTests.scala, semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/types/expressions/generalizations/ExpressionTraversalTests.scala, semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/types/structure/MethodParameterTests.scala
We have an `implicit Node -> Traversal` which I now believe was not
a good idea in the first place. This PR cleans up most of it's usage,
which are mostly completely unnecessary calls, like
`val List(sameNodeA) = someNodeA.l`
Unfortunately we can't drop the implicit, I added a comment there.
A follow up PR will tighten some of the return types - this is mostly
a refactoring.
=> remove unnecessary usage of `implicit Node -> Traversal`

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/AstCreationPassTests.scala
Came in via https://github.com/joernio/joern/pull/1658 and https://github.com/joernio/joern/pull/1659 without merge from master.
=> c2cpg: clean-up from the latest two refactorings

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala
this specific fn, and other fns around _KtQualifiedExpressions_ are in dire need of refactoring.
bringing this change in _as is_ simply because of broken upstream data-flows
=> kotlin2cpg: bring back old impl of single fn

joern-cli/frontends/javasrc2cpg/build.sbt, joern-cli/frontends/kotlin2cpg/build.sbt
Using `javasrc` in joern plugins fails when using gradle dependency resolution because the gradle tooling jars aren't present. I noticed that the dependencies were marked as optional. Now they are mandatory.
=> Make gradle dependency mandatory

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallGraphTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/DefaultContentRootsTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/EnumTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ExtensionTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/FileTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/InnerClassesTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LambdaTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LocalClassesTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LocalFunctionsTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/MethodParameterTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeAliasTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeDeclTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/NestedDeclarationTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/validation/ValidationTests.scala
mostly contains fixes for deeply-nested declarations
=> kotlin2cpg: tweak ASTs around local declarations 

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LambdaTests.scala
without this change, generating a CPG for a project containing a lambda
with no statements in its block crashes with a `NoSuchElementException`:
```
2022-08-10 11:44:33.325 INFO shutdown finished
java.util.NoSuchElementException: last of empty list
at scala.collection.immutable.Nil$.last(List.scala:665)
at scala.collection.immutable.Nil$.last(List.scala:661)
at io.joern.kotlin2cpg.ast.KtPsiToAst.astsForBlock(KtPsiToAst.scala:411)
at io.joern.kotlin2cpg.ast.KtPsiToAst.astsForBlock$(KtPsiToAst.scala:386)
at io.joern.kotlin2cpg.passes.AstCreator.astsForBlock(AstCreator.scala:25)
at io.joern.kotlin2cpg.ast.KtPsiToAst.$anonfun$astForLambda$4(KtPsiToAst.scala:530)
```
=> kotlin2cpg: fix parsing of nop lambdas 

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/ExtendedCfgNode.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/DataFlowTests.scala
Before return flows, we do a bit of filtering to remove invisible elements. However, when the source is an invisible element, we should report it. Because we did not, flows from literals were often incomplete before, starting at the surrounding call.
=> Display element in flow if it is a source element

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ControlStructureTests.scala
This fixes 2 crashes that occurred during cpg generation for https://github.com/dsolonenko/financisto. The first was another stack overflow resulting from a "getType" call, while the second was due to an invalid REF edge that was created when looping over a statically imported member in a foreach loop. TODOs from this are to implement proper static import handling, and to fix the javaparser crash, although that would be part of a much larger JavaParser fixing effort.
=> Fix some javaparser and javasrc2cpg crashes

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/DependencyResolver.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/MavenDependencies.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/dependency/DependencyResolverTests.scala
With these changes, the DependencyResolver will recursively search for all Maven project roots, starting at the given project directory, and will then sequentially fetch dependencies for all project roots found this way. I considered a parallel implementation, but decided against it for a couple of reasons:
- the main use-case for this is to still fetch dependencies when the given input directory is not actually the maven root directory, but rather a parent. In this case we're still just fetching dependencies for a single project so it doesn't matter either way.
- fetching dependencies in parallel might result in duplicate dependencies being downloaded twice, instead of using the cached version for the second run.
=> Recursively search for Maven project roots when fetching dependencies

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala
This is for: https://github.com/joernio/joern/issues/1688
=> jssrc2cpg: use "<operator>.new" as NAME for constructor calls

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/ExtendedCfgNode.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/StaticMemberTests.scala
There have long been a few tests for handling of static member variables in Java that we've left broken. This PR fixes those, albeit not in a fool-proof manner. The idea is to look up usages of member variables and take the first one as we traverse the AST from left to right, unless that first one is actually a reassignment of that member variable, in which case we skip.
=> Handle member variables

.github/workflows/pr.yml, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreatorHelper.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/datastructures/Scope.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/TypeNodePass.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala
- fixes duplicate type creation for default types
- fixes fullnames for constructor functions
- fixed function handling for deeply nested (anon) functions
- this resolves the remaining DF engine crashes on sptest projects
=> jssrc2cpg: fullName and function handling fixes

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LombokTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala
This PR adds an option to use delomboked source code for type information while still using the original source with lombok annotations when creating the CPG. This gives better type information than the original source in some cases, and gives correct filenames and line numbers instead of information from the delomboked source. The unit tests added in this PR give a simple example of where this approach works and where it doesn't.
=> Add option to use delombok for javasrc2cpg type information only

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/ExtendedCfgNode.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/ResultTable.scala
I recently introduced tracking of member variables initialized by literals. To achieve this, I expanded literals to yield the member variables initialized by those literals, prior to data flow tracking. Unfortunately, I forgot to consider that this would mean that the flow would start in the member variable and not in the literal. This PR fixes that, appending the literal if it is the actual source.
=> Fix for flows when dealing with member variables

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/DependencyResolver.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/MavenDependencies.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/dependency/DependencyResolverTests.scala
https://github.com/joernio/joern/pull/1679/files added recursive searching for multiple Maven projects, but not Gradle. This PR applies the same idea, but allows the dependency fetcher to recursively search for any mix of Maven and Gradle projects starting at the given root and will fetch the dependencies for these on a per-project basis.
This isn't necessarily useful functionality, but comes with the side effect that it would also support a single nested Maven or Gradle subproject.
=> Recursively search for a mix of Maven and Gradle projects when fetching dependencies

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Defines.scala
They are supposed to be used by statically typed frontend with
package/namespace structure to indicate unresolved static type
information.
For more details see code comment.
@fabs I did not find an already existing suitable place for those
defines. Please suggest some alternative if you have a better idea
on naming/location.
=> Add UnresolvedNamespace and UnresolvedSignature defines.

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Delombok.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LombokTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala
With these changes, `javasrc2cpg` will automatically run delombok and scan the delomboked code when a lombok dependency is found with `--fetch-dependencies`. This isn't a particularly clever default and can't be switched off as is (another `--no-delombok` option could be added, but at that point we'd pretty much need to add a decision tree picture to the documentation to make sense of delombok logic). I'm not convinced this is something we actually want to do, but is a way of getting better WebGoat results by default (at least in sptests which currently fetch dependencies by default).
Update: This also fixes filenames in the CPG when delombok is used, so the filenames will now match the original source file and not the temporary delomboked files.
=> Run delombok by default when a lombok dependency is detected

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
When `jssrc2cpg` is used as a library in an extension, then the current code for resolving the location of `astgen` fails because it is looking for a directory called `jssrc2cpg` in the staging directory. When searching the path backwards for `lib`, it works in the normal setting and when used in an extension.
=> Fix `astgen` invocation

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/TypeInferencePass.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeInferenceTests.scala
There are situations where we can currently infer the typeFullName for method return and parameter types by using import information, but since JavaParser cannot resolve these methods, this type information is missing when these methods are called from classes in other files. This PR adds a very rough implementation to find the implementation for internal methods that are called from different files. It doesn't handle overloaded methods or inheritance well, but should give better results than not having it.
=> Add a hacky call methodFullName resolution pass

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DataFlowProblem.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DataFlowSolver.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefPass.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefProblem.scala
This PR removes the tie DataFlowProblem and DataFlowSolver have to
StoredNode in order to make it reusable for other domains.
=> Generalize the DataFlowProblem and DataFlowSolver.

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/MethodStubCreator.scala
As we do not have proper full names this required filtering out empty full names in the MethodStubCreator.
For reference: https://github.com/joernio/joern/issues/1728
=> jssrc2cpg: added NAMEs for CALLs

.github/workflows/pr.yml, console/src/main/scala/io/joern/console/BridgeBase.scala, console/src/main/scala/io/joern/console/Console.scala, console/src/main/scala/io/joern/console/Reporting.scala, console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala, console/src/main/scala/io/joern/console/embammonite/UserRunnable.scala, console/src/main/scala/io/joern/console/workspacehandling/WorkspaceManager.scala, joern-cli/src/main/scala/io/joern/joerncli/console/AmmoniteBridge.scala, joern-cli/src/main/scala/io/joern/joerncli/console/Joern.scala, joern-cli/src/main/scala/io/joern/joerncli/console/Predefined.scala
A dirty hack to capture the reported output for the server-mode. Context: server mode is a bit tricky, because the
reporting happens inside the repl, but we want to retrieve it from the context _outside_ the repl, and the two have
separate classloaders. There's probably a cleaner way, but for now this serves our needs.
Note that this convolutes the output from concurrently-running jobs - so we should not run UserRunnables
concurrently.
I'll revisit this when we upgrade to scala3-repl, and hopefully make it less hacky.
=> server mode: capture reported output, instead of (only) printing on the server

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Scope.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/AnnotationTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ConstructorInvocationTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MemberTests.scala
This PR fixes https://github.com/joernio/joern/issues/1757 by adding member initializers to constructors. For consistency with java bytecode, the initializers are added to the start of every constructor body, except if that body contains a `this(...)` call. All of the assignments are also assignments to a `fieldAccess` (e.g. `int x = 12` would be represented as `this.x = 12`), again for consistency with bytecode.
=> javasrc: Add field initializers to constructors

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala
Static class members with initialization are now correctly attached to the `<clinit>` method. Non-static class members with initialization are now correctly attached to the `<constructor>` method.
=> jssrc2cpg: fix static/non-static class member handling

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Scope.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MemberTests.scala
Re-adding the same initializer asts to constructors led to issues where duplicate nodes and edges were being added to the CPG. Doing a deep copy fixes this.
=> Fix aliasing issue when adding static initializers to javasrc constructors

joern-cli/src/main/scala/io/joern/joerncli/JoernVectors.scala
* Now also works for slices (that do not contain methods)
* ids are reported in the same way as other features
=> Minor fix `joern-vectors`

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/DependencyAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/VueJsDomAstCreationPassTest.scala
Import declarations are now additionally lowered to good-old ES6 style require assignments. With this the CS require preprocessor does not need modifications.
=> jssrc2cpg: lowered import declarations

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/OperatorTests.scala
Switch statements felt like a good candidate for a common x2cpg method, but at least from comparing php2cpg and javasrc2cpg, it looks like actually extracting shared code will be difficult to do without adding just as much preprocessing code back in.
=> Add PHP switch statements and fix variable code

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/OperatorTests.scala
This PR fixes the `code` field for operators and variables, and refactors tests to use the `inside` construct instead of the `match` currently used which required an explicit `case` for failures.
=> Fix PHP code fields and use inside in tests

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/dotgenerator/DdgGenerator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DataFlowProblem.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DataFlowSolver.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskSolver.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/DependencyCfgCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/JsClassesCfgCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/MixedCfgCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/SimpleCfgCreationPassTest.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/testing/package.scala
With this PR, we now include `BLOCK` nodes in the control flow graph in order to enable data flow tracking through constructor calls and Javascript objects given in object notation, e.g., `{ a: b }`.
=> Include BLOCK nodes in the CFG and enable tracking for them

benchmarks/src/test/scala/io/joern/benchmarks/testfixtures/BenchmarkFixture.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/layers/dataflows/OssDataFlow.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/EdgeValidator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefPass.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/dotgenerator/DotDdgGeneratorTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/DataFlowCodeToCpgSuite.scala, joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/fixtures/DataFlowBinToCpgSuite.scala, joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/mips/DataFlowTests.scala, joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/mips/DataFlowThroughLoHiRegistersTests.scala, joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/querying/x86/DataFlowTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/JavaSrc2CpgTestContext.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/Jimple2CpgTestContext.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/testfixtures/DataFlowCodeToCpgSuite.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/testfixtures/KotlinCodeToCpgFixture.scala, joern-cli/src/main/scala/io/joern/joerncli/CpgBasedTool.scala, joern-cli/src/main/scala/io/joern/joerncli/DefaultOverlays.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernExport.scala
Previously, we did not apply data flow semantics at DDG generation time, but only at query-time. While that's enough for reachableBy queries and is the most flexible solution, it means that raw exports of the graph will show a lot of `REACHING_DEF` edges that shouldn't exist. Since a lot of people seem to be interested in exporting the raw graph, I want to make sure they don't mistakenly believe that we don't honor data flow semantics. Therefore, semantics are now also applied at generation time.
=> Apply data flow semantics at generation time

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/datastructures/Scope.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/LocalTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/PocTest.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala
Notes:
* Locals for a method are always added to the start of the method. This is to keep code simple by avoiding having to return a sequence of ASTs at any point. I also think this makes as much sense as putting them anywhere else, since PHP doesn't have variable declarations or shadowing.
* This also adds a global typeDecl/method similar to C to avoid any issues that arise from the assumption that locals belong to a specific method.
* This does not handle global variables yet (specifically that the `global` keyword is required to bring global variables into local scope). This will be fixed when adding support for `global`.
=> Add PHP locals and for loops

console/build.sbt, console/src/main/scala/io/joern/console/cpgcreation/CpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CpgGeneratorFactory.scala, console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala, console/src/main/scala/io/joern/console/cpgcreation/JsSrcCpgGenerator.scala, console/src/test/scala/io/joern/console/cpgqlserver/CPGQLServerTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/DependencyAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/VueJsDomAstCreationPassTest.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ImportTests.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernParse.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NodeTypeStarters.scala
This is a follow-up for https://github.com/joernio/joern/pull/1804 - the post processing passes (e.g., `RequirePass`) are now executed automatically when using `joern-parse` and `ImportCode`.
=> Execute post-processing passes automatically for `joern-parse`/`ImportCode`

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NewTagNodePairTraversal.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/testing/package.scala
initially introduced as part of the migration to the new DiffGraph API
=> Remove unnecessary logic

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreatorHelper.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/datastructures/Scope.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala
Previously, some locals were generated without a parent block for JS classes. This PR fixes that.
=> jssrc2cpg: fixed locals-blocks relation in classes

console/src/main/scala/io/joern/console/Console.scala, console/src/test/scala/io/joern/console/ConsoleTests.scala
_undo_ was introduced at some point to allow for edits while using Joern as a platform. Because it's not been used very extensively, and in order to help with removing deprecated logic, we decided to remove it for now.
=> Remove `undo`

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskSolver.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala
```
"DataFlowTest70" should {
val cpg = code("""
| int source() {
|   return 42;
| }
| void main() {
|   sink(source());
| }
| """.stripMargin)
"Test Interprocedural" should {
"have a flow from argument(which itself is a call) to return" in {
val source = cpg.literal("42")
val sink   = cpg.call("sink").argument
sink.reachableByFlows(source).size shouldBe 1
}
}
}
```
=> Remove path.size > 1 for this test case

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala
Previously, we only added `IMPORT` nodes for `import` statements while `require` calls were only accessible via `cpg.call("require")`. With this PR, it doesn't matter whether modules are imported via `import` or `require`, in both cases, we create `IMPORT` nodes.
=> jssrc2cpg: add `IMPORT` nodes for `require` statements

build.sbt, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/package.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/DependencyTraversal.scala
With this PR, `IMPORT` nodes are now connected to `DEPENDENCY` nodes via `IMPORTS` edges and it's possible to traverse from a dependency to an import via `cpg.dependency.imports.l`.
=> jssrc2cpg: link dependencies and imports

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Defines.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/MethodStubCreator.scala
This value should by used for dynamically typed languages for dynamic
call method full name properties since they cannot provide any
meaningful method/function interface guarantees like we e.g. have in
Java where a dynamically dispatched call always has a certain
method/function interface guaranteed.
=> Introduce DynamicCallUnknownFallName define.

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/TypeInferencePass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/BindingTable.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TypeInfoCalculator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Util.scala
This PR includes 2 fixes for issues found when creating a cpg for https://github.com/elastic/elasticsearch
* `typeDecl.getAncestors` throws an `IllegalArgumentException` for record types (at least when using the ReflectionTypeSolver), so catch that exception. This may be related to https://github.com/javaparser/javaparser/issues/3556
* It was possible to end up with an infinite recursive loop when substituting a type variable with a wildcard type bounded by that same type variable, so this adds a check to check if a "true" substitution occurred.
This also lowers the logging level for some warnings that are currently very noisy (and not particularly useful except for debugging) on elasticsearch.
=> Fix javasrc crash and hang bugs

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/JsSrc2Cpg.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ConstClosurePass.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/RequirePass.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ConstClosurePassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/layers/CallGraph.scala
=> Introduce a pass to handle `const foo = (x,y) => { }`

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/CCodeToCpgSuite.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/DataFlowCodeToCpgSuite.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/testfixtures/DataFlowCodeToCpgSuite.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/testfixtures/JsSrc2CpgFrontend.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/testfixtures/KotlinCodeToCpgFixture.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/testfixtures/PhpCode2CpgFixture.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/Code2CpgFixture.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/DefaultTestCpg.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/LanguageFrontend.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/TestCpg.scala, querydb/src/test/scala/io/joern/suites/AndroidQueryTestSuite.scala
This enables the reused of Code2CpgFixture also in tests setups where
additional configuration values are need for either the language
frontend or the CPG passes.
We achieve this by basically making the TestCpg a combo object where the
LangaugeFrontend trait is mixed in. By then deriving from TestCpg,
arbitrary additional configuration methods can be added.
=> Make Code2CpgFixture more flexible.

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForPrimitivesCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
String literals should look the same no matter if they are written with ", ', or ` (e.g., useful for easy secrets detection).
=> jssrc2cpg: uniform handling for string literals

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/SourceRootFinder.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/util/SourceRootFinderTests.scala
Specifically, the non-standard directory structure of https://github.com/adobe/places-monitor-android revealed some logical bugs in the source root detection logic in javasrc2cpg.
=> Fix missing javasrc sources bug for non-standard directory structures

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala
casue: 
https://github.com/joernio/joern/blob/0807206a83582935d9473180814b5befefa6e816/dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala#L88
```in(node)``` brings in unsed reaching definition, need to filter out unused node.
=> Fix bug in ddg generator

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/Main.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IncludeAutoDiscovery.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/PreprocessorPassTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/AbstractPassTest.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/CCodeToCpgSuite.scala
Can be activated with `--with-include-auto-discovery` now.
=> c2cpg: disabled auto discovery of system header include paths

joern-cli/build.sbt, joern-cli/src/main/scala/io/joern/joerncli/JoernExport.scala, joern-cli/src/test/scala/io/joern/joerncli/JoernExportTests.scala
implements https://github.com/joernio/joern/issues/1893
depends on https://github.com/ShiftLeftSecurity/overflowdb/pull/331 and https://github.com/ShiftLeftSecurity/overflowdb/pull/332 - won't compile until upgrade train has completed
Also includes some refactorings - most notably: Representation|Format: changed to uppercase 
(as per Scala convention and support in match clauses), but match on name ignore case when parsing config
=> joern-export: SplitByMethod

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/datastructures/Scope.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/OperatorTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/UseTests.scala
The use implementation here is not complete. It does include the information one needs to figure out function names and such with queries, but ideally the frontend should do this by itself. This would require interaction with includes and is still a TODO.
=> Add PHP global and use stmts

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/util/ProgramHandlingUtil.scala
`com.facebook.presto.spark.classloader_interface.IPrestoSparkServiceFactory` is passing `f.getName.contains(".class")`, `endsWith` should fix this.
Example input: [presto.zip](https://github.com/joernio/joern/files/9899376/presto.zip)
=> Fixing file extension check

console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/PythonCallLinker.scala
This PR introduce a call linker for python.
The linker links ```calls``` and ```methods``` only by their **name**(not full name), because it's hard to decide thier full name in a dynamic language.
Though this will result in wrong edges, it will make interprocedural data flow analysis work for the moment.
=> A call linker for python

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
With this PR, the frontend no longer crashes on larger projects (tested with a couple of trending PHP projects on github). The implementation for foreach loops, trait use statements and anonymous functions/classes are still TODO, but this should unblock further work on the security side for PHP for now.
=> Add remaining PHP language constructs to Domain with placeholder implemenations

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgdominator/CfgDominator.scala
the warning comes up because this looks like scaladoc, but since it's on a method inside a method, it'll never end up in scaladoc
not really critical, but to avoid further confusion as in
https://github.com/joernio/joern/pull/1925#discussion_r1011382480
=> fix scaladoc warning

build.sbt, console/build.sbt, joern-cli/frontends/c2cpg/build.sbt, joern-cli/frontends/jssrc2cpg/build.sbt, joern-cli/frontends/x2cpg/build.sbt, macros/build.sbt, semanticcpg/build.sbt
Some of the code we have under tests is or will be reused in other
projects. Mainly our test fixtures will be reused but creating
individual projects which just test utilities for each already existing
project seem overkill.
=> Publish test artifacts for all projects.

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
For `const foo = () => 42`, there should be a ```Return``` node for the data flow algrithm.
For `const foo = () => {return 42;}`, there should be only one ```Block``` node.
=> Fix ast of JS arrow functions

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/cfg/CfgCreationPassTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/CfgCreationPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/Cfg.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala
In PHP a break/continue statement can be followed by an integer literal
to specify how many levels of loop/switch statements should be effected.
This PR adds support for this.
Furthermore this PR fixes a bug in CfgCreator where continue statements
in switch statement bodies were ignored. So e.g. in the following case
the `continue` statement had no CFG successors at all:
```
while (i < 1) {
switch (j) {
case 0:
continue;
}
}
```
=> Implement leveled break/continue statement support in CfgCreator.

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreationPass.scala
The parts can just be KtFileWithMeta instead of string to avoid
KtFileWithMeta lookup.
=> Simplify Kotlin2Cpg AstCreationPass.

querydb/src/test/scala/io/joern/scanners/android/AndroidMisconfigurationsTests.scala, querydb/src/test/scala/io/joern/scanners/android/AndroidUnprotectedAppPartsTests.scala, querydb/src/test/scala/io/joern/scanners/android/RootDetectionTests.scala, querydb/src/test/scala/io/joern/scanners/android/UnsafeReflectionTests.scala, querydb/src/test/scala/io/joern/scanners/c/CopyLoopTests.scala, querydb/src/test/scala/io/joern/scanners/c/CredentialDropTests.scala, querydb/src/test/scala/io/joern/scanners/c/DangerousFunctionsTests.scala, querydb/src/test/scala/io/joern/scanners/c/FileOpRaceTests.scala, querydb/src/test/scala/io/joern/scanners/c/HeapBasedOverflowTests.scala, querydb/src/test/scala/io/joern/scanners/c/IntegerTruncationsTests.scala, querydb/src/test/scala/io/joern/scanners/c/MetricsTests.scala, querydb/src/test/scala/io/joern/scanners/c/NullTerminationTests.scala, querydb/src/test/scala/io/joern/scanners/c/RetvalChecksTests.scala, querydb/src/test/scala/io/joern/scanners/c/SignedLeftShiftTests.scala, querydb/src/test/scala/io/joern/scanners/c/SocketApiTests.scala, querydb/src/test/scala/io/joern/scanners/c/UseAfterFreePostUsage.scala, querydb/src/test/scala/io/joern/scanners/c/UseAfterFreeReturnTests.scala, querydb/src/test/scala/io/joern/scanners/c/UseAfterFreeTests.scala, querydb/src/test/scala/io/joern/scanners/ghidra/DangerousFunctionsTests.scala, querydb/src/test/scala/io/joern/scanners/ghidra/UserInputIntoDangerousFunctionsTests.scala, querydb/src/test/scala/io/joern/scanners/java/CryptographyMisuseTests.scala, querydb/src/test/scala/io/joern/scanners/kotlin/NetworkCommunicationTests.scala, querydb/src/test/scala/io/joern/scanners/kotlin/NetworkProtocolsTests.scala, querydb/src/test/scala/io/joern/scanners/kotlin/PathTraversalsTests.scala, querydb/src/test/scala/io/joern/suites/AndroidQueryTestSuite.scala, querydb/src/test/scala/io/joern/suites/CQueryTestSuite.scala, querydb/src/test/scala/io/joern/suites/GhidraQueryTestSuite.scala, querydb/src/test/scala/io/joern/suites/JavaQueryTestSuite.scala, querydb/src/test/scala/io/joern/suites/KotlinQueryTestSuite.scala
context: Scala3 is stricter on deriving the type of an inherited method, specifically:
```
trait A
object A1 extends A {
def onlyInA1 = 42
}
trait B {
def a: A
}
class B1 extends B {
override def a = A1
def fun = a.onlyInA1
}
```
fails with
```
[error] 31 |    def fun = a.onlyInA1
[error]    |              ^^^^^^^^^^
[error]    |       value onlyInA1 is not a member of io.joern.scanners.android.Foo.A
```
One fix is to annotate `def a` with the specific type in each subclass,
but in our use case I found it more natural to pass the QueryBundle to
the parent and use a type parameter.
=> querydb/Test: change test archetype in preparation for scala3

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/datastructures/Scope.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/CfgCreationPassTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ClosureTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MethodTests.scala
This supports both the long-form syntax as well as arrow functions. Both are represented as a regular method belonging to the typeDecl they were defined in.
=> Add PHP anonymous functions

console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/CallCpgTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/PythonModuleDefinedCallLinker.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/PythonNaiveCallLinker.scala
- No longer change calls to STATIC_DISPATCH
- Renamed call linkers to `PythonModuleDefinedCallLinker` and `PythonNaiveCallLinker` to reflect their linking strategies
=> pysrc2cpg: Refactor Call Linkers

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Main.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernFlow.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernParse.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernScan.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernSlice.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernVectors.scala, joern-cli/src/universal/schema-extender/schema/src/main/scala/CpgExtCodegen.scala, querydb/src/main/scala/io/joern/dumpq/Main.scala
Scala3 doesn't support the 'magic' DelayedInit trait which is used by
`extends App` - the recommended way for cross compilation is to use
regular `def main(args: Array[String])` methods instead.
See https://docs.scala-lang.org/scala3/book/methods-main-methods.html
=> rewrite `extends App` to `def main`

README.md, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DataFlowProblem.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefPass.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefProblem.scala
Remove entryNode and exitNode. Those are not required by
DataFlowProblem and DataFlowSolver and where so far only used
to piggy back the method node onto the data flow problem for the
using codes sake.
Now the using code handles the method node itself and on top we avoid
casting.
Also: Made succ and pred functions.
This enables implementors to choose how they want to implement those
to relations and are not forced to use a Map.
=> Simplifiy FlowGraph trait.

joern-install.sh
Add symlinks for the Python, Java, Kotlin, PHP and Jimple CPG construction tools to joern-install.sh, so that these tools can be called without needing to specify the path in a script.
If these symlinks have been omitted on purpose, feel free to ignore this pull request.
=> Add missing symlinks to joern-install.sh

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/ExtendedCfgNode.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/ResultTable.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskCreator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskSolver.scala, dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/queryengine/ResultTableTests.scala
Re: https://github.com/joernio/joern/pull/1967
Cleaning up and redesigning the caching at the same time may have been a bit optimistic. I am now bringing in the cleanups first and testing whether any of the cleanups negatively impact performance. In this PR, I'm getting rid of the `mutable.Stack` for call site stacks first.
=> Use `List` instead of `mutable.Stack` for callsite stack

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala
Shouled be ```RequestMapping``` to stay the same with ```javasrc2cpg```.
=> jimple2cpg: fix name of annotation

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/ResultTable.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskSolver.scala, dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/queryengine/ResultTableTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/RequirePassTests.scala
In https://github.com/joernio/joern/pull/1947, we ensured that tasks would never be computed twice. Unfortunately, we forgot to complete tasks that were held due to this optimization and just discarded them. This lead to missing flows in situations where two sinks lead to the same sources, while traversal for one of them was held and discarded. This PR fixes that issue by keeping a table of completed tasks and storing held tasks. Once all tasks have been solved, held tasks are completed and added to the result list.
=> Complete held tasks

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/DefaultSemantics.scala
Fixes instances where dynamic invocations fail to taint the receiver.
Resolves #1982 
cc: @Liyw979
=> DefaultSemantics: Fixed Missing Receiver Tainting Flows

joern-cli/frontends/javasrc2cpg/build.sbt, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/TypeInferencePass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/CachingReflectionTypeSolver.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/EagerSourceTypeSolver.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/SimpleCombinedTypeSolver.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/TypeInfoCalculator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/BindingTable.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Util.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/InferenceJarTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LombokTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeTests.scala
Changes included here:
* Add a new SimpleCombinedTypeSolver that does the same as the JavaParser CombinedTypeSolver, except that it caches types if solving results in StackOverflowErrors.
* Add a new EagerSourceTypeSolver to replace the JavaParserTypeSolver (which is responsible for source-based type solving). The JPTS parsed files a second time to search for types in them, so this new eager version pre-computes all types in the given compilation units instead. This does mean enough memory to store the types map must be available, but this seems to be a relatively small amount in the overall computation.
* Add caching to the TypeInferencePass to avoid expensive regex matches.
This brings AST creation time for elasticsearch down to under 10 minutes on a workstation with an i9 and enough …
=> Optimize javasrc2cpg type solving somewhat and add cache to TypeInferencePass

querydb/src/main/scala/io/joern/querydb/language/android/ConfigFileTraversal.scala, querydb/src/main/scala/io/joern/scanners/android/ExternalStorage.scala, querydb/src/main/scala/io/joern/scanners/android/Intents.scala, querydb/src/main/scala/io/joern/scanners/android/JavaScriptInterface.scala, querydb/src/main/scala/io/joern/scanners/android/Misconfigurations.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/android/ConfigFileTraversal.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/android/Constants.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/android/LocalTraversal.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/android/MethodTraversal.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/android/NodeTypeStarters.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/android/package.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/utils/SecureXmlParsing.scala
background: we'd like to use it downstream without inheriting a large 
dependency tree incl. console and various frontends
=> refactor: move querydb.language.android to semanticcpg

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTemplateDomCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Ast.scala
- missing argumentIndex on last block element identifier.
- Rename setIndices to setArgIndices and cleanup in that function as
it does not set order anymore.
- Set order mostly implicitly via Ast relation.
- Dont set argument index to 0 for receiver.
The call receiver in Javascript is not passed into calls as instance object
and thus an argument index of 0 was not correct.
=> JsSrc2Cpg: Argument index and order property related changes.

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/MixedCfgCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/SimpleCfgCreationPassTest.scala
Now with limited support for computed properties.
Also fixed field identifier names for string-based literals there.
=> jssrc2cpg: improved support for ObjectProperty

.github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/upgrade-deps.yml
See warnings for the latest runs here on GH.
Also: adopt jdk is now temurin (https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).
=> Updated GH Actions

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala
Reading in a single file with `javasrc` gives the following stacktrace
```
java.nio.file.NotDirectoryException: /Users/david/Documents/joernio/joern/tests/swap/swap.java
at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:419)
at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
at java.base/java.nio.file.Files.list(Files.java:3793)
at better.files.File.list(File.scala:747)
at better.files.File.children(File.scala:749)
at io.joern.javasrc2cpg.util.SourceRootFinder$.statePreSrc(SourceRootFinder.scala:19)
```
The following PR addresses this by:
- Check if the input path is a supported file or directory
- Return a singleton list if it is a supported file (or empty list if not)
- Assume usual behaviour if it is a directory
=> javasrc2cpg: Fixed issue when reading single file 

joern-cli/src/main/scala/io/joern/joerncli/JoernExport.scala
The removed code performs the same comparison as the code directly below it.
Found this code while investigating:
```
Exception in thread "main" scala.MatchError: All (of class scala.Enumeration$Val)
at io.joern.joerncli.JoernExport$.exportDot(JoernExport.scala:120)
at io.joern.joerncli.JoernExport$.exportCpg(JoernExport.scala:105)
at io.joern.joerncli.JoernExport$.$anonfun$new$8(JoernExport.scala:90)
at io.joern.joerncli.JoernExport$.$anonfun$new$8$adapted(JoernExport.scala:89)
at scala.util.Using$.resource(Using.scala:261)
at io.joern.joerncli.JoernExport$.$anonfun$new$7(JoernExport.scala:89)
at io.joern.joerncli.JoernExport$.$anonfun$new$7$adapted(JoernExport.scala:83)
at scala.Option.foreach(Option.scala:437)
at io.joern.joerncli.JoernExport$.delayedEndpoint$io$joern$joerncli$JoernExpo …
```
=> refactor: simplify

joern-cli/frontends/kotlin2cpg/build.sbt, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Main.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/interop/JavasrcInterop.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/compiler/JavaInteroperabilityTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/dataflow/JavaInteroperabilityTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/testfixtures/KotlinCodeToCpgFixture.scala
A number of Android Apps out in the wild use both Kotlin _and_ Java in the same project, having the ASTs for both should be very helpful. The functionality is currently hidden behind a flag until it's been tested a bit more that it doesn't lead to issues.
=> kotlin2cpg: add basic Java interop support

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/compiler/JavaInteroperabilityTests.scala
without the change, downstream projects complain:
```
[WARN ] Multiple entities with the same name: ShadowType(android.content.Context), must be distinct for linking
[WARN ] Multiple entities with the same name: ShadowType(android.content.Intent), must be distinct for linking
[WARN ] Multiple entities with the same name: ShadowType(android.content.IntentFilter), must be distinct for linking
```
=> kotlin2cpg: deduplicate types for Java interop

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeInferenceTests.scala
Fixes https://github.com/joernio/joern/issues/2017
The unit test removed is wrong, so safe to remove.
=> Remove unique javasrc alloc signatures

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala
This fixes a bug in `deduplicate`: we were not taking `result.sink` into account when deduplicating flows, leading to inconsistent number of flows when the input to `deduplicate` is calculated in parallel. One would assume that `result.sink` and the last element on the `path` are always the same, but that seems to not be the case. We should look into that as well.
=> Take into account `sink` in deduplication

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MethodParameterTests.scala
Added a check for if the parameter type is primitive and, if so, will set the eval strat to BY_VALUE
=> javasrc2cpg: Pass-by-value for primitive parameters

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
We need the type ref to calculate scopes / capture bindings correctly. Now it is stored under the parent block and `.parentExpression` etc. do work correctly.
=> jssrc2cpg: add AST edge for type ref for classes

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/ExtendedCfgNode.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskCreator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskSolver.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/MethodReturnTests.scala
The tests illustrate the problem quite nicely: because `METHOD_RETURN` is also the exit node, we ended up overtainting in the past. We revert to this behavior for external methods and method stubs. For internal methods, we traverse to RETURN nodes instead.
=> Fix interprocedural tracking via METHOD_RETURN nodes

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/BuiltinTypesPass.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/BuiltinTypesPassTest.scala
When built-in types are created, they are set as external, to be consistent with other frontends.
Resolves #2079
=> [jssrc2cpg] Built-in Types Now Set as External Types

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeDeclTests.scala
Fixes the issue discovered in https://github.com/joernio/joern/issues/2041
Constructors were missing any modifiers at all, so just adds that in general.
=> Add javasrc constructor modifiers

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
It is relative for project files but absolute for system header files.
=> c2cpg: fix relative/absolute path handling

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/codedumper/CodeDumper.scala
For methods generated by the MethodStubCreator (e.g., for operators) we end up with artificial method nodes in the `<global>` namespace and file but without line numbers. The fake filename (`<global>`) would crash the filename calculation here. So I moved that piece of code where it is guarded by lineNumber existence.
=> CodeDumper: safer filename calculation

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskCreator.scala
This is a minor optimization: if we reach an output argument that is a literal, then we don't need to create a task to further explore because literals can't be sinks.
=> Do not create new tasks for literal sinks

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala
The frontend did bind constructor methods to the type which the
constructors are supposed to create. This was wrong.
This caused the closed source data flow tracker to be unable to
resolve the `start` call in this example:
```
class BrowserRunner {
constructor() {
this._foo = null; // if this is missing, resolution also fails with js2cpg
}
​
start() {
}
}
​
new BrowserRunner().start();
```
=> Fix Javascript Source frontend constructor binding.

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/ReachingDefTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/macros/MacroHandlingTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/MethodTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/CallLinkerPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ConstClosurePassTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/RequirePassTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/types/TSTypesTest.scala
From the Scala 3 compiler:
* fixed explicit types for List deconstruction in tests
* fixed local return (c2cpg)
Also:
* fixed JS test strings to be consistent
=> jssrc2cpg / c2cpg: fixed warnings from Scala 3 compiler

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/ResultTable.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskCreator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskSolver.scala, dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/queryengine/ResultTableTests.scala
I cleaned up the data flow engine code in preparation for bringing in of a stable version of the fingerprinting change I previously had to revert. This PR brings the following changes:
- ReachableByTask and ReachableByResult have been simplified significantly
- `TaskFingerprint` is introduced. The idea is that when two tasks have the same `TaskFingerprint`, then their results should also be the same, making it possible to cache results.
- ResultTable now uses `TaskFingerprint` as a key. This will serve as our cache.
- The deduplication mechanism was not deterministic when facing multiple flows of the same length with the same node ids. Fixed that as well.
- `createFromTable` did not take into account `callSiteStack` on lookup, fixed that as well.
=> Refactoring of data flow engine and minor fixes

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala
Instead of keeping results in a queue, keep them in a `ResultTable`. This is a step towards reusing of results via table lookups. I also fixed a minor bug in the deduplication, which lead to more flows for current master, and fewer with this change. With the deduplication routine in this PR, we get the same number of flows for both cases.
=> Write results into table

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/ExtendedCfgNode.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/ResultTable.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskCreator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskSolver.scala, dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/queryengine/ResultTableTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala
This brings back the caching that I introduced a month back in and needed to revert because of inconsistent results. With this change, we get much improved performance while generating the same number of flows, and  `(source,sink)` pairs over runs. I do still suspect some areas in the code that could lead to inconsistencies, which I will look into next. In particular, I can imagine problems for overlapping flows.
Notes:
* I reworked the deduplication in the process, and it is a lot more aggressive now, meaning, we are intentionally returning only one result per `(source,sink)` pair
* The result table seems to not always be exactly the same, but it may not need to be.
* The number of held tasks can vary. This may also be perfectly fine, but it is worth inspecting.
* We should now be able …
=> Improved caching

benchmarks/build.sbt, dataflowengineoss/build.sbt
These 2 builds are not consumed anywhere anymore with Java 8. Last occurrence is in js2cpg where I will remove it too.
This should also fix: https://github.com/joernio/joern/issues/2117
=> Remove Java 8 compat

joern-cli/frontends/pysrc2cpg/build.sbt, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Main.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2CpgOnFileSystem.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala
Reuse already existing components. Most importantly use the same option
parser library and provide common API via X2CpgFrontend trait.
=> Use X2CpgFrontend and X2CpgConfig in Pysrc frontend.

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/datastructures/CGlobal.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/HeaderAstCreationPassTests.scala
We stored sub ASTs from header files directly into the diffgraph when de-duplicating using the global cache. Now they are correctly stored where included.
This is for: https://github.com/ShiftLeftSecurity/product/issues/11354
=> c2cpg: fix dangling sub ASTs

console/src/main/scala/io/joern/console/cpgcreation/CCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CSharpCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/GhidraCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/GoCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JavaCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JavaSrcCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JsCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JsSrcCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/KotlinCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/LlvmCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/PhpCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, console/src/test/scala/io/joern/console/testing/ConsoleFixture.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/datastructures/CGlobal.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernSlice.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/TypeDeclTraversal.scala
Prior to this, we would not pass the Xmx (max heap) setting from joern to frontends.
Only a globally configured `JAVA_OPTS` would work, but most users would either configure
that specifically for joern (e.g. `JAVA_OPTS=-Xmx30g ./joern`) or use the `-J` flag,
e.g. `./joern -J-Xmx30g` - especially if they want to import large codebases. 
Now, we determine the maxMemory that the user configured joern with, and pass that to 
all JVM based frontends. Since the sum of joern and the frontend may exceed the physical
memory of the machine, we tell the user that they may want to exit joern and invoke the 
frontend themselves.  Determining the available max memory for a machine is tricky, so 
we'll keep it simple for now.
=> Xmx max heap memory handling for importing large codebases

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/nodemethods/ExpressionMethods.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/EdgeValidator.scala
- Added a special case where CFG nodes are in succession but are only so because they are arguments to the same parameter, not because the data flows across nodes
Fixes #2120
=> [dataflowengineoss]: Fix Cross-Tainting of Arguments to Semantic Defined Parameter

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstNodeBuilder.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/datastructures/CGlobal.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/HeaderContentPass.scala, joern-cli/frontends/c2cpg/src/main/scala/org/eclipse/cdt/internal/core/parser/scanner/MacroArgumentExtractor.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/MetaDataTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/ClassTypeTests.scala
Put some helper node creation functions into AstNodeBuilder which simplifies AST node creation a lot. The Scala Int -> Java Integer mapping looks strange but is required as the NewNode interface requires Java Integers there. Switching to Scala Int also fixes some compiler warnings for c2cpg (type was inferred to Any).
=> c2cpg: refactorings and clean-ups

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/Main.scala
`--exclude` wasn't working for relative input paths because it would compare paths like `/foo/./bar` against a normalized excluded path `/foo/bar`
=> jssrc: normalize input path to fix --exclude

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala
* order of expression list elements was missing
* method stubs need an outgoing AST edge to a block (otherwise we end up with a schema violation reported when calling e.g., `cpg.method.block.l`)
=> c2cpg: fixes for method stubs / expression lists

console/src/main/scala/io/joern/console/cpgcreation/CCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CSharpCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/GhidraCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/GoCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JavaCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JavaSrcCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JsCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JsSrcCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/KotlinCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/LlvmCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/PhpCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, project/build.properties
previously it would return `Option[String]` which contained the executed 
command - that didn't make much sense
=> runShellCommand: return `Try[Unit]`

console/src/main/scala/io/joern/console/cpgcreation/JavaCpgGenerator.scala
prior to this, it would try to invoke it like a cpg generator, and e.g.
append `-J-Xmx`, which dex2jar doesn't handle, and unfortunately errors
hard
=> fix dex2jar invocation

joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/DynamicCallGraphTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/callgraph/DynamicCallLinker.scala
- If no methods are in the list of callees, attempts to first resolve the result by inspecting the superclass method names and signatures
- The method full name still makes use of the derived full name
Resolves #2142
=> [x2cpg]: DynamicCallLinker Excludes Non-Overriden Inheritted Methods

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/macros/MacroHandlingTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/MixedCfgCreationPassTest.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala
Nested macro expansions with blocks contained multiple nested blocks which led to broken CFGs. We fixed that by checking for blocks in asChildOfMacroCall.
Also: blocks are not allowed as CFG nodes within logical operators.
=> c2cpg: fixed macro expansion and CFG generation with nested blocks

.gitignore, joern-cli/frontends/jssrc2cpg/build.sbt
* this is a new attempt at https://github.com/joernio/joern/pull/1460
* that one worked locally, but failed on gh actions
* jssrc2cpg is by far the longest subproject to run tests: 110s before this change, 20s now
=> speed up build: run jssrc tests in parallel (i.e. do not fork)

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskSolver.scala
Converted started list to a hash set for better lookup performance.
Snap task processing for snap cpg ( 385 MB ) comes down from 20-30 mins to 10 seconds on my machine.
No impact on smaller repositories since task processing is anyway in seconds.
Verified flow counts for `opencrx`, `privado-accounts-api` and `sms-backup-plus` CPGs by comparing with master.
Compared paths for `privado-accounts-api` generated by `master` and this branch and verified that there is no difference.
=> Hash optimisation

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/DependencyAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/MixedAstCreationPassTest.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/VueJsDomAstCreationPassTest.scala
Imports of the form `import {foo, bar} from 'abc.js'` currently result in the creation of one import node for `foo`, and one import node for `bar`, and for both of them, `importedEntity` is `'abc.js'`, while really, it should be `'abc.js:foo'` and `abc.js:bar` respectively, where I've chosen `:` as a separator for now.
=> jssrc2cpg: fix for `IMPORT` nodes

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/callgraph/DynamicCallLinker.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/impl/PythonTypeRecovery.scala
- Abstracted the computational unit type
- Removed the need for a global table (for now)
- All recovery is within a computational unit scope, as per current capabilities
- Added `.toIndexedSeq` under `DynamicCallLinker` as per compiler suggestions
=> [XTypeRecovery] Simplify the base class

console/build.sbt, console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonNaiveCallLinker.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeHintCallLinker.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/impl/PythonTypeRecovery.scala
- Added entrypoint to base class for pre-populating
- Pre-populated symbol table with built-in function names
- Moved Python passes from `x2cpg` to `pysrc2cpg`
Resolves #2207
=> [pysrc2cpg] Built-in Function Call `MethodFullName`

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
- Moved symbol table and key variants to their own class `SymbolTable.scala`
- Created a notion of iterating multiple times over the type recovery to continue to avoid a fixed-point algorithm while achieving inter-procedural type propagation
- Tested that primitive and object instance types are successfully propagated using 2 iterations with no aliasing
=> [pysrc2cpg] Interprocedural Field Type Recovery

build.sbt, joern-cli/build.sbt, joern-cli/frontends/c2cpg/build.sbt, joern-cli/frontends/ghidra2cpg/build.sbt, joern-cli/frontends/javasrc2cpg/build.sbt, joern-cli/frontends/jimple2cpg/build.sbt, joern-cli/frontends/jssrc2cpg/build.sbt, joern-cli/frontends/kotlin2cpg/build.sbt, joern-cli/frontends/php2cpg/build.sbt, joern-cli/frontends/pysrc2cpg/build.sbt, joern-cli/frontends/x2cpg/build.sbt, project/Versions.scala
We declare slf4j-api as a regular dependency, since most logging
libraries have an implementation for it, and it is considered
a lowest common denominator for logging.
We choose log4j as the logging provider for this build, i.e. for tests
and `sbt stage`. `Optional` means "not transitive", but still included
in "stage/lib". I.e. downstream builds do not inherit it and can/must
make their own choices.
=> fix logging dependencies setup

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
When assigning a type to a member that has an invisible field load:
- Either refer to the CPG, in hopes that there is a type stub with that member's information
- Or make use of a dummy value, so that at least the member's parent type is noted in the type path
=> [pysrc2cpg] Populate Member Types with CPG Info or Dummy Values

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/CallCpgTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/MethodStubCreator.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala
- Moved `MethodStubPass` node creation to an object class
- Invoked the `MethodStubPass` creation functions in `XTypeHintCallLinker` for methods not currently in the CPG
- Linked recovered method call full names to their stubbed types
=> [x|pysrc]2cpg: Methods Stubs for Recovered Method Calls

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeHintCallLinker.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala
* Method return values from external libraries now have dummy values so that their calls can be matched with regex
* Added a safety check on method name building for method stub 
* Made sure to check imported type references that use a collection of imports
=> PythonTypeRecovery: Dummy Return from External Libraries 

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Util.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/OperatorTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/AstPropertiesUtil.scala
This moves 2 duplicated methods out of PHP/Javasrc's frontends, viz. `rootCode` and `rootType`. 
It also fixes a very minor bug in PHP's `isset` `code` property due to an unbalanced parenthesis.
Aside: I'm not sure I've written fully idiomatic Scala (it's been a few years since the last time) here. I look forward for any kind of improvement suggestions you see fit.
=> [x2cpg] Refactor some duplicated `root{Code,Type}` methods

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ContextStack.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala
- Used a much more defensive check for `ContextStack.isClassContext`
- Fixed `.charAt(0)` call for empty call names
=> [pysrc2cpg] Fixed Crashes on Import Code

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
- Load `self` field assignments into the global table
- Approximate field references by name (TODO: match objects with their type decl)
- Using dummy <indexAccess> for dict access types (TODO: model dict memory during analysis)
=> [pysrc2cpg] Handle `self` Property Type Recovery

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2Cpg.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/MethodStubCreator.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
- Made changes to recover the types based on the "type<body>" style syntax to improve linkage
- Added value for MetaData("root") in pysrc2cpg
- Check if the method belongs to an internal file to make the `isExternal=false` if a stub ultimately needs to be created due to incorrect method full name
=> pysrc2cpg: Adjust Recovered Method and Type Names

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
- Added a temporary solution for deep field access. TODO: Highlights the need for a recursive solution
- Added a dummy path for the method full name
=> pysrc2cpg: Recover Type for 3-Depth Call Access

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
- Direct imports on modules were interpreted as function pointers, this change allows them to be interpreted as modules or fields
=> pysrc2cpg: Recover Call from Imported Module

joern-cli/frontends/jssrc2cpg/build.sbt
fixes:
```
[error] java.lang.NumberFormatException: For input string: "unknown"
[error]         at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[error]         at java.base/java.lang.Integer.parseInt(Integer.java:668)
[error]         at java.base/java.lang.Integer.valueOf(Integer.java:999)
[error]         at versionsort.VersionHelper.compare(VersionHelper.java:32)
[error]         at $c486a84e185d715fb73f$.hasCompatibleAstGenVersion(build.sbt:92)
```
=> handle old astgen versions that report `unknown` as their version

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ControlStructureTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeTests.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForPrimitivesCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTemplateDomCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/KtPsiToAst.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ControlStructureTests.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CallTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala
As I tried to use a single utility method for the creation of call ASTs across frontends, I noticed that there were in fact conflicting assumptions about how a call site should look. In particular, the function `createCallAst` in the javascript frontend and the `callAst` function used in the Java, PHP, and C/C++ frontends differ in that the former allows both a base and a receiver to be specified, while the later only supports a receiver. Moreover, in the Javascript frontend, the receiver always has an `argumentIndex` of `-1`, while in the other frontends, it has an `argumentIndex` of 0 and is treated as a parameter (sometimes).
After taking a more detailed look into the difference between base and receiver, it seemed that what we called "receiver" in Java is just the instance parameter, …
=> Consistent callAST creation across frontends

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/CallCpgTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/AstNodeMethods.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/generalizations/AstNodeTraversal.scala
- Re-implemented `XTypeRecovery` using visitor pattern. This reduces the `PythonTypeRecovery` file by 50% and increases the language agnostic `XTypeRecovery` file by 100%.
- `XTypeRecovery` can now support the new `Import` node while leaving room to override the `Call` version as still used in Python.
- This change improves the soundness of the type recovery and, as such, resulted in some modifications required for some test cases.
- This change also promotes re-use of code and easy diagnostics using a logger with debugging locators. Debug level used is `WARN`. 
Breaking changes:
- Built-in types are now prefixed with `__builtin` which is what the front-end appears to use.
- `__builtin.None` is now supported, which means potentially more types may be suggested if variables were …
=> XTypeRecovery: Clean Up With Visitor-Pattern & Support New Imports

joern-cli/frontends/pysrc2cpg/pythonGrammar.jj
We now include a bunch more of the common european special characters.
This is fix 1 of 2 for: https://github.com/joernio/joern/issues/2269
=> Extend letter parser token definition.

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/ClassCpgTests.scala
In cases were the "self" parameter is not explicitly given in a class
__init__ function we did crash because we assumed that at least one
positional parameter is always defined. This is now fixed.
This is fix 2 of 2 for: https://github.com/joernio/joern/issues/2269
=> Fix meta class call handler generation.

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/ExtendedCfgNode.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/Path.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/nodemethods/ExtendedCfgNodeMethods.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskSolver.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/package.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ContextStack.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/MemberCpgTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/AstNodeMethods.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/CfgNodeMethods.scala
Previously, we were able to track flows from class variables (Python's version of static members), but not from instance variables. This PR fixes that. Previously, these flows also did not start in the member variables, which they now do.
=> Python: more fixes for member variable tracking

build.sbt, console/src/main/scala/io/joern/console/BridgeBase.scala, console/src/main/scala/io/joern/console/PPrinter.scala, console/src/test/scala/io/joern/console/PPrinterTest.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/Steps.scala
Depends on overflowdb-codegen changes... Not sure about the exact history,
but I guess back in the days we simply didn't notice that
`Product.productElementName` exists, and therefor added
`StoredNode.productElementLabel` and tweaked the pretty printer in joern.
This can be done much simpler...
Also: some more tests
=> simplify pretty printing: Product.productElementName ftw

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
- Handle the `setType*` case where a call is being called directly off an import within the parameter of another call
=> XTypeRecovery: Handle Call within Call Directly off Import

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/MethodStubCreator.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/callgraph/DynamicCallLinker.scala
This will link the stubbed TYPE_DECL to the stubbed METHOD node by an AST edge, if present.
The aim of this change will allow us to traverse the type node from a method stub. e.g.
```scala
cpg.call.callee(NoResolve).definingTypeDecl.fullName.l
```
Contributes to #2224
=> MethodStubCreator: Link Method to TypeDecl if Present

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/MemberTests.scala
Previously, we were only able to track initialized members, e.g., tracking from source to sink in the following code would fail:
```
class Foo {
int source;
public void foo() {
sink(source);
}
}
```
while `int source = 1;` would work.
=> Fix tracking of uninitialized member variables

joern-cli/build.sbt, joern-cli/src/main/scala/io/joern/joerncli/JoernSlice.scala, joern-cli/src/main/scala/io/joern/joerncli/slicing/DataFlowSlicing.scala, joern-cli/src/main/scala/io/joern/joerncli/slicing/UsageSlicing.scala, joern-cli/src/main/scala/io/joern/joerncli/slicing/package.scala
- Refactored `joern-slice` to support multiple "modes"
- The old version is DataFlow mode. This now produces slices for all calls in a given file.
- The new mode is Usage mode. This extracts calls that identifiers for a declaration are callers or arguments for.
- Separated two modes under `slicing` package.
- Added circe for JSON serialization of usage slices.
New help screen:
```
Extract intra-procedural slices from the CPG.
Usage: joern-slice [options] [cpg]
--help
cpg                      input CPG file name - defaults to `cpg.bin`
-o, --out <value>        the output file to write slices to - defaults to `slices`. The file is suffixed based on the mode.
-m, --mode <value>       the kind of slicing to perform - defaults to `DataFlow`. Options: [DataFlow, Usages]
--source-file <value> …
```
=> JoernSlice: Usage Slicing

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Rename `computationUnit` to `compilationUnit`
* Shorten extraction of possible callee names
=> Mild refactorings for PythonTypeRecovery

.github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/upgrade-deps.yml
the newly added cache-action seems to work:
https://github.com/joernio/joern/actions/runs/4244917158/jobs/7379717333
```
coursier cache keys:
coursier-release-4cbd9c71ea3856573ad5d756bdf282076d91db81
coursier-release-
coursier-
Received 75497472 of 682483443 (11.1%), 72.0 MBs/sec
Received 285212672 of 682483443 (41.8%), 136.0 MBs/sec
Received 494927872 of 682483443 (72.5%), 157.3 MBs/sec
Received 674094835 of 682483443 (98.8%), 160.6 MBs/sec
Received 682483443 of 682483443 (100.0%), 143.5 MBs/sec
Cache Size: ~651 MB (682483443 B)
/usr/bin/tar -xf /home/runner/work/_temp/f87eb0a6-de24-4145-a8a4-8e3dd48e919b/cache.tgz -P -C /home/runner/work/joern/joern -z
Cache restored successfully
coursier cache miss, fell back on coursier-release-41b508109eb9fd2c21f2db507f6c286db11483fc.
coursier cache …
```
=> gh actions: disable cache from setup-java plugin that doesn't to work

.scala-steward.conf
As per comment in project/Versions.scala:
Dont upgrade antlr to 4.10 or above since those versions require java 11 or higher which
causes problems upstreams.
=> don't upgrade antlr

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ContextStack.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/VariableReferencingCpgTests.scala
* Extract the earliest identifier node line and column number info and add this to the local node
=> pysrc2cpg: Local Node Line & Column Numbers

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
Previously, `import foo from bar` was always interpreted to mean that an object called `bar` is imported from `foo.py`, while it could also mean that `bar.py` is imported from the module (directory) `foo`. With this PR, we attempt to detect whether that is is the case and fix the `methodFullName` generation accordingly.
=> Fix handling of python imports from directories

console/src/main/scala/io/joern/console/Console.scala
Run language specific passes such as 'PythonTypeHintCallLinker' for importCpg just like it behaves for importCode.
=> Fix missing passes if running with 'importCpg'

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Added another import condition that was missing a kind of import
* Added crude "addedNode" tracker to type recovery
* Using the type recovery, will determine if the field access corresponds to an internal method and will add a method ref to the parent node
Example of AST with new method ref for the test case in this PR:
=> pysrc2cpg: Determine if a Field Access is a Method Ref

console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/DynamicTypeHintFullNamePass.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/DynamicTypeHintFullNamePassTests.scala
Previously, the dynamicTypeHintFullName wasn't a full name but just the symbol the parser picked up for the type hint. This new pass takes into account imports to resolve the type's full name.
=> pysrc2cpg: expand dynamic type hints based on imports

joern-cli/build.sbt, joern-cli/frontends/c2cpg/build.sbt
After upgrading log4j to 2.20.0 we got an OSGI error when
invoking *any* frontend, also logging didn't work.
This fixes this by removing c2cpg from the joern-cli classpath -
we invoke it via subprocess anyway, so there's really no reason to have it in the
classpath. c2cpg brings a lot of baggage from the OSGI world which
we'd rather avoid.
To fix the error for c2cpg we downgrade it's log4j version to 2.19.0.
Stacktrace:
```
Unknown error checking OSGI environment.
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:4 …
```
=> fix log4j/osgi error and massively trim classpath

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Main.scala
This commit address two issues:
1. While loading Android apk with soot's `src_prec_apk_c_j`, it takes more time than `src_prec_apk`. In my experiment, It takes about 70s to process a modern (large, ~ 120MB, with ~ 100,000 classes) apk in `Scene.v().loadNecessaryClasses()`, however it only takes abount 7s, which is 10x faster, to process the same file with `src_prec_apk`. So I add an option to accept the path to `android.jar` to make it work.
2. When Soot creates JimpleBody for some methods, it may throws exception `StmtSwitch: type of throw argument is not a RefType`. This problem is discussed in https://github.com/soot-oss/soot/issues/1256, but AFAIK it's not yet fixed, so the workaround is to disable `jb.use-original-names` when processing apk, since in most cases there're no original …
=> jimple2cpg: improvement for large Android apk loading

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/package.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/generalizations/DeclarationTraversal.scala
The nodes and edges of `ClosureBinding` and `CAPTURE` hold the information containing which parent identifiers are associated with which child identifiers in children scopes.
* Added `DeclarationTraversal` to centralize the ability to use `CAPTURE` and `CLOSURE_BINDING` properties
* Leverage these properties instead of naively traversing child methods
=> Fix: Create Sources from ClosureBindings over MethodRefs

joern-cli/src/main/scala/io/joern/joerncli/slicing/UsageSlicing.scala, joern-cli/src/test/resources/testcode/jssrc-slice/main.js
* Using `capturedByMethodRef` to find related local vars in other scopes
* Ordering calls in the slice by line/col number
=> JoernSlice: Extract Usage Slice Across Closure Bounds

console/src/main/scala/io/joern/console/cpgcreation/CCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CSharpCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CpgGeneratorFactory.scala, console/src/main/scala/io/joern/console/cpgcreation/GhidraCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/GoCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala, console/src/main/scala/io/joern/console/cpgcreation/JavaCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JavaSrcCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JsCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JsSrcCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/KotlinCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/LlvmCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/PhpCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, console/src/test/scala/io/joern/console/testing/ConsoleFixture.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernParse.scala
without this it's very hard to debug a problem in the test or build
setup, because we simply threw away the failure case `Try:toOption`
=> if cpggenerator.generate fails: keep the exception, so we can report it

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ContextStack.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitorHelpers.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Identify when the entity imported is a variable
* Find associated types with the identifier being imported and add this to the symbol table
* Detect module-level variables that could be exported and set them as members under the module-type
* Making use of member during import
* Fixed type recovery from imported variable without full refactoring
* Removed useless visitMember method
=> PythonTypeRecovery: Importing Variable from File 

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala
* Modified symbol table key to acknowledge a receiver is one is present
=> PythonTypeRecovery: Distinguish Call Alias by Receiver

console/src/main/scala/io/joern/console/cpgcreation/CCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CSharpCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/CpgGeneratorFactory.scala, console/src/main/scala/io/joern/console/cpgcreation/GhidraCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/GoCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala, console/src/main/scala/io/joern/console/cpgcreation/JavaCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JavaSrcCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JsCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/JsSrcCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/KotlinCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/LlvmCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/PhpCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernParse.scala
We aren't using the `namespaces` parameter inside overloaded methods of `generate`, it seems. It may be that it is still used somewhere in Ocular when calling `java2cpg`, but then I would propose that we remove that.
=> Remove `namespaces` from `CpgGenerator::generate`

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/DynamicTypeHintFullNamePass.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Implemented `prepopulateSymbolTable` for nodes that already contain type hints
* Fixed issue where type hint full name being replaced with full import path and not alias
=> pysrc2cpg: Fix Wrong Type Hint Path when Aliased

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/ClassCpgTests.scala
So far the full name for the instance class type of:
```
class Foo:
pass
```
was `fileName.py:<module>.Foo.Foo`. This is now changed to:
`fileName.py:<module>.Foo`.
C.f.: https://github.com/joernio/joern/issues/2225
=> Change python instance class type full names.

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Handling of .import use case 
* Unit tests for the given use case
--------
student/urls.py 
--------
```
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from .import views
urlpatterns = [
url(r'^allPage/$', views.all_page)
]
```
--------
student/views.py
--------
```
def all_page(request):
print("All pages")
```
The handling of `.import` wasn't there. This code change will handle the given use case. Added respective unit tests as well.
=> pysrc2cpg: Handling for .import use case 

build.sbt
We have an implicit lower boundary of jdk11 due to e.g. c2cpg, and usage
of more modern JDK API, so we shouldn't go lower than that IMO.
=> configure jdk11 as target platform

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyLexer.g4, joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
Many of those pesky whitespaces can be removed from the grammar spec with some tricks, but until this is "battle-tested" I find it more useful to have them so that profiling is straightforward.
Also fixes a couple of issues in the lexer that were only found when developing the parser.
=> [rubysrc2cpg] Adding a skeleton parser

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Resolve relative imports that then go into child directories
* Resolve relative import method refs if only function pointer is imported
* Improve testing for method ref full names
cc @pandurangpatil
=> PythonTypeRecovery: Handle relative imports of call only

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefProblem.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/utils/MemberAccess.scala
Previously, when using `x` as a source, we would not return flows from `x[i]` or `x->foo`. We fix this by translating identifiers into all field accesses and index accesses on those identifiers, plus the identifier itself.
=> Fix for container handling

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/generalizations/DeclarationTraversal.scala
Fix obvious copy-paste related bug.
cc @khemrajrathore
=> DeclarationTraversal: Fixed `capturedByTypeRef` returning `MethodRef`

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
* Override identifier -> call if the call looks like a Python decorator
* Traverse decorator arguments to pick up method ref and resolve method symbol
=> PythonTypeRecovery: Navigate Python Decorators

.github/workflows/pr.yml, .github/workflows/release.yml, README.md, build.sbt, joern-cli/src/universal/schema-extender/project/build.properties
Core here is dropping the scalac flag `--target`. Previously I
thought that JDK19 doesn't support `--release=11`, but turns out they
only [dropped support for JDK7 in JDK20](https://bugs.openjdk.org/browse/JDK-8173605), so we can leave this as is for
now. `--target` is deprecated anyway, so this seems to be the best way
forward.
=> upgrade to JDK19

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/package.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
Improved the handling of global variables by moving some of the logic from `SourceToStartingPoints` into DDG creation. In particular, we now create `REACHING_DEF` edges from identifiers/parameters to first usages in methods that capture them.
=> Fix handling of global variables

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/CfgNodeMethods.scala
Since `jssrc2cpg` files are `:program` methods, if a type is dynamically declared under this, we have a TYPE_DECL<-AST-METHOD relationship.
If there is a decorator on top of the TYPE_DECL, children of the type decl's annotation have a CHILD<-CONTAINS-TYPE_DECL relationship. CHILD<-CONTAINS-TYPE_DECL is marked initially as invalid by CfgNodeMethods.walkUpContains but in this context it is valid.
Resolves #2407
=> CfgNodeMethods: Handle TypeDecl Before Method during `.method` step

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/KtPsiToAst.scala
=> kotlin2cpg: remove unnessary `Ast`-wrap

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeHintCallLinker.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala
* Fix an issue where duplicate method stubs would be generated
* Separate linkCall logic for fine-grained overrides
=> XTypeHintCallLinker: Clean-Up and Duplicate MethodStub Fix

joern-cli/frontends/pysrc2cpg/pythonGrammar.jj, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/memop/MemoryOperationCalculator.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pythonparser/AstPrinter.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pythonparser/AstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pythonparser/ast/Ast.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/PatternMatchingTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pythonparser/ParserTests.scala
Pattern matching was introduced by python 3.10 and is now supported by
our python parser.
The python frontend still emits UNKNOWN node for pattern match
statements. A fine granular CPG representation will follow soon in a
separate PR.
=> Implement python parser support for pattern matching.

console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/JsSrc2Cpg.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Write to CPG each iteration of the type recovery pass to get rid of global table. This should save some memory.
* Fix some bugs where `<var>` placeholder keys would get in the final output for type hints
* Created a wrapper pass `XTypeRecoveryPass` that can run multiple propagation passes internally
* Holding member nodes until the end to make sure the updates don't overwrite one another
* Fixed issue in `pysrc2cpg` where `Member` nodes would have `Seq("")` under `dynamicTypeHintFullName`
Next up is to optimize the cost per iteration given some heuristics and early stopping.
=> XTypeRecoveryPass: Replace Global Table by Writing to CPG

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/KtPsiToAst.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeInfoProvider.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/DestructuringTests.scala
Merged two fns – `astsForDestructuringDeclarationWithNonCtorCallRHS` and `astsForDestructuringDeclarationWithCtorRHS` – into one — `astsForDestructuringDeclarationWithRHS`.
=> kotlin2cpg: remove duplication from `KtPsiToAst`

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/parser/BabelJsonParser.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/parser/JsValueVisitor.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
We handle the NumberFormatException in a custom visitor for `ujson.transform` now.
Fixes: https://github.com/joernio/joern/issues/2440
=> jssrc2cpg: fix handling of long NumericLiterals

console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/JsSrc2Cpg.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Identified that `isField` as an expensive line of code
* Resorting to memoization to reduce graph reads
* First check if types are already persisted in node before writing to avoid loading unnecessary diff operations
* Made recovery config more concise with a single object
* Only visit literal assignments on first iteration, as this will already be on the CPG on iteration > 1
=> XTypeRecovery: Improve Type Recovery Bottleneck

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala
Since the regex is basically checking if the code contains the name of an identifier, we use the "contains" method instead of regex.
Resolves #2439
=> JavaScriptTypeRecovery: Fix Regex Entering isField Check

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/NamespaceTests.scala
Only specific types of statements were expected for class bodies, but when that code was shared with namespace bodies which can contain any statement, the fallback case wasn't cleaned up. The ASTs for these statements were created anyways, so this changes nothing about the functionality of the frontend while removing the warning for perfectly valid code.
=> Remove warning about handled unhandled php statements in namespace bodies

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/DynamicTypeHintFullNamePass.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Found `DynamicTypeHintFullNamePass` directly injected code into regex, made a note here to handle this better but, for now, simply using a `Try`
* Implemented early stopping if no changes were detected from previous iteration
* Found that whole graph traversals were being done where partial graph traversals were intended when propagating method and parameter types
Resolves #2458
=> XTypeRecovery: Major Performance Improvements and Regex Handling 

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernExport.scala
Scala3 doesn't support the 'magic' DelayedInit trait which is used by
`extends App` - the recommended way for cross compilation is to use
regular `def main(args: Array[String])` methods instead.
See https://docs.scala-lang.org/scala3/book/methods-main-methods.html
=> scala3 prereq: rewrite `extends App` to `def main`

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/MemberCpgTests.scala
- __init__ fakemethod for typeDecl will work as is
- Added couple of new memberNode() fn as overloaded fn to use LineAndColumn param
- Updated all instances & passing LineAndColumn param
=> PySrc2Cpg: Add Line & Column Info to `TypeDecl` Member Functions

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Obtain type hints directly from CPG instead of symbol table
* Removed parameter propagation as the type propagation seems to already utilize this
=> XTypeRecovery: Get Method & Parameter Type Hints Directly from CPG

console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
There were a few bugs that prohibited us from traversing from constructor invocations to the corresponding classes. This can now be achieved as illustrated in the tests provided in this PR. In short, `.callee.typeDecl` brings you from the constructor invocation to the type declaration.
=> [pysrc2cpg] allow traversing from constructor calls to type declarations

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/DynamicTypeHintFullNamePass.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/DynamicTypeHintFullNamePassTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
* Attempt to find instances of `TypeDecl` nodes that match the type hint path
* This fixes instances of partial paths that do not reflect the fully qualified name
This degrades performance slightly
=> PythonTypeRecovery: Filter Type Hints by Existing Types

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/PhpBuiltins.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MemberTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MethodTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/OperatorTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala
- Rename php constructors from `<init>` to `__construct`  to match PHP naming
- Remove `__builtin` prefix from call names since this didn't actually add any relevant information
- Add filename to method nodes (so that `cpg.file.method.l` returns methods defined in the file)
=> Remove builtin prefix from call names and add fileName to method nodes

Dockerfile
* alpine's latest jdk is 17 - that's ok
* stick to a fixed alpine tag to avoid surprises in the future
* fixes https://github.com/joernio/joern/issues/2479
=> fix dockerfile: use jdk17

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala
Fixed instances where a dot import e.g. `.foo` would result in a recovered type reading as `/foo`.
=> PythonTypeRecovery: Fix leading slash in relative import

joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsDecoratorAstCreationPassTest.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/ExpressionMethods.scala
Fixes crashes in CS passes with jssrc2cpg.
See: https://github.com/ShiftLeftSecurity/codescience/pull/6921
=> Handle AnnotationParameterAssign in .parentExpression

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/DynamicTypeHintFullNamePassTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
At the end of propagation, regarding method parameters and returns, if there is only 1 type hint then this is set to the `typeFullName` property and `dynamicTypeHintFullName` is cleared.
=> XTypeRecovery: Param & Return Type Info under `TypeFullName`

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/memop/AstNodeToMemoryOperationMap.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/memop/MemoryOperation.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/MemberCpgTests.scala
* Added `toString` overrides to make memory operations easier to debug
* Added the condition that only identifiers under classes with `STORE` operations become members
Resolves #2498
=> pysrc2cpg: Fix RHS of Class Variable becoming Members

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/Main.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
If c2cpg was invoked with a relative path to the input folder we kept it that way. That broke absolute to relative (and vice versa) path conversion later on ultimately resulting in absolute paths for CPG filenames.
=> c2cpg: fixed handling of relative paths as input CLI argument

console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala, console/src/main/scala/io/joern/console/cpgcreation/PyCpgGenerator.scala, console/src/main/scala/io/joern/console/cpgcreation/package.scala
CPGs from py2cpg already has types resolved, so we don't want to run any of the type inference stuff meant for pythonsrc when importing it's cpgs in joern (or more likely ocular)
=> add a PyCpgGenerator that does not run pythonsrc passes

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ImportTests.scala
To conform to the recent standard of using `Import` nodes, replaced the import identifier with the import node.
=> javasrc2cpg: Use `ImportNode` to represent imports

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/CfgNodeMethods.scala
For Typescript, types (TypeDecls) may be declared in namespaces which we represent as NamespaceBlocks. To get to the method they are contained in we need to use the in-AST-edges.
Addresses: https://github.com/joernio/joern/issues/2512
=> Added support for NamespaceBlock used in jssrc2cpg for TS

joern-cli/frontends/php2cpg/src/main/resources/php.ini, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Main.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
This PR adds a custom `php.ini` file to use when running php-parser. This is to avoid potentially difficult-to-debug errors due to system default or configuration differences, but can be overridden if necessary.
The approach of including it as a resource and then creating a temp php.ini file isn't elegant, but it seems to be a decent approach for ease of distribution.
=> Add php.ini file to avoid unexpected system-dependent behaviour when running php-parser

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/JavaTypeHintCallLinker.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/JavaTypeRecoveryPass.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeInferenceTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeHintCallLinker.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* This aids the current type recovery by helping propagate types across boundaries and having optional dummy types
* Fixed issue where `Call(typeFullName)` was being used to hold the type of the call base/receiver instead of return value.
* Fixed assumption on `PythonTypeHintCallLinker` where if there were non-dummy types it would pick the first one instead of checking if there is exactly one before setting it to `methodFullName`
=> JavaTypeRecoveryPass: Introducing `XTypeRecoveryPass` for Java

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala
instead of _repeat_ which might cause issues on older JDKs
=> kotlin2cpg: use StringOps in single spot

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/layers/dataflows/OssDataFlow.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefPass.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/semanticsloader/Parser.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
* Added an API to enable regex defined semantic full names
* Involves preloading all method full names that match these into a matching map to avoid expensive regex calls during query time
* Added Python tests to illustrate the usefulness during type recovery
* Added API to add extra flows to `OssDataFlow`
=> dataflowengineoss: Regex Method Semantics

.github/workflows/upgrade-deps.yml, joern-cli/frontends/php2cpg/README.md
cleanup after https://github.com/joernio/joern/pull/2506 as explained in https://github.com/joernio/joern/pull/2506#issuecomment-1517319585
=> php2cpg/bin/installdeps.sh doesn't exist any longer - don't call it

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/SourceFiles.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/codedumper/CodeDumper.scala
If c2cpg is called directly on a file (and not a folder containing C/C++ files) the toAbsolutePath / code dump file name logic broke.
Fixes: https://github.com/joernio/joern/issues/2554
=> Fixed handling of absolute paths in CodeDumper and c2cpg

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Iterate through class inheritance and convert calls
* Assign calls to temp variable and set inheritance string seq to the name of the temp variable
* Type recovery resolves temp variable if found in symbol table
=> pysrc2cpg: Handle Classes Extending Call Return

build.sbt, joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesesTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyParserAbstractTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/StringTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/SymbolTests.scala
* Refactors and expands the previous unit-tests
* Adds `rubysrc2cpg` to `build.sbt` so that it (among other things) benefits from scalafmt
* Fixes missing whitespaces (WS) in the rule for arguments. Aside: this rule ought to be refactored in a future PR.
=> rubysrc2cpg: fixes missing WS the rule for arguments

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
If an identifier holds some kind of type-ref or type dummy value then an attempt to propagate this is made.
=> PythonTypeRecovery: Inheritance via Identifiers

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/JavaSrc2CpgTestContext.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/SemanticTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaDataflowFixture.scala
This extended the test suite to add custom semantic flows as said in https://github.com/joernio/joern/pull/2514.
But I can't managed to re-open the closed PR, so I just create a new one.
=> javasrc2cpg: Update JavaDataflowFixture to accept extra flows

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesesTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
* Fixes a NPE in AstPrinter when `context.children` is null (meaning it's empty)
* Adds a missing WS token when parsing default parameter values
* Adds a missing trailing COMMA when parsing invocation parameters (allowing for invocations such as `foo(1,)`.)
=> RubyParser: support for trailing commas and optional parameters

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ConstClosurePass.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ConstClosurePassTests.scala
Extended ConstClosurePass to support `export.foo = <closure>` style naming to use `foo`.
=> jssrc2cpg: Name Closure After Export Assigned Name

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/parser/BabelAst.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsAstCreationPassTest.scala
* Ignores the [`satisfies` operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html). Would there be a suitable representation for it?
* Fixes #2588
=> jssrc2cpg: handles the `satisfies` operator

joern-cli/frontends/php2cpg/build.sbt, joern-cli/frontends/php2cpg/src/main/resources/log4j2.xml, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala
Before this PR, we were using the source archives attached to https://github.com/joernio/PHP-Parser releases and extracting those to set up PHP-parser. This makes setting up php-parser quite cumbersome, so I've added a release step to our PHP-Parser fork to pack the code into a phar which is fetched by the code in this PR. Also adds log4j config for php2cpg.
=> Use archived php-parser instead of source dir

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
`relativeName` and `fullName` in the `*.json` files returned by `astgen` are different between Linux and Windows systems. While `astgen` on Windows generates them correctly, on Linux the relative path is lost.
This is for: https://github.com/joernio/joern/issues/2579
=> jssrc2cpg: fix EJS file names

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/types/TSTypesTest.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Let `this` take on the name of the parent `:program` module if it is in the method stack and there are now dynamic types in scope
* Type recovery now handles `exports.*` not only `module.exports.*`
* Type recovery also handles the exporting of closures
* Fix in `XTypeRecovery` where assign statements in blocks were only being handled if they were exactly `<operator>.assignment`
=> jssrc2cpg: Handle Exported Closures

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernSlice.scala, joern-cli/src/main/scala/io/joern/joerncli/slicing/UsageSlicing.scala, joern-cli/src/test/scala/io/joern/joerncli/JoernSliceTests.scala
* Added option to exclude operator calls
* Fixed bug where `ARGUMENT` edge was added to an annotation when it is meant to be for calls
Resolves #2592
cc @pr0me
=> JoernSlice: Option to Exclude Operator Calls

console/build.sbt, console/src/main/scala/io/joern/console/cpgcreation/JavaSrcCpgGenerator.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala
Optional type recovery was running before base passes, mostly because it was placed under the main AST gen-side and not as a post-processing pass. This has now been fixed.
Resolves #2609
=> javasrc2cpg: Fix Placement of Type Recovery in CLI

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TypeRecoveryPassTests.scala
When a closure is defined directly on an export, there is some kind of currying to enable the export to be a function pointer. This means that the "callee" is a function itself, which leads to the "name" property to be the whole function body. This fix checks the callee for being a function and resolves it locally using the `functionNodeToNameAndFullName` mapping. e.g. of bug (where `name` and `methodFullName` is now the name and path of the function):
Example of this in the wild: https://github.com/PubMatic/OpenWrap/blob/10cdc6557eb401e82db8d184602deb6f073653d0/src_new/util.js#L173
```
Call(
id = 46774L,
argumentIndex = 2,
argumentName = None,
code = """(function() {
var count = 0;
return function() {
count++;
return count;
};
})()""",
columnNumber = Some(value = 32),
dispatchType = …
```
=> jssrc2cpg: Fix Call on Closure Definition Name

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/JsClassesAstCreationPassTest.scala
Class members that are dynamically initialized in a class constructor are added as class member now. This init assignment call itself stays in the constructor block.
Fixes: https://github.com/joernio/joern/issues/2612
=> jssrc2cpg: added support for dynamically declared members

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ConstClosurePass.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ConstClosurePassTests.scala
If a closure is assigned to a mutable variable, and it is effectively treated as a constant (i.e. no reassignments), then set the closure names to the target name.
=> jssrc2cpg: Closures Assigned to Mutable Var

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstNodeBuilder.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/HeaderContentPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstNodeBuilder.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/NodeBuilders.scala
The idea is to have two consistent ways of generating nodes:
1. The `AstNodeBuilder` trait which provides fns with signatures similar to: `aTypeOfNode(PROP1, PROP2, PROP3)`
2. The `NodeBuilders` object which provides fns with signatures similar to: `newATypeOfNode(PROP1, PROP2, PROP3, LINE, COLUMN)`
=> x2cpg: rename node creation fns

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/NodeBuilders.scala
This fixes a type related crash in a WIP closed-source pass.
=> Switch PHP types from empty to ANY and register them.

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala
Replace `*` with `+` to avoid false positives. The `*` means that no dot is necessary, which is not the case for relative imports.
```
isLocalImport=true
./log4js
../log4js
isLocalImport=false
log4js
/log4js
```
=> JavaScriptTypeRecovery: Fix Local Import Regex

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Imported types used in type hints for method parameters and returns now have the import namespace prefixed as resolved by the symbol table.
* Swapped import processing and symbol table pre-population such that the latter can make use of the former
* Simplified some XTypeRecovery code
=> JavaScriptTypeRecovery: Type Hint Reflects Import

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/ConstructorInvocationTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/MethodTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/SynchronizedTests.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/codedumper/CodeDumper.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/codedumper/SourceHighlighter.scala
Storing full Jimple code bodies in `Method.code` to enable implementation body dumps for internal code.
=> jimple2cpg: Dump Implementation

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
Fix flow from module-level literal assigned to an identifier and used in a call captured by a child closure.
=> jssrc2cpg: Fix Flows from Module-Level Literal

.github/workflows/containers.yml, README.md, ci/Dockerfile.alma, ci/Dockerfile.alma8
Almalinux 9 and 8 images for joern. Almalinux uses RedHat UBI as the source and is enterprise friendly.
The workflow uses a schedule to publish the images with the tag `nightly`, `master`, and `latest` based on version tags.
After approving this PR, please visit the package settings and make all the packages public. GitHub would create packages as private by default and send a billing notice to upgrade.
=> Container images based on almalinux for joern

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala
For the attached issue, while `tryResolve` should technically only return `null` on error, it appears to throw stack traces too. So this defends the call to avoid the crash.
Resolves: #2666
=> jimple2cpg: Defend .tryResolve Call

dataflowengineoss/src/main/antlr4/io/joern/dataflowengineoss/Semantics.g4, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/DefaultSemantics.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/nodemethods/ExpressionMethods.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/EdgeValidator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/semanticsloader/Parser.scala, dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/semanticsloader/ParserTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/SemanticTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/SemanticTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
The current semantic definition only supports positional arguments which should correspond to the ordering of the callee parameter.
This is not always the case when named arguments are used, and this PR allows one to define strings as the names of the argument in the callee and match these up with other arguments whether named or positional.
When tracking a flow from a defined semantic, named arguments are given precedence over their positional counterparts.
A test in Python is added to verify flows through named arguments are no longer discarded.
=> dataflowengineoss: Semantics for Named Arguments

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/EnumTests.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MemberTests.scala
This is a temporary hack, pending proper handling of enum args and anonymous classes.
=> Do not add AST children to member nodes

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
Fixed code where a call occurring in another call has its receiver declaring type assigned to the parent call declaring type.
=> XTypeRecovery: Fix Accidental Arg/Call Mix Up

.github/workflows/containers.yml, ci/Dockerfile.alma, ci/Dockerfile.slim
Firstly, COPY of the source code isn't required in any image. Then using the tool `czkawka` I delete newer jars alone excluding `/opt/joern/joern-cli/lib`.
```
❯ docker run --rm -it -v /tmp:/tmp -v $(pwd):/app:rw -w /app -t ghcr.io/joernio/joern-slim
Compiling /app/(console)
creating workspace directory: /app/workspace
██╗ ██████╗ ███████╗██████╗ ███╗   ██╗
██║██╔═══██╗██╔════╝██╔══██╗████╗  ██║
██║██║   ██║█████╗  ██████╔╝██╔██╗ ██║
██   ██║██║   ██║██╔══╝  ██╔══██╗██║╚██╗██║
╚█████╔╝╚██████╔╝███████╗██║  ██║██║ ╚████║
╚════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝
Version: 1.1.1698
Type `help` or `browse(help)` to begin
joern>
```
Nearly 1 GB is trimmed from the exploded image.
```
❯ docker images
REPOSITORY                                                           TAG …
```
=> New slim image with less os packages and less jars

.github/workflows/containers.yml
ARM 64 version isn't required for slim and alma8
=> ARM 64 version isn't required for slim and alma8

.github/workflows/containers.yml, .github/workflows/release.yml, .github/workflows/upgrade-deps.yml, README.md
It's a great problem to have, but we really don't want to release 10x
a day (for each commit). Contributors can still manually trigger a
release in github actions.
=> throttle releases: only one per day by default

joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Parses available types around `Return` nodes and stores them as type hints in the callee `MethodReturn`
* Currently only handles simple calls and literals
=> XTypeRecovery: Use Return Nodes As MethodReturn Hints

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeHintCallLinker.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
If a call is a field access below a return, attempts to resolve the type of the field on the CPG or symbol table and use it as a type hint on the method return.
=> XTypeRecovery: Extend Field Accesses to Return Hints

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
This problem became apparent after https://github.com/joernio/joern/pull/2680 was merged: when using a receiver as a source, and we manage to track back all the way to an invocation on that receiver, we do not consider the call on that receiver to be a source as well. In fact, it's somewhat debatable whether we should. The reason I believe we should is that if we are unable to resolve the method, we will actually jump back to the receiver, while if we can resolve it, we don't. In order to be consistent regardless of whether the method can be resolved or not, this change is necessary.
=> ossdataflowengine: fix edge case when tracking from receivers

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/NamespaceTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/OperatorTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala
With these changes, we re-use the existing `astForClassLike` and `astForMethodDecl` methods to create the ASTs for the fake global method and typeDecl.
This also fixes https://github.com/joernio/joern/issues/2710
=> Refactor php2cpg file AST creation

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeTests.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/TypeTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeTests.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NodeTypeStarters.scala, semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/types/structure/TypeTests.scala
make cpg.typ consistent with the comment
https://github.com/joernio/joern/blob/9263414af3a55945376c7bf40a01fa60c462be06/semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/NodeTypeStarters.scala#L273-L277
also consistent with 
- `cpg.typeDecl(<short-name>)`
- `cpg.call(<short-name>)`
=> make cpg.typ consistent

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/MixedCfgCreationPassTest.scala
Right now, while default parameter semantics are modelled in the CPG, there is no easy query for "Does this parameter have a default value?".
Now ideally, there would be some `MethodParameterIn(defaultValue: Option[String])` or `MethodParameterIn -DEFAULT-> Literal` construct in the schema, but this PR is a quick-and-dirty way in the meantime to easily show a parameter is assigned a default.
=> jssrc2cpg: Default Parameters Show Default in .code

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/ClosureRefPass.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/LocalCreationPass.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/utils/Scope.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ArrayTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CallTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ClosureTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MethodTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/OperatorTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala
Since PHP doesn't require variable declarations, php2cpg would create a Local node on the first use of a new identifier in scope and add a ref edge from the identifier to the local. This approach works well if the identifier in question is added to the CPG, but this isn't always the case. This led to a situation where identifier nodes are added to the CPG (due to the ref edge being added), but not to the AST, leaving them without AST parents. 
This PR removes most Local creation from the AstCreator and creates them in a follow-up pass instead. This also means that locals captured by closures must be referenced separately, since the locals being referenced may not exist yet, so the ClosureRefPass adds these.
Resolves https://github.com/joernio/joern/issues/2732
=> Add php2cpg local creation and ClosureRefEdge passes

.github/workflows/master.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/upgrade-deps.yml
Now that we 'only' release once a day we should run tests on each
merge to master, just to be safe. There's a few paths how things get
merged to master that are red, e.g. two PRs that are merged at the
same time that bring in incompatible changes. Or simply someone using
admin rights to merge.
Also use the -latest runners to avoid being in the 'no runner
available because they've been sunsetted' situation again.
=> github actions: master build and use -latest runners

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Testing and verifying behaviour around recovering types for field accesses that end up using temp variables to achieve 3-address code
* Cleaned up some code in `XTypeRecovery` to be more Scala-like
=> Recover types for deconstructed field access structures

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ContextStack.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/DynamicTypeHintFullNamePass.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeHintCallLinker.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/ClassCpgTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/FunctionDefCpgTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/MemberCpgTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/VariableReferencingCpgTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XInheritanceFullNamePass.scala
* Reverted [commit 4691b4a](https://github.com/joernio/joern/commit/4691b4a54b23d23d4e6aa3193bb703cfb7398b57)
* Added tests that were resulting in some failure
* Added support for string constant type hints (idk how but this is valid Python)
* Using `ForkJoinParallelCpgPass` for `DynamicTypeHintFullNamePass`
* Making sure that `DynamicTypeHintFullNamePass` considers types within the current scope
=> Reintroduce Python Compatibility Changes

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsClassesAstCreationPassTest.scala
For example
```typescript
interface Symbol {
/** Returns a string representation of an object. */
toString(): string;
/** Returns the primitive value of the specified object. */
valueOf(): symbol;
}
```
The names of members for `Symbol` would be the full code. With this change, it would (more) correctly use the identifier name for `Member.name`.
=> Correctly Account for Method Names in TS Interfaces

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
In a follow-up, `MethodFullNames.OperatorPrefix` shall also be removed.
=> rubysrc2cpg: refactor to use x2cpg's DynamicCallUnknownName

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForPrimitivesCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
* Moved `AstCreator.Defines` into a separate object. Also renamed/added/deleted a few fields. E.g. In Ruby, there is no "Boolean" class, but "TrueClass" and "FalseClass".
* Renamed Defines.Number to Defines.Numeric (following Ruby)
* Completely rewrote `astForPseudoVariableIdentifier` following jssrc2cpg's scheme of an `AstForPrimitivesCreator` trait.
=> rubysrc2cpg: refactored pseudo-variables' AST

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/DataFlowSlicing.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/UsageSlicing.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/package.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernSlice.scala, joern-cli/src/test/scala/io/joern/joerncli/JoernSliceTests.scala
* Using `scopt`'s `cmd` feature to separate modes into commands
* Added `BaseConfig` trait to seamlessly separate configs between commands
E.g. instead of `joern-slice -m Usages` one would use `joern-slice usages`, followed by the arguments.
cc: @pr0me @xavierpinho
=> Separate Joern Slice Modes into Commands

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForPrimitivesCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesesTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RegexTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/StringTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/SymbolTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/IdentifierTests.scala
* Simplifies `astForLiteralPrimaryContext` by naming each literal alternative explicitly (in RubyParser.g4)
* The `.code` property for strings was not including the `"` or `'` characters. We fix that here.
* Adds `/regexp/` literals as LITERAL nodes.
=> rubysrc2cpg: supports regexp literals, and refactors literals support in general

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/IdentifierTests.scala
Used `Operator.XYZ` standard names and method fullnames for several operator nodes. More to be covered in another PR.
Got `cpg.assignment.l `working.
=> rubysrc2Cpg: Operator name correction

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
Extended the fix #2722 by testing when the source is an identifier and accommodating this case
=> Flow From Identifier Receiver Source

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* When an identifier is given a type reference, strip the <meta> suffix if one is present
* If a new node is created as a result of the type recovery, attach the contains edge appropriately
=> Point Symbol to Non-Meta Type Ref + Contains Edge Fix 

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/ReachingDefTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/dotgenerator/DotCfgGeneratorTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgdominator/CpgCfgAdapter.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgdominator/ReverseCpgCfgAdapter.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/codepencegraph/CdgPass.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/codepencegraph/CpgPostDomTreeAdapter.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeHintCallLinker.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/LinkingUtil.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/CallGraphGenerator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/CdgGenerator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/CfgGenerator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/TypeHierarchyGenerator.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/AstNodeMethods.scala, semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/StepsTest.scala
Structures like `int a; if(a) { foo(); }` are actually something like `int a; if(a!=null) { foo(); }`. Hence `a` is the condition in the CFG and should be displayed even if it's just an Identifier. This PR fixes that.
See: https://discord.com/channels/832209896089976854/832214243230744626/1115821653956513884
Also: some minor clean-ups.
=> dotgenerator: display Identifier in ControlStructure

joern-cli/src/main/scala/io/joern/joerncli/JoernParse.scala, joern-cli/src/main/scala/io/joern/joerncli/JoernSlice.scala
prior to this, the exception handling threw away useful information
like stack traces, and was a mix of different styles, including
`Either` and regular `try` blocks. Using `Try` everywhere makes it
more readable and report all information users might want.
fixes https://github.com/joernio/joern/issues/2820
note: this will make the output more verbose - the stack trace was previously hidden..
=> joern-parse exception handling: report root causes

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ConfigPass.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ConfigPassTest.scala
Stores the contents of any root-leveled `Gemfile` or `Gemfile.lock` files as CONFIG_FILE(s).
A future pass shall later process these CONFIG_FILE(s) in a similar manner to how pysrc2cpg handles `requirements.txt` files.
=> rubysrc2cpg: support for Gemfile{.lock} as CONFIG_FILES(s)

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/DataFlowSlicing.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/UsageSlicing.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/package.scala, joern-cli/JOERN_SLICE.md, joern-cli/src/main/scala/io/joern/joerncli/JoernSlice.scala, joern-cli/src/test/scala/io/joern/joerncli/JoernSliceTests.scala
* Simplified data-flow slice
* Modified usages slice to include source code, the one that `joernti` [CodeTIDAL5](https://github.com/joernio/type-inference-models/blob/main/data/model_checkpoints/download_codet5_model.sh) uses
* Increased documentation on `JOERN_SLICE.md`
Note: This will be followed up by the TODO's laid out under `JOERN_SLICE.md`. For now, the usage slices here match `dave/joernti` and this is an effort to set a Joern version with a reproducible artifact following the work on [JoernTI](https://github.com/joernio/type-inference-models). A separate repository will be created to showcase this interaction as to not be something to maintain in Joern directly.
=> Slicing Documentation: Towards Formalizing the Slices

.sbtopts, build.sbt
Many of the runners on the CI/CD are aborting the test suites on occasion. This is likely to the scaling number of tests and parallelism of the test execution demanding more memory as development continues.
I've set the task limit on tests to be 2 x available cores and updated the memory via `.sbtopts`.
Alternatively I can update the memory in the CI/CD via
```
- name: Increase memory allocation
run: echo "SBT_OPTS=Xmx4G Xms4G" >> $GITHUB_ENV
````
=> Increase Memory Alloc and Constrain Test Tasks

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XInheritanceFullNamePass.scala
The regex matcher is much too expensive with arguably not much benefit. This PR simply makes the matching use `cpg.typDecl.nameExact` on the entity imported. This comes with great performance improvements.
=> XInheritancePass: Switch to Name Exact Matching

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
1. undef implementation
2. Crashfix for class body containing direct identifiers
3. Crashfix for import having an expression instead of a literal
4. Unit tests with the above
Some Ruby repositories that I usually import to test are now again getting imported with this PR without exceptions
=> rubysrc2cpg: More fixes

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefProblem.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
We previously removed lone identifiers even if they actually also appeared in `return` statements. That was incorrect but not triggered when the affected identifier was a local or parameter. The bug became apparent because in the ruby frontend, locals are currently missing. While we should add locals to the ruby CPG, this fix should be made nonetheless and it fixes a missing flow we were observing.
=> Make sure `lone identifier optimization` respects `return`

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsClassesAstCreationPassTest.scala
Accommodates an edge case where objects exported as types did not have members. I hope this doesn't create members for everything that is defined as an object in this way, but perhaps that's not the worst thing.
=> jssrc2cpg: Include Members for Dynamic Exported Types

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsClassesAstCreationPassTest.scala
Following the logic of type aliases, and dynamic types in parameters, added support for destructured params
=> jssrc2cpg: Handle Destructured Params

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
The last statement in a method should be considered a return if it is not already a return. Converted the last statement to `returnAST()` for this purpose. Associated unit test written as well.
=> rubysrc2cpg: Last statement in method should be considered a return

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
The control structure usage done for Ruby for for loop was like C ( since that has the only wrapper usage for for loop ) but the iterator is not present in Ruby. Nor is the post loop update AST relevant in Ruby. The Ruby for control structure usage was resulting in a incorrect CFG.
Ruby for loop is similar to Python. No FOR control structure is used in the Python front end. For has been modelled as a while in the Python frontend. Did something similar here without introducing dummy (`tmp`) variables and got things working. CFG now looks sane.
=> rubysrc2cpg: Modelled for loop as a while loop

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/CodeDumperTests.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/CodeDumperTest.scala, semanticcpg/src/main/scala/io/shiftleft/semanticcpg/codedumper/CodeDumper.scala
When evaluating multiple methods and calling dump on a series of them, it's difficult to know which is which especially if they share the same name. This change adds the name of the method incorporated into the arrow comment.
=> Include Method Name in Dump

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Main.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
* Add a `--php-parser-bin` option to specify the path to php-parser
* Add better error messages if php-parser can't be initailzed with given php-parser-bin and php-ini paths
* Don't attempt ast creation if php-parser couldn't be initialized
=> php2cpg: Add PhpParserBin option and better errors

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/MethodTests.scala
specifically around the use of type upper bounds
=> kotlin2cpg: change fullnames for certain contructs

changelog/passthrough_semantics.md, dataflowengineoss/src/main/antlr4/io/joern/dataflowengineoss/Semantics.g4, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/DefaultSemantics.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/nodemethods/ExpressionMethods.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/EdgeValidator.scala, dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/semanticsloader/Parser.scala, dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/semanticsloader/ParserTests.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
* Added a `PASSTHROUGH` mapping that represents an instance where parameters are not sanitized, may affect the return value, and do not cross-taint. e.g. `foo(1, 2) = 1 -> 1, 2 -> 2, 1 -> -1, 2 -> -1`. `0->0` is not included, but can be added as a mapping.
* Made it compulsory to add a parameter index if using an argument name in the semantics. This makes the summary more "method"-centric and less "caller"-centric. Argument names still have precedence, so if the argument index is not appropriate due to type unpacking used by the method, then it may be left as some arbitrary value.
* Added `PASSTHROUGH` for Python's set, dict, tuple, and list literals
Open to discussions!
Resolves #2663
=> Introduction of 'PASSTHROUGH' Mappings & Update Arg Name Semantics

console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/JsSrc2Cpg.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ImportResolverPass.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ImportsPass.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ImportResolverPass.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ImportsPass.scala, joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/SymbolTable.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XImportResolverPass.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XImportsPass.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
Import resolution until now has been integrated into the type recovery pass. The type recovery pass is an iterate-and-propagate algorithm, where import resolution would be run every iteration for every file. Since the type recovery operates on a fork-join concurrency (since inter-file writing is involved), whereas the import resolution alone is mostly read-only, there is room for optimization. The following changes are made:
* Introduced the `XImportPass` class, which unifies the two `ImportPass` classes from `jssrc2cpg` and `pysrc2cpg`, and implements them using the `ConcurrentWriterCpgPass`.
* Introduced a `XImportResolutionPass` class, which uses the `Tag` node feature to resolve the entities that the `ImportNode`s refer to. The values of the `Tag` node are serialized versions of a …
=> Unifying Import Resolution

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/AssignmentTests.scala
Fixes issues where multiple RHS/LHS values in assignments (eg. c, d = a, b) work properly with dataflows. This fixes the previously broken test case where flow from a to c was not working:
```
a = 1
b = 2
c, d = a, b
puts c
```
Also works with other cases where RHS values are in array. eg. a, b = [1, 2]. More complex cases will be tested and added in subsequent PRs
=> rubysrc2cpg: fix multiple assignments

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala
We now exit with 1 if the JRE c2cpg runs on is < JRE 17.
=> c2cpg: exit early on old JREs

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallTests.scala
method fullnames for types with upper bounds found in qualified
expressions were previously not rendered correctly. that is, for the
following piece of code:
```
package mypkg
fun f1() {
val ns = sequenceOf("four", "three", "two", "one")
val ml = mutableListOf<String>()
ns.mapIndexedNotNullTo(ml, { i, s -> s })
}
```
the call to `mapIndexedNotNullTo` had a METHOD_FULL_NAME of:
```
kotlin.sequences.Sequence.mapIndexedNotNullTo:java.lang.Object(java.lang.Object,kotlin.Function2)
```
instead of:
```
kotlin.sequences.Sequence.mapIndexedNotNullTo:java.lang.Object(java.util.Collection,kotlin.Function2)
```
signature from the docs:
```
inline fun <T, R : Any, C : MutableCollection<in R>> Sequence<T>.mapIndexedNotNullTo(
destination: C,
transform: (index: Int, T) -> R?
): C
``` …
=> kotlin2cpg: change fullnames for qualified exprs

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/FunctionTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MiscTests.scala
1. Block accepting arguments do not have a direct provision in the AST construction code. Modelled blocks with arguments as dummy method and calls to them as calls to these methods
2. `object.member` is not possible in Ruby and getter MUST be used. Hence, that case gets eliminated
3. Made corresponding UT changes. Block parameters were being incorrectly picked as identifiers. That got fixed.
4. Some UTs were not working because they were incorrectly written. Corrected them
=> rubysrc2cpg: Block with parameters as dummy method

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/EagerSourceTypeSolver.scala, joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MemberTests.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/interop/JavasrcInterop.scala
`JavaSrcInterop` was re-implementing a lot of javasrc functionality that actually belongs in the javasrc2cpg `AstCreationPass`. This PR moves the relevant code into the ACP and removes the duplicate code from `JavaSrcInterop`
=> Move JavaParser ast creation into AstCreationPass to reduce code duplication

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AnyTypePass.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstParentInfoPass.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MethodTests.scala
* Add ast parent info for general linking
* Replace all `<empty>` type full names in the ast with `ANY` in an attempt to avoid the DynamicTypeLinker crash.
=> Add php2cpg ast parent info and ANY type as placeholder

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
1. Fix for yield invocations. Considered the method specific yield block as a new fake method and converted the yield call to a `CALL` node. The fake method is a new `METHOD` node with _yield suffixed to its name. A `METHODREF` of the fake method has been passed to it.
2. Removed lazy appending block methods. They can instead be put in the creation path
3. Test case changes for the same
=> rubysrc2cpg: Fix for yield invocations

joern-cli/frontends/php2cpg/build.sbt, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala, joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala
Due to how php-parser was packaged, there was a php > 8 requirement to run it, even though php-parser itself is supported by php > 7.1. This change brings in the fixed php-parser, while also introducing a versioning scheme for php-parser binaries.
=> Fix php > 8 requirement in php2cpg

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
* The previous unaryMinus handling logic no longer applies after a grammar change (see #2878)
* `super` is now a call (previously it was just only its children), but that's not the full story yet.
=> rubysrc2cpg: refactor unaryMinus and superExpression

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
* Each command alternative has now a name (in the parser), allowing us to split their handling into their own separate methods.
(Next PR will clean-up each method individually.)
=> rubysrc2cpg: refactoring commands to have their own methods

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
* Unified the handling of `super` commands and `super` expressions into a common `astForSuperCall`.
=> rubysrc2cpg: clean-up the AST construction of `super` calls a bit

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala, joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
* Uses identifiers to get types for method return nodes
* Added some cleanups and convenience node extensions
=> Use Identifiers for Method Return Type Recovery

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyLexerBase.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyLexerRegexHandling.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RegexTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
* Now regex literals are properly identified when used as arguments to commands
=> rubysrc2cpg: improved regex literal support

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala, joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/EnumTypeTests.scala, joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/StructTypeTests.scala
Aliased type defs got their correct (alias) name now. This also solved lost type decls from anonymous structs. (https://discord.com/channels/832209896089976854/832229141355954176/1122999607501262959)
=> c2cpg: fix (alias) type decl creation

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MiscTests.scala
The fake `METHOD` nodes being returned after creation through the call stack results in them being passed as argument to `CALL` nodes eventually as the stack unwinds. The below exception is seen
` Edge with type='ARGUMENT' with direction='IN' not supported by nodeType='METHOD'
`
Reintroduced putting the `METHOD` nodes in a separate list to be appended lazily to get rid of this exception. Also introduced a unit test for the same.
=> rubysrc2cpg: Fix for METHOD node being passed to CALL nodes as argument

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
Thanks @rahul-privado for bringing this up.
=> rubysrc2cpg: fixes missing whitespace before proc-parameter

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala, joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPrimitivesCreator.scala, joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala, joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AstCreationPassTests.scala
This PR contains the following
- Ast node creation for Declaration and Initialization statements. Ex - `var local int = 1`
- Resolved name, typeFullName for initialized variables
- Refactoring to move out the code which adds Import Nodes
=> add - ast for variable declaration and initialization

console/build.sbt, console/src/main/scala/io/joern/console/cpgcreation/RubyCpgGenerator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/AstPackagePass.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/utils/PackageTable.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/TypeDeclAstCreationPassTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallGraphTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RubyMethodFullNameTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/DataFlowCodeToCpgSuite.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala
* The class stack & scope are not being used properly, while this does not address the scope issue, this does start addressing the class stack issue
* Filename was used in the place of what a relative file name should be used, thus method full names were incorrect
* Method full names and calls also always assumed they were at the base of the file, and did not include the `:program` class (it was originally missing from the stack)
* Added the `NaiveCallLinker` to the post-processing pass to get some call linking going
* Creating very basic type declaration nodes for now, but this is to be revisited in another PR, as it cannot proceed until this work is merged
* Removed `<unresolvedSignature>` from dependency call resolver as there is no overloading in Ruby
=> [rubysrc2cpg] Fix Class Stack & Method Full Names

joern-cli/frontends/gosrc2cpg/build.sbt
fixup for https://github.com/joernio/joern/pull/2960
=> simplify versions: use the same circeVersion as globally (0.14.5)

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsClassesAstCreationPassTest.scala
Related to [#2971](https://github.com/joernio/joern/pull/2971), prevents the case where the destructuring of parameter operations are not linked to the parent block node correctly.
=> [jssrc2cpg] Fixed dangling Cfg Nodes From Destruct Params

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
* Reworked the previous `else` handling (that was being placed under a `JUMP_TARGET` node), to be placed under a `BLOCK` node.
* Removed an incorrect unit-test
* Ignored a unit-test for `when-case-else` expressions, as they also need to be refactored and improved.
=> rubysrc2cpg: Refactor if statement

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
* `astForBlockContext` takes an optional method name that complicates matters just for 1 possible scenario. Also, there's duplicate code for handling do/brace blocks. I'm arranging this logic in smaller pieces. Since the full refactoring would make for a convoluted diff, I'm splitting this in 2-3 PRs.
=> rubysrc2cpg: start refactoring astForBlock

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RubyMethodFullNameTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/DataFlowCodeToCpgSuite.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala
https://github.com/joernio/joern/pull/2982 added a `withConfig` method to testCpgs to set the config on a per-testcase basis without having to wire class parameters through the various fixtures. This PR enables this for rubysrc2cpg.
=> Enable withConfig for rubysrc2cpg

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
... as the only scenario where it's needed is already directly handled.
=> rubysrc2cpg: removing blockMethodName from astForBlockContext

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
* This way `astForBlock` creates a typical `BLOCK`, whereas `astForBlockMethod` creates a method, and the two are not coupled anymore.
=> rubysrc2cpg: single out usages of astForBlockMethod

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/CCodeToCpgSuite.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/testfixtures/JsSrc2CpgFrontend.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/testfixtures/PhpCode2CpgFixture.scala
https://github.com/joernio/joern/pull/2982 added a `withConfig` method to testCpgs to set the config on a per-testcase basis without having to wire class parameters through the various fixtures. This PR enables this for c2cpg, jssrc2cpg, and php2cpg.
=> Add withConfig support for c2cpg, jssrc2cpg, and php2cpg

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/CaseConditionTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesesTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/UnlessConditionTests.scala
* Names `variableIdentifier` alternatives (so that we can safely pattern match on context types.)
* Moves and simplifies `astForVariableIdentifier`
=> rubysrc2cpg: Refactor astForVariableIdentifier

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/BeginExpressionTests.scala
=> rubysrc2cpg: Missing ws in `rescueClause`

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
=> rubysrc2cpg: Add missing splatting argument

benchmarks/src/test/scala/io/joern/benchmarks/BenchmarkTags.scala
Seems that the type could not be implicitly inferred. for `ofDim` so this has been added explicitly. Seems to only happen on IntelliJ and not cause issues on SBT via terminal. Possibly this is coming from Scala 3 migration.
=> [benchmarks] IntelliJ Warning on T for `Array.ofDim`

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
=> rubysrc2cpg: Fix missing double splatting argument/parameter

joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/FileTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/FileTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MetaDataTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MethodOneTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MethodTwoTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/NamespaceBlockTest.scala
ruby and go AST unit tests
1. File node related unit tests - Added similar unit tests for `gosrc2cpg`
2. Metadata unit tests
3. Namespace unit tests
4. Method unit tests covering 
- Two types of method definitions a. def ... end b. define_method ... end
- Method parameters and its traversal
- Method return nodes and its traversal
=> [rubysrc2cpg] Unit tests replicated from c2cpg and pysrc2cpg

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/ImportAstCreationTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RubyMethodFullNameTests.scala
The PR contains the following
- Support for linking import nodes with call nodes
- Test Cases
- Currently have made this change directly in the AstCreation pass, should this be done in the Import pass separately?
=> rubySrc2Cpg : Linking import node with respective call nodes

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/SourceFiles.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/SourceFilesTests.scala, joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/IgnoreInWindows.scala
__Motivation:__ We've run into issues in the past where invalid source directories were given, but `*2cpg` failed silently. These silent failures are difficult to debug (especially with customer submissions) and are most likely due to user error. This PR adds 2 failure modes when finding source files:
* __The input path doesn't exist or isn't readable:__ this is most likely due to a typo in the input path. This should definitely be an exception that terminates execution since this does not match user intent.
* ~__No source files could be found at the given input paths:__ This could be an acceptable error (for example when finding config files), but in general will not be. The current implementation always throws an exception (which can then be handled by the caller if an empty source list …
=> Throw an exception when source paths don't exist or no source files are found

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
=> RubyParser: Support for keyword parameters

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MethodOneTests.scala
Fixes issue where only one method param was getting added for `def foo(a, b)`. Ignored test switched on
=> rubysrc2cpg: fix method param not populating

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithoutParenthesesTests.scala
We already allowed keywords to be used as member names, e.g. `foo.class`. Now we allow the usage of `?` as suffix as well, e.g. `foo.class?`
Closes #3036
=> rubysrc2cpg: Allow keyword?-named method invocations

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesesTests.scala
Closes #3041 .
Closes #3046 as well.
=> rubysrc2cpg: Allow keyword-named association keys

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala, joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsClassesAstCreationPassTest.scala
Fixed instance where identifiers generated by destructured parameters were not linked to their respective locals.
Resolves #3024
=> [jssrc2cpg] Destructured Params Refs Fix

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/TypeDeclAstCreationPassTest.scala
Using basic detection of `@` prefixes to determine class members. It's sorta hacky but there is a bit of a lack of existing structure for determining a class body outside of a normal body :(
Resolves #3007
=> [rubysrc2cpg] Generate TypeDecl Members

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/TypeDeclAstCreationPassTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/FunctionTests.scala
* Some code cleanups
* Detected when `@`-style field accesses were called and generated the necessary `Operators.fieldAccess` structure
* For members: Added static modifier when `@@` notation detected and the virtual modifier otherwise
Partially resolves #3068, more to be done for instance object field accesses.
=> [rubysrc2cpg] `this` style field accesses handled

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
1. Used try-catch control structure for rescue like other frontends. Used the wrapper in it
2. Changes to handle implicit returns only if there is no rescue block. This is to handle the complications of implicit/explicit returns separately in a different PR
3. Disabled test case for implicit return handling with if-else
4. Enabled test cases passing due to this change. They were failing due to implicit returns being used in try-catch
=> rubysrc2cpg: Try catch for rescue and fixes

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/StringTests.scala
Supports samples such as
```ruby
"foo" \
"bar"
```
by representing them as a call to `<operator>.stringConcatenation` with the given string literals for arguments.
Towards closing #3081 .
=> RubyParser: support for whitespace-separated string literals

README.md, joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala, joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala, joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala, joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/dataflow/DataflowTests.scala, joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AstCreationPassTests.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/Nodes.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstNodeBuilder.scala
The PR covers the following
- Ast creation for switch case
- Corresponding Ast and dataflow tests
- Moved JumpTargetNode from kotlin2cpg to x2cpg as it was redundant
- Ignored 1 test case in Ast creation where due to the presence of a `local` node in the condition of switch it throws an error
- Ignored 1 test case in Dataflow where due to an empty condition in the switch, dataflow doesn't propagate
=> GoSrc2Cpg : AST generation for switch case

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/IdentifierLocalTests.scala
Adds ref edges from method param nodes to relevant identifiers in method block. Fixes 3 failing tests.
=> rubysrc2cpg: method param ref edges

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/StringTests.scala
* Unified string literals and string interpolations under the same rule ("string expressions"), since the ability to concatenate strings applied to both literals and interpolations.
Closes #3081
=> rubysrc2cpg: Support for whitespace-separated general string expressions

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForPrimitivesCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImportResolverPass.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryPass.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/utils/PackageTable.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala
The PR contains the following
- Streamlined built-in primitives generation for ruby. Ex - The type for Integer will be `__builtin.Integer`
- Support for resolving Module variables across file in Type Recovery
- Have Ignored 3 test cases in TypeRecovery which will be fixed once the Ast Generation for Modules is in place
- Added a data structure in packageTable to store Encountered Modules. (May not need this in future)
cc - @DavidBakerEffendi
=> [rubysrc2cpg] Fixes existing ignored test cases for RubyTypeRecovery

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MethodOneTests.scala
1. Got implicit returns working when the last method statement is not just an expression but contains blocks like if-else
2. Could not do this for the last statement of begin blocks since there is an existing issue with the data flow engine. The below Java code does not return flows due to that issue. Raised it with @fabsx00 separately.
3. Enabled and corrected some other test cases that are working.
Java code that does not produce data flows.
```
public class Main {
public static int foo(String args) {
try {
System.out.println("in begin");
return 0 ;
} catch (Exception e) {
System.out.println("Something went wrong." + args);
}
}
public static void main(String[ ] args) {
String x = "1";
foo(x);
}
}
```
If we set `source -> x` and `sink -> println()` we do not get data flows in the below …
=> rubysrc2cpg: Implicit return handling in blocks

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyLexer.g4, joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ProcDefinitionTests.scala
=> rubysrc2cpg: Support for proc literals

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala
Used, in a private discussion, to show that this is properly parsed. Might as well add it since there's no similar unit-test for this.
=> RubyLexer: extra regex unit-test

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ClassDefinitionTests.scala
=> RubyParser: fix missing WS for singleton class definitions

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyLexer.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyLexerBase.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala
Expressions like `x+@y`, which mean addition between `x` and `@y`, were not being properly lexed since `+@` is a token by itself. However, the usage of `+@` is restricted to (re-)definitions of the unary `+` (and `-`) operator. To disambiguate, we shall only emit `+@` tokens when the previous non-whitespace token is `def`, thus complying with the restriction.
Found in #3037.
=> RubyLexer: disambiguate `x+@y`

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyLexer.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyLexerBase.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesesTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala
In an expression like `foo(x:y)`, the lexer would recognize `x:y` as 2 tokens:  `LOCAL_VARIABLE_IDENTIFIER`, `SYMBOL_LITERAL`, when it should recognize 3: `LOCAL_VARIABLE_IDENTIFIER`, `COLON`, `LOCAL_VARIABLE_IDENTIFIER`.
Found in #3037
=> RubyLexer: disambiguate `x:y`

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/ModuleTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/TypeDeclAstCreationPassTest.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/StringUtils.scala
1. Handled mapping of module and class constants as members of the TypeDecl.
2. Added additional unit tests to verify the changes.
3. Added a few more unit tests which verify if hierarchical modules or classes are defined with members. Does it generates the expected AST nodes. As of now, these tests are failing hence marking them ignored will handle that in the next PR.
=> Support for constants of Module and class

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
Safety check to get around crash due to https://github.com/joernio/joern/issues/3040 while importing some Ruby repositories
@xavierpinho
=> rubysrc2cpg: Safety check for blank compound statements

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala
generally we want CPGs generated from the same input to be identical
=> kotlin2cpg: remove CLOSURE_BINDING id randomness

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithoutParenthesesTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MiscTests.scala
Commands have optional do-blocks. Hence, their optional counterpart should have higher precedence, as otherwise the parser will prefer the (shorter) alternative without it. Took this opportunity to simplify and remove one unnecessary alternative as well.
Found in #3139
@rahul-privado: I had to ignore one of your unit-tests for now. (The pros outweigh the cons in this case and presently I must continue improving the parser.) That bit of yours in which you transform a do-block into a method needs to be reconsidered. I'll leave that to you.
=> RubyParser: fixes command-with-do's precedence 

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyLexerRegexHandling.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesesTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala
The lexer predicate that decides if a `SLASH` token should start a regex literal was not taking into account colons (`:`), which is necessary to properly lex associations whose value are regex literals - e.g. `{x: /.*/}`.
Closes #3139
=> RubyLexer: improve regex starting predicate

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
=> RubyParser: support for mandatory keyword parameters

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
The null `ctx` was being references in the log message causing a crash. Removed it. This makes some more repository scans to proceed further.
@xavierpinho @tuxology
=> rubysrc2cpg: Removed null pointer dereference

.sbtopts, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala, joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/noncaching/JdkJarTypeSolver.scala
Using the `ReflectionTypeSolver` and the `JdkJarTypeSolver` with jars from the current runtime java home give similar, but not identical results. This is problematic for getting consistent results, particularly when updating expectations for SP tests. This PR switches to the `JdkJarTypeSolver` as the single "java stdlib" type solver for the sake of consistency.
=> Replace javasrc2cpg ReflectionTypeSolver with JdkJarTypeSolver at java home

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithoutParenthesesTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ProcDefinitionTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RescueClauseTests.scala
Standalone `rescue` statements were initially only allowed inside `begin..end` expressions. Turns out (e.g. [StackOverflow](https://stackoverflow.com/questions/1542672/how-does-one-use-rescue-in-ruby-without-the-begin-and-end-block)), `def`, `do` and `{` also act as if they were "begin" expressions wrt `rescue` statements.
Closes #3160
=> rubysrc2cpg: Support for `rescue` stmts in `def` blocks

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Main.scala, joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/util/ProgramHandlingUtil.scala, joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/unpacking/JarUnpackingTests.scala
I noticed that the recent fixes to the jar unpacking had one downside: jars inside jars were unpacked by default. In practice, this would lead to long CPG generation times. With this PR, there is now a `recurse`-flag to control whether recursive unpacking happens or not. This flag is set to `false` by default, that is, recursive unpacking is disabled by default.
=> [jimple2cpg] Do not unpack "jars in jars" by default

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesesTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithoutParenthesesTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
Added support for usage of safe navigation operator on method calls. Now the parser does not throw an error when we use AMPDOT operator for a chained invocation.
Example usecase:
```
class Foo
def bar
puts "bar"
end
end
foo = Foo.new
foo&.bar
```
Issue solved: #3143 #3168
=> [rubysrc2cpg] Add support for Safe Navigation Operator to method call.

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesesTests.scala
=> RubyParser: allow wsOrNl before `.` in a chained invocation

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyLexer.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala
=> RubyLexer: disambiguate `:x=>`

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/EnsureClauseTests.scala
=> RubyParser: fix missing wsOrNl before `ensure` clauses

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyLexerRegexHandling.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RegexTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala
=> RubyLexer: allow regex after `when`

joern-cli/frontends/rubysrc2cpg/.gitignore
To hide IntelliJ's ANTLR plugin generated files
=> rubysrc2cpg: Add .gitignore

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyLexerRegexHandling.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RegexTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala
=> RubyLexer: allow regex literal after `unless`

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/UnlessConditionTests.scala
=> RubyParser: allow parenthesised arguments in a return jump

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ReturnTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/UnlessConditionTests.scala
Previously `return` commands could be parsed as primary expressions, which would be incorrect. E.g. `return ::X.y`. Here, `::X.y` is meant to be the argument to `return`, and not the member of a `return`.
Thanks @rahul-privado for pointing this out.
=> RubyParser: refactoring`return` statements

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
In some cases like following ones, we encounter a call node instead of an identifier when we model a block as a method. Trying to set it as a param of the method causes issues. This is specifically present when `_` is used to discard iterations over a hash:
```
x.each do |_, y|
puts y
end
```
```
params.permit(:a, :b).reject { |_, v| v.blank? }
```
To fix this, we just ignore calls nodes when encountered as a param in a block (modeled as method). Should not have any major repercussions AFAIU. I've left a TODO explicitly just in case.
=> rubysrc2cpg: ignore call node as param

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MiscTests.scala
The `class << x` has no implementation and returns no statement ASTs. This caused a crash in the statement `Seq(lastStmtAsReturn(stCtx.getText, stAsts.head))` since `stAsts` was a empty list.
Put a check for the list size to avoid a crash. Wrote a test for the same. 
A proper implementation of `class << x` will avoid this issue. However, that will be in a separate PR. This one only avoids the crash.
@xavierpinho
=> rubysrc2cpg: Checked statement list size to avoid crash

testDistro.sh
trying to fix the flakey testDistro execution: https://github.com/joernio/joern/issues/3087
It seems to be classpath related, and the querydb-test manually fiddles with the classpath. Not sure if it's that, but doesn't harm to do this in the very last step either way.
=> testDistro: run querydb last

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/AssignCpgTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MethodOneTests.scala
Handles cases like `x.y = [ ]` where a new empty literal of `NilClass` type is introduced when there is empty array in RHS
=> rubysrc2cpg: handle empty arrays

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
Assignment-like method names (e.g. `foo=`) cannot be used when declaring the so-called endless methods. For instance, the following isn't valid:
```ruby
def foo=(x) = x
```
Thanks @rahul-privado for pointing this out.
=> RubyParser: don't allow assignment-like method identifiers on endless methods

joern-cli/frontends/rubysrc2cpg/.gitignore
Preventing `RubyLexer.tokens` from showing up.
=> rubysrc2cpg: Add `*.tokens` to .gitignore

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MiscTests.scala
1. Fix for crash in super call by putting a Option/null check
2. Test for the same
3. Removed defensive code that was put in to handle this issue
@xavierpinho
=> rubysrc2cpg: Crash fix in super call w/o arguments

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/Main.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AntlrParser.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
* Fix a bug in command line parsing (when flag was enabled by user, flag was disabled in the config)
* Catch parser errors inside `createAst` and skip the corresponding file rather than failing
I'm still tuning the logging a bit so that we get actionable information.
=> [rubysrc2cpg] Decouple parser and ASTCreator

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
@xavierpinho , tagging for review.
Should ideally fix #3331
=> [rubysrc2cpg] Added wsOrNl* before and after parameters

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
1. Fix for crash in indexing arguments handling by putting a Option/null check
2. Test for the same
3. Removed defensive code that was put in to handle this issue
@xavierpinho
=> rubysrc2cpg: Option based null check to avoid crash in indexing arguments

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyLexer.g4, joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala
Previously, so-called assignment-like method identifiers (e.g. `foo2=` in `def foo2=(x) ... end`) were being lexed as two separate tokens (`LOCAL_VARIABLE_IDENTIFIER` and `EQ`) and handled together in a parser rule. However, with the introduction of so-called endless methods, this separation could lead to wrong parse trees, as witnessed by #3270 .
To resolve this ambiguity, we shall now gobble up the `EQ` token as part of the method name, emitting an `ASSIGNMENT_LIKE_METHOD_IDENTIFIER` token instead.
Closes #3270
=> RubyParser: emit ASSIGNMENT_LIKE_METHOD_IDENTIFIERS

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf
This brings in gzexe compression for smaller Linux executables (half the size).
=> jssrc2cpg: updated astgen to 3.2.0

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
Test case is related to: https://github.com/joernio/joern/pull/3131
Cases covered:
1. Extending a class using `<<` operator
2. Defining a empty class inheriting using`self`.
=> ruby: method defined under class using << operator

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MethodOneTests.scala
Fixes #3330 
For now, this removes the definition node completely. Here is the rearranged AST so far for a similar accessor case:
Upon investigation, it seems we can ignore the method node for now since the accessor is storing only identifiers. We will add them later if we want, so added boilerplate code
=> rubysrc2cpg: handle method def in method arg

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ArrayTests.scala
I'm in the process of providing an alternative implementation for this construct (one that doesn't emit a token for each character). But until then, we can use this approach to keep parsing some code bases.
=> RubyParser: support for `%w` literals

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
Scenario: firstName(source) is a identifier defined under inner class and puts(sink) is statement just after the same. Expected dataflow should be exist in between two but its failing so marked it as ignore.
=> rubysrc2cpg: added test case for failing dataflow

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
@xavierpinho, tagging for review.
=> [rubysrc2cpg] Added ast and dataflow tests for `:x=>`

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/dataflow/IntraMethodDataflowTests.scala, joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/testfixtures/PhpCode2CpgFixture.scala
Fixes https://github.com/joernio/joern/issues/2099 
This is an alternative to https://github.com/joernio/joern/pull/3183 which doesn't rely on the parameter `code` field for the comparison since there's no guarantee that the `code` field will contain only `$parameterName`. For example, parameters with default values will likely show those in the code field as well (this is TODO for php2cpg, but may already exist in other frontends). Instead, this PR uses `nodeToString` to consistently compare node types.
=> Fix php param to identifier dataflow issue

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
1. Fix to be able to send parameters to a proc function. 
2. Data flow tests cases for `proc` were incorrectly written. The flow being tested was within the `proc`. Corrected it. Disabled a test case that is not working.
@xavierpinho
=> rubysrc2cg: Proc parameter fixes

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
1. Fix for member access command code
2. `astForInvocationWithBlockOnlyPrimaryContext()` had incorrect code in in which the primary and block ASTs were just being appended resulting in the loss of a call node in the primary AST causing a UT fail. Corrected it.
3. Test case correction. The variable `x` which is source was in the path. This causes confusion in the test. Also enabled a test case that works after this change.
4. Corrected test case `flow through symbol literal defined using`. It was not working because it was incorrectly structured
@xavierpinho
=> rubysrc2cpg: Fix for member access command

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MethodOneTests.scala
In Ruby we can define a private class method in a way where the argument to the `private_class_method` function can itself be a function definition
```
private_class_method def foo(a) 
1
end
```
Here, we model the argument of `private_class_method` function itself as an identifier and add the foo method definition to the main `:program` block (is that ideal?)
This is the resulting AST for above case 👇
=> rubysrc2cpg: handle private_class_method

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
If a yield block has been specified alongwith call for a method, it was not being treated as a yield. Treated it as a yield and enabled the corresponding data flow test.
@xavierpinho
=> rubysrc2cpg: Fix for yield block along with call

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MethodOneTests.scala
Following up on #3401 adding more "special" method prefixes. In addition one more test that needs fixing a bit where multiple prefixes are used. Will be handled in subsequent PR
=> rubysrc2cpg: add more special prefix functions

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AntlrParser.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/UnknownConstructPass.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
When an unexpected symbol is encountered, The Ruby grammar and parser seem to be prone to bombing out to `ProgramContext` and the default error strategy continues until `<EOF>`.
This is not great for a variety of reasons, but this is understandable as Ruby is a wild west language in terms of understanding which context we're currently in, so I propose an equally wild west solution - inspired by a questionable Discord conversation between @xavierpinho and I:
* Add an error listener and keep track of the line on which an error occurred.
* If the parser wrapper detects that an error occurred, remove that line and reparse. Continue until completion.
A more elegant, two-phase parsing strategy has been suggested by @fabsx00, but for the best interest of having a robust parser as soon as …
=> [rubysrc2cpg] Cowboy Parser Hardening

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForPrimitivesCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
Each element in a `%i(..)` array gets handled the same as a `:..` (symbol).
=> rubysrc2cpg: Support for `%i`

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForPrimitivesCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
`%r...` literals are handled the same way as `/.../`.
=> rubysrc2cpg: Support for `%r`

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
Exceptions are being seen due to none of the cases matching. The required productions have been handled in code and so this will require more debugging. This change is to avoid a crash.
=> rubysrc2cpg: Handled exceptions due to none of the cases matching

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/Main.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AntlrParser.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/UnknownConstructPass.scala, joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/TimeUtils.scala
Another issue encountered by the Ruby parser is that some inputs cause ANTLR to parse indefinitely (see https://github.com/joernio/joern/issues/3424). To reduce the impact of this issue until it is fixed, a configurable timeout as been introduced.
This PR also fixes an issue in the [cowboy PR](https://github.com/joernio/joern/pull/3421) that causes the line removal to occur infinitely if removing lines does not fix the parsing issues by the final line.
=> [rubysrc2cpg] Parser Hardening on Timeouts

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyLexer.g4, joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForDeclarationsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ArrayTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala
`\n` was not included in the set of separators for `%i` elements and as a result multi-line symbol arrays wouldn't be properly split.
=> RubyParser: fix multi-line `%i` parsing

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstCreator.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala, joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/IfExpressionsTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LambdaTests.scala, joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ObjectExpressionTests.scala, querydb/src/test/scala/io/joern/scanners/android/MisconfigurationsTests.scala
also fixes bug with generating Asts for object literal expressions when they are arguments of certain types of expressions
=> kotlin2cpg: refactor handling of object literals

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
An input path like `foo/bar/file.php` will now result in a filename `file.php` instead of `<unknown>`
=> Fix php filename if single file is given as inputPath

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
Added unit and dataflow test for multiline `%i`
=> [rubysrc2cpg] multiline `%i` support

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
1. When primary is a yield block and its return is passed in a chain, the flow was not working. Fixed it.
2. Corrected related test cases since they were incorrectly written 
3. Removed test cases which are neither valid Ruby code not will ever give flows since they are incorrect
@xavierpinho
=> rubysrc2cpg: Data flow fix when the primary is a yield block and its return has to be used

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/psi/PsiUtils.scala
without the check, the visitor may crash when encountering certain constructs
=> kotlin2cpg: add null-check in tree visitor

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/Main.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala, joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AntlrParser.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/UnknownConstructPass.scala, joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
Reverting the changes, @DavidBakerEffendi recently made to handle the situation where the parser was getting into a loop for the specific use cases of the file. For now we were able to proceed by removing this file.
1. It has introduced inconsistent behaviour in the scan results.
2. It has also increased the source code parsing time.
3. When I tried with the latest master by reverting these changes and with this change. I observed CPG of bigger size, along with more files being processed, and more sources and sinks being tagged.
=> [rubysrc2cpg] Reverting Workarounds Related to Parsing
