joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/KtPsiToAst.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ObjectExpressionTests.scala

versus obj exprs defined inside function scope

kotlin2cpg: handle obj exprs at pkg top-level

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/AssignCpgTests.scala

* When using `printAst`, we are testing a specific parser rule (often `primary`), and thus extra whitespaces could cause parsing errors (purposely unaccounted by that rule). I removed those unaccounted whitespaces in those occasions.
* Also fixed a test that contained invalid syntax.

rubysrc2cpg: clear parser errors in unit-tests

---

joern-cli/frontends/javasrc2cpg/build.sbt
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/EagerSourceTypeSolver.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/SimpleCombinedTypeSolver.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/TypeInfoCalculator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/noncaching/JdkJarTypeSolver.scala

The patch introduced in our fork was released upstream (actually quite long ago), so switching to the latest version is useful before starting to debug javaparser stack overflows that may have already been fixed.

Upgrade javaparser

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

This PR fixes new lines being interpreted as array initializer arguments and strips any trailing newlines from the string literal.

[rubysrc2cpg] Array Entries With Newlines

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/StringTests.scala

In Ruby (like in C) we can implicitly concatenate string literals by writing them consecutively, e.g
```ruby
"x" "y" # => "xy"
```
However, this rule does not apply to quoted strings (`%q` or `%Q`). So this patch corrects #3477 , in which that would be admissible.

RubyParser: fix `%q` and `%Q` contexts

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala

1. Used the correct operator for array initialization and index access
2. Corrected test cases
@xavierpinho

rubysrc2cpg: Correct operator usage for arrays

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/StringTests.scala

Since `%(` is handled the same way as `%Q` by the lexer, all that's left are parser unit-tests.

RubyParser: support for `%(` literals

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyLexer.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/ExpandedDelimiterHandling.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/NonExpandedDelimiterHandling.scala

* The end goal is to have a unified handling of either expanded vs non-expanded delimiters.
* Fixed a bug (due to an autocomplete typo) in which the handling of `%x` was inserting an extra delimiter to the stack thereof.
* Slight quality of life improvement: having `-> pushMode(..)` (i.e. outside of semantic actions) allows the ANTLR plugin to jump directly to that mode.

RubyLexer: refactoring (non-)expanded delimiter handling

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/TypeInferencePass.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeInferenceTests.scala

The focus of this PR is just performance, so it speeds up the pass without modifying the logic (which could do with a revision as well). With that being said, the new version takes the pass runtime from ~160s to <10s when creating a CPG for elasticsearch on my machine.

Speed up javasrc type inference pass

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Ast.scala

Fixed issue where `CONDITION` edge was being checked instead of `ARGUMENT`

[Schema Validation] Fixed incorrect `CONDITION` check under `withArgEdges`

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala

We only generated stubs for CPP lambdas. This PR fixes that.
Fixes: https://github.com/joernio/joern/issues/3522

c2cpg: handle method bodies for lambdas

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyLexerPostProcessor.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/AssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/BeginExpressionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/CaseConditionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ClassDefinitionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/EnsureClauseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/HashLiteralTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesesTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithoutParenthesesTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ProcDefinitionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RegexTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RescueClauseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RubyLexerTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/StringTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/TernaryConditionalTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/UnlessConditionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

Removes `WS` tokens from the token stream (in RubyLexerPostProcessor) and provides the least amount of changes to the grammar and unit-tests that keep them passing.

RubyParser: omit `WS` tokens from the token stream

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/CaseConditionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/EnsureClauseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesesTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RescueClauseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/UnlessConditionTests.scala

Fully removes references to `wsOrNl` rule and `WS` tokens.

RubyParser: remove `wsOrNl` rule

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/TypeInferencePass.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeInferenceTests.scala

Fixes https://github.com/joernio/joern/issues/3527
The argument <-> parameter matching added during the speed-up pr was too strict and didn't handle `ANY` types correctly. With this PR, `ANY` argument types will match every type for the purposes of finding matching methods.
The behaviour still won't be exactly the same as the pre-speedup version since that version didn't take argument types into account at all, but this version will be closer and fixes https://github.com/joernio/joern/issues/3527

Have ANY argument types match every argument type in javasrc type inference pass

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/ReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala

* Did a check at the implicit return where if the last statement is a method, create a method ref and return that instead
* Added a dispatch type for the call node that calls a block procedure
* Tests are in `ReturnTests`
* Added `"module_function"` to `prefixMethods`

[rubysrc2cpg] Fixed Returning Method instead of MethodRef

---

joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/VariableReferencingTests.scala

This PR contains unit tests for variable referencing tests in `gosrc2cpg`.
Changes that need to be added in the variable referencing tests after respective AST is handled -
1. Parameter variable referencing
2. Class variable referencing
3. Nested methods variable referencing
4. Closure bindings for all local nodes.
@DavidBakerEffendi, please review. 
cc: @pandurangpatil

[gosrc2cpg] Variable referencing tests for `golang`

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/BeginExpressionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/BeginStatementTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/CaseConditionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ClassDefinitionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/EnsureClauseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithoutParenthesesTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ModuleTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ProcDefinitionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RegexTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RescueClauseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/UnlessConditionTests.scala

* `separators` has been in-place replaced by its definition, since we don't care for them in the resulting AST.
* Fixed a couple of previously-mandatory `NL` that shouldn't be.
* `compoundStatement` now includes leading/trailing separators, so that rules that rely on it don't have to include them all the time as well.
* Replaced usages of `NL*` by `NL?` since the lexer already merges contiguous `NL` together.

RubyParser: refactor separators

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/dotgenerator/DotAstGeneratorTests.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Ast.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotSerializer.scala

* Added control structure type to dot visualizer
* Check if an if-statement `lhs` is a `next` command with return values, if this is the case, convert it to a conditional return instead
* Extended `Ast.subTreeCopy` to be able to replace the root node with a given node. This is used to replace the `ControlStructure(next)` with a `Return`
Fixes invalid AST due to `CONTINUE` having a non-integer child literal. Note this always assumes a return when this pattern is detected, though this is likely a reasonable assumption.

[rubysrc2cpg] Handle Conditional `next` as Conditional Return

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/CodeToCpg.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2Cpg.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2CpgOnFileSystem.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/Py2CpgTestContext.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/FunctionDefCpgTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala

This the introduction of META_DATA.root, absolute path are not longer
required.
@DavidBakerEffendi can you please have a special look on the expectation i change in joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
To me it looks like it has been wrong in the first place because `find_one` should be external.

Make the filename property in pysrc2cpg relative again.

---

joern-cli/frontends/gosrc2cpg/src/main/resources/application.conf
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodTests.scala

1. Added unit test in ignore state for use case a. Pointer to pointer parameter type handling is not done b. struct paramter imported from external package with `.` alias.
2. Addition of parameter node to `scope`. 
3. Handling for use case function is being called before it has been declared in the same file. `goastgen` will create a `FuncDecl` inside `CallExp` being created for the method call and refer this `node_id` from the place `FuncDecl` is declared. Have added respective unit tests for the same.
4. Upgraded `goastgen` to new `0.8.0` to pickup parallel process changes done in it.
5. Handled some past review comments by David

[gosrc2cpg] - pending items for method node

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala

Currently any crashes would result in an empty cpg, even when the ast for some files could be created correctly. This PR changes this behaviour to allow scanning projects with some broken source files.

Don't re-throw javasrc astcreator errors to allow working files to be added to the ast

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodTests.scala

1. MethodReturn Node handling for single return type.
2. Refactored the code around `processTypeInfo` method.
3. Also removed unwanted white space between method name and `(` while generting the method signature. Made changes in unit tests to adjust to this change.
TODO:
1. Need to work on tuple handling.

[gosrc2cpg] - Simple return node handling

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForDeclarationsCreator.scala

```
[warn] -- [E121] Pattern Match Warning:
/home/mp/Projects/shiftleft/joern/joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForDeclarationsCreator.scala:519:11
[warn] 519 |      case _                   => false
[warn]     |           ^
[warn]     |Unreachable case except for null (if this is intentional,
consider writing case null => instead).
```

kotlin2cpg: deprecation fix: pattern match

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/CallCpgTests.scala

Fixed an instance of the call node construction not including the other arguments if a do-block was one of the arguments.

[rubysrc2cpg] Fixed Call with Block Ignoring Args

---

console/src/main/scala/io/joern/console/workspacehandling/WorkspaceLoader.scala

i found it easiest to use ujson for this simple task...
```
[warn] -- Deprecation Warning:
/home/mp/Projects/shiftleft/joern/console/src/main/scala/io/joern/console/workspacehandling/WorkspaceLoader.scala:56:56
[warn] 56 |    val map     = jsonRead[Map[String, String]](content)
[warn]    |                                                        ^
[warn]    |Compiler synthesis of Manifest and OptManifest is deprecated,
instead
[warn]    |replace with the type `scala.reflect.ClassTag[Map[String,
String]]`.
[warn]    |Alternatively, consider using the new metaprogramming
features of Scala 3,
[warn]    |see
https://docs.scala-lang.org/scala3/reference/metaprogramming.html
```

console: fix deprecation warning

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStructuresCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ASTCreationForStructureTests.scala

Changes:
1. Added support for Go's structure.
2. Covered test cases having simple structure definition to complex(one structure used under another)

gosrc2cpg: structure support

---

build.sbt
console/src/test/scala/io/joern/console/workspacehandling/WorkspaceLoaderTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ObjectExpressionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/CustomAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

n.b. I dropped the test because I didn't deem it helpful - we don't
need to test a json library that we don't maintain

fix deprecation warnings in Test/compile

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/GoSrc2Cpg.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/Defines.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/datastructures/GoGlobal.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/CallTypeAndSigntureLinkerPass.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ASTCreationForDeclarationsTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ASTCreationForExpressionsTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ASTCreationForMethodCallTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/AstCreationForArraysTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/testfixtures/GoCodeToCpgSuite.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/Code2CpgFixture.scala

1. Updated call node methodFullName, typeFullName and signature recovered for methods defined within the same project. We first tag identified call nodes TypeFullName with `<TO_BE_FILLED>`. While processing method declarations, we cache the Method Return type full name and signature. With additional `CallTypeAndSigntureLinkerPass` pass, we look for call nodes whose TypeFullName is tagged with `<TO_BE_FILLED>` and update their type fullname and signature by doing a lookup inside the cache.
2. Listed builtin functions of go while identifying  return type and signature
3. Respective unit tests covering call node use cases. TODO: There are a few more use cases that need to be added.
4. Made changes to create `IDENTIFIER` node when a variable is only declared.
5. Identified bug while setting …

[gosrc2cpg] - Call node handling

---

joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ArraysTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ConditionalsTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/DeclarationsTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ExpressionsTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/LoopsTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodCallTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/OperatorsTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/SwitchTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeDeclTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/VariableReferencingTests.scala

The Test file names were not very quickly readable because every files starts with `AstCreationFor` removed the unwanted prefix for all the tests to make it more readable.

[gosrc2cpg] - Refactoring of test file names

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/package.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/StepsTest.scala

this fixes the following, since `.sorted` returns a `Seq`:
```
joern> cpg.method.external.fullName.sorted.browse
-- [E008] Not Found Error: -----------------------------------------------------
1 |cpg.method.external.fullName.sorted.browse
|^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|value browse is not a member of Seq[String]
```

make steps (`.s`, `.browse` etc.) available on `IterableOnce` also

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/ExtendedCfgNode.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/nodemethods/ExtendedCfgNodeMethods.scala

One can silently fail by accidentally calling `sink.reachableBy()` and there will not be any feedback due to the variadic style of the arguments. This change forces at least 1 source to be given, with optional extra sources to follow.

[dataflowengine] Force at least 1 source argument for `reachableBy`

---

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/TryTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala

In the case of a try-block, if an explicit return node was given then the fringe would be erased (due to the nature of the `++` operator) and the Cfg would no longer be a graph rooted in the method node. The first statement in the try block would have it's fringe erased by the Cfg of the return node and thus be dangling.
This change would detect if the return node is within a try-block and conditionally inherit the fringe.
E.g.
```
public static int tryWithExplicitReturn(String args) {
try {
var x = 1;
System.out.println("in begin");
return x;          // <---- the culprit
} catch (Exception e) {
System.out.println("Something went wrong." + args);
}
return 1;
}
public static void test10(String[] args) {
String s = "MALICIOUS";
tryWithExplicitReturn(s);
}
```

[CfgCreator] Fixed fringe erasure in try-blocks

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/parser/JsValueVisitor.scala

this PR makes the following warning disappear:
```
[warn] -- Warning: joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/parser/JsValueVisitor.scala:40:15
[warn] 40 |  override def visitArray(length: Int, index: Int): ArrVisitor[Value, Value] =
[warn]    |               ^
[warn]    |               No DRI found for query: Visitor
[warn] -- Warning: ujson/src/ujson/JsVisitor.scala:76:15 ------------------------------
```
Context: the warning "No DRI..." comes from scaladoc as it tries to
lookup all references. The referenced `Visitor` is actually in the
parent class that's not within this repo. Copying and adapting it
works though...
There's one more that seems even more obscure...
```
sbt:joern> jssrc2cpg/Compile/doc
[info] Main Scala API documentation to …
```

fix strange scaladoc warning

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala

Follow-up on https://github.com/joernio/joern/pull/3572 to fix non-exhaustive match by logging a warning and returning a fairly "empty" result

[gosrc2cpg] Fix non-exhaustive match

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/SootAstCreationPass.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/util/ProgramHandlingUtil.scala

* Replace manual parsing code with `org.objectweb.asm.Type` static parsing calls. This also resolves warnings over "deprecated: use scala.util.boundary instead"
* Fix IDE warnings on unused code or code that could be private, general house keeping, etc.

[jimple2cpg] Using ASM's Type.getType instead of manual parsing

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForTypeDeclCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeDeclMembersAndMemberMethodsTest.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeDeclTests.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreator.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForDeclarationsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForFunctionsCreator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/NodeBuilders.scala

1. Changed the signature of `x2cpg` `NodeBuilders.newThisParameterNode` method to take `name` and `code` as a parameter and set defaults to `this`. This is done to use the receiver name as is defined in the code instead of naming it as `this`. This will make sure to have `ref` edges built as natural processing of `Identifiers.`  Have updated the places where this method was getting called to adjust with the updated interface.
2. `ThisParameterNode` handling while generating AST for method declaration that can be called with struct  type receiver
```
type Rect struct {
len, wid int
}
func (re Rect) Area_by_value() int {
return re.len * re.wid
}
```
3. Handling for more than one member, defined as a `,` separated list of the same type. 
```
package main
type Rect struct {
len, wid int
}
```

[gosrc2cpg] - Receiver node or `thisParameterIn` node handling while processing method declaration 

---

joern-cli/frontends/gosrc2cpg/src/main/resources/application.conf
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/utils/AstGenRunner.scala

we can now exclude file for go frontend:
`importCode.golang.apply(inputPath = "path", projectName = "name", args = List("--exclude-regex", "regex"))`

[gosrc2cpg] - support to exclude files

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodCallTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/SwitchTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeDeclMethodCallTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeFullNameTests.scala

1. Initial call node handling for struct object to set proper method fullname and signature.
2. Refactored some code inside `AstForPrimitivesCreator.astForIdentifier`. Along with that, I refactored some unit tests to make it them more readable.
3. Added few unit test for TypeFullName Checks.
4. Changed method signature for method node to remove the receiver type prefixed as its already been prefixed in the method name used in the signature.
TODO:
1. 0th index argument node handling.
2. Issue identified in switch case handling.
3. Updating typeFullName of the LHS identifier when type is not declared and it is inferred from RHS.
4. FieldAccess call node handling.

[gosrc2cpg] - call node handling for method called on struct object

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/IdentifierToCallPass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/AssignCpgTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/CallCpgTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/RescueKeywordCpgTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/cfg/SimpleCfgCreationPassTest.scala

This PR was intended to only address the issue where calls without parenthesis were detected as identifiers due to not having the method within immediate scope, but I found that Ruby CPGs do not generate `LOCAL` nodes which was necessary for this feature.
* Corrected `.code` property for binary operation calls
* Added `IdentifierToCallPass` to heuristically determine if an identifier is meant to be a call node and would replace it in-place.
* Modified the `scope` variable by introducing a new `RubyScope` subtype that can generate local variables of the given scope and link them to their identifiers.
This resulted in many tests to be modified if they checked on certain properties.
**Note**: `this` parameter nodes need to be tested as I saw this wasn't being generated implicitly.

[rubysrc2cpg] Creating Locals & Detecting Non-Parenthesis Calls

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/dataflow/MethodAndCallDataFlowTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ArraysTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ConstructorCallTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/FieldAccessTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodCallTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeDeclMethodCallTests.scala

1. Receiver argument handling for method call nodes
2. Fixed the duplicate call nodes getting created for Constructor call nodes.
3. Few additional unit tests
4. FieldAccess call node handling along with field identifier.
5. Created `NotHandledType` for the ast types which we have not yet handled and logged the warning.
6. Some other code refactoring.

[gosrc2cpg] - FieldAccess call node handling along with Receiver identifier handling for method call node.

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/LoopsTests.scala

In Go Language we can define `for-loop` even without break condition.
Example:
```
package main
func main() {
for {
}
}
```
Changes:
1. Handled case where `initParserNode` and `condParserNode` can be empty for `for-loop`

gosrc2cpg: for loop without break condition

---

joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/dataflow/MethodAndCallDataFlowTests.scala

Added ignore test case where a internal call is returning two objects.
cc: @pandurangpatil @DavidBakerEffendi

gosrc2cpg: added tuple return ignore case

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForDeclarationsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/JavaScopeElement.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/BindingTable.scala

This PR is the first in a series of javasrc2cpg refactors and this just moves code related to method creation, lambda creation and type decl creation into separate traits (following the pattern used by other frontends). This does not actually change any code though, and more specific cleanups will follow in separate PRs over time.

[javasrc2cpg] Move method, lambda and type decl creation into separate AST creators

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImportResolverPass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryPass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/CustomAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/FileTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MethodOneTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/NamespaceBlockTest.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/TypeDeclAstCreationPassTest.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/cfg/SimpleCfgCreationPassTest.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/FunctionTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MiscTests.scala

This PR follows up from the discussion of https://github.com/joernio/joern/pull/3611. It was found that some identifiers were not linked via REF edges to their local nodes and thus causing issues with dataflow.
* Fixed instances of dangling identifier nodes from their referencing local nodes by extending `RubyScope` functionality.
* Fixed code for RHS of arrays
* Moved type/method ref assignments at the beginning of the block (after locals) so that it is before their references
* Made `signature` and `name` properties consistent with arrays and binops
* Added ScalaDoc comments to RubyScope
* Implemented constructors
* Moved to using x2cpg AstBase methods where possible
* Use `relativeFilename` instead of `filename`
* Lots of general optimizations
cc @khemrajrathore

[rubysrc2cpg] Follow-Up to Local Node & Identifier Handling 

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/Main.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala

The documentation for the options are listed here:
https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.cdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcdt%2Fcore%2Fdom%2Fparser%2FAbstractCLikeLanguage.html
Skipping function and method bodies enables downstream tools to perform a faster signature-only parsing.

Exposes couple of cdt performance options

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodTests.scala

Handling:
If key is not found under parserNodeCache (https://github.com/joernio/joern/blob/master/joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala#L47) program is breaking with `key not found` exception which is halting further processing of file.
Test Case:
Added breaking test case for which processing is skipped (where node_reference_id is exist). We need to handle it separately.
cc: @pandurangpatil @ankit-privado

gosrc2cpg: handledling ast creation when reference id found in node

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodCallTests.scala

Handled call node creation when it is invoked on chain of calls such as:
```
person.SetName("John").SetAge(30).SetLocation("New York")
```
Breaking test case(marked ignore for now): call node falling between start and tail call are not getting added in AST.

gosrc2cpg: call on chained method calls(like builder)

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/Defines.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/parser/ParserAst.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/BuiltInMethodCallTests.scala

Background:
In Go programming language, the  make  function is used to create and initialise slices, maps, and channels.
In current pull request I have added support for make function over a map.\
cc: @pandurangpatil @ankit-privado

gosrc2cpg: Inbuilt method(make) support

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForTypeDeclCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/FileTests.scala

1. While creating TypeDecl node, we were using only fileName instead of the entire relative path. Made changes to fix along with respective unit tests
Fixes #3649

[gosrc2cpg] - fix for #3649 for additional node 

---

joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeDeclMethodCallTests.scala

sample code:
`
func NewService(node *Node) *Service {
return &Service{
value: &Node{node},
}
}
`
return statement is where a structure is initialised. Expectation here is: a call node with `Service` as name should be get created with single parameter.
In pull request I have added two test cases where we are covering argument of Node structure is primitive and non-primitive.

gosrc2cpg: return statement struct initialisation

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/DoBlockTest.scala

* Handling method definitions using `define_method` keyword
* Fixed bug where do-block functions always assumed max 1 parameter
TODO: Method names defined by identifier values or other dynamic operations are not handled.

[rubysrc2cpg] Basic Metaprogramming Handling

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/LoopsTests.scala

In Go we can even write a for loop in below fashion:
for range collections {
isTrue = isTrue && <-shutdownChan
}
We can able to a iterator over item in collections is not mentioned here, Go handles this implicitly.

gosrc2cpg: added range loop support

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/MethodTwoTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MiscTests.scala

* Implemented `define_method` handling when parenthesis are used
* Fixed dangling identifiers when they are converted to method parameters by removing them from scope
* Properly propagated do-block function AST members as a Seq
* All tests in MethodTwoTests are un-ignored and pass
* Modified tests here and there, with dotAst visual confirmation of fixes

[rubysrc2cpg] General Do-Block Function Fixes

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/SwitchTests.scala

Fix for issue #3678.
For now, this PR fixes the issue related to the breaking error for the Local node being pushed to as a condition AST node for switch AST. 
Fixed the issue and resolved the breaking error.
This will still require a proper fix to push the Assign AST as the first child of which block AST. We will handle this issue at a later stage.

[GO] - Fix for ticket #3678

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/Defines.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ArraysAndMapTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ExpressionsTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeFullNameTests.scala

1. LHS typeFullName set with RHS typeFullName handling covering bothe the declration styles.
2. Boolean LITERAL handling required different way of handling. Made respective changes along with corresponding unit tests.
3. Changed Array Initialiser to take array elements as its argument nodes. Which was not done earlier. Made respective changes in all unit tests.
Fixes #3614
TODO: Add more unit tests and handle Struct type member typeFullName handling along with its cache

[gosrc2cpg] - LHS typefullname set with RHS typeFullName fix for #3614

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForTypeDeclCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/CacheBuilder.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/datastructures/GoGlobal.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ConstructorCallTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/FieldAccessTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/FileTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/NamespaceBlockTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeDeclMethodCallTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeDeclTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeFullNameTests.scala

fixes ticket #3665
Type Decl Member type cache and use the same
1. Processed `TypeSepc` information to build the cache mapping members to TypeFullName
2. Used this cached information to set the TypeFullName for FieldAccess `CALL` node.
3. Updated unit tests as well as added new unit test to verify these changes.
4. Gone through a few IGNORED unit tests and update those unit test in working state
5. Refactored a few TypeFullName tests to merge a few non-working and working tests.
2. Removed setting the ParentTypeFullName and ParentType for TypeDecl node as that was unnecessary. Removed respective unit tests checking the same.

[gosrc2cpg] - Struct type member Type information cache - fixes ticket #3665

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/CacheBuilder.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/datastructures/GoGlobal.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeFullNameTests.scala

**package name is different from the namespace folder name**
Handling for the scenario when the package name and namespace folder name are different.
In the below example, we are importing `joern.io/sample/lib` but `fpkg` alias is getting used. We created a global cache for this mapping and did the lookup if the alias to namespace lookup fails for the file level mapping we maintain.
```
package main
import "joern.io/sample/lib"
func main() {
var a = fpkg.Woo(10)
var b = fpkg.Sample{name: "Pandurang"}
var c = b.Name
var d fpkg.Sample
}
```
**Type declared after its being used**
Member Type cache wasn't getting populated before AST Creation pass is invoked. It seems the respective unit test didn't cover the scenario, which will cover this scenario where it is required to have a cache built …

[gosrc2cpg] - Handling for scenario where package name is different than the enclosing folder name of the package

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala

Currently in Kotlin2Cpg, If we are unable to download dependency for some reason, we cancel the scan, This PR proposes to continue scanning even if we are unable to download dependency

[Kotlin2Cpg] - Continue with cpg generation even if unable to download dependency

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForTypeDeclCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/CacheBuilder.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/Defines.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/datastructures/GoGlobal.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/DownloadDependencyTest.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/GlobalVariableAndConstantTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/TypeDeclMethodCallTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/testfixtures/GoCodeToCpgSuite.scala

Handling for package level global variable access. Fixes #3695
1. Handled package level global variable access with FieldAccess `CALL` node with respective handling to set the TypeFullName properly.
2. Made changes to handle the situation where we couldn't identify the TypeFullName in that situation, we are setting the TypeFullName of the receiver with respective labels postfixed to it like `<FieldAccess>` or `<ReturnType>`.
3. Updated respective unit tests along with a few more unit tests.
TODO:
Need to handle Global Variable Declaration.

[gosrc2cpg] - Handling for package level global variable access. Fixes #3695

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XImportResolverPass.scala

Encoding the values of the entries with base64 to avoid instances where `,` is in the value, causing extra pairings during parsing. Base64 mappings do not include ',' so it should be safe.
TODO: Replace this with a non-TagNode implementation.
Resolves [#3701](https://github.com/joernio/joern/issues/3701)

[ImportResolver] Encoding Values to Avoid Separator Char

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/AstCreator.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/passes/DeclarationRefPass.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/LocalTests.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/MethodParameterTests.scala

Somehow, `jimple2cpg` has gone this long without parameter/locals with REF edges to identifiers.
A quick solution is following it with a ref edge pass, since the AST is flat so there is always one block under a method.

[jimple2cpg] Declaration Ref Edges to Identifiers

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/DoBlockTest.scala

Removed adding do block functions from chained invocations to the block method map to reduce duplicate method creation.

[rubysrc2cpg] Fixed Duplicate Do-Blocks Due to Side-Effect

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForPrimitivesCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/KotlinTypeHintCallLinker.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/KotlinTypeRecoveryPass.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/postProcessing/TypeRecoveryPassTest.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/testfixtures/KotlinCodeToCpgFixture.scala

The PR contains
- Introduction of TypeRecoveryPass as a Post processing step
- Fix - To get the actual import name and assign it to importNode while AST Creation
- 3 test case to validate the TypeRecovery changes, out of which 1 test case is in ignored state, which will be worked on in subsequent PR's
Note - The TypeRecoveryPass changes have been referred from Java Frontend

Kotlin2Cpg - Introduction of TypeRecoveryPass

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/LiteralCpgTests.scala

fix for: https://github.com/joernio/joern/issues/3725

[Gosrc2cpg] - Limit literal code character length

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ast/DoBlockTest.scala

Fixed bug regarding do-block functions as control structure conditionals.
Example AST:

[rubysrc2cpg] Do-Block Function as Conditional

---

build.sbt
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/AstLinkerPass.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/passes/AstLinkerPassTest.scala

Prerequisite changes to fix #3695 issue.
Handling done to set the member node under given TypeDecl parent.

Prerequisite changes to fix #3695

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/GoSrc2Cpg.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/CacheBuilder.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/datastructures/GoGlobal.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/model/GoMod.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/DownloadDependenciesPass.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/MethodAndTypeCacheBuilderPass.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/ArraysAndMapTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/FileTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/MethodTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/NamespaceBlockTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/VariableReferencingTests.scala

This is one more partial handling for package-level Global variable handling ticket #3695 
Earlier, we were creating an AST structure per file in the following way.
NameSpaceNode(`package prefixed with filename`)=>TypeDecl(`Fake TypeDecl node representing the given file`)=>Method(`Fake Method node representing the statements (imports, gobal var and constants, types and functions) in the given file`)=>Block(`all the direct statment asts as child nodes`)
With the new structure, we wanted to create a Fake TypeDecl node representing one package (One package can have multiple go files in it). In order to achieve this, we are following the order of nodes being created for a package and then for a file.
For package, i.e. per folder
NameSpaceNode(`one namespace node representing one …

[gosrc2cpg] - Made structural changes while creating initial AST nodes per file #3695

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ImportResolverPass.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala

Fixes a bug where import relativity was always treated as within modules on the root, and did not resolve types relative to the project root.

[pysrc2cpg] Import Resolution in Non-Root Module

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForDeclarationsCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/dataflow/TypeDeclTests.scala

Fixed a bug where secondary constructors share the same call node to the primary constructor.
Resolves #3706

[kotlin2cpg] Secondary Constructor Sharing Same `<init>`

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CallTests.scala

When a static method call is made by referring to `self`, the AST node created for it failed to resolve the proper method full name.
For example:
```
<?php
class Foo {
static function bar($x) {
return 0;
}
function baz($x) {
self::bar($x);
}
}
```
The method full name of the call node for `self::bar($x)` is `self::bar`, but it should be `Foo::bar`.
This PR resolves the method full name of functions called by `self`.

[php2cpg] Resolve static method call name when called by self

---

build.sbt
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/jpastprinter/JavaParserAstPrinter.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/SourceParser.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/OffsetTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstNodeBuilder.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/OffsetUtils.scala

This PR implements the FILE_CONTENT property changes introduced in https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1737. 
Currently a temporary `enable-file-content` option is added (disabled by default) to avoid accidental source in commercial CPGs due to release schedules, but a `disable-file-content` is also added with the intent of enabling file content by default which can be turned off by this flag (currently unused).

Add file content flags and support to javasrc2cpg

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/TypeInfoCalculator.scala

The body of this match can throw an `UnsolvedException` under certain conditions (definitely when the JDK types are missing, possibly others), so this PR handles that more gracefully.
During testing, I also noticed that schema violation issues where parameters were missing edges to their defining methods were fixed by this change as well, so it seems they were caused by an incomplete AST due to the crash.

Fix javasrc crash that occurs when builtin types cannot be read from JDK

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

Fixes literals in method returns not having type information populated. This done via the type recovery pass.

[pysrc2cpg] Literals in Method Return Fix

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

Fixes a bug where method refs may add an additional argument under an operator assignment.

[TypeRecovery] Prevent Adding Method Refs Under Operators

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForDeclarationsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForExpressionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForFunctionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForStatementsCreator.scala

This PR aims to use `headOption` and `lastOption` instead of `head` and `last` when accessing from Seq[Ast]

[kotlin2cpg] - Use Defaults when Using Head/Last Calls

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/ReachingDefProblem.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ImportResolverPass.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XInheritanceFullNamePass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

Upon ingesting code bases with large methods that contain many child methods, the `.ast` call becomes extremely expensive on the top of the AST. This work reviews the performance of the CPG generation using the code reported in #3778 to inspect various "hanging" points which were largely related `.ast` calls. These `.ast` calls were replaced by their `_.containsOut` equivalent where appropriate to minimize the traversal depths.
Unfortunately, `XTypeRecovery` is still experimental and relies on `.ast`. Future work is planned to move this to `.statement` instead, and recover select symbols from which shortcut edges can be used. If `XTypeRecovery` hangs, the recommendation is to reduce the iterations to `1` or `0`.
Resolves #3778

[Performance] Replace `.ast` with `CONTAINS` Traversals where Possible

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/slicing/JsUsageSliceTests.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForDeclarationsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForExpressionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForFunctionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForStatementsCreator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstNodeBuilder.scala

Current creation of Local nodes in JS & kotlin dosen't have columnNumber, lineNumber.
We used same method to create LocalNodes as in other frontends.

[(js|kotlin)src2cpg] - Refactor the Local Node Creation to use `localNode` Where Possible

---

joern-cli/frontends/c2cpg/build.sbt

I don't know how this dependency slipped in there but it looks like it is not used at all.
@mpollmeier any idea? You added it with: https://github.com/joernio/joern/pull/816
All tests work fine and a locally build joern also works.

c2cpg: removed org.jline dependency

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ImportResolverPass.scala

This fixes a bug where `root` is always assumed to be a directory in `ImportResolverPass`.

[pysrc2cpg] Handle Import Resolution when Root is File

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ConditionalTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/SingleAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/ast/AssignCpgTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/ast/AttributeCpgTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/ast/BoolOpCpgTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/ast/CallCpgTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/ast/CustomAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/ast/MethodOneTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/IndexAccessTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala

In order to ballpark how big the gap between the two frontends presently is, this PR introduces 2 tags to annotate the deprecated frontend unit-tests with:
* `SameInNewFrontend` meaning that expectations are -essentially- the same in the new frontend, and there's already a unit-test covering this case there.
* `DifferentInNewFrontend` meaning that expectations are different in the new frontend, and there's already a unit-test covering this case there.
Ideally, all unit-tests in the deprecated version should become annotated, at which point we would have supported (in some way) all previous features.

[rubysrc2cpg] start gap comparison via unit-tests

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/dataflow/IntraMethodDataflowTests.scala

Fixes issue https://github.com/joernio/joern/issues/3745
I've discovered that no data flow is built between function calls, whereas data flows for the same code ported to `C` or `JavaScript` are found. Tracked down the problem to the function `sameVariable` of `DdgGenerator`. 
Problem is that this function compares two Nodes and tries to figures whether they are equal or not. With `PHP`, the node's _name_ is e.g. `my_input`, but the node's _code_ would be `$my_input` (mark the trailing $-sign). So the function fails by comparing the _name_ of the left node and the _code_ of the right node.
Added unit test.

[dataflowengineoss] Fix identifier name/code mismatch in the `sameVariable` function

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/ast/ReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

* Expands the implicit RETURN node handling for array and hash literals.
* When the last statement in a method is another method declaration, the result of invoking the outer method is the name of the inner method, e.g. invoking `f` after the following snippet returns `:g` (a symbol literal), rather than the method declaration itself:
```ruby
def f
def g = 0
end
f # returns :g
```
In the "v1" ruby frontend we would return a METHOD_REF. In the "v2" we explicitly return the symbol name.

[rubysrc2cpg] implicit RETURN node handling for array/hash literals and method declarations

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

Previously there was only support for `if-then-elsif-else-end` statements. Here we convert them to ternary conditionals when they are used as expressions, e.g. on the RHS of an assignment.

[rubysrc2cpg] support `if-then-elsif-else-end` expressions

---

.github/workflows/master.yml
.github/workflows/pr.yml

This prevents CI/CD to run if the only files edited are markdown files.
Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
> When all the path names match patterns in paths-ignore, the workflow will not run. If any path names do not match patterns in paths-ignore, even if some path names match the patterns, the workflow will run.
Resolves #3803

[CI/CD] GitHub Actions to Ignore `**.md` Edits

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/C2Cpg.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/PreprocessorPass.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/jpastprinter/JavaParserAstPrinter.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/SourceParser.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/MethodTests.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2CpgOnFileSystem.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/deprecated/passes/AstCreationPass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/SourceFiles.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/SourceFilesTests.scala

This PR addresses the following [issue](https://github.com/joernio/joern/issues/3811)
As of today we have 5 different overloaded `determine` method for getting SourceFiles, as part of this PR
- Removed the 2 `determine` methods which used `X2CpgConfig`
- Refactored 1 `determine` method to use `ignoredDefaultRegex`, `ignoredFilesRegex` and `ignoredFilesPath`
- Removed 1 `determine` method as it became redundant after refactor done by this PR
Effectively now we have 2 `determine` methods which can be used accordingly
Note - This refactoring is not applied to `JsSrc2Cpg` frontend, as there we have our own custom handling for ignored files

X2CPG : Refactor implementation and usage of SourceFiles determine method

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LambdaTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala

The closure bindings for Java lambdas are over-approximated to all variables in the surrounding context. This attempts to constrain this set to variables referenced in the AST body.
Note: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1739
Resolves #3790

[javasrc2cpg] Precise Variable Capturing by Lambdas

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/PreprocessorPass.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/jpastprinter/JavaParserAstPrinter.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2CpgOnFileSystem.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/deprecated/passes/AstCreationPass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/SourceFiles.scala

There was a bug, in Kotlin frontend where we are not applying file filtering to remove the excluded files. This PR takes care of that.
This PR is an extension of https://github.com/joernio/joern/pull/3813

[kotlin2cpg] - Apply `X2CpgConfig` File Filtering in Kotlin

---

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/modulevariable/Implicits.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/modulevariable/ModuleReferenceTraversal.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/modulevariable/ModuleVariableAsMemberTraversal.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/modulevariable/ModuleVariableTraversal.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/modulevariable/NodeTypeStarters.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/modulevariable/OpNodes.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/modulevariable/README.md
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/modulevariable/nodemethods/ModuleVariableAsMemberMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/modulevariable/nodemethods/ModuleVariableReferenceMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/package.scala

This query package, `modulevariable`, adds the necessary complexity to reason and handle the changes introduced by https://github.com/joernio/joern/pull/3750/
See the README.md for additional context.
One can now navigate the module members, the block references, the locals and identifiers referencing these variables, and go navigate back concisely.

[pysrc2cpg] Module Reference Query Layer

---

joern-cli/frontends/pysrc2cpg/pythonGrammar.jj
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/DictCpgTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/SetCpgTests.scala

It was errornously parsed as a set literal.

Fix empty dict literal parsing.

---

joern-cli/frontends/rubysrc2cpg/src/main/resources/log4j2.xml
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrParser.scala

* rubysrc2cpg was missing the usual log4j2.xml configuration file. Added here.
* ANTLR's default logging mechanism is to print everything to stdout. Here we make it use our logger instead.

[rubysrc2cpg] log ANTLR errors and inclusion of log4j2.xml

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

Allows the creation of implicit returns also for simple invocations and member accesses. The basic support was already in place, all that was required was allowing the conversion.

[rubysrc2cpg] allow implicit return of simple calls and member accesses

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala

We added an existing TypeDecl for a type alias twice if it was seen already ending up with AST edge loops over the same TypeDecl crashing .ast queries. This PR fixes that.
Fixes: https://github.com/joernio/joern/issues/3818

[jssrc2cpg] fix malformed CPG for type alias

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

getting the following error while scanning https://github.com/odinsride/olubalance repository. This may not be the proper fix, but at least the scan will continue instead of abruptly exiting the scan with an error.
```
java.util.NoSuchElementException: next on empty iterator
at scala.collection.Iterator$$anon$19.next(Iterator.scala:973) ~[org.scala-lang.scala-library-2.13.10.jar:?]
at scala.collection.Iterator$$anon$19.next(Iterator.scala:971) ~[org.scala-lang.scala-library-2.13.10.jar:?]
at scala.collection.Iterator$$anon$7.next(Iterator.scala:535) ~[org.scala-lang.scala-library-2.13.10.jar:?]
at overflowdb.traversal.TraversalSugarExt$.head$extension(Traversal.scala:64) ~[io.shiftleft.overflowdb-traversal_3-1.181.jar:1.181]
at io.shiftleft.semanticcpg.language.nodemethods.CallMethods$.arg …
```

[RubyTypeRecovery] Using Defensive `argumentOption(1)` Check

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

Just completing the list of abbreviated arithmetical assignment operators.

[rubysrc2cpg] support missing `||=`, `&&=`, etc. assignments

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala

Before this PR, `MemberAccess` is handled twice, which thankfully scalac notifies us about:
```
[warn] -- [E030] Match case Unreachable Warning: /home/mp/Projects/shiftleft/joern/joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala:203:11
[warn] 203 |      case node: MemberAccess    => astForReturnMemberCall(node) :: Nil
[warn]     |           ^^^^^^^^^^^^^^^^^^
[warn]     |           Unreachable case
```
I'm not familiar with the ruby frontend, but given that MemberAccess is handled separately, we can probably drop it from the first case.

rubysrc ast creation: fix double handled 'MemberAccess' case

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/LiteralTests.scala

[rubysrc2cpg] support `%()` literals

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala

The statements in the matcher statement first check `other.getParent != null` before checking `other != null`.  This has led to some NPE errors, reported by the community on Discord.
The fix makes sure `other` is not `null` before checking the parent.

[c/c++] NPE Due to Incorrect Order of Statements

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/AccessPathUsage.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/dataflow/DataflowTest.scala

1. Added ERROR log for missing node handling and continued with further processing. Added respective unit tests for the same. Note: This is not the fix, this will just unblock the further processing of the CPG.
2. Added a few comments as a result of suggestions from past PR review comments.

[dataflowengineoss] - Graceful Error Handling for AccessPathUsage

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptImportResolverPass.scala

Local imports in JavaScript are file paths, but can sometimes be string concatenations.
These are currently not simulated, and are given directly to a path resolution. This, however, will throw an exception.
This commit wraps this resolution in a try-catch and gives a sensible default for the CPG to attempt to look-up against.
Resolves #3903

[js] Defensive Import Resolution

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForNameExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForForLoopsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForSimpleStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/JavaScopeElement.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/TypeDeclContainer.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/EagerSourceTypeSolver.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/TypeInfoCalculator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/BindingTableAdapterImpls.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/NameConstants.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/AnonymousClassTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ConstructorInvocationTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LambdaTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LocalClassTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MemberTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeDeclTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/util/ScopeTests.scala

This PR adds capture logic to nested and inner classes that mimics javac logic. In short, captured variables are represented as members in the capturing class and are passed as extra constructor arguments. In addition, an `outerClass` member/parameter is created with `this` from the outer class passed in, which can then be used to access captured members and methods. For example,
```java
class Foo {
int fooMember = 0;
void foo(int x, int y) { ... }
void definesClass(int capturedParameter) {
class Bar {
void bar() {
foo(fooMember, capturedParameter);
}
}
Bar b = new Bar();
b.bar();
}
```
is represented as
```java
class Foo {
int fooMember = 0;
void foo(int x, int y) { ... }
void definesClass(int capturedParameter) {
class Bar {
int capturedParameter;
Foo outerClass;
public Bar(Foo …
```

[javasrc2cpg] Add anonymous classes and captures for inner classes

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Main.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/util/ProgramHandlingUtil.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/unpacking/JarUnpackingTests.scala

The [PR 3170](https://github.com/joernio/joern/pull/3170) added a optino `--recurse` for `jimple2cpg`, but without max-depths limit.
And also, this make the behavior of `jimple2cpg` odd. If you want to scanning a directory with some jar file you have to specify the `--recurse` option. However, `--recurse` should only control whether to unpack "jars in jars" as described.
This PR correct the behavior, we can now scanning a directory directly without `--recurse` option. If want to enable the `recurse`, set the `--recurse`. And I have add a option `--depths` to control the max-depths of recurse, the default value of max-depth is 1, that's meaning all the jars in a jar file will be unpack but the jars in theses jar will no be unpack again (unless you set the `--depths` to 2).

[jimple2cpg] Add maximum depths for recurse unpack "jars in jars"

---

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LambdaTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/TypeNodePass.scala

The regex just matched everything following the last `.` in the type name until the `:`, but this can easily be done without a regex.

Replace typeNodePass regex with more efficient name extraction

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/GoSrc2Cpg.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForLambdaCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForMethodCallExpressionCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPackageConstructorCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForTypeDeclCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/CacheBuilder.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/datastructures/GoGlobal.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/DownloadDependenciesPass.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/MethodAndTypeCacheBuilderPass.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/PackageCtorCreationPass.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/testfixtures/GoCodeToCpgSuite.scala

1. It seems creating NewMethodNode directly was causing this issue. As the `methodNode()` from `NodeBuilder` was also setting some offset. Not sure what exactly it does. So, I tried creating the Dummy `ParserNodeInfo` object and used it to call `NodeBuilder` methods.
2. Also refactored the code to use the class instance of GoGlobal instead of the Singleton object, which required clearing the state before each unit test execution.

[gosrc2cpg] - Fix for unwanted error because of malformed CPG creation

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/GoSrc2Cpg.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForGenDeclarationCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForLambdaCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/CacheBuilder.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/datastructures/GoGlobal.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/DownloadDependencyTest.scala

1. It's been observed that the AST nodes were getting created for package-level global variables and constants from the dependencies code. As it was getting processed through the same ASTCreators code. Made changes to handle this situation.
2. Also identified that the variables, constants, types and functions from dependencies which starts with lower case letter will not be referred from the main source code. Hence, I ignored the processing for those. This will also reduce the memory footprint as we are not storing that metadata in the cache. This will also speed up the processing
3. With a lesser memory footprint, unit tests with download dependencies should work. Hence enabled those unit tests. These tests will be helpful in identifying some breaking changes. Like the other ignore test …

[gosrc2cpg] - fix for package-level global variables from dependencies.

---

joern-cli/frontends/gosrc2cpg/src/main/resources/application.conf
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/GoSrc2Cpg.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/Main.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/model/GoMod.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/DownloadDependenciesPass.scala

1. `go.mod` also contains indirect dependencies, as we were processing all the dependencies to cache type and method signature metadata. Even with few direct dependencies, it may end up having many indirect dependencies, which are generally not used in the main code. Hence for now ignoring these indirect dependencies so that it can reduce the time it takes to download and process those dependencies.
2. Introduced the `include-indirect-dependencies` flag in case someone wants to try downloading and processing indirect dependencies.

[gosrc2cpg] - Ignore indirect dependencies

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/noncaching/JdkJarTypeSolver.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/JavaSrc2CpgTestContext.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala

* `JdkJarTypeSolver` is now built using a builder pattern, cf. `JdkJarTypeSolverBuilder`. This comes after the realization that `JdkJarTypeSolver` is essentially comprised of just a `parent`, `classPool` and `knownPackagePrefixes`. And, if it were not for `setParent` (which comes from `TypeSolver`), it'd have no mutators. Since we throw a runtime exception if we attempt to invoke `setParent` twice, I chose to cache `JdkJarTypeSolverBuilder`s instead of `JdkJarTypeSolver`s. This allows us to cheaply create new `JdkJarTypeSolver`s from `JdkJarTypeSolverBuilder`s each time we require a new one without changing any of the former's logic.
* The companion object method `JdkJarTypeSolver.fromJdkPath` now takes an extra parameter (`useCache = false`), which  looks up the given JDK path in a cache …

[javasrc2cpg] - add ability to cache JdkTypeSolver

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/SwiftSrc2Cpg.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCollectionCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/passes/DependenciesPass.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/passes/GlobalBuiltins.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/dependency/DependenciesPassTests.scala

Generated directly from the Swift AST withing the Package.swift file. That allows for dependency retrieval without manually parsing the actual dependency specification syntax.
To do that, this PR adds support for calls and array lists.

[swiftsrc2cpg] Added support for dependencies

---

.github/workflows/release.yml

A completion following the fix done here: https://github.com/joernio/joern/commit/73243dd31d860c212c8d0a856cd7a95f30e9d11e

Fix `release` Action: Specify Ruby Bundler

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala

* Wrapped `bindingContext.get(BindingContext.ANNOTATION, expr)` in `Option` to filter out instances where the return is `null`.
* Fixed bug where `fnDesc` was treated as a raw type, however it was already an `Option` type.
Resolves #3949

[kotlin] Null-safe Handling of `.get` and `Option`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala

The related issue assumes the RubyNode intermediate AST is complete for Begin, Rescue, Ensure, but this is not the case. The scope of this issue has crept to include handling the ANTLR-to-RubyNode AST feature for these expressions, as well as the AstCreator CPG building. This appears to be the case for a few of the other Ruby issues, which will influence their ETA accordingly.
Additionally, Rescue clauses in Ruby can contain splats which isn't handled yet in parsing. For now the exception list is will be an unknown block and posted as a medium-priority issue. I am unsure if adding a RubyNode for multipleRightHandSide affects anything else.
The scope of this PR is reduced to just the intermediate AST and the AST creator changes will be in a follow up.

[ruby] Begin, Rescue, Ensure (Try-Catch Statements) for intermediate ast #3927

---

.github/workflows/pr.yml
console/build.sbt
joern-cli/frontends/php2cpg/build.sbt

Without this, the milestone version of circe overrides the final release
that we really want to use.
fixes https://github.com/joernio/joern/issues/3924

use correct (non-milestone) circe version

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala

`filename` may already be an absolute path on Windows systems when running jssrc2cpg with an absolute path as input directory because node.js Babel works differently there (keeping that absolute path). When calling `in / filename` we would crash on Windows because concatenating two absolute paths with better.files throws an exception then.

[jssrc2cpg] Fixed crash on Windows

---

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/FieldAccessTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/layers/TypeRelations.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/typerelations/FieldAccessLinkerPass.scala

Given there is a `CALL.referencedMember` step, it suggests that the schema requires a REF edge between all calls accessing fields to the referenced member node.
This, however, is not the case in general and is neglected to be implemented consistently throughout frontends. The problem is fairly language agnostic, and one can rely on the `EVAL_TYPE` edge on the base of a field access along with the `FIELD_IDENTIFIER` to resolve the referenced member.
This pass executes the above, to create a reference edge between a field access and its referencing member.
Resolves #3950

FieldAccessLinkerPass: A Base Pass for Field Access -> Member

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/ConfigFileCreationPass.scala
joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/basic.yaml
joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/basic.yml
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/passes/ConfigFileCreationPassTests.scala

* Besides `*.properties`,  Spring also takes into account `*.{yaml,yml}` files, not necessarily named `application.yaml`, cf. https://docs.spring.io/spring-boot/docs/3.2.0/reference/html/features.html#features.external-config
Fixes #3943

[javasrc2cpg] - add YAML files as configuration files

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/TypeMap.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/io/ProjectParseTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/NamespaceTests.scala

Implemented a pre-pass that will allow one to maximize the type resolution during the AST creator phase.
In C#, it is common to import whole namespaces rather than individual classes, so this type map will allow one to fetch all declared classes from an imported namespace.
Resolves #3856

[c#] Type Map

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

- Set the name of method nodes of ruby initialize methods whose parent method ast is a TYPE_DECL to be `<init>`.
- Also set the full name AST accordingly
- Create a default `<init>` if no constructor is present
This is done pretty jankily, as I have added a stack  of boolean flags of whether the immediate TypeDecl contains a constructor. I'd love to know if there is a better way.

Add <init> naming for ruby constructors

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/typerelations/FieldAccessLinkerPass.scala

* Exclude indexAccess operations from being considered in `FieldAccessLinkerPass` to avoid unnecessary warnings.
* Added warnings in `XTypeRecovery` when a member doesn't have a type decl parent instead of throw schema exception. This will add to general robustness.

[x2cpg] Field Access Linker Warnings

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/typerelations/FieldAccessLinkerPass.scala

This fixes the incompatible field access operations from entering the `FieldAccessLinkerPass.dstMemberFullNames` by using the same name set as `cpg.fieldAccess`.
Follows from #4026

FieldAccessLinkerPass Use Same Name Check as `cpg.fieldAccess`

---

joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/ConcurrentTaskUtilTests.scala

These tests are too unpredictable to consistently pass, so they are to be removed.

Remove Flaky ConcurrentTaskUtilTests

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/macros/MacroHandlingTests.scala

If we encounter an IASTProblemStatement generated by CDT for an un-parsable macro we now retry parsing that particular code snipped standalone (without any macro expansion / context).
Fixes: https://github.com/joernio/joern/issues/4032

[c2cpg] Recover from un-parsable macros

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MethodParameterTests.scala

Noticed the following discrepancy w.r.t. a method parameter's type.
If a method's parameter type is (e.g.):
1. `List`, and we have no appropriate import, it resolves to `<unresolvedNamespace>.List`
2. `List`, and we have some kind of import (e.g. `import foo.List`), it resolves to `foo.List`
3. `List<String>`, and we have no appropriate import, it resolves to `<unresolvedNamespace>.List<String>` 
4. `List<String>`, and we have some kind of import (e.g. `import foo.List`), it resolves to `<unresolvedNamespace>.List<String>`
Comparing 1-2 vs 3-4, we see that when a type has type arguments, it may fail to resolve in a situation where it wouldn't fail if it had none. This PR makes it so that 4. resolves to `foo.List`.
There might be some valid reason we shouldn't do this that I'm not aware …

javasrc2cpg - workaround for failing to resolve a method parameter's type

---

dataflowengineoss/build.sbt
dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/testfixtures/SemanticTestCpg.scala
joern-cli/frontends/c2cpg/build.sbt
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/CCodeToCpgSuite.scala
joern-cli/frontends/csharpsrc2cpg/build.sbt
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DotNetAstGenRunner.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/testfixtures/CSharpCode2CpgFixture.scala
joern-cli/frontends/gosrc2cpg/build.sbt
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/testfixtures/GoCodeToCpgSuite.scala
joern-cli/frontends/javasrc2cpg/build.sbt
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala
joern-cli/frontends/jimple2cpg/build.sbt
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/testfixtures/JimpleCodeToCpgFixture.scala
joern-cli/frontends/jssrc2cpg/build.sbt
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/testfixtures/JsSrc2CpgFrontend.scala
joern-cli/frontends/kotlin2cpg/build.sbt
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/testfixtures/KotlinCodeToCpgFixture.scala
joern-cli/frontends/php2cpg/build.sbt
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/testfixtures/PhpCode2CpgFixture.scala
joern-cli/frontends/pysrc2cpg/build.sbt
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala
joern-cli/frontends/rubysrc2cpg/build.sbt
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala
joern-cli/frontends/swiftsrc2cpg/build.sbt
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/testfixtures/SwiftSrc2CpgFrontend.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/TestCpg.scala

Two main groups of properties are commonly duplicated among test fixtures:
* Dataflow processing with custom semantic definitions
* Post processing passes
This PR uses a combination of traits and new additions to `TestCpg` to improve the re-usability and consistency of these among frontend fixtures.
I leave it up to the authors of the frontends to refactor these changes in each test suite.themselves. The result is that all test fixtures include the options for
```scala
.withOssDataflow(Boolean)
.withExtraFlows(List[FlowSemantic])
.withPostProcessingPasses(Boolean)
```
Misc: Added a fix for #4019

Unify Common Test Fixture Properties (Note Possible API Changes)

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/FreshVariableCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala

This draft translates ruby `case` expressions into `if-elif-...-else-end` chains. 
The expression matched against is assigned a temporary variable `<tmp-#>` where # is a number. I was not sure on the convention but I wanted to be sure the variable is always fresh.
A single when can contain a list of expressions to match against, which I translate into an `or-expression` if there is more than one. When matching against an expression `mExpr`, it is turned into a condition with `mExpr.=== <tmp-#>`.
This list of expressions can contain a splat at the end, which we aren't handling yet.
It also remains maybe to special case to a switch ast if all match expressions are literals.
TextSpans for the generated intermediate ast are not sane and will need to be considered more carefully.
Sanity …

[ruby] when Statements (Switch Statements) #3926

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MethodTests.scala

This is a continuation of #4037, but this time relative to a method's return type - the same discrepancy is observed.
Missing from that same PR was the handling of method parameters from a `ResolvedMethodLikeDeclaration` in `calcParameterTypes`. 
I'm not proud of applying the same fix twice, but I don't see a good way around the handling of ordinary parameters and parameters from a `ResolvedMethodLikeDeclaration` without uncomfortable drastic changes, so I even reused the comment. Let me know if you can think of a better way.

javasrc2cpg - workaround for failing to resolve a method's external return type when it contains external type arguments

---

.gitignore
joern-cli/frontends/c2cpg/build.sbt

The currently used CDT dependency is > 3 years old and won't get any updates (the spotless project repacked CDT as standalone release because CDT itself isn't published via Maven).
We now use the packaged jar artifact from CDT's build server instead and unsign it.

[c2cpg] Use direct CDT dependency

---

joern-cli/frontends/pysrc2cpg/pythonGrammar.jj
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/memop/MemoryOperationCalculator.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pythonparser/AstPrinter.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pythonparser/AstVisitor.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pythonparser/ast/Ast.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pythonparser/ParserTests.scala

- Add support for new generic type syntax introduced in python 3.12.
- Add tests for quote reuse in python 3.12 format strings.
- Create unknown node for new type alias statement of python 3.12.

Python 3.12 support.

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ImportsPass.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitorHelpers.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonImportResolverPass.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonTypeRecovery.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/ImportCpgTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/MethodCpgTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala

Hierarchical imports like 'import a.b' are now represented correctly.
Do not yet merge.

Properly handle python sub module imports.

---

.github/workflows/pr.yml
CITATION.cff

GitHub apparently can't parse the CITATION.cff file and gives no feedback. This GitHub action will give us more insight.

Validate CITATION.cff

---

joern-cli/frontends/c2cpg/build.sbt
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroArgumentExtractor.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/ExternalCommand.scala

I changed the visibilities upstream and the maintainers agreed. Hence, we can use `org.eclipse.cdt.internal.core.parser.scanner.PreprocessorMacro` and `org.eclipse.cdt.internal.core.parser.scanner.TokenList` directly now.

[c2cpg] Use the CDT dependency directly without modifications

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/LoopsTests.scala

This PR includes,
1. Upgrading to new `DotNetAstGen` version.
2. AST Creation for `foreach` statements.
3. Tests for `foreach` statements.
4. Type Mapping for `PredefinedType` node.
Resolves #3986

[c#] Ast for `foreach` statements 

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/ExternalCommand.scala

With https://github.com/joernio/joern/pull/4068 c2cpg also got two different handlers for std err and out which messes up the handling/retrieval of system header file locations.

[c2cpg] Fixed logging from ExternalCommand

---

build.sbt
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/MethodMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/MethodTraversal.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/TypeDeclTraversal.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/testing/package.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/types/structure/MethodTests.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/types/structure/TypeTests.scala

With these new steps the parts of FILE content belonging to a TYPE_DECL
or METHOD can be easily accessed.

Add content steps for METHOD and TYPE_DECL nodes.

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala

* Added basic for-in loop support, mostly handling off each component to other visitors
* Added handling for `MandatoryParameter` as a basic identifier
* Added `handleNewVariableOccurrence` as a re-usable feature for handling new and existing identifier occurrences
* Removed debugging code in ControlStructureTests
* Added package heading to ControlStructureTests
Resolves #3936

[ruby] For-In Loop Support

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/SimpleDataflowTests.scala

Simple data-flows were not being propagated after some re-assignment. This was found to be caused by only a limited class of RHS nodes being handled on the EqualsValueClause. This has now been fixed and tested.
Other style-related changes added.
Resolves #4078

[c#] Fix RHS of EqualsValueClause

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForFunctionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForStatementsCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/WhenExpressionTests.scala

- Avoid null expression warning for Unit/void return statements.
We achieve this by not calling astForExpression on null.
- Avoid calling astsForExpression for null else branch.
- Properly handle 'when' statement/expression without argument.
- Add debug logging facility with declaration text and stack trace.

Kotlin fixes and debug logging.

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/ConfigFileCreationPass.scala
joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/hibernate.cfg.xml
joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/persistence.xml
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/passes/ConfigFileCreationPassTests.scala

Often JPA/Hibernate settings are stored in `persistence.xml` and `*.cfg.xml` files. In fact, they could be stored in any XML file and be referenced programatically. However, including all XML files in the CPG is probably a bit too much for some, so I chose a more conservative approach here. (If it would be ok to include all XML files, I'd happily propose a PR for that.)

javasrc2cpg - allow `persistence.xml` and `*.cfg.xml` files as ConfigFiles

---

joern-cli/frontends/swiftsrc2cpg/README.md
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/Main.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/AbstractPassTest.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/DirectiveTests.scala

We can't statically evaluate the conditions for these #if defs (they work pretty much the same is in C/C++). (plus, we do not want to re-implement the Swift pre-processor)
So we now provide a `--define` flag (same as in c2cpg) to set the desired config and generate all the sub ASTs accordingly. Obviously, this will only work for simple identifiers whereas Swift allows for arbitrary expression as `#if` condition.

[swiftsrc2cpg] Added support for IfConfigDecls

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/DirectiveTests.scala

Swift allows `#if` config clauses in between calls (and only there). So we have to manually patch the base node into the resulting member access call.

[swiftsrc2cpg] Added support for PostfixIfConfigExpr

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ControlStructureTests.scala

This PR includes, 
1. AST Creation for `Switch` statements.
2. Corresponding tests. 
3. Upgrading the `DotNetAstGen` version to allow new properties.
Resolves [#3984](https://github.com/joernio/joern/issues/3984)

[C#] Ast for `switch` and `label` statements

---

joern-cli/frontends/c2cpg/build.sbt
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/ExternalCommand.scala
joern-cli/frontends/c2cpg/src/main/scala/org/eclipse/cdt/internal/core/parser/scanner/MacroArgumentExtractor.scala

https://download.eclipse.org/tools/cdt/releases/11.4/cdt-11.4.0/plugins/
While we're waiting for 8.4 to get officially released, we need the old jar fiddling hack. 
That's unfortunate, but better than having commits in master that won't work in the future (e.g. if we need to bisect anything) because the jars disappeared from their CI (which they do after a week).

cdt: download from official releases rather than jenkins

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForNameExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/JavaScopeElement.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/BooleanOperationsTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala

The main purpose of this PR is to deduplicate assignment code paths that were handled separately for variable declaration expressions and assignment expressions, which in turn will help clean up code for object creation expressions. 
It also removes unused code for handling static imports (cases to handle static imports from the scope were added, but static imports weren't added to the scope since representing these properly is problematic). Static imports as `NewVariableType`s was causing some trouble since they don't really fit the pattern for the others.

[javasrc2cpg] Clean up assignment creation code

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ClosureTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MethodTests.scala

There's a pattern in `php2cpg` where ASTs are sometimes created, but not added to the graph (doing it this way seemed sensible at the time, but now I'm doubting that). Regardless, this was causing an issue with `astForNameExpression` which added ref edges from the newly created node to the declaring node directly to the graph, even if that AST was not added, resulting in orphan identifier nodes. These orphan nodes, in turn, caused issues with some backend passes.
This PR cleans up a few of the cases where the AST is created but not added, but also changed `astForNameExpr` to return the ref edges in the identifier AST instead of adding them to the graph directly, which fixes the orphan issue even if created ASTs are discarded.
This should also fix …

[php2cpg] Fix orphan identifier issue

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForStatementsCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/WhenExpressionTests.scala

This PR handles
- The assumption of having an `Else` block for when without argument 
- Initializes elseAst as `empty AST` instead of `null`, which results in runtime error while creation

[Kotlin2Cpg] - Handle when without argument and without else block

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/TypeMap.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeDeclTests.scala

* Parses interfaces like class declarations
* Handles methods with empty bodies
* Excludes inheritance handling, which is related to #3992
Resolves  [#3998](https://github.com/joernio/joern/issues/3998)

[c#] Interface support

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala

A follow up to https://github.com/joernio/joern/pull/4133 which cleans up another instance of usused AST elements being created.
The same issue exists for the condition ASTs in `astForSwitchCase` and `astForMatchArm`, but the correct fix for those would be a change to the lowering we do, so I'll do that separately.

Clean up unused created AST in class statements

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DestructuredAssignmentsTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala

* Handles desugaring a multi-assignment statement into pairs and eventually mapped to a list of single assignments
* Handles the case where there is an unpaired variable on the LHS, and simply leaves it undeclared as is the behaviour of the interpreter
Partially resolves #3931

[ruby] Multi-Assignment Statements (excl. Splatting)

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala

Allow users to specify multiple inference jar paths with a `:` separated list. I chose `:` since it's the path separator on Linux and not a valid path character in Windows.

Allow multiple colon-separated inference jar paths

---

.gitignore
joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/ast/CallCpgTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DestructuredAssignmentsTests.scala

* Modified grammar to expect splat operator in more positions on the multi-lhs
* Tested the splat operator slurping RHS variables for three tests
* Modified MandatoryParameter to contain its identifier
* Handle implicit slurping
Continuation of [#4136](https://github.com/joernio/joern/pull/4136)

[ruby] Handle Slurping of Multi-Assignments

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DestructuredAssignmentsTests.scala

* Handles the splat operator on an array on the RHS of a multi-assignment
* Rolls back change where we could expect two splats on LHS, but had to work around some other grammar restrictions for the splat operator being on other points in the multi-assignment, e.g., `*a, b, c = ...` and `a, *b, c = ...`
In the following example
```ruby
list = [2, 3]
a, b, c = 1, *list
```
We would get
```ruby
a => 1
b => 2
c => 3
```
But we may not always be able to see `list`, instead, this is approximated with an `<operator>.splat` call node to look like
```ruby
a => 1
b => *list
c => *list
```
Finally Resolves #3931

[ruby] Handle Multi-Assignment Splitting

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyProgramSummary.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/ScopeElement.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/datastructures/ProgramSummary.scala

This is a big one, but here we go
* Created basic implementation classes for `ProgramSummary` and `TypedScopeElement` in Ruby
* Added program summary hooks with implementation in `AstSummaryVisitor` that re-uses some `AstCreator` processes.
* Implemented pre-parse of high-level structures 
* Used this to fix implicit constructor bugs (and other bugs that were lurking around due to having 3 stacks)
* Differentiated modules/types to make sure implicit constructor wasn't created for modules
* Removed other stacks, only using `scope` now
Now we should be able to figure out if an `identifier` is a call or not with the lookahead that `RubyScope` and `RubyProgramSummary` provides us with.
Resolves #4128

[ruby] Program Summary & Typed Scope

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/Path.scala

so that the whole column uses less space

data flow table: use shorter column name for line number

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/deprecated/ParseInternalStructures.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/ast/CallCpgTests.scala

Following up on https://github.com/joernio/joern/pull/4145, this removes the mulithreaded pre-parsing.
The issue was that the underlying data structures in `packageTable` were not thread-safe, and thus resulted in race-conditions. As this is the deprecated frontend, I will leave the pre-parsing as serial for now.
Used this as an opportunity to add an additional test case, visiting modules & classes for methods in the look-ahead.
Resolves  #4057

[ruby] Fix Flaky Pre-Parse Test & Handle Class Look-Ahead

---

.github/workflows/master.yml
.github/workflows/pr.yml

Reverts joernio/joern#3807
I believe we didn't think this through back in the days... the result is that PRs like https://github.com/joernio/joern/pull/4182 can't get merged because CI doesn't run, while it's mandatory for CI to run in order to merge...
I guess we could perform the same check before running `sbt test`, but in order to unblock the linked PR, I'd like to revert this now.

Revert "[CI/CD] GitHub Actions to Ignore `**.md` Edits"

---

joern-cli/frontends/swiftsrc2cpg/src/main/resources/application.conf

This version of SwiftAstGen was built on Ubuntu 20.04 which ships with an older version of lib6-dev and libgcc9-dev. Hopefully, this unblocks our CS integration tests.

[swiftsrc2cpg] Update SwiftAstGen

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ConstructorInvocationTests.scala

Before this PR, 2 ASTs were created to handle the different cases for our constructor invocation lowering: one for the inlined version
```
Foo f = Foo.<alloc>()
f.<init>(...)
```
and one for the block version
```
bar({
Foo tmp = Foo.<alloc>()
tmp.<init>(...)
tmp
})
```
Both of these representations were passed back up in the AST creator (one as the return value for `astForObjCreationExpr` and one in a queue in the scope). Only the "correct" representation was then added to the graph.
With this new change, the representation is chosen before creating the `<init>` AST, so the correct representation is created directly.

[javasrc2cpg] Don't create 2 ASTs for init calls

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/JavaScopeElement.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ConstructorInvocationTests.scala

In javasrc2cpg inner classes, we have an `outerClass` constructor parameter for the captured outer class. Before, a reference to the enclosing class was always provided as an argument for this, but this is incorrect for inner class constructors, e.g. `new Foo().new Bar()` where the `outerClass` argument for `Bar.<init>` should be the value of the scope expression `new Foo()`. This PR fixes this issue.

[javasrc2cpg] Fix inner class constructors

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/CodeDumperFromContentTest.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/io/CodeDumperFromContentTest.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForPatternSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/io/CodeDumperFromContentTest.scala

In the presence of unmappable UTF8 characters we should not calculate offsets out of bounds. That happened if an unmappable UTF8 character was replaced by something of different length compared to the original source code. (when reading the file with `IOUtils.readEntireFile`)
(also a few improvements to swiftsrc2cpg AST generation)

[jssrc2cpg][swiftsrc2cpg] Safer offset calculation

---

joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CallTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

This PR partially fixes an issue that came up in https://github.com/joernio/joern/issues/4172.
In this case, the `file` identifier matches the `file` method name, so in `XTypeRecovery` the `handlePotentialFunctionPointer` confuses them and creates a `METHOD_REF` in any case. The `handlePontentialFunctionPointer` function comment 
```
/** In the case this field access is a function pointer, we would want to make sure this has a method ref.
*/
```
suggests that change in this PR is the intended behaviour, but I'm not sure about that and this isn't a proper fix for php either. Even if the `file` identifier were referring to a field, we'd still not want to enable this behaviour. A better fix could be to move `handlePotentialFunctionPointer` into the `XTypeRecovery` class to make it possible …

[XTypeRecovery] Fix type recovery function pointer bug

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ConstructorInvocationTests.scala

A copy of the synthetic temporary variable used as the init receiver in object creation expressions was added to the graph via a ref edge, but was not added to the AST. This PR fixes that issue. I've added a unit test for this, but also ran `cpg2sp` locally on 2 of the failing sptests projects with no crashes.

Fix orphan identifiers in object creation expressions

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyProgramSummary.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/ScopeElement.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

* Following [#4196](https://github.com/joernio/joern/pull/4196), similarly implemented a look-ahead and summary using an in-memory CPG
* Testing that a parenthesis-less call is correctly created as a call instead of identifier
* Resolving direct function calls if possible using the scope object
* Fixed scope around new pre-parse & loaded builtins

[ruby] Implement RubySummary with CPG Lookahead

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

* generate implicit return for index access
Resolves #4230

[ruby] Bug Fix - Generate Implicit Return for IndexAccess

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/Main.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HashTests.scala

* Added default ignore regex for test suites
* Added warnings to unhandled cases in `AntlrContextHelpers`
* Created common `RubyCall` traits
* Created the `DummyNode` to inject new nodes into `RubyNode` operations
* Made hashes return the `tmp` variable that is lowered
* Made all block arguments behave like lambdas so that they can be resolved to some function interprocedurally with an associated type and method decl
As per the comment on `astsForCallWithBlock`
```
/* `foo(<args>) do <params> <stmts> end` is lowered as a METHOD node shaped like so:
* ```
* <method_ref> = def <lambda>0(<params>)
*   <stmts>
* end
* foo(<args>, <method_ref>)
* ```
*/
```  
Resolves #4232

[ruby] Do-Block Arguments (with or without params)

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForExpressionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallsToFieldAccessTests.scala

1. As part of the performance issue troubleshooting exercise came across the issue where the FieldAccess `CALL` Node was getting created for chained field access e.g. a.b.c. While creating the fieldAccess `CALL` node for `.c` it was creating CALL node with `methodFullName` set to `<operator>.fieldAccess` and the name was getting set as `c` instead of the same value as `methodFullName`. Because of this, it resulted in creating many `METHOD` node stubs. In turn in StaticCodeLinker pass it was linking all the FieldAccess `CALL` Nodes to all of these `METHOD` stubs as the look-up was done over `methodFullName`. Added respective unit tests for the same.
2. Made respective changes to fix this issue.

[kotlin2cpg] Kotlin frontend FieldAccess CALL node issue fixes.

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala

Discovered during testing with https://github.com/OWASP/iGoat-Swift

[swiftsrc2cpg] Added support for missing operators and expressions

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala

This PR fixes an issue that was introduced in https://github.com/joernio/joern/pull/2831, where an error message in the unsolved symbol exception name would sometimes be appended to a wildcard.

Fix issue that resulted in error messages being used as namespace names

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ConditionalTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

* Added conditional related `RubyNode` traits to group control structure nodes
* Added `rubyNodeForExplicitReturnControlFlowExpression` to add a return node around the last statements in the correct places depending on the control structure as play
* Changed `endlessMethod` grammar rule to allow for a statement on the RHS as it wasn't detecting control structures such as ternary operators
* Removed the notion of a `ConditionalExpression` and simply mapped ternary operators to `if-else` statements to match the semantics
* If the control structure is an implicitly returned one, but lacks an else clause, then a default one is supplied as `return nil`
* Adjusted all tests accordingly
Resolves #4233

[ruby] Implicit Return Handling for Control Structures

---

joern-cli/frontends/csharpsrc2cpg/build.sbt
joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DotNetAstGenRunner.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/LambdaTests.scala

* Added basic handling for simple lambda expressions, which includes making the related Method/Type decl and method ref
* Parsing param type hints down from receiver if the lambda is used as a call argument, otherwise parameter isn't typed.
* Created a helper to unpack the type hint, as a collection type will be given, and too much context is stripped away to do this much more gracefully
* Updated DotNetAstGen and made appropriate changes for no longer having win-arm
Concerns #4000
TODO: Lambdas with multiple parameters 
TODO: Statement lambdas
TODO: Capturing variables

[c#] Simple Lambda Expression Handling

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/noncaching/JdkJarTypeSolver.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala

JavaParser represents "standard" nested class names `a.b.Foo$Bar` as `a.b.Foo.Bar`. Therefore, when looking up nested class names in the classpool, we need to convert the JavaParser name to the standard representation. This was done incorrectly, leading to type resolution failures for types we know about.
This PR changes the approach to try all possible combinations of `.` and `$` before returning an unsolved symbol (short-circuiting if a match is found), so for the example above we'd try:
- `a.b.Foo.Bar`
- `a.b.Foo$Bar` -- (found, so stop here but in theory also try the below if this was not resolved)
- `a.b$Foo$Bar`
- `a$b$Foo$Bar`

[javasrc] Fix JavaParser -> standard name conversion for nested classes

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

* added implicit returns for `MemberCall` and `Association`
Resolves #4234

[ruby] Implicit Return for `MemberCall` and `Assocation` nodes

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImportsPass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala

Add the import nodes in a new pass. The X2Cpg generic pass requires an assignment node for the importAs, but this doesn't fit the Ruby import mechanics which behave more like c `#includes` with dedup.

[ruby] Import Nodes & Require Support #3939

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala

* Handling `proc { ... }` or `lambda { ... }` expressions
* Made sure closure method/type decl's can attach to parent scope automatically by defining `AST_PARENT_FULL_NAME` and `AST_PARENT_TYPE` properties
* Using `AstLinkerPass` on summary to ensure the above is emulated
* Made a trait `LiteralExpr` to bind all literals, and added support for them in implicit returns
* Added `LAMBDA` modifier to closure method and type decls
* Implemented closure bindings and variable capturing
Resolves [#4248](https://github.com/joernio/joern/issues/4248)

[ruby] Proc Expressions & Captured Variables

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForPatternSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/SimpleAstCreationPassTest.scala

Type names from type annotation with ? (optional) or ! (implicitly unwrapped optional) are registered without ? or ! now as we do not process them as new types (we can't express such things in the CPG anyway).

[swiftsrc2cpg] Fix-up type names for optional types

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/FieldAccessTests.scala

Frameworks such as Ruby on Rails implicitly loads classes in a way that requires more careful analysis, which is the goal of [#3940](https://github.com/joernio/joern/issues/3940). For now, however, we can choose a layered approach of first looking at types in scope, then looking at the rest of the program. This is useful for instances such as `User.save`, where `User` doesn't have an associated `require`, nor is its definition in the same directory.
This PR does this, which allows `astForMemberCall` to resolve method calls, as well as adds simple handling for occurrences of the `self` identifier.

[ruby] Overapproximate Static Type References & Handle `self`

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCollectionCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/dependency/DependenciesPassTests.scala

Previously, we created a top level block if
1) a source file contained only one statement, and
2) a source file contained two or more statements
which resulted in two nested blocks in the second case where the statements are wrapped in a `CodeBlockItemListSyntax` node for which we always create a surrounding block.
With this PR we only create a block for 1 manually.

[swiftsrc2cpg] Fix creation of unnecessary nested blocks

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ConditionalTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

* implicit assignment of control structures to variables
* Adds `nil` assignment for `if` statements without `else` branches
Resolves #4245

[ruby] Added implicit assignment for control structures

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/passes/Defines.scala

- only calculate a type fullname if we have not seen that type already (extension types)
- re-use the typedecls fullname as return type fullname for its constructor instead of calculating a new one
- register types from inherits clauses

[swiftsrc2cpg] more type calculation and registration fixes

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala

* handling of explicit return statements in a control structure that is being handled as an implicit return.
Resolves #4273

[ruby] Bugfix - Handling explicit return statements in Control Structures

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Main.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2CpgOnFileSystem.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/config/ConfigTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/config/VenvExcludeTests.scala

- directories with a `pyvenv.cfg` file are ignored if `ignoreVenvDir == true`
- nothing is ignored if `ignoreVenvDir == false`
- if `ignoreVenvDir == true` and there is at least one folder set via old `--venvDir` or new `--venvDirs`: only these are ignored; no auto-discovery then

[pysrc2cpg] Added auto-discovery for venv directories

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/datastructures/ProgramSummary.scala

* Restructured `ObjectInstantiation` `RubyNode` as a trait, and the calls into `SimpleObjectInstantiation` and `ObjectInstantiationWithBlock` to leverage existing call handling
* Testing that object instantiations with blocks do the usual lowering, but also handle the block closure situation
Resolves #4274

[ruby] Block Constructors

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala

The fix for GH runners inadvertently causes issues on non-runner windows paths. This checks for this temporary folder, and prevents that extra handling in the necessary cases.
Resolves #4281

[c#] Fix `indexOf` Becoming out of Range on Windows

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/astcreation/AstCreator.scala

```
protected def astsForAnnotations(annotationTag: AnnotationTag, host: AbstractHost): Ast = {
val typeFullName = registerType(annotationTag.getType.parseAsJavaType)
val name         = typeFullName.split('.').last
val elementNodes = annotationTag.getElems.asScala.map(astForAnnotationElement(_, host)).toSeq
val code = s"@$name(${elementNodes.flatMap(_.root).flatMap(_.properties.get(PropertyNames.CODE)).mkString(", ")})"
val annotation = annotationNode(host, code, name, typeFullName)
annotationAst(annotation, elementNodes)
}
```
Some times the `annotationTag.getType` returns a `MethodRef` and  `Type.getType(s)`  will throw excpetions.
Just catch this for the moment.

[Jimple2cpg] catch error caused by soot and asm

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/LambdaTests.scala

This PR includes AST generation for the currently missing `ParenthesizedLambdaExpression`. Achieved this as a refactor to the existing `SimpleLambdaExpression` function.
Resolves #4276

[C#] Ast for ParenthesizedLambdaExpression

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeTests.scala

Handles types for `null` literals.
Resolves #4302

[C#] Type handling for null literal

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/SwiftSrc2Cpg.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/passes/ExtensionInheritancePass.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ClassExtensionTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/inheritance/ExtensionInheritancePassTests.scala

This pass adds the inheritance relation between base types and their extensions. Although, that is semantically not quite correct in the way Swift extensions work its still the closest lowering in our CPG world.

[swiftsrc2cpg] Added ExtensionInheritancePass

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeTests.scala

This PR is an attempt to resolve correct types for operators that have a fixed type. Currently, we try to resolve types from operand nodes, which might propagate types incorrectly.

[C#] Resolve correct types for fixed type operators

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/Main.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala

The `METHOD_REF` from do-block call construction was returned for reference, but accidentally committed to the AST when it was also found in the call resulting from the lambda arg. This resulted in two AST parent edges.
Resolves #4266

[ruby|bug] Fixed bug where `METHOD_REF` has multiple parents

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/datastructures/ProgramSummary.scala

This PR handles qualified base names in class declarations.
* Qualified base names are created as `MemberAccess` nodes for convenience
* These are resolves against the scope, so they may resolve fully if the type is within the program summary
* Added the ability for the program summary to visit nested types, and approximated that they share the namespace as their root parent
* Handle partially qualified names in `tryResolveTypeReference` to avoid collisions by checking whole suffixes
Resolves #4270

[ruby] Qualified Base Names

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/Main.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/passes/DependencyPass.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DotNetAstGenRunner.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/io/DependencyDownloadTests.scala

* Added download dependencies CLI argument
* If downloading of dependencies is enabled, then these packages are downloaded and unzipped from NuGet
* Calling DotNetAstGen to summarize results and merges these with internal summaries
TODO: Choose the version of DLL to summarize more intelligently. If a package publishes binaries with more than one dot net version, the first is taken.
TODO: Extend `DotNetAstGen` to parse DLLs even when PDB files are not present. Right now dependencies without PDB files are skipped.
Resolves [#4188](https://github.com/joernio/joern/issues/4188)

[c#] Download & Summarise Dependencies

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

The Ruby calls were somewhat a bastard child in terms of structure. This PR aligns the structure closer to `pysrc2cpg` in that there is always some kind of base/receiver. e.g.
```ruby
x.foo(a, b)
```
and
```ruby
foo(a, b)
```

[ruby] Call Restructuring

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala

Add a type hint to the LHS identifier of an object instantiation assignment to be hinted that the type would be that of the created object.
Question @max-leuthaeuser, is this a good place to use `dynamicTypeHintFullName`? Or should I stick to `possibleTypes`?

[ruby] Object Instantiation Type Hint

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala

For cases not matching against an expression  use `.any?` and with it we use `.include? expr`. This is not entirely faithful to ruby semantics, as matching is done with `.===` but doing so would be uglier with not much upside.

[ruby] implement splatting for when in case statements (#4318)

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/Main.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Main.scala
joern-cli/frontends/rubysrc2cpg/build.sbt
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/Main.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/DependencyPass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/querying/RubyMethodFullNameTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DependencyTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala

* Unified the download dependency option as a trait under `X2Cpg` to be readily added to configurations
* Dependencies are parsed from  `Gemfile` and `Gemfile.lock`
* Downloads, unarchives, and parses dependencies for symbol information
* Library symbols successfully resolved against `RubyScope` and the `RubyPorgramSummary` classes
* Made sure all relative paths in `fullName` properties are Unix delimited
One advantage of this version of dependency downloading and parsing against the deprecated frontend is that this is OS independent and reduces the need for `gems` being installed.
cc @pandurangpatil 
Resolves #4314

[ruby] Download & Summarize Dependencies

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/ScopeElement.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

* Class Variables - used a similar structure to the instance variables where all class variables found are added as `Member` nodes under the `TypeDecl`, and initialized to `nil` under the `<clinit>` method
TODO:
* Need to filter out `var = nil` in the `<clinit>` method if the var is already assigned a default value when created (similar issue to instance variables).
Resolves #4246

[ruby] Class Variables

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

This PR Handles
* Changed casting of body for MethodDecl to handle case for body where it isn't StatementList. Defaulted to `List.empty` until proper implementation is done at a later stage.

[ruby] Bug-Fix: Safe casting for body of MethodDecl to StatementList

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/jpastprinter/JavaParserAstPrinter.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Delombok.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/PackageRootFinder.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/SourceParser.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LombokTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/util/PackageRootFinderTests.scala

Before, the default `Delombok` behaviour was to check if `lombok` was found in the list of fetched dependencies and to run `delombok` if it was. With this PR, we check if `lombok` appears in code instead. This eliminates the dependence on successful dependency fetching.
I chose to just check for the substring `lombok` in any of the source files since this is a very simple check to do while also accounting for using lombok with fully qualified types instead of imports and it's not a common enough string to appear in natural non-lombok code in most cases. The cost for a false positive is also quite small. We would unnecessarily delombok the code, but since lombok wasn't used, we'd effectively still be scanning the original source files with only a bit of time wasted.
The bulk of the changes …

Find lombok uses by scanning source code instead of fetched dependencies

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/ast/CallCpgTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HashTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

`Array::[]` and `Hash::[]` may look like index accesses to the parser, this change adds a check that, if the name on the LHS is a known method, then treat it as such.
This also fixes the hash initializer structure where the lowering happened under the hash initializer call, this change makes this align closer to what Python has for dict literals.
Resolves #4357

[ruby] Handle Method with Array/Hash Init Arg

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/passes/DependencyPass.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/DependencyTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/testfixtures/CSharpCode2CpgFixture.scala

* Fixed non-exhaustive matching on string interpolation handling
* Wrapped the package version check in a try-catch
* Ignore looking to nuget for packages that are internal to a potential c# monolith
* Fixed test config loading in fixture
Resolves https://github.com/joernio/DotNetAstGen/issues/23
Resolves https://github.com/joernio/DotNetAstGen/issues/24

[c#] Safe Download Dependency Handling & Cleanups

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/io/DependencyDownloadTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/DependencyTests.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyProgramSummary.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/datastructures/ProgramSummary.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/datastructures/ProgramSummaryTests.scala

* Adds a check to existing summaries if existing namespacing starting with the dependency name exists.
* Added `TypeLike` addition handler to handle member collisions.
* Upgraded DotNetAstGen version
Resolves #4368

[c#] Avoid Downloading an Existing Summary & Improve Summary Merging

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MemberAccessTests.scala

Includes changes to handle chained calls and field accesses when a conditional access or a null  forgiving operator is used.
Resolves #4370

[C#] Handle chained calls and fields with conditional access and null forgiving operators

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/CallMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/MethodMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/TypeDeclTraversal.scala

also use `.slice()` in order to avoid crashing in `.substring()` when the offsets are out of bounds. This just papers over issues with invalid offsets though, so it's arguable whether we actually want to do this?
Also contains a random refactor of the `.macroExpansion` step.

correctly handle <empty> in .content steps

---

build.sbt
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/cfg/CfgCreationPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/ControlStructureTraversal.scala

With this change catches do not have to have order 2 for correct control flow generation. Multiple siblings with the same order are invalid.
The change in CfgCreator allows for backwards compatibility.
We fall back to order(2) for catch and order(3) for finally if no ControlStructure CATCH or ControlStructure FINALLY is found.

[c2cpg] Emit Catch ControlStructures

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HashTests.scala

* Rolled back some method receiver/base changes
* Corrected argument structure in `Array::[]` style calls
* Corrected oversight on array literals always being treated as `%i` style arrays instead of the `[1,2,p]` style array literals (which are created elsewhere too)
* Added some temporary receiver type fetching logic for call receivers
* Treat member calls with `::` as static dispatch
* Registered `===` as an `equals` binary op

[ruby] Final Tweaks for Beta

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ConditionalTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

- Make return and assignment transformation for control flow expressions recursive
- Make `else return nil` or `else x = nil` TextSpan more localized
- Make a conditional operator when `unless` appears as an expression.

[ruby] Nested ruby control flow structures in assign and return #4337 

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/AnnotationTests.scala

The Attribute nodes were not getting proper `code` extracted rom them since default truncation was at `{`. This skips it while not disturbing code extraction for other nodes. Test also added.

[c#] fix code extraction for attribute node

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

* Added visitor for `methodOnlyIdentifier` (methods ending with `=?!`
Resolves #4336

[ruby] Add visitor for `MethodOnlyIdentifier`

---

joern-cli/frontends/c2cpg/c2cpg.sh
joern-cli/frontends/csharpsrc2cpg/src/universal/bin/csharpsrc2cpg.sh
joern-cli/frontends/ghidra2cpg/ghidra2cpg.sh
joern-cli/frontends/ghidra2cpg/src/universal/bin/ghidra2cpg.sh
joern-cli/frontends/gosrc2cpg/gosrc2cpg.sh
joern-cli/frontends/javasrc2cpg/javasrc2cpg.sh
joern-cli/frontends/javasrc2cpg/src/universal/bin/javasrc2cpg.sh
joern-cli/frontends/jimple2cpg/jimple2cpg.sh
joern-cli/frontends/jimple2cpg/src/universal/bin/jimple2cpg.sh
joern-cli/frontends/jssrc2cpg/jssrc2cpg.sh
joern-cli/frontends/php2cpg/php2cpg.sh
joern-cli/frontends/php2cpg/src/universal/bin/php2cpg.sh
joern-cli/frontends/rubysrc2cpg/rubysrc2cpg.sh
joern-cli/frontends/swiftsrc2cpg/swiftsrc2cpg.sh

Simply invoke the staged x2cpg.sh script without defining additional
JVM properties. If we want to define those by default, it should
rather be done in `src/universal/x2cpg.sh`
N.b. we can't just symlink to the `target/universal/stage/bin/x2cpg.sh`
because of the `SCRIPT_ABS_PATH` handling - we wouldn't be able to
invoke the frontend from different directories any longer.
For now only c2cpg to gather feedback, if it's to your liking I'll
apply the same to all frontends.

simplify staged frontend starter scripts

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

This PR Handles:
* Added node and handling for `BreakStatement`
* Added handling for `RescueExpression` as a method body
* Added handling for explicit `ReturnExpression` as final statement in statement list

[ruby] Handling of break statements, `RescueExpression` as method body, and explicit `ReturnStatement`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/SingleAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/FieldAccessTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ProcParameterAndYieldTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SetterTests.scala

* No longer making call receivers field accesses, this is the source of many bugs
* Included `<empty>` and `ANY` type creation for the linker as these are explicitly ignored otherwise and have `null` implications for nodes that evaluate to those types
* Adjusted tests accordingly

[ruby] Call & Receiver Tweaks

---

.github/workflows/pr.yml

They enabled caching since v4. We do not need it.

Disable caching for actions/setup-go

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/NamespaceTests.scala

Added `TypeNodePass` for the linker to link all necessary types

[c#] Type Node Pass

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

This PR Handles:
* Added new trait `AllowedTypeDeclerationChild` for all nodes that are allowed to be directly under `TypeDecl`. 
* Moved all nodes at start of class definition not allowed under `TypeDecl` into the `<init>` method.
* `astForConstructorMethodBody` parses method body for constructor without the implicit return.
Resolves #4395

[ruby] Handling nodes directly under typedecl

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

* Arrow syntax for lambda expressions.
Resolves #4394

[ruby] Arrow Syntax for Lambda Expressions

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForTypeSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/io/CodeDumperFromContentTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ActorTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/AsyncSyntaxTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/AsyncTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ClosureTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/TypealiasTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/inheritance/ClassExtensionTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/inheritance/EnumerationExtensionTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/inheritance/ProtocolExtensionTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/inheritance/StructureExtensionTests.scala

Also put in proper method signatures and fullnames.

[swiftsrc2cpg] Implemented Actor/Async tests

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/MemberDataflowTests.scala

The AST for `throw` statement in the test code snippet was not created, because it had no arguments, and the `json` access in the AST Creator expected some arguments.  The dataflow couldn't jump from the wrapping `try-catch` to the required call, resulting in the `sinks.reachableBy` query being stuck. Wrapped the throw `json` access in a try block to prevent this from happening.

[C#] Null safe json access for throw

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForStmtSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/DoExpressionTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/StatementTests.scala

swiftsrc2cpg uses the same try/catch lowering as c2cpg now (using `ControlStructureTypes.CATCH`).
Also: fixed order values for catch ASTs.

[swiftsrc2cpg | c2cpg] Proper handling of do expressions

---

joern-cli/frontends/csharpsrc2cpg/build.sbt
joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DotNetAstGenRunner.scala

This solves an issue where for a joern scan, a directory containing spaces in the name would not get scanned by DotNetAstGen

[C#] Fix `dotnetastgen` runner to handle space containing paths

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/CollectionTests.scala

* `ElementAccessExpression` - This is both Array and Dict indexing
Resolves #4363

[c#] Handle `ElementAccessExpression`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

Made sure the correct parameters are used in `toMethodDeclaration` call

[ruby] Fix Bug where Proc & Lambda Parameters Aren't Created

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MethodTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala

This PR adds support for the file content field and offsets for php2cpg.
Currently multi-byte characters break this, since the offset returned by php-parser is the byte offset, not character offset. I'm going to fix that in our fork of php-parser, but my first attempt at doing so was unsuccessful. I think this PR still stands well on its own since all that will be required once php-parser is fixed is to bump the version we use of that and to un-ignore the currently broken testcase.

Add file content for php2cpg with broken unicode

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/TypeHelper.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/Defines.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/types/TSTypesTests.scala

Follow-up for: https://github.com/joernio/joern/pull/4426

[jssrc2cpg] Fix for dynamicTypeHintFullName on this identifier

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala

Tested this manually since I'm not aware of a way to easily do this in our unit test setup.
```
❯ export JAVASRC_FETCH_DEPENDENCIES=t
❯ ./joern-cli/frontends/javasrc2cpg/javasrc2cpg ~/code/java/HelloShiftLeft
...
[INFO ] Enabling dependency fetching: Environment variable JAVASRC_FETCH_DEPENDENCIES is set
[INFO ] got 63 Maven dependencies
```
The idea is to set this by default in SL, but then customers can still unset it if they want to (which should be a rare case).

Add environment variable to javasrc to fetch dependencies

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/DependencyPass.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/PhpDependencyPassTests.scala

* Added parsing of `composer.json`
* This results in two kinds of dependencies
- The usual that are downloaded without namespace modifications/autoloading
- Those that have custom namespaces/autoloading The latter is prefixed with `<autoload>` as dependency nodes can't be tagged.
Next steps are to add import nodes for these whenever a composer autoload is referenced. This is the first PR to address #4403

[php] Dependency Pass for Composer Files

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/AnnotationTests.scala

This PR includes creating annotation nodes in the `php2cpg` frontend, and linking them to their corresponding parent AST nodes (methods, classes, parameters). 
Resolves #4453

[php2cpg] Annotation Support

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/util/ProgramHandlingUtil.scala

Currently, archives are determined by extension, and then corruption is detected if there is a failure along the line.
This change ignores file name completely, and runs through the whole zip to make sure it's valid and uncorrupted before processing. This adds a bit more computation but helps with validity.

[jimple] General Archive Detection

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/callgraph/DynamicCallLinker.scala

* Converted all calls' dispatch types to `DYNAMIC_DISPATCH` to match Ruby's semantics more closely
* using `nameExact` over `name` in `DynamicCallLinker` (unrelated "bug")
* Made sure identifiers have precedence over calls if an identifier is declared

[ruby] Call Consistency & Precedence

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/DataFlowSlicing.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/package.scala

It appears that running `.code` in a multi-threaded environment may lead to the database returning `null` to the regex matcher. It is a bit bizarre, but this PR moves the `code` filter in a serial position. See #4459 for more details.
Resolves #4459

[slicing] Dataflow Slicing Concurrency Fix

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala

Some member calls have `ANY` as the full name when unresolved which is incorrect. Changed this to `<unknownMethodFullName>`

[ruby] Bug Fix `ANY` Method Full Name

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MethodTests.scala

This PR fixes offset calculations when processing utf-8 files with the file content feature enabled. The 2 main issues with this PR are that it assumes a utf-8 encoding (which will work for ascii as well, but not for more niche encodings) and a possible performance hit from the offset calculation. A potential optimization would be to cache known offsets and to calculate the new offset from the closest one, but since this is not a common operation, it likely won't be too much of a slow-down and we can revisit this decision if performance does turn out to be an issue.

[php2cpg] Handle utf-8 offsets correctly

---

.github/workflows/pr.yml

Looks like they are no longer pre-installed.

Add sbt and php to MacOS runner

---

.github/workflows/pr.yml
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyProgramSummary.scala

This PR:
* adds `derives ReadWriter` to `RubyField`, `RubyType` in `RubyProgramSummary`
* adds custom serialization/deserialization logic for `RubyMethod`

[ruby] `RubyProgramSummary` types derive ReadWriter

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala

We reach out-of-memory exceptions when running consecutive scans (within the same process) and providing the so-called «inference jar paths» (`--inference-jar-paths`).
This can be observed if we run all javasrc2cpg unit-tests with some additional inference jar. In the following experiment, I've used the same 100MB .jar throughout unit-tests and the 8GB limit is quickly reached, precluding them from finishing.
Poking around, it seems clear that each time an inference jar is loaded its TypeSolver remains in memory. 
By clearing JavaParser caches the situation improves considerably:

[javasrc2cpg] Clear JavaParser caches after AST creation

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImplicitRequirePass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImportsPass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala

[Autoloading in Ruby](https://www.rubyguides.com/2019/08/autoloading-in-ruby/) is fairly common, however it's important for us to represent these import nodes explicitly.
This pass adds a check for modules with no high-level require calls, to check call receivers and constructor allocations for types from other files, and add explicit require calls for them.

[ruby] Implicit Require Handling

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala

The 'csharpsrc2cpg/src/main/resources/builtin_types' is not loaded into the classpath after the stage. 
Resolves #4474

[C#] Fix: Built-in Type Stubs not Loaded When Packaged

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/package.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/CfgNodeMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/generalizations/CfgNodeTraversal.scala

In a more naive time in my life, I wrote https://github.com/joernio/joern/pull/1423, but this did not *exactly* achieve what I wanted, since this is designed for sanitizers. This also took a set argument, which was a bit weird.
This fixes the above approach, by actually checking the path for the element in the traversal.
Note: For some calls, one might need to have something like `sink.reachableByFlows(source).passesNot(_.collectAll[Expression].inCall.name("sanitizer"))` as the way the path elements are presented, the call may be skipped in languages such as Python.
Resolves #2438
Resolves #2175

[dataflowengineoss] Passes/PassesNot Fix

---

project/Versions.scala

Soot 4.5.0 uses [ASM 9.7](https://github.com/soot-oss/soot/blob/4.5.0/pom.xml#L76) compared to 4.4.1 which uses ASM 9.4.
This will help parse newer versions of JVM bytecode.

[jimple] Upgrade Soot

---

console/src/main/scala/io/joern/console/cpgcreation/JavaSrcCpgGenerator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/TypeInfoCalculator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/VarDeclTests.scala

The desire for type arguments to be persisted in type nodes and properties has been around for a while.
This PR adds a hidden, off-by-default flag, `keep-type-arguments`, signals to the `TypeInfoCalculator` to build the full name with the full names of the type arguments.
Resolves #4488

[javasrc] `keepTypeArguments` Flag

---

.github/workflows/pr.yml
.gitignore
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala
joern-cli/frontends/rubysrc2cpg/.gitignore
joern-cli/frontends/rubysrc2cpg/build.sbt
joern-cli/frontends/rubysrc2cpg/src/main/resources/application.conf
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/Main.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyProgramSummary.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/typestub/TypeStubConfig.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/typestub/TypeStubUtil.scala

* Downloads compressed type-stubs from `joern-type-stubs` release during `sbt stage` and sha512 checksums the downloaded files with the sha512 on `joern-type-stubs` release page
* Populates the initial `namespaceToType` map from the builtin type-stubs
Todo:
* Filter out types from the `namespaceToType` map that are not imported
*

[ruby] Builtin type-stubs for `Ruby`

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/propertyaccessors/ModifierAccessors.scala

I have a (large) CPG here where the general `.out` is catastrophically slow: 130k calls to `method.isConstructor` took 8 minutes on my machine before, compared to 500ms with this change. I haven't dug deeper but I guess part of this is that methods have a LOT of outgoing CONTAINS edges that are irrelevant for modifiers.

use AST edges for modifier accessors

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala

This PR partly reverts #4187. The change to `CompilerAPI.makeEnvironment` breaks sptests. We may want to revisit that change later as it was intented to improve performance.
With publishing this PR here locally sptests runs fine again.

[kotlin2cpg] Partly revert #4187

---

.gitignore
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/CaseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ConditionalTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DestructuredAssignmentsTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/HashTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/LiteralTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/MultipleAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ProcParameterAndYieldTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/RangeTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/RegexTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/SingleAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/dataflow/DataFlowTests.scala

Moved all of the dataflow tests to the new Ruby frontend from the deprecated one. Ignored the ones that aren't working for now, the next step is to start working on fixing those tests.

[ruby] Move over dataflow tests

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/DependencyPass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImplicitRequirePass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala

Uses `Gemsfile.lock` which is parsed (if present) in the `DependencyPass` to determine if implicit imports are to be enabled.

[ruby] Enable `ImplicitRequirePass` if `zeitwerk` is Detected

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala

Handling `Begin-End-Until` as a lowered `do-while` loop.
Resolves #4507

[ruby] Begin-End-Until Loop

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/MultipleAssignmentTests.scala

* Fixed issue where lists of `StatementList` were not being unpacked in grouped assignments
* Fixed ambiguity of assignment to a splat without spacing being detected as a call multiplied by RHS, e.g. `y=*x`
Resolves #4506

[ruby] Fixed Grouped Stmt Flows & Splat Ambiguity

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala

Handles splatting argument when given to a call.
Resolves #4437

[ruby] Handle Splatting Argument in Call

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/VarDeclTests.scala

It's been known that certain types return as `ANY` when it's an external type with type arguments. However, the type would resolve when type arguments are removed.
This PR detects if the type to be resolved is a `ClassOrInterfaceType`, and if so, will only pass the type name to the type resolver, and resolve the type arguments separately. The type arguments are then placed in the `fullName` if `keepFullNames` is enabled.

[java] Resolve External Non-JDK Types with Type Arguments

---

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/AnnotationTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/CfgNodeMethods.scala

Added additional annotation specific cases to `CfgNodeMethods.method`.
Resolves #4529

[language] Fix `Annotation.asInstanceOf[CfgNode].method` Throwing NullException

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ProcParameterAndYieldTests.scala

* Fixed parameter alignment issue where some methods didn't have a 0th parameter
* Fixed `require` regex to account for local relative file imports

[ruby] Fixed Call/Method Dataflow Tests

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ProcParameterAndYieldTests.scala

* Added handling for `Block` lambda expressions
* Enabled more ProcParameterAndYieldTests
* Further passing tests require type propagation
Resolves #4520

[ruby] Some Proc/Lambda Flows

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ArrayTests.scala

* Added handling for `SplattingArgumentIndexingArgumentListContext` and `OperatorExpressionListWithSplattingArgumentIndexingArgumentListContext`
* Enabled more Array Tests
Resolves #4517

[ruby] Array Dataflow Tests & Argument Cases

---

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/passes/ConfigFileCreationPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XConfigFileCreationPass.scala

When going from 2.0.352 to 2.0.353, we noticed that `ConfigFile`'s `.name` property no longer contained their path, but rather just their file name. 
An alternative fix would be to explicitly provide `rootDir = Option(config.inputPath)` in https://github.com/joernio/joern/blob/ebd93bf07ab3261c25fb27756d772768fec02979/joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala#L34
but since XConfigFileCreationPass is expected to gather that from `metaData.root` when omitted, figured it would be preferable to patch it instead.

[javasrc2cpg] Preserve path in ConfigFile name

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Main.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForExpressionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeRenderer.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/TypeTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/testfixtures/KotlinCodeToCpgFixture.scala

* Similar to https://github.com/joernio/joern/pull/4502, but for Kotlin.
* Made `TypeRenderer` an object for easier global setting of `keepTypeArgument`
* Improved null safety of `expr.getCalleeExpression` under `AstForExpressionsCreator.astsForNonCtorCall`
Note: This acknowledges that enabling this flag may break type linking, thus it is hidden and disabled by default.

[kotlin] `keepTypeArguments` Flag

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeInfoProvider.scala

For whatever reason `if desc.getKind == CallableMemberDescriptor.Kind.DECLARATION` slipped into `resolvedCallDescriptor(expr: KtExpression)` with the previous PR (most likely something I debugged there and forgot about).

[kotlin2cpg] Fixed type info provider

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala

When dealing with:
* external method calls whose receiver type we can't resolve, and
* if there is a variable in scope with that same name, then
we are resolving to that variable's type, as in:
```java
import org.Client;
import org.Builder;
...
Client foo = new Builder().foo().build(); // build's receiver is org.Client
Client bar = new Builder().somethingElse().build(); // build's receiver is <unresolvedNamespace>
```
This gets worse: if in the 2nd statement above we had used `foo()` again instead of `somethingElse()`, it would resolve again to `org.Client`.
This patch stinks, though: I'm not a fan of that edge condition. Hopefully we can find something nicer.

[javasrc2cpg] fix ext method call full name with same name of a scope var

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

* Added `METHOD_REF` nodes directly under `:program` for all methods defined in file
* Added `TYPE_REF` nodes directly under `:program` for all class/modules defined in file

[ruby] add `METHOD_REF` and `TYPE_REF` nodes for methods and class/module decls

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/TsClassesAstCreationPassTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/types/TSTypesTests.scala

Assignment calls from TypeAliasNode members created for object parameters to functions are not stored directly under the TypeDecl any longer. We only attach members now.

 [jssrc2cpg] Fix for TypeDecl creation from TypeAliasNode for function params

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2CpgOnFileSystem.scala

To help debug some issues.
Generally speaking, I think we should always always log exact versions in every run. Just to allow us to quickly ensure whether that is a possible cause of a bug.

add slightly more verbose logging to pysrc2cpg

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/package.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/SingleAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala

In #4549, we noticed an extra flow in the following sample:
```python
x = foo(20) # with source being the LITERAL
sink(x)
```
This was traced to `globalFromLiteral`, in which the statement `x = foo(20)` would consider `x`, adding it to the starting points of the query.
In this patch we only trigger if the literal is the RHS of the assignment. 
I may be missing some relevant context here that I didn't gather from the failing unit-tests. Before going through the trouble of fixing them all, is this patch coherent?
EDIT: Resolves #4549

[dataflowengineoss] globalFromLit only when it's a standalone assignment

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/MavenDependencies.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/dependency/DependencyResolverTests.scala

There's also a --fail-at-end. But in my cursory testing, it still skips over future steps after a failure, so --fail-never it is.

[javasrc]: keep maven dep fetching running after failure

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/GradleDependencies.scala

`configurations.default` can not be resolved by default. The previous hack with `.setCanBeResolved(true)` will be deprecated with Gradle 9 and finally removed / disabled in future releases (same for `implementation`). The proper way to do this is by re-using a resolvable configuration (resolvable by default) in the `from` clause of the task.
More info: https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:resolvable-consumable-configs and https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph

Fixed Gradle script for dependency downloading with Gradle >9

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImportsPass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala

Creating import nodes for `require_all`, `require_relative`, and `load` calls. `require_all` is interpreted as a wildcard import as it imports a whole directory.
Additionally handling the `require_relative` and `require_all` correctly as per their semantics with accompanying tests.

[ruby] `require*` and `load` import nodes

---

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/AnnotationTests.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForPrimitivesCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/AnnotationsTests.scala

* populates types where local imports are used for annotations
* add tests for java as well as kotlin to demonstrate parity

[kotlin] fix types for custom annotations

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

This PR handles rescue clauses specifying caught exceptions and creating their respective node. Exception types are assigned as dynamic type hints. This also tests that splatted exceptions are handled in a stable way.

[ruby] Handle Rescue Exception Lists

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/package.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

Noticed a regression after #4559, in which flows from imported members would not longer propagate, e.g.
```python
from models import FOOBAR # defined as e.g. FOOBAR = "123" in `models.py`
print(FOOBAR)             # this FOOBAR (argument) would not be tainted by "123"
```
At play is the representation of `import` statements, which look like `FOOBAR = import("models", "FOOBAR")`. 
Prior to #4559, `globalFromLiteral` would yield `FOOBAR` in the aforementioned import statement, since it would recursively look for literals in assignments. That wasn't bullet-proof because then in `x = foo(20)` we would also yield `x`, leading to an extra (incorrect) data-flow from `20` to `x` (see #4549.)
In #4559, we changed that to only look for literals as the proper RHS of assignments, which then misses …

[dataflowengineoss] handle python imports in globalFromLiteral

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitorHelpers.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

The current AST of the try except does not keep the `except` bodies as `order=2` and pass empty block nodes for `finally` and `else` bodies if they are not there.
This change keeps the `except` bodies as `order=2` and groups the `finally` and `else` bodies under a single body, while discarding empty blocks if they are unimplemented.
Partially addresses #4578, as the node is unfortunately still dangling. This could also be because `file` is a built-in function call and is re-assigned in `a9_lab` from the initial assignment under the parent `<module>`.
One note is that setting the source to `cpg.parameter.nameExact("request").l` does not work, and it may be due to the excessive AST depth under the assignment to `file`.

[python] Correct `try-except` AST `order` Property and Structure

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/package.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

Follow up on #4576:
* Reverts `globalFromLiteral` to the implementation that fixed #4549
* Makes `DdgGenerator` use the original (before 4549) `globalFromLiteral` implementation, inlined.
The issue in 4549 is that `globalFromLiteral` was being overly inclusive when computing the starting points for `reachableBy`. Having fixed that, we noticed missing flows afterward. The trouble is that `globalFromLiteral` is also being used by `DdgGenerator`. So, a quick fix is to have `DdgGenerator` use the original `globalFromLiteral` while keeping `reachableBy` use the updated version.

[dataflowengineoss] revert DdgGenerator usage of `globalFromLiteral`

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MemberTests.scala

Locals shadowing fields were erroneously treated as the field instead, resulting in incorrect type names among other things.

[javasrc2cpg] Fix javasrc local shadowing bug

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrParser.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/LiteralTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

The [`facter`](https://github.com/puppetlabs/facter) repository causes this frontend to throw a lot of warnings. This PR fixes much of the low-hanging fruit, and improves the warning techniques to help make the warnings more meaningful. There are still, however, quite a few syntax errors to handle from this repository.
* Handles regexes generated from string formating.
* Handled the `!~` regex not match function. Long term any unrecognized functions are interpreted as calls.
* Added more cases for implicit returns

[ruby] Grouped `facter` Bug Fixes

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RegexLiteralHandling.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DependencyTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RegexTests.scala

The [logger](https://github.com/ruby/logger) repository causes this frontend to throw a lot of warnings. This PR fixes these warnings
* Handles regexs used in conditions of IF statements
* Added `<<` as a valid `definedMethodName`
* Added handling of `rescue` as a modifier statement seen in the logger repo with `@dev.close rescue nil`

[ruby] Grouped `logger` bug fixes

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RegexLiteralHandling.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HashTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/LiteralTests.scala

The lexer predicate that decides when a `/.../` regex literal is about to start looks at the previous token to decide... and it was missing the `=>` token 🤦 
Credit for finding: @DavidBakerEffendi

[ruby] add missing token used to decide regex start

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/PhpTypeRecovery.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/PhpTypeRecoveryPassTests.scala

Handles propagating types via chained call patterns, as well as `$this->` calls where the method being invoked is inherited.
Follows up from https://github.com/joernio/joern/pull/4569

[php] Type Recovery for Inherited Methods & Chained Calls

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitorHelpers.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/TryCpgTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala

Uses `ControlStructureTypes.CATCH`, `ControlStructureTypes.FINALLY`, and `ControlStructureTypes.ELSE` now instead of relying on explicit order values.
Will do the same for all the other Joern frontends in individual PRs.

[pysrc2cpg] Use ControlStructureTypes for Try-Catch-Clauses

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/SimpleCfgCreationPassTests.scala

Uses ControlStructureTypes.CATCH and ControlStructureTypes.FINALLY now instead of relying on explicit order values. 
Also add catch clause parameters (declarations) to their bodies content (which was missing entirely).

[jssrc2cpg] Use ControlStructureTypes for Try-Catch-Clauses

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

Methods require binding/ref edges with their corresponding type declaration in dynamic languages to correctly model their object-like behaviour. This PR implements these bindings following `pysrc2cpg`'s `createBinding` function.
Additionally, adds the `CONSTRUCTOR` modifier to constructors.
Resolves #4593

[ruby] Method Bindings & Constructor Modifier

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForStatementsCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/WhenExpressionTests.scala

Uses ControlStructureTypes.CATCH and ControlStructureTypes.FINALLY now instead of relying on explicit order values.

[kotlin2cpg] Use ControlStructureTypes for Try-Catch-Clauses

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ControlStructureTests.scala

Uses ControlStructureTypes.CATCH and ControlStructureTypes.FINALLY now instead of relying on explicit order values.

[csharpsrc2cpg] Use ControlStructureTypes for Try-Catch-Clauses

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/Main.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala

Symbols are not parsed as operator expressions, so when they are given as a value to a named argument, they trigger an unhandled RubyNodeCreator case. This PR fixes that.
Additionally, `tests` is added as an ignore pattern.

[ruby] Named Argument with Symbol Value

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala

Uses ControlStructureTypes.CATCH and ControlStructureTypes.FINALLY now instead of relying on explicit order values.

[php2cpg] Use ControlStructureTypes for Try-Catch-Clauses

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala

This PR fixes previously unhandled call receivers, which creates an issue later during dynamic call linking as the receiver would be an Unknown node.
* Handled quoted expanded regex literals
* Handled constant variable references
Additionally, this brings back warnings for `Unknown` nodes as these unhandled nodes are not syntax errors but don't necessarily have explicit warnings when unhandled.

[ruby] Unhandled Receiver Types

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForSimpleStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ControlStructureTests.scala

Uses ControlStructureTypes.CATCH and ControlStructureTypes.FINALLY now instead of relying on explicit order values.

[javasrc2cpg] Use ControlStructureTypes for Try-Catch-Clauses

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Util.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/EnumTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/GenericsTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MemberTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/VarDeclTests.scala

At the last level of our type fallback mechanisms, we use `javaParserNode.getTypeAsString` to get the type name, but this still includes generic types which is inconsistent with what we do elsewhere. This PR strips the generic types from these fallback type names.

[javasrc2cpg] Remove generic types from unresolved fullnames

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForNameExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LambdaTests.scala

Due to an interaction between regular/anonymous class capture logic and lambda capture logic, the assumption that a `this` parameter will always be available in the direct enclosing method when handling captures is sometimes false. In this case, an `Unknown` node was added to the cpg, causing dynamic call linker failures.
This pr fixes the lambda issue by seaching the entire scope for a `this` param, which correctly (-ish, see note below) creates the field access with the correct type, but also replaces the `Unknown` fallback with an identifier which would still result in dynamic linking failing (probably), but won't crash.
Note on captured params in lambdas: the current representation just treats them as `this.capturedField`, but with the type of `this` set to the class in which it is …

[javasrc2cpg] Don't add unknown nodes to cpg for unhandled captured variables

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/package.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/CallTraversal.scala

In #4583, I didn't account for how Python dictionary literals are lowered as 3 address code. Specifically, the problem is at `inCall.assignment` here:
https://github.com/joernio/joern/blob/ff9c08f62539eba4194eee5c0a96f5d28d586ab7/dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/package.scala#L19
In an expression such as `print(1, {'x': 10})`, `1.inCall.assignment` wouldn't be empty - it would contain the assignments that build `{'x': 10}`. The intent behind `inCall.assignment` was to filter the surrounding call by assignment. So, introduced a new CallTraversal `isAssignment` to do just that and used it here instead.
I'm a bit concerned about introducing a new API for CallTraversal. Any thoughts about that?
Resolves #4605

[python] prevent overtainting dictLiterals

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/package.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/CallTests.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForNameExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/Util.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/EnumTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/GenericsTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LambdaTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MemberTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/VarDeclTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyProgramSummary.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DependencyTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/datastructures/ProgramSummary.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ConcurrentTaskUtil.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/datastructures/ProgramSummaryTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/CallTraversal.scala

As pointed out in https://github.com/joernio/joern/pull/4240, combining this nested immutable map-like structure has a quadratic performance, and the more performant strategy would be to use nested data-structures to merge.
For now, I've decided not to opt for a builder pattern, but rather keep the underlying structure mutable, and accessor methods return immutable structures.

[x2cpg] Program Summary Mutable Merging 

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala

- log cpg creation for each file in DEBUG only instead of INFO
- log the astgen path only once with INFO
- removed logging that astgen runs now in the given input folder

[jssrc2cpg] Reduce logging noise

---

joern-cli/frontends/pysrc2cpg/pythonGrammar.jj
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala

- Fix last error token position if error token itself is semicolon,
newline or EOF.
- Also log the parser exception message.

Improve pysrc2cpg parse error handling.

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/JsSrc2Cpg.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/ObjectPropertyCallLinker.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TypeRecoveryPassTests.scala

A common pattern in JavaScript is something like
```javascript
var foo = {};
foo.bar = {};
foo.bar.someFunc = function someFunc() {};
foo.bar.someFunc();
```
This PR adds a post-processing pass to find instances where the definition and the call live in the same file and to link them. This "common file" limitation aims to reduce false linking.

[javascript] Object Property Call Linker

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyProgramSummary.scala

Allow the frontend to continue analysis if the type stubs for built-ins is missing.

[ruby] Continue if Type Stubs are Missing

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/TypeHelper.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/Defines.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptImportResolverPass.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptInheritanceNamePass.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeHintCallLinker.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeNodePass.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/JavaScriptTypeRecovery.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/TypeRecoveryPassTests.scala

The `new` operator can prefix an ordinary call, e.g.
```javascript
var Print = function(str) {
console.log(str)
}
new Print("Hello")
```
The type recovery pass only considers object instantiations from type declarations on `new` calls, but this change allows it to consider functions too.
Other changes include adding constants for `:program` and `<operator>.new`

[javascript] `new` Function Calls

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/SingleAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ProcParameterAndYieldTests.scala

Added implicit `self` receiver to simple calls.

[ruby] Add `self` Base to Simple Calls

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala

In ruby as for all other dynamic language there is no vtable and thus
only a single entry in the binding tables with name=="" and
signature=="".

[ruby] Fix binding name

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

This change moves the type/method identifier references for entities exportable from the script to prefix the respective entity at the definition.

[ruby] Type/Method Identifier Ref Prefixes Definition

---

.gitignore

this caused me some headaches as I had an old jar lying around there,
likely from a bisect session...

gitignore: remove `c2cpg/lib`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

This changes makes the type decl/method references at the module-level explicitly assign members of the `self` object.

[ruby] Type/Method Identifier Ref Self Access

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/SingleAssignmentTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

* Added `Member` nodes for each method, to relate to their respective bound `TypeDecl` nodes.
* Added a type decl for "fake methods" that include the methods and classes exported by the file

[ruby] Members for Methods to Related to Bound Type Decls

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HashTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HereDocTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/LiteralTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RegexTests.scala

To simplify the call graph, methods resolved to the `Kernel` class are dispatched as static.
Additionally, replaced `__builtin` with `Kernel` to map more closely to Ruby's internals and implemented `MemberAccessCommandContext`.

[ruby] `Kernel` Methods are Static Dispatch

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForSimpleStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MethodTests.scala

The `.code` field for arguments presently includes comments, e.g. in
```java
Foo.create(
"username", // hehe, silly comment
"password"
);
```
the `.code` for `argument(2)` is ` // hehe, silly comment\n  "password"`.
This patch:
1. provides a default implementation for AstCreator's `code(Node): String` method that prints the node's text as if it didn't contain any comments attached, and
2. uses it (instead of `.toString`) throughout AstCreator.
Credit for finding: @sean-gahagan

[javasrc2cpg] add AstCreator `code` implementation removing comments 

---

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/RubyTypeRecoveryTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

The starting point here was a discrepancy wrt `methodFullName`s in Python for the following two samples:
```python
a = 10
foo(a) # methodFullName = __builtin.int.foo
```
vs
```python
foo(10) # methodFullName = <unknownFullName>
```
It was noticed that in `setTypeInformationForRecCall` the argument `i` isn't always set according to the convention that the receiver should have argument index 0 when it's a DYNAMIC_DISPATCH call and 1 when it's a STATIC_DISPATCH. This patch requires the convention to be satisfied. In turn, had to ignore 2 (deprecated) Ruby tests that were not verifying this convention.

[TypeRecovery] Makes sure the receiver's index matches the dispatch type

---

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

It was observed (#4558) a discrepancy between typeFullNames in Python for the following two samples:
```python
from helpers import foo
x = foo()
y = x[0] # y.typeFullName = helpers.py:<module>.foo.<returnValue>.<indexAccess>
```
vs
```python
from helpers import foo
y = foo()[0] # y.typeFullName = helpers.py:<module>.foo.<indexAccess>
```
The difference is the missing `<returnValue>` dummy in the second sample. This patch checks (in `getIndexAccessTypes`) whether the indexAccess' target is a call and that there's already in the symbol table an entry for it.

[TypeRecovery] include <returnValue> dummy for index accesses of calls

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala

While attempting to debug a customer issue, I got as far as "the AstCreator is crashing due to a UnsolvedSymbolException somewhere after processing a lambda", but since the stack trace wasn't logged in this case, the issue could be more-or-less anywhere.
Logging the stack trace is ugly, but also makes debugging much easier for projects we don't have the source code to.
I also lowered the logging level to a warning since this is more consistent with what these levels mean elsewhere

Log stack trace if javasrc AstCreator crashes due to an UnsolvedSymbolException

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForForLoopsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/TypeInfoCalculator.scala

Related to https://github.com/joernio/joern/pull/4665
The AstCreator is crashing on a customer project due to an `UnsolvedSymbolException`. As mentioned in the PR, there isn't enough information in the logs to locate the exact issue, but my theory is that it is due to a `getType` call somewhere. For this PR, I've wrapped all `getType` calls in a `Try` (unless they were already wrapped) since the JavaParser symbol solver and the interactions between the various kinds of solvers are too complex to easily tell when these calls should be safe and when not.
Revision 2: I've changed `Try` to `tryWithSafeStackOverflow`, which also logs stack traces for errors now. This isn't called during regular type resolution, so we won't log every failed type (since those are often to be expected), but we …

Wrap all javaparser getType calls in Try

---

joern-cli/frontends/csharpsrc2cpg/build.sbt
joern-cli/frontends/gosrc2cpg/build.sbt
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/jssrc2cpg/build.sbt
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/astgen/AstGenRunner.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/Environment.scala
project/Environment.scala

I don't like the amount of code we have there that pretends as if "ARM" is a single architecture... so I've moved things in a slightly better direction renaming some constants to ARMv8. (But I'm not going to fix that all completely in one day.)
The downloaded binaries actually already exist, just the integration here was missing.

fix jssrc astgen invocation on linux/aarch64

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/EdgeValidator.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

Apropos #4664, adds a couple of ignored failing tests with the intention of validating the intended behaviour. I was able to resolve a few of them (not included in this patch), but wanted to make sure this is right expectation before causing too much damage.

[dataflowengineoss] Refactor isCallRetVal

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImplicitRequirePass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ProcParameterAndYieldTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ConditionalTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/FieldAccessTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HashTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/IndexAccessTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ModuleTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SetterTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/datastructures/ProgramSummary.scala

* `initialize` methods are under all types/modules with fields that need to be initialized, where `InstanceFields` under classes are considered `ClassFields` and places under the singleton type. e.g, `class Foo;SomeMember=1;end` is considered under the singleton.
* `MemberAccess` is now not always treated as a call. As per Ruby, if the first letter of the member is capitalized, then it is a field access, otherwise a function call.
* Calls (and qualified calls) have their base/targets recursively checked for if they need to be prepended with `self.` (i.e., not a local variable that has been declared in scope).
* Added initial `<body>` method to catch all arbitrary statements under a type declaration, requires follow-up work
* Fixed local variable scoping, where variables introduced in …

[ruby] MemberAccess/MemberCall Handling

---

console/build.sbt
console/src/main/scala/io/joern/console/cpgcreation/JavaSrcCpgGenerator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/javasrc2cpg/JavaTypeHintCallLinker.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/javasrc2cpg/JavaTypeRecoveryPassGenerator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/javasrc2cpg/package.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/package.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

Please review with care - this is the archetype setup for all other frontends. 
As discussed in e.g. https://github.com/joernio/joern/issues/4625#issuecomment-2166427270
we want to avoid having classpath dependencies on the frontends and instead invoke them
frontends as external processes (i.e. execute their start script). Otherwise we'll end in
jar hell with various incompatible versions of many different dependencies, and complex
issues with things like OSGI and JPMS.
There's no perfect way to do so, this is the one I currently like the most...
Fixes tab completion bug https://github.com/joernio/joern/issues/4625

reduce classpath dependencies from frontends: javasrc

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DotNetAstGenRunner.scala
joern-cli/frontends/gosrc2cpg/src/main/resources/application.conf
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/GoSrc2Cpg.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/model/GoMod.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/DownloadDependenciesPass.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/MethodAndTypeCacheBuilderPass.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/astgen/AstGenRunner.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/astgen/package.scala

1. Changed parsing of AST json inside AST Creator itself.
2. Made changes in download dependency processing to generate AST only for the used packages and subsequently only processing used packages. There was a change required inside `goastgen` utility to support the `-include` input option.
TODO:
At this moment `AstCreator` gets instantiated while first-level processing for building the cache and it stays in memory till `AstCreationPass` is done. In subsequent changes, we will split the processing in such a way that we create `AstCreator` for that pass and destroy it once it's used. Instantiate it again for `AstCreationPass`.
The above change is done as part of the larger change.

[gosrc2cpg] Partial gosrc2cpg frontend perforamnce optimisations

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/EdgeValidator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

In expressions such as `foo(x)`, for which there are semantics for `foo` that don't taint its return value (cf. `isCallRetval`), we prevent creating an edge from `x` to `foo(x)`.
Otherwise, an expression such as `print(foo(x))` would be tainted by `x` when it shouldn't (since there are semantics preventing from tainting `foo`'s return value.)

[dataflowengineoss] refine return value semantics honouring

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ModuleTests.scala

* Create a new `<body>` `MethodDecl` in `RubyNodeCreator` that holds all statements that aren't `methods`/`singleton methods`/`type decls` which was previously put under the `initialize` and `initialize<class>` methods manually
* Invoke a call to `self::className::<body>` after the `TypeDecl` is created
Resolves #4683

[ruby] Create `<body>` method for `TypeDecl` statements

---

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

Noticed the following discrepancy in Python:
```python
a = 10
foo(a) # methodFullName = <unknownFullName>
```
vs
```python
a = 10
b = foo(a) # methodFullName = __builtin.int.foo
```
`a` was being handled as if it were the receiver of `foo`. This patch proposes checking that `a` has `argumentIndex` 0.

[TypeRecovery] make sure base has argumentIndex 0

---

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/pysrc2cpg/PythonTypeRecovery.scala

Noticed that type recovery wasn't handling index accesses of field access calls, e.g.
```python
import foo
foo.bar()[0] # bar.methodFullName = <unknownFullName>
```
The igniting clue here was that `bar` was not in the symbol time at the right time (`getIndexAccessTypes`).

[python] type-recovery for index accesses of calls

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HashTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ModuleTests.scala

* Builtins are renamed from `__builtin` -> `__core` to more closely resemble the core gem in Ruby
* Removed surrounding `<` and `>` tags from builtin packages
* Handling `Array:[]` type calls as `Array.[]` calls

[ruby] Remove `<|>` Tags From Builtins & Handle `[]` Differently

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala

Given the code block below:
```ruby
def foo &block
puts block.call
end
foo do
"world!"
end
```
Proc parameters from do-blocks (interpreted with the usual CPG lambda handling), suggests that there is a `call` member on the type bound to the type decl.
This PR adds this member, with the dynamic type hint referring to the type decl bound to this method.
Resolves #4700
cc @ml86

[ruby] Lambda Type Decl `call` Member

---

joern-cli/frontends/gosrc2cpg/src/main/resources/application.conf
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/model/GoMod.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/passes/DownloadDependenciesPass.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/utils/AstGenRunner.scala

Earlier changes to include packages with include regex, didn't filter all the packages and had a limitation to include all sub folders/packages if root package is being used. However, that wasn't the case. Hence, we introduced a mechanism to check the entire package folder path with `goastgen` with a separate flag `-includePacakges` and updated integration.

changes to use includePackages option to process only used packages

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf

This astgen version skips giant unparsable js files with EMSCRIPTEN code now by default.
(we did the same in js2cpg)
For: https://shiftleftinc.atlassian.net/browse/SEN-2797

[jssrc2cpg] Update astgen to v3.16.0

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala

May crash with a NullPointerException.
Also: safer AstCreator.createAst so we do not crash c2cpg completely if createAst throws. (same as all other frontends now)
For: https://shiftleftinc.atlassian.net/browse/SEN-2777

[c2cpg] Safe .getOverload.getType access / safer AstCreator.createAst

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/DataFlowCodeToCpgSuite.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/testfixtures/DataFlowCodeToCpgSuite.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/testfixtures/DataFlowCodeToCpgSuite.scala

```
[warn] -- [E092] Pattern Match Unchecked Warning:
/home/mp/Projects/shiftleft/joern.1/joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala:74:61
[warn] 74 |    path.resultPairs().collect { case (firstElement: String,
secondElement: Option[Integer]) =>
[warn]
|                                                             ^
[warn]    |the type test for Option[Integer] cannot be checked at
runtime because its type arguments can't be determined from Option[Int]
[warn]    |
[warn]    | longer explanation available when compiling with `-explain`
}
```

minify flatgraph diff: remove unnessecary (and misleading) typescheck

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala

For: https://shiftleftinc.atlassian.net/browse/SEN-2777
`Any` there does not make much of a difference but it stops the DynamicCallLinker from crashing.

[c2cpg] Added typefullnames to all calls

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

This PR changes the modelling of Singleton methods on objects. Ex:
```ruby
class Animal; end
animal = Animal.new
class << animal
def bark
"woof"
end
end
```
Creates a lambda method for `animal.bark`, and assigns `animal.bark = methodRef(bark)`
Resolves #4721

[ruby] Singleton methods on objects

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

For new frontends with potentially malformed ASTs, type recovery must safely handle instances where members don't have AST parents.
Allows for a CPG to result from the analysis. See #4732
Following up with a fix for this missing AST edge.
cc @spingARbor

[TypeRecovery] Handle Member without AST Parent Safely

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

The parser emits calls to `super` as different from simple calls, this PR handles them.

[ruby] Handle `super` Calls

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala

* Safely handles the case when `super` call has a `null` argument from the parser
* Shadows keywords when they are used as keys in association keys for named arguments in calls
* Handles singleton methods in implicit returns

[ruby] `super` Argument `null` & Association Key Handling

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

This PR fixes a bug where method members were not correctly linked to surrounding methods' bound type decls. Additionally, this handles `return` statements without any proceeding expression.
Resolves #4732

[ruby] Bind nested method members to method type

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala

The initial implementation of the edge creation and captured local node was wrongly added to the `Ast` object instead of the diff graph. This PR rectifies this.

[ruby] Fixed Persistence Issue of Captured Variable Info

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/TemplateTypeTests.scala

Happened during more sptests testing.
We need to normalize all names as they may contain linebreaks in their generic parameters, e.g.:
```
std::pair<StringRef, StringRef> *Buff = Allocator.Allocate<std::pair<StringRef,
StringRef>>(Arr.size());
```

[c2cpg] More fullname fixes

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ProcParameterAndYieldTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

Due to Ruby method references being called via a `.call()` method, the type ref that should be emitted, is one that contains the `.call` method, but is not necessarily the same type as the one bound to the actual lambda. This makes that change, however, data-flow no longer works in the open-source data-flow tracker as this is not supported.

[ruby] Emit TypeRef instead of MethodRef for Lambdas

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/ScopeElement.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/DependencySummarySolverPass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImplicitRequirePass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/RubyImportResolverPass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/RubyTypeHintCallLinker.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryPassGenerator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DependencyTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/FieldAccessTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ModuleTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RegexTests.scala

* Renamed `:program` to `<main>`
* Replaced `:` method separator to `.`
* Removed `<global>` from full names of types and methods

[ruby] Method/Type Full Name Simplification

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala

We are not able to represent them with the CPG format.
See e.g.:
```
template <class charT, class traits>
inline re_syntax_base* basic_regex_creator<charT, traits>::append_set(
const basic_char_set<charT, traits>& char_set)
{
typedef mpl::bool_< (sizeof(charT) == 1) > truth_type;
return char_set.has_digraphs() 
? append_set(char_set, static_cast<mpl::false_*>(0))
: append_set(char_set, static_cast<truth_type*>(0));
}
```
The type of `append_set` is dependent to some boost library magic w.r.t. to the method template instantiation. I just set it to ANY here.

[c2cpg] Fix string repr for type of dependent expressions

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

In the case of a type or method re-definition, the full name is ensured to be unique by a set that tracks all full-names for that compilation unit, and a counter.
Resolves #4742

[ruby] Handle Re-definitions

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala

* Added new `NextExpression` RubyNode
* Generate `continue` control structure AST for `NEXT` in Ruby

[ruby] Handle `NEXT` control structure

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala

https://github.com/joernio/joern/commit/b4ff8b3ad17d6dcec6467db680ad82928807ee6b seems to contain a copy/paste error leading to incorrect `lineNumberEnd` fields. This PR fixes this.

[c2cpg] Fix regression (incorrect end line numbers)

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/cfg/CfgCreationPassTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/DependencyCfgCreationPassTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/JsClassesCfgCreationPassTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/MixedCfgCreationPassTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/cfg/SimpleCfgCreationPassTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/CfgCreationPassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/deprecated/passes/cfg/SimpleCfgCreationPassTest.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/testfixtures/CfgTestFixture.scala

- Changed test constructs used to test the CFG creation to return
List instead of Set. This avoids deduplication which is required
for correct tests because the number of edges between two nodes
matters.
- The above change unveiled a problem with the for-statement CFG:
Duplicate edge between loop condition and body

[x2cpg] Improve Cfg creation.

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyLexer.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/Main.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrParser.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/KeywordHandling.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyLexerBase.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithoutParenthesesParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

An issue was picked up where having a reserved keyword as the call on a member (e.g. `batch.retry!`) was causing a syntax error due to lexer and parser issues.
* Changed precedence of keywords in the ANTLR Lexer to come after `LOCAL_VARIABLE_IDENTIFIER`
* Added handling to `LOCAL_VARIABLE_IDENTIFIER` tokens to determine whether a token should be marked as reserved keyword or not. We check if the previous `nonWs` token is `.`, `:` or `::`, or if the next token is `.` or `:`. If this holds, we know it cannot be a reserved keyword and is instead marked as a `LOCAL_VARIABLE_IDENTIFIER`.
* Added debug flag to ANTLR parser to print out the parse tree. Hidden and off by default.
Resolves #4748

[ruby] Calls with reserved keywords

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala

Fixes `org.eclipse.cdt.core.dom.ast.ExpansionOverlapsBoundaryException` for `.getSyntax` calls.

[c2cpg] Ignore ExpansionOverlapsBoundaryException while query static modifier

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/macros/MacroHandlingTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/cfg/CfgCreationPassTests.scala

No more LOCALs with multiple AST parents.

[c2cpg] Fix CFG creation for INLINE calls (LOCALS with multiple AST parents)

---

.github/workflows/pr.yml
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/slicing/DataFlowSlicing.scala
test-dataflow-slice.sc
tests/code/javasrc/SliceTest.java

* Added a script that parses and creates a sensible string from a slice that can be tested against.
* Fixed a slicing bug where slicing direction was in the opposite direction of neighbour retrieval and ended up ignoring certain nodes.
* Added entry in the `test-scripts` job to run the slice script, parse the slice, and assert the expected flow with `grep`.
Resolves #4783
@mpollmeier, is this the direction we want to go? Is this test satisfactory to assert some expected behaviour with?

Added `joern-slice` Data-Flow Script Test

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala

There was a case that would mistakenly prepend `@` on a member that start with a capitalized first letter.

[ruby] Fix Case Where Field Access Prepends `@` on CONST

---

joern-cli/build.sbt

on stage: remove module-info.class from dependency jars - a hacky workaround for a
scala3 compiler bug: https://github.com/scala/scala3/issues/20421
Fixes https://github.com/joernio/joern/issues/4625

workaround for scala completion bug

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/C2Cpg.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/CGlobal.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/Defines.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/FunctionDeclNodePass.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/HeaderAstCreationPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/MethodTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/NamespaceTypeTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/TypeNodePassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/AstC2CpgFrontend.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/TypeNodePass.scala

For method de-duplication (CDT always copy methods from header files into the implementation files so we would end up generating CPG METHODs for both with the same fullName), we now skip over all method decls but remember their properties.
Afterwards, a new pass stubs them iff no actual method definition exists.

[c2cpg] Defer method decl handling

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/FileHandlingTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/SourceFiles.scala

This may throw (FileSystemLoopException, or any other reason why this dir may not be readable).
We use Files.walkFileTree now. The only solution where a safe continue mechanism can be implemented.
Fixes: https://shiftleftinc.atlassian.net/browse/SEN-2976

[x2cpg] Do not crash on .listRecursively

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/MethodTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/ClassTypeTests.scala

- implicit this param for CPP functions
- identifiers that are actual member accesses are now transformed, e.g., this->varname if varname is a member and we are in the corresponding context
@maltek This needs serious testing

[c2cpg] Add implicit this param + access

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/cfg/CfgCreationPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala

1. Added the support in the CfgCreator. A THROW control structure now
breaks control flow.
2. Adjust c2cpg to generate such a control structure instead of a CALL
node.

Add support for THROW control structure.

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/cfg/CfgCreationPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/controlflow/cfgcreation/CfgCreator.scala

In this PR https://github.com/joernio/joern/pull/4807 the CFG for
`throw` statements was changes in the way that they have no outgoing CFG
edges. Since this might break assumptions of some CFG consuming code, we
now create outgoing CFG edges from `throw` statements to the method exit
nodes.

Ammendment to previous `throw` statement cfg change.

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

This PR fixes:
* Parameters and statements from the initialize method in a `Class` were missing, fixed by adding the `initMethod` back into the `StatementList` after moving all `nonAllowedTypeDeclChildren` to the `<body>` method.
Resolves #4812

[ruby] Fix: explicit initialize method statements and params missing

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/StringParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

This PR adds:
* Adds handling for command literal using `%x` syntax. This is modelled to be a call to `exec` as it runs a system command.
Resolves #4816

[ruby] Add handling for command literal `%x`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImplicitRequirePass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala

- Fix method lookup via AST edges. The approach of looking up module
methods via is not possible at the execution time of the pass because
AST is not yet linked.
I replaced this buy a fullname based regex lookup.
We should likely just change the execution time to after AST linking.
- The other changes are just for better readability and debugability.
@DavidBakerEffendi Please double check this PR thoroughly and ping me for discussion of running the ImplicitRequirePass later.

[ruby2cpg] Fix ImplicitRequirePass.

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala

This PR adds:
* Handling for Interpolated symbol array with `%I()`
* Parser tests
Resolves #4811

[ruby] Add handling for interpolated symbol array

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/AssignmentParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

This PR adds: 
* Handling for `BracketAssignmentExpression` (`foo[:id] = bar[:id]`)
* Relevant parser test for new structure

[ruby] Add handling for `BracketAssignmentExpression`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala

This PR:
* added a filter on the `RubySrc2Cpg` to filter out source files that are empty. Added a warning log if there is an empty file.

[ruby] Fix NPE when creating Ast on empty source files

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/AssignmentParserTests.scala

This PR fixes:
* Assignment parser test with single value on LHS, and multiple values on RHS

[ruby] Fix assignment parser test

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithoutParenthesesParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

This PR fixes:
* All arguments after the first one on a `MemberAccessCommand` were missing
e.g.:
```ruby
foo&.bar 1, 2 # argument 2 would be missing here.
```

[ruby][bug] Arguments missing on `MemberAccessCommand`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala

Although the parser rule for picking up pseudo-variables seems fine, it may sometimes choose to represent it as a local variable. This fixes this and adds the related tests.

[ruby] Fixed Pseudo-Variables as Literals

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala

As Ruby may consider `<<` as either shifting left (if LHS is a number) or as an append (if LHS is an array), one cannot statically approximate the operation.
We thus consider this as a call named `<<`.

[ruby] Consider `<<` as append calls

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImplicitRequirePass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala

The implicit require calls that are generated after the AST creation had an older/out-dated format and lead to identifiers not being linked via REF edges.

[ruby] Fix Implicit Require Call Structure

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ConfigFileCreationPass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/ConfigFileCreationPassTests.scala

Includes `y(a)ml`, `xml`, `erb` files as config file nodes.

[ruby] Include `y(a)ml`, `xml`, and `erb` files

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DependencyTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala

* Fixed constructor lowering structure as per https://github.com/joernio/joern/issues/4822
* Tested and fixed issue in parenthesis-less `new` member calls (could use a better long-term fix in the parser)
* Handling cases where the constructor call is off of an expression instead of some class identifier

[ruby] Constructor Lowering Fix 

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstSummaryVisitor.scala

Added `rootNode` to `AstCreator` so that we don't generate the intermediate Ruby AST twice (once for summary, once for full AstCreationPass)

[ruby] Add `rootNode` for `RubyNodeCreator` to `AstCreator`

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ConfigFileCreationPass.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/ConfigPassTests.scala

Includes `Pipfile[.lock]` files as `CONFIG_FILE` nodes, which can be useful to extract Python+dependencies versions.

[python] Include Pipfile[.lock]

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/FieldAccessTests.scala

`self` parameters within the scope of methods reverts back to initial surrounding type information, and keeps `ANY` otherwise, e.g. `<main>` methods.

[ruby] Revert type changes in `self` PR #4838

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ImplicitRequirePass.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala

* Reverted implicit requires to use `require` instead of `require_relative`
* Removed requirement for `ImplicitRequirePass` to need `programSummary` argument
* Moved import processing to post-processing

[ruby] Implicit Require & Import Processing Tweaks

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/Constants.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/ImplicitRequirePass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/ImportsPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/RubyImportResolverPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/RubyTypeHintCallLinker.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/RubyTypeRecoveryPassGenerator.scala

Following the other frontends, migrates the non-deprecated post-processing passes to `x2cpg`

[ruby] Move Post-Processing to `x2cpg`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

This PR fixes an issue where 2 `LOCAL` nodes were being created in `LAMBDA` blocks, even when the variable was only defined in the scope of the `LAMBDA` block.

[ruby] Conflicting local nodes

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DependencyTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/RubyTypeRecoveryPassGenerator.scala

Fixed an issue where the `methodFullName` on the `Initialize` call for `ObjectInstantiation` was being set to `ANY` instead of `DynamicCallUnknownFullName`

[ruby] Fix `methodFullName` on `Initialize` callNodes

---

joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/ImplicitRequirePass.scala

Fixed an issue where the type on the path for a require from the `ImplicitRequireResolver` was being set to `__core.String` instead of `__core.Kernel.String`

[ruby] Fixed type prefix on require paths from `ImplicitRequireResolver`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

Fixed an issue where the `self` param typeFullName on static methods were not including the `<class>`

[ruby] Changed type of the `this` param on singleton method declarations

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ModuleTests.scala

Fixed an issue where classes defined in namespaces had different fullNames for the class and singleton instance defined in the namespace. Also resolved an issue where methods defined in class defined in a namespace was not being defined under the new `TypeDecl`

[ruby] Fix namespace inconsistencies

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala

* Modified `raise` calls to be control structures of type `THROW`
* If a literal argument is given, this is then explicitly represented as a `StandardError.new`

[ruby] `raise` Calls Represented as Operator

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

Updated AST generation for `RescueExpression` to use `try/catch/else/finally controlStructureNode` types.

[ruby] Use `try/catch/else/finally controlStructureNode` for `RescueExpression`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

Removed `warning` log and `defaultResult` when using any assignment operator other than equals on `BracketAssignment`

[ruby] removed assignment operator restriction on BracketedAssignments

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/AccessModifierTests.scala

* Handles various access modifiers private/public/protected
* Also considers file-level methods are private and initialize methods cannot be anything other than private
* Accounts for nested types where their modifiers are separate from surrounding type

[ruby] Visibility Access Modifiers

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

Lowered `||=` and `&&=` assignment operators to `nil` checks on the respective variables. E.g.
```ruby
hash[:id] ||= s[:id]
```
becomes
```ruby
if hash[:id].nil? then
hash[:id] = s[:id]
end
```

[ruby] Lower `||=` and `&&=` assignment operators

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala

Some calls such as `select` may be commonly shadowed by auto-loaded calls, thus, on an example basis, we will continue to comment out similar calls.

[ruby] Remove `select` as Built-in Call

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala

Added `commandTernaryExpression` to `command` in the ANTLR grammar for situations like the given test case where we have a `ternaryExpression` as a parameter to a parenthesisless call

[ruby] Add `commandTernaryExpression` to `command`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/FieldAccessTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

For chained calls such as `a().b()`, where the base/receiver of `b` involves a call, to avoid invoking the call in both the base and receiver, we now assign a temporary variable to the first invocation and refer to it on the second invocation.

[ruby] Apply Cached Side-Effect Variables

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ExternalCommand.scala

This php parser we use seems to have some warmup phase in which it
has very poor performance which makes it very expensive to feed
it single files like we so far did.
This change invokes the php parser with groups of 20 files which on my
machine give ~40% performance increase for the total frontend runtime on
large projects.
Bigger groups of files strangely only show marginal performance
increases despite the fact that profiling the frontend indicates that
there is still a lot of time wasted by the large amount of individual
parser invocations.
For now we keep it like this because for bigger groups we would run into
argument length limitations which are especially a pain on systems
like Windows. Sadly the php parser does not provide means to specify
the to be parsed files other than as a …

[php2cpg] Improve performance.

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MemberTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala

1. The initialization of static members of class should be placed in `<clinit>` function, not in the constructor of the class. 
2. Access to static members should be prefixed with `self` keyword to distinguish them from normal class members. For example:
```php
<?php
class Foo {
static $A = "A";
const B = "B";
function foo() {
echo self::$A;
echo self::B;
}
}
```

[php2cpg] Fixed the initialization of static/const members of class

---

joern-cli/src/main/scala/io/joern/joerncli/console/Predefined.scala

Recently noticed that the `help` command was no longer working as expected, cf.
```
% ./joern
██╗ ██████╗ ███████╗██████╗ ███╗   ██╗
██║██╔═══██╗██╔════╝██╔══██╗████╗  ██║
██║██║   ██║█████╗  ██████╔╝██╔██╗ ██║
██   ██║██║   ██║██╔══╝  ██╔══██╗██║╚██╗██║
╚█████╔╝╚██████╔╝███████╗██║  ██║██║ ╚████║
╚════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝
Version: 4.0.52
Type `help` to begin
joern> help
val res0: io.shiftleft.codepropertygraph.generated.help.type = io.shiftleft.codepropertygraph.generated.package$help$@1b2f18bd
```
---
This PR hides this specific `help` object from the REPL imports, thus recovering the original behaviour. Not sure this is the ideal approach, but not being familiar with this neck of the woods, didn't want to invest too much time without consulting first.

[cli] recover `help` functionality

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/LoopsTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/ControlStructureDataflowTests.scala

The current `foreach` implementation is based on an older approach that doesn't capture the semantics quite as well.
This PR implements the newer `forAst` construct, which encourages de-sugaring and representing what is semantically happening underneath the `foreach` statement.
Resolves https://github.com/joernio/joern/issues/4674#issuecomment-2222254060

[c#] Implements the `forAst` Construct

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/AssignmentParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

Fixed an issue that was missed where `SingleAssignmentStatement` wasn't being handled properly, usually where there would be some expression for the LHS and the RHS, instead of a simple variable on the LHS.

[ruby] Handle `SingleAssignmentStatement`

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/MethodDefinitionParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

Fixed `parameterList` in ANTLR to allow for `mandatoryOrOptionalParameter` after other types of parameters

[ruby] `ParameterList` parser fixes

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/DependencyPass.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/utils/DependencyDownloader.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DependencyTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/ImplicitRequirePass.scala

* Allows a user of the pass to add additional type identifiers to consider for implicit imports (preference to internal types, motivation is that internal types are generally loaded later which works with zeitwerk's newest-first logic)
* Handles qualified type names to be detected and imported
* Added tests and better handling for constructors
* Deduplicates require calls
* Add core gems to `DependencyPass`

[ruby] Implicit Imports: Additional Types & Qualified Names

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/AssignmentParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DestructuredAssignmentsTests.scala

* Updated ANTLR grammar to allow for the `splat` operator to be in the middle of a multiple assignment LHS
* Updated ANTLR grammar to allow for multiple `splat` operators at different positions of a multiple assignment RHS

[ruby] Splat operator fixes

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ReturnParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

Added `primaryValueListWithAssociation` to `RETURN` ANTLR rule to allow associations to be used in return statements.

[ruby] Add `primaryValueListWithAssociation` to `RETURN` ANTLR rule

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

Changed how the code property is constructed for temp var calls to be more robust.

[ruby] Temp Var Call `code` Fix

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/ScopeElement.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ConditionalTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala

* Reduced redundant match done by `AstForTypesCreator->handleDefaultConstructor`
* Refactored control structure handling into `AstForControlStructuresCreator`
* Re-named `RubyNode` to `RubyExpression` as most-if-not-all Ruby constructs can be evaluated to some value, even statements (assignments, control structures, method definitions, etc. all return a value), and added `RubyStatement` to try to subtly define constructs that stand on their own more often that not -> this will be more fleshed out in Pt. 2
* Noted areas where more clean-up and refactoring is required, but want to keep this diff small-ish

[ruby] General Maintenance & Cleanup Pt. 1

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala

Fixed a bug where `self` identifiers are included in the capture logic, as their REF edges are handled elsewhere.
Railsgoat now returns the following
```scala
joern> cpg.identifier.count(_.refsTo.size != 1)
val res1: Int = 0
```

[ruby] Fix Duplicate `self` References

---

console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/package.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/X2CpgTests.scala
joern-cli/src/main/scala/io/joern/joerncli/JoernParse.scala

as discussed in https://github.com/joernio/joern/issues/4896, we
currently fail hard when the user passes additional frontend
arguments, which we forward to XTypeRecoveryConfig.parse
With this case we still print a warning, but at least don't error.
Potentially better would be to filter out everything _but_ the
expected arguments in this case...
simple test case: foo.sc:
```
@main def main() = {
importCode.python("tests/code/pythonsrc/simple.py",
args=List("--exclude-regex", "test*"))
}
```
```
sbt stage
./joern --script foo.sc
```

XTypeRecoveryConfig: don't error when being passes unknown arguments

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ProcParameterAndYieldTests.scala

Added handling for named arguments when using hash rocket syntax with "symbol" keys.

[ruby] Named Arguments with Hash Rocket Syntax

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/ImportsPass.scala

* All `require`-like call names are now a set under `ImportsPass`
* These calls are now static calls with only the arguments as children
Seems related to https://github.com/joernio/joern/pull/4901

[ruby] All `require`-like Calls are Static

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ProcDefinitionParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/LiteralTests.scala

Fixed `lambda` expression parser rule to allow a parameter list without parentheses

[ruby] Fix `lambda` expression parser rule

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/RangeParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RangeTests.scala

Added parser rules and lowering for `beginless` and `endless` range expressions. 
```ruby
(..0) -> (-Float::INFINITY..0)
(0..) -> (0..Float::INFINITY)
```

[ruby] Add handling for `beginless` and `endless` range expressions

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/TypeDeclTraversal.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/TypeTraversal.scala

such loops are bugs that should be fixed. But they happen occasionally, and right now they lead to OOM and infinite loops. I'd prefer it if we handled that a bit more gracefully. The cost of the set in `.dedup` should be pretty low.

semanticcpg: harden inheritance steps against loops

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/ReturnParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

Added `methodInvocationWithoutParentheses` to `RETURN` arguments

[ruby] add `methodInvocationWithoutParentheses` to RETURN argumentList

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/ImportsPass.scala

Only static calls with import related names 'require', 'load" and so on
are linked to import nodes.
Before that we ended up with import nodes and links for calls like
`Marshal.load(...)`.

[rubysrc2cpg] Fix ImportPass.

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala

Fixed an instance where something like `foo.bar` would represent `foo` as a `self.foo` field access instead of a `foo()` call, given that no `foo` variable is present.

[ruby] Member Access Base as Call Fix

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala

Updated ANTLR grammar rules to allow for any number of mixed element types in an `BracketedArrayLiteral`

[ruby] Added mixed-elements functionality to `BracketedArrayLiteral`

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/DoBlockParserTests.scala

Fixed some ANTLR rules to get rid of warnings for possible empty string matches.

[ruby] Fixed anltr warnings on possible empty string matches

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForPrimitivesCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/AnnotationsTests.scala

If an annotation type full name cannot be resolved we now use
`<unresolvedNamespace>.ClassName` instead of `ANY`.

[kotlin2cpg] Better fallback for annotation types.

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForExpressionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallsToFieldAccessTests.scala

In case of a field access after a map/array access, the following field
access had invalid argument indicies because it triggered the code path
for dynamic receiver calls. This is now fixed.

[kotlin2cpg] Fix field access representation.

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/AccessModifierTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HashTests.scala

* Fixed issue where access modifiers in expression positions would be unhandled
* Handling identifiers on LHS of associations as symbols

[ruby] Access Modifier Names in Expr

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForExpressionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallbackTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala

Fix representation of "nacked" calls like `someFunc(someArg)`. These so
far have always being represented as statically dispatched which is
obviously not correct.

[kotlin2cpg] Fix "nacked" call representation.

---

build.sbt
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala

as brought up in https://github.com/joernio/joern/pull/4936 it can
lead to confusing situations if type parameters are shadowed, so for
the sake of readability and disambiguity alone we should enable this
compiler warning IMO.
That being said, I'd like to stress that it's not something
fundamentally complicated, afaics. Simple example copied from #4936:
```scala
class Example[NodeType <: Object](node: NodeType) extends AnyVal{
def foo[NodeType](x: List[NodeType]): List[NodeType] = x
}
```
These two type parameters in your Example class are not related at all. They happen to have the same name, which only means that within `def foo` we cannot reference the `NodeType` type from the `class Example`, but apart from that there's no connection at all between them.
Semantically it's similar to …

scalac: warn when type parameters are shadowed

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/nodemethods/ExtendedCfgNodeMethods.scala

@tajobe has been doing some byte code surgery in order to create a Kotlin interoperability layer and found an interesting edge case when type parameters are shadowed.
---
Taking a simpler example, consider the following Scala code:
```scala
class Example[NodeType <: Object](node: NodeType) extends AnyVal{
def foo[NodeType](x: List[NodeType]): List[NodeType] = x
}
```
When decompiling the `foo` method, we'll find the following:
```
public static <NodeType extends java.lang.Object, NodeType extends java.lang.Object> scala.collection.immutable.List<NodeType> foo$extension(java.lang.Object, scala.collection.immutable.List<NodeType>);
descriptor: (Ljava/lang/Object;Lscala/collection/immutable/List;)Lscala/collection/immutable/List;
flags: (0x0009) ACC_PUBLIC, ACC_STATIC
Code:
stack=3, …
```

ExtendedCfgNodeMethods: rename type parameter

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/Main.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrParser.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyParserFixture.scala

* Added ANTLR profiling with the `--antlrProfile` frontend argument.
* If enabled, will gather parser metrics and log them right next to the file that was parsed, as well as print any syntax ambiguities.

[ruby] Antlr Profiler

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/utils/FreshNameGenerator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

Added handling for unnamed proc parameter:
```ruby
def foo(&)
bar(&)
end
def bar
yield if block_given?
end
foo do
puts "hello"
end
```

[ruby] Add handling for `(&)` param

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrParser.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala

Profiled `ArrayTests` to detect ambiguity and decisions with high lookaheads and modified test fixture to print profiler logs if enabled. This led to converting certain array rules to use more specific rules and fall back to more general rules less often.
Some small improvements on `railsgoat` measured with `time` command on `joern-parse`:
```
// With ambiguity
75.58s user 1.98s system 356% cpu 21.762 total
73.56s user 2.61s system 492% cpu 15.452 total
66.52s user 2.01s system 387% cpu 17.667 total
// With reduced ambiguity
65.42s user 1.94s system 443% cpu 15.189 total
74.58s user 2.01s system 557% cpu 13.744 total
74.39s user 1.75s system 560% cpu 13.595 total
```

[ruby] Reduce Array Parser Ambiguity

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala

Added handling for multiple splat arguments.

[ruby] Add handling for multiple `Splat` args

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/DependencyResolver.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/GradleDependencies.scala

Before this PR , android project detection only worked for some projects, which would cause conflicts between the `android` plugin in a (java, I think) android subproject and the `java` plugin added by the init script.
The second issue this PR addresses is needing to provide a project name and configuration to the dependency fetcher (without which it would fall back to some defaults ). This is problematic for enterprise customers who would need to do this per app uploaded, but also limited the dependency fetcher to fetching dependencies for a single subproject. The new version automatically detects all projects/subprojects with dependencies, filters configuration names based on some heuristics and fetches dependencies for all of these. 
I tested these manually on some projects I found on …

[Dependency Fetcher] Fix gradle dependency fetcher android detection and detect project and configuration names automatically

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/layers/dataflows/OssDataFlow.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/semanticsloader/FullNameSemantics.scala
dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/testfixtures/SemanticTestCpg.scala

Simple convenience `plus` method for extending `FullNameSemantics` with extra flows.
In general, i.e. for an arbitrary `Semantics`, such a `plus` method (or, more generally, `combine(x: A, y: A): A` for `A <: Semantics`) is not meaningful, unless we want to restrict it considerably (e.g. to a monoid), but we currently don't have any use for such restrictions.

[dataflowengineoss] provide FullNameSemantics.plus method

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AstPrinter.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/AssignmentParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

Added `simpleCommandArgumentList` to allow multiple call args for `methodInvocationWithoutParentheses`

[ruby] Add handling for multiple call args

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/DefaultSemantics.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/SingleAssignmentTests.scala

Conflicting (i.e. same methodFullNamed) `FlowSemantics` are not currently handled by `FullNameSemantics.fromList` and silently it's the last entry that takes precedence. (Will create another PR for this shortly, that combines two such `FlowSemantics` into a single one.)
Take for example `<operators>.assignmentModulo` (as in `x%=y`). We have 2 conflicting entries for it in `DefaultSemantics`:
* `F(Operators.assignmentModulo, List((2, 1), (1, 1), (2, -1)))`
* `F("<operators>.assignmentModulo", List((2, 1), (1, 1)))`
Coincidentally, `Operators.assignmentModulo` is `"<operators>.assignmentModulo"`, so it's the latter `FlowSemantic` that ends up being used, thus preventing the `FlowMapping(2,-1)` from being considered. As such, in an expression such as `call(x%=2)`, the literal `2` doesn't …

[dataflowengineoss] remove overriding operator semantics

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/layers/dataflows/OssDataFlow.scala
dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/testfixtures/SemanticTestCpg.scala

As soon as `FullNameSemantics` started logging duplicate semantics (in #4953), it was observed that `SemanticTestCpg` was passing a fresh Semantics instance to `EngineContext` instead of passing the one used by `OssDataFlow`, cf. `SemanticTestCpg.scala:40`. By coincidence they were the same, so everything was good except for some duplicate work. Nevertheless, this patch guarantees they are the same, by exposing the semantics used by `OssDataFlow`.

[dataflowengineoss] SemanticTestCpg doesn't rebuild semantics

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/layers/dataflows/OssDataFlow.scala
dataflowengineoss/src/test/scala/io/joern/dataflowengineoss/testfixtures/SemanticTestCpg.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/FileHandlingTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/C2CpgSuite.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/testfixtures/CSharpCode2CpgFixture.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/testfixtures/GoCodeToCpgSuite.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/SemanticTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaDataflowFixture.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/dataflow/SemanticTests.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/testfixtures/JimpleCodeToCpgFixture.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/testfixtures/JimpleDataflowCodeToCpgSuite.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/testfixtures/JsSrc2CpgSuite.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/testfixtures/KotlinCodeToCpgFixture.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/testfixtures/PhpCode2CpgFixture.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/PySrc2CpgFixture.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/testfixtures/RubyCode2CpgFixture.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/testfixtures/SwiftSrc2CpgSuite.scala

Continuing the abstraction work from `FullNameSemantics` towards an arbitrary `Semantics`, this PR refactors the test fixtures and `OssDataFlow` layer by replacing the traditional `extraFlows: List[FlowSemantic]` by a more general `semantics: Semantics`. Whereas previously we'd just pass the `FlowSemantic` fragment that we'd like to append to `DefaultSemantics`, the caller is now responsible for building it explicitly, which right now is as simple as `DefaultSemantics().plus(<fragment to append>)`.

[dataflowengineoss] replace `extraFlows` with `semantics`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrContextHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/parser/InvocationWithParenthesisParserTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

Fixed bug introduced by https://github.com/joernio/joern/pull/4946. In this PR, the ordering was accounted for after the fact, but this appeared to have been missed in a few places as some instances in practice had mixed up orders. This uses `line` and `column` information to order arguments correctly at the `elements` call before other nodes are constructed from the result.

[ruby] Fixed Argument Order on `ArgumentListContextHelper`

---

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/TypeRecoveryPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/pysrc2cpg/PythonTypeHintCallLinker.scala

If a method is named `^(import).*`, e.g. `import_table()`, its `methodFullName` is never set, remaining `<unknownFullName>`. Turns out, `PythonTypeHintCallLinker` was filtering it out because of its name.
Credit for finding this edge case: @tajobe

[python] fix methodFullName for methods named ^(import).*

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/AntlrParser.scala

* Introduced global profiling to summarize rule and parse performance across the project
* Added a shutdown hook to dump a summary of the profiler rules in a file `antlr_summary.log` at the root of the project with this information
Examples from below give a good starting point for the currently most expensive rules:
```
Summary for project at 'railsgoat'
Total Parsed Files: 85
Total Parse Time (CPU): 47960.30 (ms)
Avg. Parse Time Per File: 564.24 (ms)
Most Expensive File: app/controllers/admin_controller.rb (4232.11 ms)
Most Expensive Rules By Time in Prediction
==========================================
┌──────────────────────────────────┬────────────────────┬────────────────┐
│Rule Name                         │Prediction Time (ms)│Total Lookaheads│ …
```

[ruby] ANTLR Profiler Summary

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/semanticsloader/Semantics.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

* Allows one to compose arbitrary `Semantics` at runtime, cf. the newly introduced `Semantics.after`, with `NoSemantics` as the identity.
* Identifies `NilSemantics`, which under the current engine seems to work as "negative semantics", removing any potential flows that would otherwise be created. I can't say I have it fully covered yet, but fwiw that's my interpretation at the moment.
* Introduces `NoCrossTaintSemantics`, which can be built both extensionally/intensionally, allowing one to, for instance, specify that an entire external library should have this kind of semantics.
`pysrc2cpg` was the frontend I used for testing them, but only because that's the frontend I was playing with. There's no other reason for not testing with other frontends.

[dataflowengineoss] composable semantics

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MemberTests.scala

This is a hack to fix an autofix issue. The `offset` and `offsetEnd` properties aren't set for the static init method since there aren't always sensible values to set these to, but since they weren't external, autofix was expecting this.
Some backend passes may be affected by this too

Set PHP static initalizer offsets to the whole file

---

joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/IndexAccessTests.scala

Added check to `visitMemberAccessExpression` to modify `.[](index)` notation to an `IndexAccess`.

[ruby] Add `IndexAccess` for `.[](index)` notation

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Ast.scala

Sometimes AST trees would be thrown away, specifically when long chained expressions would be compressed into temporary cache variables. Sometimes the ASTs that are thrown away, have nodes directly written to the diff graph. This only happens with expressions, and closures typically write directly to the diff graph.
This PR minimizes what is written directly to the diff graph from function creation, and extends `x2cpg.Ast` to also include `CAPTURE` edges. This also introduces `closureToRefs` map to track which `Block` nodes already have live method ASTs in the diff graph.

[ruby] Ignore "Throwaway" AST Structures

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Ast.scala

This reverts commit 3c27bf61eea749ac030ae0c981bb9fd88cec0cec.
This PR introduced a bug causing invalid CDGs around the type references.

Revert "[ruby] Ignore "Throwaway" AST Structures (#4982)"

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Ast.scala

This correctly prevents re-use of nodes that are already being used elsewhere by ensuring deep copies.

[ruby] Re-implemented "Ignore "Throwaway" AST Structures (#4982)"

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

`RubyExpression` nodes don't inherently consider the `span` in the calculation of its hash, so when put into any hashed context, nodes that only rely on `span` alone will collide in these contexts.

[ruby] Implement `hashCode` for `RubyExpression`

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/astgen/AstGenRunner.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ExternalCommand.scala

The logic to guess the base dir of the installation is quite fiddly but
works for our use cases for astgen. PhpParser implemented something similar, but
not quite - and it failed for buildbot.
On buildbot the installation path for php2cpg is
`/worker/sptestV2-php2cpg/build/x2cpg-internal/php2cpg/target/universal/stage`
which (prior to this PR) leads to an invalid derived php-parser name
and the following error:
```
2024-09-25 09:30:08.623 ERROR Invalid path for PhpParserBin: /worker/sptestV2-/php2cpg/bin/php-parser/php-parser.php
```

external commands (astgen, php-parser etc.): fix and consolidate base dir

---

joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Main.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/io/Jimple2CpgHTTPServerTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/server/FrontendHTTPClient.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/server/FrontendHTTPServer.scala

Turns out the HTTPServer expects an explicit "Connection: close" header which requests the connection to be closed after the transaction ends. Otherwise, it would wait for a 10sec timeout for the next thread to become available. In case we only allow for one thread (jimple2cpg) that would mean additional waiting which renders the whole server approach useless. This in now fixes as we immediately close the connection after the frontend is finished.

[x2cpg|jimple2cpg] Added server mode to jimple2cpg after fixing response header

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/FullNameProvider.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/MethodTests.scala

This happened for parameter and variable declarations in parentheses.

[c2cpg] Fixed name for nested declarators

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CustomFileContentProvider.scala

Needs some testing for (very) large projects.
Caching all the header file contents may make things worse compared to (re-) reading them from disk and GC immediately/soonish.

[c2cpg] Implemented cached header file loading

---

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ClassLoaderTypeTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/LocalTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeNodeTests.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/types/structure/TypeTests.scala

While waiting for another PR job to conclude, noticed some "garbage" in the logs. Tidying them up a little bit...

[test] remove leftover `println`

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/language/nodemethods/ExpressionMethods.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

It's been observed some time ago that `PassThroughMapping` wasn't behaving as expected when there were named arguments involved. For instance, see the first two added unit-tests: they were failing while the semantics for `foo` were `0->0, PassThroughMapping`.
The criteria for `hasDefinedFlowTo` was, in the same vein of #5000, not taking into account the fact that named arguments share the same index, even if their argument names are different.

[dataflowengineoss] Fix PassThroughMapping criteria for same-call named arguments

---

joern-cli/frontends/kotlin2cpg/build.sbt
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeRenderer.scala

DescriptorRendererImpl [asserts that the options are locked upon init](https://github.com/JetBrains/kotlin/blob/master/core/descriptors/src/org/jetbrains/kotlin/renderer/DescriptorRendererImpl.kt#L36). This means that the type rendering will fail anywhere with assertions enabled (`-ea` JVM option) as the options weren't being locked after setup.
In order to test this, I added `-ea` to the test javaOptions (which requires `Test/fork` to be `true`) and things fail. With the addition of `opts.lock()`, they pass. I'm not sure if there's a reason the tests were explicitly set to not fork or if there's a desire to keep the javaOpts "clean", but this was the easiest way to illustrate the error and fix.

[kotlin2cpg] Fix assertion error by locking descriptorRenderer options

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/Main.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/JSONCompilationDatabaseParser.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/ParserConfig.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/PreprocessorPass.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/JSONCompilationDatabaseParserTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/SourceFiles.scala

Specifications e.g., here: https://clang.llvm.org/docs/JSONCompilationDatabase.html
With this, we only handle files listed there.
Additionally, defines and includes are passed to CDT on a per file level just like the actual compiler invocation.

[c2cpg] Implemented support for JSON Compilation Database Files

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ExternalCommand.scala
joern-cli/frontends/x2cpg/src/test/scala/io/joern/x2cpg/utils/ExternalCommandTest.scala

* report exit code if it's non-zero
* pass on original error (if any) rather than disregarding it
* log.warn stderr output (if any)
* add tests

ExternalCommand: more information in error conditions

---

joern-cli/frontends/x2cpg/build.sbt
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/MavenDependencies.scala
project/Versions.scala

fixes the regression from the ExternalCommand refactor, but I just couldn't leave the the env var handling as it was either. Splitting at any whitespace isn't correct (quotes!). Switching to a proper library for parsing CLI arguments instead.

fix maven dependency fetching

---

console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala

Trying to `importCode.kotlin.fromString(...)` from the REPL would silently fail as no files would be parsed, since the temporary file suffix would be `.kotlin`, and thus unrecognised.

[console] fix kotlin's extension

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ExternalCommand.scala

This bypasses tty buffering and read timeouts.
Ubuntu runner time here on GH went from 27min down to 17min.

[x2cpg] Redirect stdout/stderr to tmp files

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/DefaultSemantics.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala

Adds (passthrough) semantics for `Operators.modulo`. Otherwise, the default behaviour would let, e.g. `x` taint `y` in `x % y`.

[dataflowengineoss] add Operators.modulo semantics

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/DefaultSemantics.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala

Elements of `arrayInitializer` should not taint each other; instead, they should only taint the resulting expression.

[dataflowengineoss] add Operators.arrayInitializer semantics

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForNameExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/AnonymousClassTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/FieldAccessTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/ScopeTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/accesspath/TrackedBase.scala

For static field access like `String x = staticField1;` we used to
generate a IDENTIFIER with the name of the class declaring the static
field as base for the field access operator.
Now we generate a TYPE_REF referencing the declaring type. This better
represents the actual situation where there is no local variable for
a class/type which in practice also resulted in a CPG format error
because the IDENTIFIFER node was at least not in all cases linked to a
LOCAL.
While implementing this i reorganized the code a bit to avoid
duplication.
Also changes the `equals` semantic for TrackedTypeRef. Before it was
based on the actual TYPE_REF node which does not make sense. Instead we
need to compare the referenced TYPE itself to check if two different
type references in code point to the same TYPE.

[javasrc2cpg] Generate TYPE_REF for implicit base of static field accesses.

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/MavenDependencies.scala

We already do this for gradle tasks that fail, so also log the full maven output if fetching dependencies fails to make debugging easier.

Log full maven output on failure

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForDeclarationsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForExpressionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForPrimitivesCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/DefaultTypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/types/TypeInfoProvider.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallTests.scala

Fixes: https://github.com/joernio/joern/issues/5042

[kotlin2cpg] Named arguments for KtCallExpression and implicit this

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala

Moved the lowering of `||=` and `&&=` to respective `AstCreator`'s and updated `ControlFlowStatement` areas to account for new `OperatorAssignment` node.

[ruby] Move lowering of `||=` and `&&=` to `AstCreator`

---

joern-cli/frontends/rubysrc2cpg/src/main/resources/application.conf

Some stats on https://github.com/joernio/ruby_ast_gen/pull/10, however, `AstCreation` only begins to ingest parsed files once the parsing is complete instead of as files are ready, which may be required to realize further performance gains on large repositories such as `gitlab`.
Resolves [#5066](https://github.com/joernio/joern/issues/5066)

Upgrade to Multi-Threaded `ruby_ast_gen`

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala

We were observing some OOM exceptions when providing large .jars to kotlin2cpg's classpath. Profiling the memory usage, it was clear it kept growing between multiple same-process invocations.
Below are two such graphs. They were obtained by:
* including a ~350MB .jar in kotlin2cpg's test resources
* setting the flag `withDefaultJars=true` by default
* running the kotlin2cpg tests
Before:
After:

[kotlin2cpg] Dispose the environment as soon as it's not needed

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ModuleTests.scala

Added handling for `private_class_method` and `public_class_method` access modifiers, making the function def that follows them have either `PRIVATE` or `PUBLIC` modifiers.
TODO: 
handle multiple args: It's possible to call `private_class_method` with a list of symbols representing function names. All the functions matching these symbols would then also have a PRIVATE access modifier.
Resolves #5061

[ruby] handle `private_class_method` and `public_class_method` access modifiers

---

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/ObjectTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/testfixtures/JavaSrcCodeToCpgFixture.scala

Apropos #5049, includes an ignored test that stopped working after #5036. Unfortunately, such a test wasn't there before to flag this regression.
Previously, in the example's `System.out.println(CONST)` we were lowering `CONST` as `Bar.CONST`, with `Bar` an IDENTIFIER. Presently, `Bar` is a TYPE_REF and we lose this dataflow. 
Another thing to point out regarding this design change is that it's not consistent throughout. For instance, if we had written `System.out.println(Bar.CONST)` , `Bar` is here not a TYPE_REF but again an IDENTIFIER.
I'm willing to contribute patch(es) to the recovery of this flow, but would need some guidance as I've not been able to find a workaround after some initial experiments. (Thanks in advance)

[javasrc2cpg] add basic static field test

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/dataflow/ObjectTests.scala

Resolves #5049 and fixes the ignored unit-test introduced in #5075

[javasrc2cpg] support flows for field accesses with a TYPE_REF base node

---

joern-cli/frontends/rubysrc2cpg/src/main/resources/application.conf
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/Main.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyAstGenRunner.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/config/IgnoreRegexTest.scala

* Fixed ignore regex for Ruby to account for prefix or suffix on the `db/migrate` dir.
* Fixed regex passing to `ruby_ast_gen` so that it also ignores the correct directories.
Resolves #5062

[ruby] Fix ignore regex for Ruby

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ModuleTests.scala

Fixed call type for block when using `protected` keyword.
Resolves #5069

[ruby] Fix Call Type for Block

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

Added handling for `ReturnExpression` as implicit return statement.
Resolves #5089

[ruby] Implicit Return for `RangeExpression`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala

Accept default handling for `MemberAccess` and `IndexAccess` when used as an association key.
Resolves #5091

[ruby] AssocKey handling

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/compiler/CompilerAPI.scala

It seems unnecessary to save the resource to a temporary file in order to load it. I couldn’t find any specific reasoning for this approach in the original PRs, so it’s possible I’m missing some context from the original authors.
Locally, this consistently shaved off 3 seconds when running `kotlin2cpg/test`, but with larger inference .jars the savings would naturally be more noticeable.

[kotlin2cpg] JvmClasspathRoot without an actual temporary file

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/ScopeElement.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ProcParameterAndYieldTests.scala

Added handling for `yield` in a constructor.
Resolves #5090

[ruby] Handle `yield` in Constructor

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ModuleTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XTypeRecovery.scala

Fixed lifting of field statements, previously was lifting out any `SingleAssignments` that were inside of methods causing variables to be registered at fields when they shouldn't have been.
Resolves #5092

[ruby] Fix lifting of Field Statements

---

querydb/src/main/scala/io/joern/scanners/c/UseAfterFree.scala

In the file `querydb/src/main/scala/io/joern/scanners/c/UseAfterFree.scala`, the free-follows-value-reuse query has a comment in the "the query does not match" examples. The comment states that the `return x` is not post-dominated by the free call, I believe this is not what the author meant as this statement is not relevant to what the query is doing. This could confuse users. I believe the author wanted to write the following comment instead `return x doesn't post-dominate the free call`.

[QueryDB][docs] Fix comment in UseAfterFree query

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

Fixed warning where `public` was a call to a user-defined method instead of to the Ruby reserved keyword.
resolves #5109

[ruby] `public` in a Method body is lowered to `SimpleCall`

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/compiler/CompilerAPI.scala

This reverts commit 16f9541eb84605053e9c5484830b4b05e72364a7.
See source code comment for further details.
cc @xavierpinho

Revert "[kotlin2cpg] JvmClasspathRoot without an actual temporary file (#5097)"

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

* Moved getters and setters defined in the `included do` block to directly under the class/module `TYPE_DECL`
* Added implicit return for `FieldsDeclaration` (We generate the AST for the `FieldsDeclaration` and add an implicit `return nil` afterwards)
Partially resolves #5118

[ruby] `FieldsDeclaration` in `included do` block

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ContextStack.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/VariableReferencingCpgTests.scala

The linking of captured variables was not yet working if variables from
outside of a class have been captured into methods of a class.
This was the case because of a possible name clashes between those
captured variables and variables inside of the class body methods.
To avoid such clashes captures variables get a `<captured>` prefix
inside the class body methods.
This solves a long standing issue where data flows via such captured
variables were not found.

[pysrc2cpg] Fix captured variable linking into class scopes.

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

* Moved `AliasStatement` lowering to `AstCreator`
* Added handling to ensure methods are lowered to directly under the respective `TYPE_DECL` when found in the `<body>` method.
Resolves #5116

[ruby] Alias and Method Lowering

---

joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/parser/BabelJsonParser.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/AstCreationPass.scala

https://github.com/joernio/joern/pull/5127 made `BabelJsonParser.readFile` a bit safer by simply wrapping everything into a big try.
This PR changes that to:
- separate Try blocks for type map loading, json loading, and parse result generation
- forward exceptions from json loading and parse result generation to `AstCreationPass.runOnPart`, and
- do a proper WARN logging of these exceptions

[jssrc2cpg] Improve error handling even further

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/config/ConfigTests.scala
joern-cli/frontends/ghidra2cpg/src/test/scala/io/joern/ghidra2cpg/config/ConfigTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/config/ConfigTests.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/config/ConfigTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/config/ConfigTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/config/ConfigTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/config/ConfigTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/config/ConfigTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/config/ConfigTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala

previously this was supposed to be called with `,` as a separator,
e.g. `--exclude foo,bar` - which (among others) has the disadvantage
that under windows a `,` is treated as an argument separator
better: provide this argument multiple times, i.e. `--exlude foo --exclude bar`
note: the old way using commas is still supported

frontends: allow multiple `--exclude` parameters (additionally)

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/utils/AstGenRunner.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala

This passes the ignored files and the ignored files regex down to astgen so we do not parse files matching them for nothing.
Also: removed `NODE_OPTIONS` as this is already hardcoded into the astgen build

[jssrc2cpg] Pass excludes to astgen

---

console/src/main/scala/io/joern/console/cpgcreation/JavaSrcCpgGenerator.scala
console/src/main/scala/io/joern/console/cpgcreation/JsSrcCpgGenerator.scala
console/src/main/scala/io/joern/console/cpgcreation/PhpCpgGenerator.scala
console/src/main/scala/io/joern/console/cpgcreation/PythonSrcCpgGenerator.scala
console/src/main/scala/io/joern/console/cpgcreation/SwiftSrcCpgGenerator.scala

We trigger the post-processing directly if a cpg is loaded on startup
(e.g. `./joern cpg.bin`). In that case, the typeRecoveryConfig has not
been initialized. There's a reason why in Scala you have to explicitly
make an effort to start with `null`, because more often than not
you'll be missing out some random edge case... lazy val is the better
alternative
fixes https://github.com/joernio/joern/issues/4999 (again...)

fixup initialisation order of cpg generators

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForNameExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForPatternExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForForLoopsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForSimpleStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/JavaScopeElement.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/TemporaryNameProvider.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/PatternExprTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/util/ScopeTests.scala
project/Versions.scala

This PR adds several things related to type pattern matching (which was added in Java 16 and extended to switch statements in Java 21), in particular:
* Locals for all pattern variables that appear in `instanceof` expressions or switch entry labels
* Assignments for pattern variables which are used or introduced to a block scope
* Temporary locals and assignments for the left-hand sides of `instanceof` expressions or switch conditions which are complex expressions to avoid side effects from invoking these twice
There are a few TODOs still left after this:
* Record pattern support is still missing. The code as it is now shouldn't create an invalid CPG (in the sense of throwing errors), but the `instanceof` comparison for record patterns does not consider the types of nested patterns/types …

Add support for java type pattern matching

---

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala

Closes #4664 
The ignored tests were moved since they were being built with `DefaultSemantics`, i.e. `withSemantics` only changes the query-time `Semantics`, hence the new test classes.

[pysrc2cpg] add dataflow test

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/Main.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForNameExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForPatternExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForSimpleStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/JavaScopeElement.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/TypeFallbackTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/util/ScopeTests.scala

This PR adds functionality to disable wildcard import handling and `expectedType` fallbacks with the `disable-type-fallback` flag and changes the behaviour of the `ANY` type fallback when this flag is set. Where a type name is available but cannot be resolved, `<unresolvedNamespace>.TypeName` will be used instead of  `ANY`. In cases where the simple name isn't available either, `ANY` is still used, but this can easily be changed in the `defaultTypeFallback()` method.

Add option to disable type fallbacks for javasrc2cpg

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

Added implicit return handling for `MethodAccessModifiers`
Resolves #5145

[ruby] Implicit Return for `MethodAccessModifier`

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/PythonAstVisitor.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/ClassCpgTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/MethodMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/MethodTraversal.scala

In class body functions, assignments to variables represent assignments
to members in the meta class object.
This change adds the additional statement to the class body method to
reflect this.
Also: Made `topLevelExpressions` step available for individual methods.

[pysrc2cpg] Create member writes for variables writes in class bodies.

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala

For: https://shiftleftinc.atlassian.net/browse/SEN-3467

[c2cpg] Guard instanceOf casts

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/C2Cpg.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CustomFileContentProvider.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/JSONCompilationDatabaseParser.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/ParserConfig.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/PreprocessorPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IncludeAutoDiscovery.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/JSONCompilationDatabaseParserTests.scala

This adds support for MSVC system header discovery via `--with-include-auto-discovery`.
1) Ask `vswhere.exe` for the actual MSVC installation path (https://github.com/microsoft/vswhere, included in every installation as of Visual Studio 2017).
2) Call `vcvars64.bat` to set the `INCLUDE` environment variable.
3) Use that to configure CDT.
Also in this PR (disovered during testing the MSVC stuff):
- fixed the `DefaultIgnoredFolders` regex for paths containing dot folders.
- proper thread-safe header file caching (caching the actual parse result and not only the plain code) using `createForExternalFileLocation` and `resetForTranslationUnit()`.

[c2cpg] Added MSVC support

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

Fixes issue where `<body>` calls from nested types were being given as direct children to type decls. The solution pushes `<body>` calls to the next method.
Another issue was that access modifier calls did not check that the argument was actually a method. Sometimes methods could be referred to via an identifier in some data structure. This PR currently emits a warning for these cases.
Resolves #5155

[ruby] Fix Call as TypeDecl AST Child

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala

Fixed an issue where we were encountering a warning: `Parameter without method encountered`. This one was a bit of a rabbit hole to figure out
The following is a minimal example to reproduce the error we were having:
```ruby
class Foo
def bar(baz, &)
someFunc(&)
@limit -= 100
puts @limit.zero?
end
end
```
1) We hit `@limit -= 100`, `@limit` here was seen as `SimpleIdent` and gets added as a variable to the scope with name `@limit`
2) We then hit `puts @limit.zero?`, which has a `FieldAccess(target=FieldIdentifier(@limit))`, where the `FieldIdentifier` is `RubyIdentifier` so it goes into `AstForExpressionsCreator::astForSimpleIdentifier`
3) When we get here, we call the `scope.lookupVariable(name)` but now it wrongly finds `@limit` in the variable scope because the `FieldIdentifier` here …

[ruby] Fixed `Paramater without method` issue

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CustomFileContentProvider.scala

This caused unstable (sptests) results.
Turns out CDTs `InternalFileContent` is not thread-safe and concurrent AST modifications (e.g., macro expansions) make problems.
(Needs a x2cpg bump and release afterwards!)

[c2cpg] Reverted changes to header content cache

---

console/src/main/scala/io/joern/console/cpgcreation/CSharpSrcCpgGenerator.scala
console/src/main/scala/io/joern/console/cpgcreation/ImportCode.scala
console/src/main/scala/io/joern/console/cpgcreation/package.scala

Allow the use of `importCode.csharpsrc.fromString(...)`, which proxies to `csharpsrc2cpg`.
Follows the pattern found in `JavaCpgGenerator` and `JavaSrcCpgGenerator`. I reckon there is room for improvement (i.e. refactoring) here when dealing with `commercialAvailable` and `ossAvailable`, but one step at a time.

[console] add csharpsrc

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/Main.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/passes/DependencyTests.scala

Adds support for ignoring `builtin_types` in C#. This is a preliminary step toward enabling users to supply their own custom `builtin_types`, and thus avoid name clashes.

[c#] add `disable-builtin-summaries`

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForSimpleStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/JavaScopeElement.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/MethodParameterTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/RecordTests.scala

This PR adds proper support for java records by introducing the following:
```
record Foo(Bar bar, Baz baz) {}
```
will have the fields
```
private Bar bar;
private Baz baz;
```
```
record Foo(Bar bar, Baz baz) {}
```
will have the getter methods
```
public Bar bar() { return this.bar; }
public Baz baz() { return this.baz; }
```
The correct canonical constructor which initializes the record fields is created instead of the default empty constructor. For example:
```
record Foo(Bar bar, Baz baz) {} 
```
will have the constructor 
```
public Foo(Bar bar, Baz baz) {
this.bar = bar;
this.baz = baz;
}
```
```
record Foo(Bar bar, Baz baz) {
public Foo {
sink(bar)
}
}
```
will have the constructor
```
public Foo(Bar bar, Baz baz) {
this.bar = bar;
this.baz = baz;
sink(bar);
}
```

Add proper support for java record classes

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/ImplicitRequirePass.scala

The implicit `require` call node creation is now deferred until the AST parent is presented.

[ruby] Fixed issue where implicit require generates floating node

---

joern-cli/frontends/c2cpg/eclipse-cdt/CCorePlugin.java

We can release this later. Just saw null there during testing on the chromium source code again.

[c2cpg] Safer CCorePlugin.log with null

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/ExcludeTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/SourceFiles.scala

Some major improvements here:
1. Storage of found files in now in an Array (constant append). A Set was never actually needed. 
2. Filtering and skipping of files/folders happens now directly during the traversal instead of at the very end.
3. Proper scaladoc.
1 and 2 reduced the runtime for finding all C/C++ files in the chromium sources by ~50% (30sec down to 15sec on my machine).
This also fixed the case-sensitive/insensitive issues on Mac as shown in: https://github.com/joernio/joern/pull/5180/commits/b183fc2a4ab1be6385aaf5ba04a7c33a601a65c5

[x2cpg] Completely overhauled SourceFiles

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala

* Multiple assignments may be given as arguments to calls and such, thus they are now handled under `astForExpression` as a block containing the multiple assignments
* BackRef's from regexs are handled as `self.$&`
* Lowered the warning level for non-method nodes as access modifier arguments

[ruby] BackRef and Multi-Assign Args

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/Main.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/passes/DependencyTests.scala

Introduces an `external-summary-paths` option, allowing users to provide custom directories for type summaries à la `builtin_types`. Some minor refactoring otherwise.

[c#] add `external-summary-paths` option

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala

#5169 was open before #5180. The latter got merged first and thus the former would break the build.
This is just the most straightforward patch to get out of this situation immediately.

C# - update usage of SourceFiles.determine

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/SourceFiles.scala

`File.extension` does some additional checks before returning the actual extension (`isRegularFile` and `exists`). We do not need these checks as the files we operate on are returned by a file visitor traversing said files.
This shaves off plenty of time when traversing large directories.

[x2cpg] Replace better.File.extension

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/UsingDirectiveTests.scala

Adds support for handling `global using` directives. These are distinguished both during summarisation and in `CSharpProgramSummary`, so that `findGlobalTypes` accounts for them.

[c#] support for `global using` directives in `CSharpProgramSummary`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

* Fixed a bug where singleton methods defined on types unresolvable in scope were assigned themselves as AST parents
* Fixed a bug where bracket invocations on unresolvable types were interpreted as index accesses without an index

[ruby] Cyclic Singleton Method AST & Bracket Invocation Fix 

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TopLevelStatementTests.scala

Adds support for top-level statements by imitating the lowering performed by Roslyn, i.e. by wrapping them inside a code block like
```csharp
internal class Program
{
private static void <Main>$(string[] args)
{
<top-level-statements>
}
}
```
I used the same names (`<Main>$` and `Program`) here, but I'm not sure if the usage of `<` or `$` is reserved in full names? If so, what would the recommended names be?
Caveat: there can only be one such file (with top-level statements), which implicitly becomes the program's entry point. In an arbitrary repo we might find more than one since this restriction is tied to a `csproj`. In other words, the "compilation unit" would ideally be a .csproj, but that would mean a large refactoring.

[c#] support for top-level statements

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForNameExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala

Promotes `javasrc2cpg`'s `createFieldAccessAst` utility method to `x2cpg` and reuses it in `csharpsrc2cpg`.
Context: I have a couple of PRs in the pipeline for improving csharpsrc2cpg with some missing features (like chained member accesses and field initialisers) and am creating smaller PRs as I clean it up.

[x2cpg] add fieldAccessAst

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MemberTests.scala

* Replaces 2 unit-tests with a bunch more granular ones that completely cover them. In general, these unit-tests contain quite some irrelevant information and only tested at the highest level, as it became clear once we started splitting them; see the `// TODO` comments and `ignored` test cases.
* Fixes the `.code` property for the field initialisations moved to the constructors. E.g. in `class C { int x = 200; }`, the assignment for `x = 200` was setting the code for `x` (the target) as `x = 200`, instead of just `x`.

[c#] fix member assignment LHS `.code` property

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala

`astForSimpleMemberAccess` was doing more than its fair share of work. This makes sure it's exclusively handling `SimpleMemberAcessExpression` node kinds -- that `case _` fallback previously in there shouldn't exist. The next step is to handle chained member accesses while taking into account the `SuppressNullableWarningExpression` kinds.

[c#] astForSimpleMemberAccess deals exclusively with SimpleMemberAccessExpression nodes

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForNameExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForPatternExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForSimpleStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/JavaScopeElement.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/TypeInfoCalculator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/PatternExprTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/Defines.scala

This PR adds support for pattern matching with record patterns. The lowering is effectively done in 2 stages:
First, the `instanceof` check for the record pattern is created. This is represented as a series of `instanceof` checks for the whole record tree. There are lots of examples of what this lowering looks like in the unit tests but, since the resulting lowering gets rather large very quickly, I'll include a simple example here.
```
record Foo(String left, Integer right) {}
class Test {
void test(Object o) {
if (o instanceof Foo(String s, Integer i)) {}
}
}
```
the `instanceof` check is lowered to
```
(o instanceof Foo) && ((($obj1 = ((Foo) o).left()) instanceof String) && (($obj0 = ((Foo) o).right()) instanceof Integer))
```
The first `o instanceof Foo` call is the same we'd expect …

Add support for record pattern matching

---

joern-cli/frontends/php2cpg/build.sbt

others will follow once the entire chain works

write the php parser version to the manifest for downstream usage: php2cpg

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstSummaryVisitor.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MemberTests.scala

* `astForSimpleMemberAccess` is now without edge cases.
* This refactoring brought up to light another edge case: classes/typeDecls found outside an explicit namespace block were not being loaded into `CSharpProgramSummary`, and thus their fields wouldn't be found later on.
* Fixes a semantically invalid unit-test code sample: `this.nonInitMaxSpeed` inside a `static` method isn't valid C# code.

[c#] finish refactoring astForSimpleMemberAccess

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/PatternExprTests.scala

While troubleshooting a customer issue, I reproduced some missing locals using the elasticsearch repo as a test project. This fixes some of the orphan locals, but there is another issue which I'm still looking into, but which is unrelated to patterns.

Add tmp locals for pattern initializers to lambda method bodies

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/FieldAccessTests.scala

Follow up of #5198 -- noticed that, e.g. in `System.Console.WriteLine`, the `typeFullName` for `Console` was `ANY`, when it should've been `System.Console`. In this example, `System` is not a type (and thus, `Console` not its field); the proper type is `System.Console`, which is what we look-up for in this patch.

[c#] support namespace reference in nested field accesses

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MemberTests.scala

Fields with initial assignments are now moved to the `<init>` (constructor) method, even when a default constructor is not explicitly declared. Previously, this behavior was supported only for explicitly declared constructors. This patch applies exclusively to dynamic fields -- support for moving static field initializations will be addressed in a future PR.

[c#] create implicit ctor for field inits

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/AnonymousClassTests.scala

When an anonymous class is defined, the name of the enclosing scope is prepended to the anonymous class name to ensure uniqueness. I previously used an empty method node for lambda methods, however, so the enclosing scope name for anonymous classes in lambdas would just be `<empty>`. This resulted in duplicate anonymous class names being possible and in an edge case where orphan locals were created in anonymous classes of the same name where one is defined in a lambda in a static scope and one in a non-static scope.
This PR fixes this issue by using the actual lambda method node in the scope.

Fix names of anonymous classes defined in lambdas

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala

`alias_method` is a builtin call that performs a more "dynamic" version of `alias` as it makes use of symbols. This change applies the same alias lowering logic to this function as what happens with `alias` calls.
Misc additions:
* Addresses warning for `reassign` not having an exhaustive match (due to the `InClause` object)
* Strips the leading `*` from collection parameters, as these are referred to in the method body as splatted identifiers without the leading `*`.

[ruby] Alias Handling for `alias_method`

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala

Fixed an issue where the variables that the pattern extracted to were interpreted as fields instead of local variables. Also makes sure the pattern match call happens on the original expression and not on the LHS match variable.

[ruby] In Pattern Variable Scoping Fix

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/ControlStructureTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/TemplateTypeTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/LocalQueryTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala

- range-based for-statement blocks had multiple outgoing CFG edges because the children were not wrapped into blocks.
- code fields for locals from NamedTypeSpecifiers now preserve static and const modifier

[c2cpg] Improvements for range-based for-statement and local code fields

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/typesolvers/TypeInfoCalculator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/EnumTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/RecordTests.scala

The lowering for enum constants still needs an overhaul, but this fixes the inheritance hierarchy, at least.

[javasrc2cpg] Have enums and records extend java.lang.Enum and java.lang.Record

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/GccSpecificExternalCommand.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IncludeAutoDiscovery.scala

Fixes: https://shiftleftinc.atlassian.net/browse/SEN-3587

[c2cpg] Fix StackOverflowError within IncludeAutoDiscovery

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/FieldAccessTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/ListUtils.scala

Follow up to #5205 -- the previous tests worked fine since `System` was being imported. However, we should still resolve e.g. `System.Console` when `System` is not being imported. I forgot to take into account this scenario in the previous PR.

[c#] allow resolving fully-qualified names without importing them first

---

build.sbt
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MethodTests.scala

There's a customer issue where reading the file content was resulting in a `MalformedInputException` being thrown. With this PR, we just try all of the Java standard charsets before emitting a warning instead of crashing: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/charset/StandardCharsets.html
I would be very surprised if we ever need the specific endianness UTF-16 variants, but since this only tries encodings until something works, I also don't think adding them to the list has much of a downside.

[php2cpg] Try multiple charsets when reading file content

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TopLevelStatementTests.scala

Top-level method declarations, i.e. method declarations outside of class declarations, are lowered (following Roslyn's approach) as local functions to the implicit `main` method created for the file they are found in. Their node kind -- `LocalFunctionStatement` -- is shared for local/inner method declarations, and support for these is also in the works.

[c#] support top-level method declarations

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala

This change reworks the means of extracting the variables from an array pattern match by using an index access corresponding to the location we want to extract. e.g.
```ruby
case [type, location]
in [:value, result]
puts "#{result}"
else
puts "else"
end
```
Accesses `result` by `<tmp-0>[1]` (where `<tmp-0> = [type, location]`)

[ruby] Rework In Pattern Match Overtainting

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala

The more semantically sound version of the current lowering checks for all "falsey" states of a variable instead of only the nil condition. Thus, the lowering is changed as follows: `aaa ||= bbb` becomes `aaa = bbb if !aaa`
`aaa &&= bbb` becomes aaa = bbb if aaa`

[ruby] Rework Conditional Assignments

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala

Pattern match array creation is now lowered so that both reads and writes assign array indices to where each element much be read and written from.

[ruby] Lower Array Creation for In Pattern Match

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/OuterClassRefPass.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LocalClassTests.scala

If a class captures the outer class, then we lower the constructor
```
public Foo() {
this("chained constructor call");
}
```
to
```
public Foo(OuterClassType outerClass) {
this("chained constructor call", outerClass);
}
```
The implementation for this was creating an orphan `outerClass` identifier in the CPG due to a REF edge that was incorrectly added. 
This is a fix in 2 parts. The first is to remove a ref edge to an `outerClass` used capture which shouldn't have been added to the CPG.
The second is to create the correct ref edge to the `outerClass` parameter. I did it in a pass after the fact since the current implementation handles the creation of parameters for captured variables and adding arguments to constructor calls separately, both outside of the actual method scope. This …

[javasrc2cpg] Fix orphan outerClass locals in constructor bodies

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CaseTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DestructuredAssignmentsTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala

All arrays are initialized via a block at each specific index access the element is positioned, e.g. `a = [1, 2]` becomes
```
a = {
<tmp-0> = Array.new
<tmp-0>[0] = 1
<tmp-0>[1] = 2
<tmp-0>
}
```

[ruby] Lower Array Creation for All Arrays

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/TypeNodePassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/LocalQueryTests.scala

The local code field is now the actual source code for that declaration. Not something we reconstruct from its type. Never lose static again.

[c2cpg] Refactored code string calculation for locals

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/ProgramSummaryCreator.scala

The creation of the local `CSharpProgramSummary` was previously scattered across `createCpg` without clear benefits. This centralizes it into a dedicated util.

[c#] refactor local summary creator into its own util

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/CSharpSrc2Cpg.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpProgramSummary.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/ImplicitUsingsCollector.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/ProgramSummaryCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ImplicitUsingsTests.scala

Introduces an initial mechanism to handle implicit global imports enabled by `<ImplicitUsings>` in `.csproj` files. Behind the scenes, Roslyn generates a set of `global using XXX` directives based on the project type. In this PR these directives are globally collected and included as `globalImports` to `CSharpProgramSummary`. Remaining changes are just minor refactoring tweaks.

[c#] basic support for ImplicitUsings

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/ImplicitUsingsCollector.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ImplicitUsingsTests.scala

Handles `<ItemGroup><Using Remove="XXX"/></ItemGroup>` tags in `.csproj` files. These tags allows one to manually exclude certain namespaces from the generated global imports.

[c#] support for <Using Remove=XXX> in csproj files

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala

We see a few not-handled-yet warning for `MemberBindingExpression` when, in fact, it's being handled -- just not at the top-level. Given how the AST is structured, we need to pass the base type full name to this visitor, making it an helper-like visitor to be used by others. In this PR we fix these erroneous warnings by not going through the top-level `astForNode` when we already have the base type full name. Consequently, we also avoid the creation of an UNKNOWN node that was never added to the CPG.

[c#] fix erroneous not-handled-yet warning for MemberBindingExpression

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ExtensionMethodTests.scala

Extension methods are syntactic sugar that underneath expand to the resolved method call, e.g.
```csharp
x = new MyClass();
x.DoStuff(); // is actually rewritten by Roslyn as MyClassExtensions.DoStuff(x);
class MyClass {}
static class MyClassExtensions {
public static void DoStuff(this MyClass c) {}
}
```
See: [Binding Extension Methods at Compile Time
](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods#binding-extension-methods-at-compile-time)
This PR is only a first move towards "full support" (as much as it's feasible) and fixes the `methodFullName` properties of those calls. So, in `x.DoStuff()`, it's still a dynamic dispatch call with an argument `x`, but whose fullName is no longer `MyClass.DoStuff():<unresolvedSignature>` but …

[c#] methodFullName for extension method calls

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/dotgenerator/DotAstGeneratorTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/dotgenerator/DotCdgGeneratorTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/io/dotgenerator/DotCfgGeneratorTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/dotgenerator/DotSerializer.scala

Basically revives https://github.com/joernio/joern/pull/2002

Improved DotSerializer layout

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala

Making sure we (a) use `composeMethodFullName` every time we build a `methodFullName`; (b) use `Constants.This`.

[c#] cleaning up around "this" and composeMethodFullName

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ExtensionMethodTests.scala

In #5245, we resolved an extension method only if there was exactly one potential match, which deviates from the referenced source documentation, which states the resolution should target the first match found. However, it's not clear the order in which matches should be considered -- or, at least, I couldn't find it. Based on experimentation, it seems to prioritise the compile-time type, as can be seen in the tests involving `MyConcrete` and `MyAbstract`. To this end, I relaxed `tryResolveExtensionMethodInvocation` to always pick the 1st match.
In doing so, also uncovered a bug in which two methods can share the same `methodFullName`. We should disambiguate e.g. `DoStuff(List<string>)` from `DoStuff<T>(List<T>)`. Included an ignored test, since it's not handled here. Once these are …

[c#] not requiring exact match for extension methods

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/PropertyGetterTests.scala

Reworks property accesses into method calls. For instance, 
* `System.Console.Out` is no longer a field access (to `Out`) but a static (because `Out` is a static property) call `System.Console.get_Out()`.
* `x.KeyChar`, where `x` has type `System.ConsoleKeyInfo`, is no longer a field access but a dynamic (because `KeyChar` is not static) call `System.ConsoleKeyInfo.get_KeyChar(x)`.

[c#] getter access is get_* call

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ExtensionMethodTests.scala

Loosens extension method matching to accomodate for the current lack of support for default parameter values and type compatibility checking. These issues will likely require updates to DotNetAstGen's output. Once they have some kind of support, we should tighten this criteria again.

[c#] laxer extension method matching

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/DotNetAstGenRunner.scala

The Linux ARM version is named `dotnetastgen-linux-arm64`. However, the default suffix on `AstGenRunnerBase` for this configuration is `arm`, leading to a lookup for `dotnetastgen-linux-arm` that doesn't exist. The fix is similar to gosrc2cpg's:
https://github.com/joernio/joern/blob/bdb65e2ddd934633dedfec18bdd19d68ffd60e8d/joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/utils/AstGenRunner.scala#L33
credits: @tajobe

[c#] dotnetastgen for linux on arm is linux-arm64

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala

We see a bunch of 
```
[WARN ] `ast.AttributeArgumentList` AST type is not handled.
```
during AST creation, even though attributes/annotations already have some kind of representation. All that is missing is a DotNetJsonAst node for them.

[c#] add AttributeArgument{List} to DotNetJsonAst

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/HeaderFileFinder.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/PreprocessorPass.scala

- only use one instance of HeaderFileFinder during the whole parse process and CPG generation (no need to initialize this more than once)
- respect file exclusions during header file search
Reduces runtime on polarphp by ~10sec on my machine.

[c2cpg] Some performance fixes

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/parser/DotNetJsonAst.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MemberAccessTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MemberTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/PropertyGetterTests.scala

Reworks `get;` accessors to become METHODs instead of MEMBERs. At this point, we already have special logic for rewriting e.g. `Console.Out` into `Console.get_Out()` (as that's its real name, coming from DotNetAstGen), but we are still missing the same lowering for properties declared in the source-code, which are currently represented as MEMBERs. This PR turns them into get_* METHODs.
I had to ignore 3 unit-tests related to MemberBindingExpression + ConditionalAccessExpression: the original test samples for these were using getters, though they didn't have to, as can be seen by their adapted variants using traditional fields. Thus, we didn't lose on the amount of tests, only adapted them for now. Fixing all that in the same PR would make it considerably more noisy, hence the split.

[c#] lower get accessor declarations to get_* methods

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/Utils.scala

* Introduces `CSharpScope.tryResolveGetterInvocation` that, together with `composeGetterName`, simplifies the getter lookup in `astForSimpleMemberAccessInvocation`.
* Introduces an overloaded method for `composeMethodFullName` taking in the parameter ASTs, so we don't have to get their types beforehand every time.

[c#] refactor composeMethodFullName-alikes

---

console/src/main/scala/io/joern/console/BridgeBase.scala

Just discovered the latest addition to #5256 of the sarif config was `val` and would not be able to be redefined for tools extending the REPL.

[sarif] Make SarifConfig Mutable in REPL

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/Utils.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/PropertySetterTests.scala

Similarly to `get;` accessors, this also lowers setters into methods with an implicit `value`-named parameter.

[c#] lower setter declaration into a METHOD node

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ExtensionMethodTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/InheritanceFullNameTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/LambdaTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MemberTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MethodTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TopLevelStatementTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeDeclTests.scala

When reading from the output from DotNetAstGen, `void` is always denoted as `System.Void`. However, when building the AST we often use `void` instead. The same kind of situation happens with e.g. `int` vs `System.Int32`, but in this case we always use the latter. So, for consistency, this changes it so that `System.Void` is used throughout.

[c#] void always mapped to System.Void

---

console/src/main/scala/io/joern/console/BridgeBase.scala
joern-cli/src/main/scala/io/joern/joerncli/console/RunBeforeCode.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/SarifExtension.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/sarif/SarifConfig.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/sarif/SarifSchema.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/sarif/ScanResultToSarifConverter.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/sarif/v2_1_0/JoernScanResultToSarifConverter.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/sarif/v2_1_0/Schema.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/SarifTests.scala

* Added reporting descriptors which allow one to add more meta data to rules, and link findings to a given existing entry.
* Moved the sarif instantiation to the RunBeforeCode object which separates actions from tools deriving from Joern
* Using more "optional" properties where possible on properties which are not required by the sarif schema

[sarif] Add Reporting Descriptors & More "Optionality"

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/sarif/SarifSchema.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/sarif/v2_1_0/JoernScanResultToSarifConverter.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/sarif/v2_1_0/Schema.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/SarifTests.scala

GitHub code scanning has strict requirements on SARIF files that need to be enforced, such as minimum elements in an array, line number > 0, etc. Some validators emit warnings on this, but GH fails the pipeline.
Additionally, GitHub makes use of fingerprinting to avoid duplication between versions.
The SARIF conversion has been adapted to accommodate the above.

[sarif] GH Scanning: Fingerprints & Array/Position Validation

---

joern-cli/frontends/javasrc2cpg/build.sbt
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/BinarySignatureCalculator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForCallExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForPatternExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForForLoopsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/JavaScopeElement.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/GenericSignatureTests.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/util/ScopeTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstNodeBuilder.scala
project/Versions.scala

The generic signatures added by this PR follow the format described in https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.9.1 and largely correspond to the generic signatures in class files with some notable differences:
* In most cases, only the simple name for the class will be used (so `LString;` will be used instead of `Ljava/lang/String`)
* Where a qualified name is used in source, that name is used verbatim in the signature, for example `Ljava.util.List` (note the `.` were not substituted for `/`. 
* For local classes, the name of the class as it appears in the CPG is used in the signature for instances of that class (we don't follow the JVM naming scheme for these), for example `Ltestpackage.TestClass.testMethod.LocalClass;`
From the language specification:
``` …
```

[javasrc2cpg] Populate generic signatures roughly following the class file signature format

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/utils/Utils.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeDeclTests.scala

The synthetic TYPE_DECL for anonymous objects contained in its full name the surrounding method's signature part. See TypeDeclTests. They are already numbered, so I don't think a conflict should arise from this, and we get to keep uniform full names.
Also changed the approach wrt `composeMethodScopeName`: while trying to support nested methods, noticed we should have the surrounding method's full name, including its signature, as that is later needed for creating the `AST` edge that will place the nested method "inside" its parent method. Thus, instead of pushing MethodScopes without signatures, we make sure that the current method's fullName doesn't contain its parent's signature.

[c#] fix anonymous types' fullname

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForDeclarationsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/LambdaTests.scala

Uniformizes the full names for the synthetic METHODs created for anonymous functions, in the vein of #5283.
Previously they did not have a signature: now they do, albeit an `<unresolvedSignature>` only. I reckon it might be possible to improve this, but not without a big change, I fear.

[c#] fix anonymous functions' fullname

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/PropertySetterTests.scala

Renders setter assignments as their corresponding `set_PropertyName` calls, e.g. `x.MyProperty = y` roughly becomes `x.set_MyProperty(y)`. There are still some edges to be addressed in future PRs; in particular, we should have a general solution for building signatures so we don't keep falling for them.

[c#] initial support for replacing setter assignments with setter calls

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/sarif/v2_1_0/JoernScanResultToSarifConverter.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/SarifTests.scala

In the case where an unexpected string in placed in the `filename` property, default to attempting URI construction within a `Try` and returning a `None` on failure

[sarif] Safe URI Construction

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ObjectCreationTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/PropertyGetterTests.scala

Type full names for fully-qualified object creation expressions were missing, e.g. `new System.Text.StringBuilder()` had `ANY` for typeFullName.

[c#] fix object creation involving qualified names

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/PropertySetterTests.scala

Handles setters involving `+=`, `*=`, etc assignments with the obvious lowering. Previously, only straightforward `=` assignments were handled. E.g. `x.MyProperty += 0` is handled as `x.set_MyProperty(x.get_MyProperty() + 0)`.
Note: Built on top of #5294 (hence the larger diff.)

[c#] support setter assignments via += et al assignments

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/PropertySetterTests.scala

Supporting, e.g. `x = 0` and `x += 1` when `x` denotes a setter property, lowering them as `set_X(0)` and `set_X(get_X() + 1)`, respectively. Previously, this lowering only applied when the LHS was a member access, like `this.x` or `SomeClass.x`.

[c#] support setter assignments whose lhs is an identifier

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RegexTests.scala

Lowering regex matches to reflect assignments made to global variables. The lowering becomes:
```ruby
tmp = 'hello'.match(/h(el)lo/)
if tmp
$~ = tmp
$& = tmp[0]
tmp.begin(0)
else 
$~ = nil
$& = nil
nil
end
```
Some heuristics to assign group matching global variables is next.

[ruby] Regex Global Var Lowering 

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForPatternExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/PatternExprTests.scala

When pattern matching on, for example, a `record Foo(String value){}`, the field accessor call `Foo foo; foo.value()` was being created with `foo` as an argument and not a receiver which, in turn, breaks dataflows. This PR fixes this. I only updated one unit test to demonstrate this, but will use `X.receiver` consistently when redoing the unit tests for the new pattern variable initialization representation.

[javasrc2cpg] Fix record accessor call receiver in pattern matches

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RegexTests.scala

This PR implements the other component of regex matching defining global variables. In Ruby, `$1`, `$2`, etc. correspond to the group matched in the last match. This is synonymous to how a `MatchData` object could refer to these matches.
This PR models these `nref` objects to `$[1]` and, during a match lowering, defines them to the corresponding index position of the lowered temp match object, i.e., `$[1] = <tmp-0>[1]` where `N` is determined by the number of opening parenthesis (simple heuristic).
Additionally, the lowered `match` calls have their `methodFullName` defined for convenient policy/semantic definition creation.

[ruby] Regex Match Defines `$N` Vars

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/datastructures/RubyScope.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonHelpers.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/passes/RubyTypeRecoveryTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ArrayTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ClassTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ControlStructureTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/DoBlockTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HashTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/HereDocTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ImportTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/LiteralTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodReturnTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/MethodTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/ModuleTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RegexTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/SingleAssignmentTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/rubysrc2cpg/ImplicitRequirePass.scala

It was recently determined that bundled types were prefixed with the `__core.Kernel` prefix which was unintended, as it should only go as far as `__core`.
This change remediates this, as well as logs a warning when a full name is attempted to be constructed in a way that will generate a bundled type with the `__core.Kernel` prefix, or if a non-bundled type will be created with a `__core` prefix.

[ruby] Bundled Type Full Name Consistency

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/ClassDeclarationTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MemberAccessTests.scala

Noticed this sample was yielding 2 TYPE_DECLs (`Bar` and `Foo.Bar`):
```c#
namespace Foo;
class Bar {
Bar Field1;
void DoStuff() { var x = this.Field1; }
}
```
Reason: `this.Field1` had typeFullName `Bar` only.

[c#] fix typeFullName for fieldAccess of same-class members

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/RubyIntermediateAst.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyJsonToNodeCreator.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/Defines.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RegexTests.scala

Fixed a bug introduced by converting all regex match methods by the `~=` binary statements. The bug is introduced is that this replaces ordinary calls (expressions) with binary statements leading to unexpected structures during AST creation.
This was done to prevent infinite lowering whenever a regex method is created (as a `match` call is part of this lowering, which in of itself is a regex method).
This change adds a "tag" to show when a call needs this lowering.

[ruby] Fix Regex Lowering Bug

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForNameExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForPatternExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForVarDeclAndAssignsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForForLoopsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForSimpleStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/JavaScopeElement.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/scope/Scope.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/PatternExprTests.scala

This PR builds on https://github.com/joernio/joern/pull/5305 and is a follow-up to https://github.com/joernio/joern/pull/5305 and adds name mangling for locals that conflict with hoisted pattern locals. Where conflicting variables have the same types as well, a single local is shared instead.
```java
static void foo(Object o) {
if (o instanceof String value) {
sink(value);
}
// mangled
int value;
}
```
```java
static void foo(Object o) {
if (o instanceof String value) {
sink(value);
}
if (o instanceof Integer value) {
// mangled
sink(value);
}
}
```
```java
static void foo(Object o) {
switch (o) {
case Integer value -> sink(value);
// not mangled since the local is enclosed in a block in the body of the switch entry
case Boolean value -> sink(value);
}
if (o instanceof String value) {
// …
```

[javasrc2cpg] Add name mangling for pattern locals that conflict with locals in the enclosing scope

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala

Replaced the check for the installed PHP version using Michael's `VersionHelper` instead of regex.
Resolves https://github.com/joernio/joern/issues/5320

[php] Use Robust Version Checking

---

joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/passes/ConfigFileCreationPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XConfigFileCreationPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/DependencyResolver.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/GradleDependencies.scala

The biggest change in functionality that this PR introduces is to fetch jars containing classes instead of the source jars. We we previously using 
```
def result = dependencies.createArtifactResolutionQuery()
.forComponents(componentIds)
.withArtifacts(JvmLibrary, SourcesArtifact)
.execute()
...
from result.resolvedComponents.collect { it.getArtifacts(SourcesArtifact).collect { it.file } }
```
to fetch the `JvmLibrary` and `SourcesArtifact` artifacts, but then filtering out non-`SourcesArtifacts` and copying over the sources. I don't know why it was done this way, but this has certainly never worked for `javasrc2cpg` and from experiments on a small toy project, it doesn't look like this works for `kotlin2cpg` either. 
The new version gets artifacts with
```
artifactFiles in …
```

[x2cpg] Fix a few Gradle dependency fetching issues

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/parser/RubyAstGenRunner.scala

For many concurrent requests on the HTTP server, the current configuration bombs out. This uses the thread safe config.

[ruby] Use `THREADSAFE` Configuration for Script Container

---

joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/RegexTests.scala

To be consistent with other dynamic calls, adds a dynamic type hint to literals + sets `match` to be `DynamicCallUnknownFullName` to enable dynamic call resolution strategies to kick in.

[ruby] Ruby `match` to use `DynamicCallUnknownFullName`

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/GradleDependencies.scala

Before this PR, a lot of the logic for gradle dependency fetching was happening from Scala code through the gradle connection via the API. This has a lot of overhead as the project needs to be reloaded/initialized/correct verb each time. For example, just listing the available projects with their configurations for the elasticsearch project took ~30 minutes on my machine since there's a configuration step that had to happen for each request. Doing this from a gradle task defined in the build or init file is almost instantaneous.
With this PR, all of that logic is moved into the gradle init script. A separate task to fetch dependencies is created for each subproject and then one task is created in the root project which either depends on all of these, or only on that of the `:app` project …

Move gradle dependency fetching logic into init.gradle

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/Defines.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala

No custom operator call anymore. It's semantically just a block of expressions.

[c2cpg] Fixed lowering for ExpressionList

---

console/src/test/scala/io/joern/console/ConsoleTests.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/Main.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForInitializersCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/CdtParser.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/Report.scala

This speeds up parsing quite a lot.
(OPTION_NO_IMAGE_LOCATIONS, OPTION_SKIP_TRIVIAL_EXPRESSIONS_IN_AGGREGATE_INITIALIZERS)
E.g., this shaves off ~16% on polarphp (39sec -> 33sec) total runtime.
Also cleaned up the logs:
- do not log preprocessorErrorCount and parse problem numbers. These numbers might be nice for small code snippets but do not mean anything on real projects when they go to >100 or the like.
- only log relative paths (easier to read logs)

[c2cpg] Speed up parsing

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/C2Cpg.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/Defines.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/FullNameProvider.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/parser/HeaderFileFinder.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/FunctionDeclNodePass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/MethodFullNameUniquenessPass.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/TypeDeclNodePass.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/cpp/features20/Cpp20FeaturesTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/MethodFullNameUniquenessPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/types/ClassTypeTests.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/testfixtures/AstC2CpgFrontend.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/callgraph/DynamicCallLinker.scala

This pull request includes several changes to improve the handling of method full names, particularly ensuring their uniqueness and supporting const methods. The changes also include updates to various passes and test cases to incorporate these improvements.
* Added logic to append a `const` suffix to method full names when applicable.
* Added a utility function to check if a type is const and updated method full name generation to include the `const` suffix.
* Added `ConstSuffix` and `DuplicateSuffix` constants for use in method full name generation.
* Introduced a new pass to ensure method full names are unique across the CPG by appending unique suffixes with an incrementing counter to duplicates.
* Updated the `C2Cpg` class to execute the new `MethodFullNameUniquenessPass`.
* Updated …

[c2cpg] Make method fullNames truly unique

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstNodeBuilder.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/NodeBuilders.scala

This is the first in a series of PRs which will deprecate the node builder methods in `NodeBuliders.scala` in favour of the `AstNodeBuilder` methods which follow the pattern of taking an origin node and calculating line/column numbers and offsets from that. 
I think that breaking these PRs up by method will probably be the easiest to review, but am happy to do it by frontend instead if that's better.

Deprecate newAnnotationLiteral node

---

joern-cli/frontends/x2cpg/src/main/resources/io/joern/x2cpg/utils/dependency/dependency-fetcher-init.gradle
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/GradleDependencies.scala

This is a follow-up to https://github.com/joernio/joern/pull/5348
It moves the gradle init script into a separate file which is accessed as a resource. We need to inject some information at runtime, so to do this `__TAG_NAME__` tags are used in the init script and replaced in the output script. I've also added commented-out defs for all of these which can be uncommented for easier manual debugging/development.

Move init.gradle content into separate resource file

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstNodeBuilder.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/NodeBuilders.scala

Ideally we wouldn't need the `localNodeWithExplicitPositionInfo` method at all, but I don't see an obvious way to avoid it in the `AstCreatorHelper` classes. @max-leuthaeuser you're more familiar with this part of code, so if you have any ideas please let me know. Otherwise I think keeping moving this local creation method into `AstNodeBuilders` and clearly distinguishing it from `localNode` by name is fine.

Deprecate newLocalNode method

---

joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForTypeDeclCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForForLoopsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/util/NameConstants.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/NodeBuilders.scala

There's still one use left in x2cpg in the same `fieldAccessAst` method mentioned in the `newOperatorCall` PR

Deprecate newFieldIdentifierNode and remove uses

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForForLoopsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/jartypereader/descriptorparser/DescriptorParser.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/jartypereader/descriptorparser/TypeParser.scala

javasrc2cpg has some error-level logs left over from before a general logging level lowering a while ago. None of these should be logged at an error level, so this PR sets more appropriate levels.
These error logs may also be causing "language failure" messages to appear in the SL UI, but that's just a hunch.

[javasrc2cpg] Lower some unnecessary error logs to warn/debug

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/ForEachLoopTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/base/MethodStubCreator.scala

This:
1. Never causes fullname collisions during method stubbing
2. gets the arguments of stubbed methods correct
3. warns if there are mismatches
The main point is: In order to make anything work, each argument of a call to the method must have a matching parameter. Matching means: argumentIndex or argument equals index of parameter.
Unfortunately the old code looks hopelessly confused about all that, and it is used from other components. These components need to deconfuse themselves, and then we need to clean this up.

Fix some issues in methodStubCreator

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/AstCreator.scala

Replaces the `\r\n` windows new lines with Unix `\n` newlines in the `.code` function for `javasrc2cpg`

Replace windows newlines on the code method for java

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForPrimitivesCreator.scala

May crash due to missing includes / macros so we need to be more defensive here.

[c2cpg] Safer .getScope call

---

joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/querying/AstQueryTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/LiteralTests.scala
joern-cli/frontends/gosrc2cpg/src/test/scala/io/joern/go2cpg/passes/ast/LiteralCpgTests.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/LiteralTests.scala
joern-cli/frontends/jimple2cpg/src/test/scala/io/joern/jimple2cpg/querying/LiteralTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/ast/SimpleAstCreationPassTests.scala
joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/testfixtures/AstJsSrc2CpgFrontend.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LiteralTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ScalarTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/StrLiteralCpgTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/querying/LiteralTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ExpressionTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/LiteralMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/package.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/LiteralTraversal.scala

* Added a new `.innerText` step for String literals to get the value inside the quotes
* Returns `Some(string)` if the literal is a `string` and has surrounding quotes (language specific), otherwise returns `None`
* Only works on `LITERAL` nodes, not on interpolated strings that are transformed into calls in the AST.

Add `.strippedCode` step for String literals

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/utils/IncludeAutoDiscovery.scala

* fix for MacOS clang specific paths
* fix for language setting

[c2cpg] Fixes for system header auto discovery

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/FullNameUniquenessPass.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/FullNameUniquenessPassTests.scala

The PolicyLinker compares them  by name + signature so adjusting the fullname was not enough. We set the name now also. That should not break things as the REFed  method stays the same (REF edge is already there).

[c2cpg] Make bindings also unique to the PolicyLinker

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/CallTests.scala

Calls with an explicit `super` receiver, e.g. `super.foo()` were missing a `REF` edge to the `this` parameter of the method in which it is called. This PR fixes that.

Add ref edge to this for explicit super receiver

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForFunctionsCreator.scala

Even so PR #5399 fixed the retrieval of a ClassDescriptor for a given function w.r.t. null safety we may still end up in a situation where the name or signature calculation throws a NPE in case of missing types.

[kotlin2cpg] Another NPE fix

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala

We do not need a file offset table for a node which is not part of the current compilation unit anyway (stuff from included files is top-level only and already filtered).
This shaves off 6sec on my machine for polarphp (39sec -> 33sec).

[c2cpg] Remove global file offset table

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/dependency/GradleDependencies.scala

The zip filter would filter out and not extract an `aar` not containing a `jar`. `Files.walk(outDir)` would then throw an exception since `outdir` doesn't exist. By removing the filter, the `aar` will always be extracted, preventing the crash. I think this is fine since the `if` statement below filters out these results afterwards regardless.

[x2cpg] Fix crash when GradleDependencies fetches aar without jar

---

joern-cli/frontends/csharpsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/CallTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/MethodTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/NamespaceTests.scala
joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/TypeDeclTests.scala

* Resumes #5314, by upgrading DotNetAstGen to 0.42.0
* Fixes the `.code` property for `CALL` nodes
* No more edge cases in AstCreatorHelper -- doesn't seem to break any test. This effectively shifts the responsibility of formatting a resulting node's `.code` to their respective `astForXXX` methods.

[c#] fix .code property

---

joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForFunctionsCreator.scala
joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForPrimitivesCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForMethodsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/declarations/AstForTypeDeclsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForLambdasCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForNameExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForPatternExpressionsCreator.scala
joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/expressions/AstForSimpleExpressionsCreator.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/astcreation/AstCreator.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/astcreation/declarations/AstForDeclarationsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForDeclarationsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForExpressionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForFunctionsCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstForPrimitivesCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/NodeBuilder.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/AstCreatorBase.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/NodeBuilders.scala

Deprecate the `NodeBuilders` companion object along with 2 left-over uses

[x2cpg] Deprecate NodeBuilders

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/C2CpgScope.scala

- Simplifies variable lookup using a recursive approach instead of iteration
- Improves variable resolution with cleaner stack-based navigation

[c2cpg] Remove ScopeElementIterator

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
README.md

Fixes #5451:
- changed base image from CentOS to AlmaLinux
- updated JDK to version 21
Additional changes:
- removed unnecessary packages installed by `yum`
- updated `sbt` to version 1.10
- updated `devcontainer.json` (this new structure is expected by the current version of VS Code)
- updated the readme

Update obsolete dev container

---

joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/PCodePass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/arm/ArmFunctionPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/mips/MipsFunctionPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/passes/x86/X86FunctionPass.scala
joern-cli/frontends/ghidra2cpg/src/main/scala/io/joern/ghidra2cpg/utils/Utils.scala

Currently [`getExternalFunctions`](https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/FunctionManager.html#getExternalFunctions()) is used to determine if a function is external. The problem with this approach is that the code needs to iterate over this list each time it wants to decide if a function is external or not. `Function`s already have this information and it can be obtained using [`getThunkedFunction`](https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/Function.html#getThunkedFunction(boolean)) together with [`isExternal`](https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/Function.html#isExternal()) which is simpler and more efficient. Thunk functions are references to other functions (e.g. external ones), so first we need to follow the …

[ghidra2cpg] Simplify checking of external functions

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/utils/Scope.scala

Removed `match` statement in `surroundingAstLabel` and used pattern matching for the `collectFirst` instead. `match` statement was causing `match error` due to new `NewBlock` scope node that was added in #5438

[php] Fix match error in `surroundingAstLabel` and `surroundingFullName`

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/C2CpgScope.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/FullNameProvider.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala

Missing includes / header files may lead to AST names being null (Java `null`) and filenames being empty (empty string `""`).
Discoverd during testing on https://github.com/openssl/openssl

[c2cpg] Fixed empty filenames and AST names

---

joern-cli/frontends/swiftsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/Main.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/parser/SwiftJsonParser.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/io/ProjectParseTests.scala

Swifts representation of characters beyond 127 differ from what the JVM does. E.g.,  ️⃣  is `\ufe0f\u20e3` in Swift but `\ufe0f\u20e3\u0020` in Scala. SwiftAstGen now encodes all of them before parsing and passes that as content to swiftsrc2cpg. Hence, all offsets are the same.

[swiftsrc2cpg] Bring in encoding fix

---

.github/workflows/pr.yml
joern-cli/frontends/swiftsrc2cpg/build.sbt
joern-cli/frontends/swiftsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/utils/AstGenRunner.scala

Brings in the new musl based swiftastgen Linux binary (no glibc version dependency anymore)

[swiftsrc2cpg] Bump swiftastgen version

---

querydb/src/main/scala/io/joern/scanners/Crew.scala
querydb/src/main/scala/io/joern/scanners/QueryTags.scala
querydb/src/main/scala/io/joern/scanners/php/MagicHash.scala
querydb/src/test/scala/io/joern/scanners/php/MagicHashTests.scala

Magic hash exploits the type juggling in PHP, for example, the following conditional statement would be evaluated as true. 
```php
<php
if(md5("240610708")== md5("QLTHNDT"))
echo "good";
```
This is because 
- `md5("240610708")= "0e462097431906509019562988736854"`
-  `md5("QLTHNDT")="0e405967825401955372549139051580"`
- Both form the scientific notation of 0*10^xxx, then 0;
This PR query identifies flows from 1. source -> hash functions, and 2. hash functions -> loose comparison.

[PHP] Add query to detect magic hash

---

.github/workflows/release.yml
project/plugins.sbt

originally suggested in https://github.com/joernio/joern/issues/3823,
I just added that functionality to sbt-ci-release-early
To prevent situations like this:

ciRelease: skip if there's no changes

---

.github/workflows/release-github.yml
.github/workflows/release.yml

Required because we no longer create a release if there's no changes - see
the currently release build.
Triggered by version tags, which are set by the regular release build.
Also: use the tag from gh actions env

factor out 'release-github' as a separate build.

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/PhpParser.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstParsingPass.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/SymbolSummaryPass.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/PhpSymbolSummaryPassTest.scala

Implemented a leaner version of https://github.com/joernio/joern/pull/5467 by operating directly on `PhpNode`s and parsing code twice to keep memory low. Handles namespace collisions gracefully.

[php] Pre-Parsing Directly on `PhpNode` objects

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/passes/ast/AstCreationPassTests.scala

We now do no longer generate unknown nodes there.
Instead, a TypeRef is used just like e.g., in javasrc2cpg.

[c2cpg] Support for cast expressions

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/Php2Cpg.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/AstCreationPass.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/SymbolSummaryPass.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/utils/Scope.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/datastructures/PhpScopeTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/passes/PhpSymbolSummaryPassTest.scala

* Modifies the scope object to incorporate summaries and knowledge of imports into the scope 
* Using import information, it is able to map a symbol or alias to an imported entity that has appeared from the summary pass
* Simplified the summary pass to not be nested, but rather flattened, and use string paths similar to PHP notation
* When a symbol is resolved, the kind of symbol is also returned, i.e., class, function, namespace, etc.
Note: Excluded class member summarization (anything nested under a class) as PHP class members cannot be imported directly.

[php] Incorporate Imports into Scope

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/TaskCreator.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/CallTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/MethodTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/dataflow/DataFlowTests.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/CallMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/ExpressionMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/MethodParameterInMethods.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/expressions/CallTraversal.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/MethodParameterOutTraversal.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/types/structure/MethodParameterTraversal.scala

At first I had changed the numbered `call.arguments(i)` query to not return named arguments. That's why I changed some frontend tests to query by argument name. In the end, I felt that went a bit too far as a potentially breaking change. So that DSL step continues to just look at the value of the `argumentIndex` property without considering whether there is a `argumentName` or not.
(I've kept the changes to the tests anyway, because 1) it's more correct in the context of the test to query for a named argument and 2) it provides some test coverage for the DSL step.)
One Ruby dataflow is now ignored that wasn't previously - it sort of accidentally worked until now, since the first (named) argument happened to get matched to the name-variadic parameter that also happens to have index 1. …

 DSL: make param <-> argument steps respect named arguments 

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/parser/Domain.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/passes/LocalCreationPass.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CallTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/MemberTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/NamespaceTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeNodeTests.scala

* Create a meta `TYPE_DECL` node, which is a sibling to the normal `TYPE_DECL` node for named classes, anonymous classes and enums (handled like class structures in `php2cpg`)
* Move `<clinit>` (static init method), all static methods, all static variables and consts to the meta `TYPE_DECL`
* Moved the AST generation for the global type decl into it's own function, was creating too much convolution in the `astForNamedClass` function
* updated required test expectations to account for the new `.<class>` type decl that is introduced.

[php] Create meta `TYPE_DECL` (.<class>) for class-like structures

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf

Contains an important fix to tsc type map generation (could end up in an infinite loop at certain JS constructs).
See: https://github.com/joernio/astgen/pull/34
Was reported via Discord: https://discord.com/channels/832209896089976854/842699104383533076/1374703465858863247

[jssrc2cpg] Update astgen

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CallTests.scala

As the PHP frontend composes full names from method code, this appropriately handled `::`, `->`, and `?`.

[php] Normalize code before composing full name

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CallTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/FieldAccessTests.scala

At current, many field access calls have `Identifier` RHS nodes, whereas a `FieldIdentifier` node would be the correct node.
Breaks up the diff of https://github.com/joernio/joern/pull/5493

[php] Fix Field Identifier Representation

---

dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/package.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/passes/reachingdef/DdgGenerator.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/Engine.scala
dataflowengineoss/src/main/scala/io/joern/dataflowengineoss/queryengine/SourcesToStartingPoints.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/rubysrc2cpg/src/test/scala/io/joern/rubysrc2cpg/dataflow/ClassTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/dataflow/DataFlowTests.scala

Fixed an overapproximation in `SourcesToStartingPoints` that propagates an identifier as a source in many more places than it should, ending the propagation if the identifier is an argument to some call or operation already.
Resolves https://github.com/joernio/joern/issues/5520
(see ticket for discussion)
Note: This is branched off of https://github.com/joernio/joern/pull/5522
Resolves: https://github.com/joernio/joern/issues/5511

[dataflow] Fix identifier overapproximation as starting point

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/Kotlin2Cpg.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstCreator.scala
joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/passes/AstCreationPass.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/dataflow/TypeDeclTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/AnonymousFunctionsTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/LambdaTests.scala
joern-cli/frontends/kotlin2cpg/src/test/scala/io/joern/kotlin2cpg/querying/MethodTests.scala

This PR populates the offset fields for all node types, but only tests methods and type decls since these are the only node types for which this is currently used.

[kotlin2cpg] Populate offset and offset fields

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForTypesCreator.scala
joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/MacroHandler.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/SwiftSrc2Cpg.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForStmtSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCollectionCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForTypeSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/utils/ExternalCommand.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/GuardTests.scala

~~And set block children order instead of argumentIndex.~~
Removed setting explicit order by relying on `io.joern.x2cpg.Ast#setOrderWhereNotSet`
Just some initial cleanups before starting with PRs for new features.

[swiftsrc2cpg][c2cpg] Initial round of refactorings

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/jssrc2cpg/src/main/scala/io/joern/jssrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/swiftsrc2cpg/src/main/resources/application.conf
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/parser/SwiftJsonParser.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/Report.scala

- enhanced logging for CPG generation in these frontends to use consistent messages and log levels
- updated `SwiftJsonParser` to include LOC in `ParseResult` and refactored its AstCreationPass to use this value for reporting
- fixed total LOC calculation in `Report` to exclude files with negative LOC
- bumped Swift `astgen_version` to `0.2.9` (includes the LOC directly so no duplicate file reading)

[swiftsrc2cpg][c2cpg][jssrc2cpg] Improve reporting and logging in AstCreationPasses

---

joern-cli/frontends/c2cpg/src/main/scala/io/joern/c2cpg/astcreation/AstForStatementsCreator.scala
joern-cli/frontends/c2cpg/src/test/scala/io/joern/c2cpg/cpp/features20/Cpp20FeaturesTests.scala

Do not proceed to generate nonsense from the broken parse tree. Warn the user instead.

[c2cpg] Handle unsupported co_await gracefully 

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/utils/Scope.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/CallTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/TypeDeclTests.scala

* Adjusted constructor `code` and `dispatchType` (to STATIC)
* Added constructor test
* Made adjustment to scope import/summary handling to handle both ways one can reference imports (either by last token, or full name)

[php] Constructor Tweaks

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf

Brings in the latest version of astgen build with the latest yao-pkg/pkg instead of the deprecated vercel/pkg (since more than 2 years).

[jssrc2cpg] Bump astgen

---

joern-cli/frontends/jssrc2cpg/src/main/resources/application.conf

This is hopefully the last bump for this week.
This brings yet another performance fix for astgen. Time for https://github.com/swc-project/ts-parser-test-ref down to ~15 sec from ~2 minutes on my machine.

[jssrc2cpg] Bump astgen (again)

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForPatternSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/dataflow/DataFlowTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/DeclarationTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ExpressionTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ToplevelLibraryTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/swiftsrc2cpg/Defines.scala

* dictionary, tuple, and list lowering
* proper typeRefNode in cast expressions
* no dynamicTypeHintFullName anymore; just possibleTypes if applicable
* added support for missing addressOf calls
* fixed wrong Operators.plus calls; it's Operators.addition
* fixed wrong Operators.minus calls; it's Operators.subtraction

[swiftsrc2cpg] Several improvements

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/nodemethods/CfgNodeMethods.scala

* these don't work on the node of the value class, so it's rather
confusing
* their code was copied without changes in codescience, this way we can
reuse it

move walkUpAst and walkUpContains into companion object of CfgNodeMethods

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForDeclSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForExprSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForPatternSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForStmtSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCollectionCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstForSyntaxCreator.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/astcreation/AstNodeBuilder.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ActorTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/AsyncTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/SimpleAstCreationPassTest.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/passes/ast/ToplevelLibraryTests.scala

Swift does not support defining classes _on the fly_ at the position of an expression.
All types must be declared in advance, either globally or locally (inside a function), but not as anonymous or inline types. Hence, we never need typerefs there.

[swiftsrc2cpg] Fix for @objc annotations and typerefs from type declarations

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/FieldAccessTests.scala

This PR changes the representation for php property accesses with arbitrary expressions on the RHS, for example:
```
$obj->{foo()}
```
Previously, these were represented as field access calls, but this causes a crash in the back-end since it breaks the assumption that a field access calls have an identifier or field identifier as the second argument. Instead, these are now represented as index access calls, per the suggestion from @maltek

Use indexAccess operator for php field access calls with arbitrary expressions

---

joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/passes/ImportsPassTests.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/frontendspecific/pysrc2cpg/ImportsPass.scala

In Python, it is possible to create imports of the following form:
```
from . import bar
```
Prior to this commit, this would lead to an imported entity of `..bar`. Now, it is `$package.bar`, where `$package` is the package of the current module.

[pysrc2cpg] Fix for `from . import Bar`

---

joern-cli/frontends/kotlin2cpg/src/main/scala/io/joern/kotlin2cpg/ast/AstCreator.scala

The kotlin frontend used the `code` function in order to populate the
file content property. That was not a bad idea since the `code` function
limits the returned string length. We now just use the complete string
coming from the kotlin API.

[kotlin2cpg] Fix file content length restriction.

---

joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstCreatorHelper.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstForControlStructuresCreator.scala
joern-cli/frontends/php2cpg/src/main/scala/io/joern/php2cpg/astcreation/AstForExpressionsCreator.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/dataflow/IntraMethodDataflowTests.scala
joern-cli/frontends/php2cpg/src/test/scala/io/joern/php2cpg/querying/ControlStructureTests.scala

* Added `PhpListExpr` deconstruction support in foreach loop
* Removed `astForListExp` as it is no longer used
```php
$data = [[1, 2]]
foreach ($data as list($a, $b)) {
echo $a; // prints 1
echo $b; // prints 2
}
```

[php] Add `ListExpr` support in foreach loop

---

semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/Location.scala
semanticcpg/src/main/scala/io/shiftleft/semanticcpg/language/Steps.scala
semanticcpg/src/test/scala/io/shiftleft/semanticcpg/language/StepsTest.scala

prior to this change:
```
List((1,2,3)).toJson
// [{"head":1,"next":{"head":2,"next":{"head":3,"next":{}}}}]
```
now:
```
List((1,2,3)).toJson
// [1,2,3]
```
It's a regression that was introduced in https://github.com/joernio/joern/pull/5530
I have no idea why Michael Flanders made this change.
This is also adding a test so we catch it early next time round.

fix json serializer: define only for nodes, not for all Products

---

console/src/main/scala/io/joern/console/cpgcreation/CpgGenerator.scala

so that error messages contain the stderr/stdout of the failed command

CpgGenerator: use ExternalCommand facilities for verifying success

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala

Before:
```
> swiftsrc2cpg.sh --fooo
Error: Unknown option --fooo
Error: Missing argument input-dir
Try --help for more information.
Error parsing the command line
Process finished with exit code 1
```
After:
```
> swiftsrc2cpg.sh --fooo
Error: Unknown option --fooo
Error: Missing argument input-dir
Usage: swiftsrc2cpg [options] input-dir
input-dir                source directory
-o, --output <value>     output filename
--exclude <file1>        files or folders to exclude during CPG generation (paths relative to <input-dir> or absolute paths)
--exclude-regex <value>  a regex specifying files to exclude during CPG generation (paths relative to <input-dir> are matched)
--enable-early-schema-checking
enables early schema validation during AST creation (disabled by default) …
```

[x2cpg] Show usage on error for command line arguments

---

joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/CodeToCpg.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/cpg/ParsingErrorHandlingTests.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/testfixtures/Py2CpgTestContext.scala

Create a File node with file content in presence of parser exception.
This is mainly to help with debugging in case where enableFileContent is
set to true.

[pysrc2cpg] Ensure File node in case of parser exceptions.

---

joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/testfixtures/CSharpCode2CpgFixture.scala

Hopefully this fixes the csharpsrc2cpg test issues we see lately, e.g., https://github.com/joernio/joern/actions/runs/17240626125/job/48916564889

[csharpsrc2cpg] Use temporary CPG location in tests

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/astcreation/statements/AstForSimpleStatementsCreator.scala
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/querying/PatternExprTests.scala

Selector AST of switch statements of kind identifier and field access
could end up multiple times as sub AST in the resulting methods AST
which is invalid.
Happened for:
```
switch(expr) {
case Type1 identifier1 -> { ... }
case Type2 identifier2 -> { ... }
}
```
Fix for https://shiftleftinc.atlassian.net/browse/SEN-4375?focusedCommentId=34914

[javasrc2cpg] Fix invalid AST.

---

joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/utils/server/FrontendHTTPServer.scala

This resulted in exceptions that are not caught by the frontend specific
code to be logged twice which can be very confusing.
The other log location is in X2CpgMain.main() which i deem more
appropriate.

Remove withErrorsToConsole from X2CpgFrontend.run().

---

joern-cli/frontends/javasrc2cpg/src/main/scala/io/joern/javasrc2cpg/JavaSrc2Cpg.scala
joern-cli/frontends/javasrc2cpg/src/test/resources/config_tests/excluded/excluded.properties
joern-cli/frontends/javasrc2cpg/src/test/scala/io/joern/javasrc2cpg/passes/ConfigFileCreationPassTests.scala
joern-cli/frontends/jimple2cpg/src/main/scala/io/joern/jimple2cpg/Jimple2Cpg.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/ConfigFileCreationPass.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2Cpg.scala
joern-cli/frontends/pysrc2cpg/src/main/scala/io/joern/pysrc2cpg/Py2CpgOnFileSystem.scala
joern-cli/frontends/pysrc2cpg/src/test/scala/io/joern/pysrc2cpg/testfixtures/Py2CpgTestContext.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/RubySrc2Cpg.scala
joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/passes/ConfigFileCreationPass.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/SwiftSrc2Cpg.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/passes/ConfigFileCreationPass.scala
joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/passes/frontend/XConfigFileCreationPass.scala

This PR introduces filtering for config files using the same exclude mechanism we currently use for `SourceFiles`. It's implemented here as an `isExcludedFile` method which can be overridden per-frontend if we want to (either to disable this completely or to use a custom filter), but is enabled by default here (which I'm happy to change if need be).

Use SourceFiles.filterFile logic to also filter config files

---

joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/passes/AstCreationPass.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/utils/FullnameProvider.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/utils/GsonTypeInfoReader.scala
joern-cli/frontends/swiftsrc2cpg/src/main/scala/io/joern/swiftsrc2cpg/utils/SwiftTypesProvider.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/utils/FullnameProviderTests.scala
joern-cli/frontends/swiftsrc2cpg/src/test/scala/io/joern/swiftsrc2cpg/utils/SwiftCompilerTests.scala

Even if the compute function looks more complicated now this ensures that multiple concurrent updates to the inner Map are not lost and computed at most once (TrieMap actually uses a retry mechanic which results in additional performance overhead as we call the swift-demangle binary externally).

[swiftsrc2cpg] Refactor Swift type mapping to use ConcurrentHashMap

---

joern-cli/frontends/swiftsrc2cpg/src/main/resources/application.conf

Brings in https://github.com/joernio/SwiftAstGen/pull/18 so we can finally run it on larger projects on certain Linux distributions where the small default musl stack size resulted in seg faults.
See: https://wiki.musl-libc.org/functional-differences-from-glibc.html#Thread-stack-size

[swiftsrc2cpg] Update swiftastgen to 0.3.3
